DARPA-ASKEM/terarium

- packages/server/package.json
- packages/shared/tsconfig.json
Needed to add the --build flag to use "[build mode](https://www.typescriptlang.org/docs/handbook/project-references.html#build-mode-for-typescript)".
Build mode will follow references to other typescript packages (in this case, `shared`) so that they are built as well.
This PR also adds an output directory for `shared` so that when the TypeScript is compiled the output isn't mixed in with the source or included in version control
From the root of the project, run:
```
yarn workspace server run build
```
Which should complete without issue. You should notice a `dist` directory created within `shared`.
> fix: correct failing server build script

- .dockerignore
- .gitignore
- Dockerfile
- packages/server/package.json
- packages/server/src/app.ts
- packages/server/tsconfig.json
- yarn.lock
Added koa-static for serving client code, added basic Dockerfile, added dockerignore.
Mostly behind the scene for now, so no updates to README.
- `docker build . -t terarium-dev`
- `docker run -p 3000:3000 terarium-dev`
Application will be available at http://localhost:3000/, API endpoints available at http://localhost:3000/api
> Docker build

- .husky/pre-commit
- package.json
- yarn.lock
The issue that git hook wasn't triggering was that local git config variable, `core.hooksPath` wasn't set. 
`husky install` sets `core.hooksPath` variable to `.husky` so that the hooks inside the folder are triggered properly. 
`postinstall` makes sure that `husky install` is called automatically after `yarn install` (**Note**: There's an issue that `postinstall` doesn't run automatically when yarn package cache isn't changed, in that case you need to run `yarn postinstall` manually once
**Testing**
1. `yarn install` to trigger `postinstall` (or `yarn run postinstall`)
2.  change any vue, ts files
3. test commit by (`git commit -a -m`)
4. Check pre commit hook is running
You should expect to see something similar to this
```
git commit -a -m "Test commit"
[STARTED] Preparing …
```
> Fix issue that git hook set by husky wasn't triggering

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Enabling basic Issue and Feature template that GitHub provides.
These are for the most part the defaults they provide, let me know if you want to change them.
> chore: add issue and feature templates

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Adding a basic template for PRs. This can be modified if we want it simpler or other information to be included. Additionally we can make multiple PR templates that are better suited for certain tasks if needed.
Adding a sample for this PR of what the template would look like
---
Add PR template to the project to simplify and standardize reviews.
Resolves # N/A
Visual test of the markdown. Will not be active until merged.
> chore: add basic PR template

- .github/CODEOWNERS
- renovate.json
Make files that RenovateBot touches owned by everyone. This 'should' resolve the catch 22 of needing approval for Renovate updates during automerge. This does not break the fact that approval is still required for major upgrades.
NOTE: temporarily removing scheduling for the bot (so that it is triggered daily) for testing purpose of this fix will reschedule once resolved.
Resolves N/A
No manual test. Requires live testing of the bot runner.
> chore: add workaround for renovate and codeowners to play well together

- packages/client/webapp/src/components/Header.vue
- packages/client/webapp/src/components/data-explorer/articles-listview.vue
- packages/client/webapp/src/components/data-explorer/common-listview.vue
- packages/client/webapp/src/components/data-explorer/models-listview.vue
- packages/client/webapp/src/components/data-explorer/search-bar.vue
- packages/client/webapp/src/components/data-explorer/search.vue
- packages/client/webapp/src/components/side-panel/side-panel-nav.vue
- packages/client/webapp/src/components/widgets/full-screen-modal-header.vue
- packages/client/webapp/src/styles/variables.scss
- packages/client/webapp/src/views/DataExplorer.vue
Refine data explorer styles, e.g. making the explorer view on top of everything and cover the whole page as well as use "greenish" colors matching a bit TERarium look 'n feel
Manual testing
> feat: refine data explorer styles

- .github/CODEOWNERS
Adding Dockerfile changes to be automergable by Renovate
None
> chore: add Dockerfile to exlude permission file for automerge

- packages/client/webapp/src/views/TA2Playground.vue
This PR further develops the TA2-playground with ODE simulations. This provides some capability to prototype ideas around simulation itself, parameterization, and other related things. 
Depends on https://github.com/DARPA-ASKEM/model-transform/pull/2, you will need to start the model-transform service.
Navigate to http://localhost:8078/app/#/ta2-playground
- click on LotkaVolterra to load the petri-net
- click on simulate to run, you can click this many times to run with different initial conditions
-
> feat: add simulation to TA2-playground

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/task-request.md
The feature template was using an old `label` type that no longer exists. Updating it to use `feature` now.
> chore: add missing label for feature

- packages/client/graph-scaffolder/src/core/delta-renderer.ts
When using D3's d3.each syntax with d3.selection, `this` needs to refer to the bounded selection context. The current code uses arrow-functions which provides the wrong context so things can break. This PR fixes this by restoring them back into non-arrow functions and add TS/ES ignore declarations to get around the build warnings.
This is rather awkward  to test, since the problems are introduced in a piece of code (DeltaRenderer) that is not currently in use. 
To test, replace `packages/client/graph-scaffolder/examples/src/index.ts` with the following code snippet which uses the DeltaRenderer
Then under graph-scaffolder
- Run `npm run develop`
- Goto `localhost:8090` 
- With the changes in this PR you will be able to see a sample graph
- Without the changes in this PR you will get JS …
> fix: d3.each selecton context with "this"

- .github/workflows/playwright.yml
- .github/workflows/publish.yaml
The workflow_run call is less than desired. Switching to manually trigger tests on publish instead and not have a long dependency chain.
Increased timeout to 10 min on main build phase
> ci: switch to use triggers rather than wait on workflow completion

- packages/client/hmi-client/src/router/index.ts
- packages/client/hmi-client/src/types/Model.ts
- packages/client/hmi-client/src/views/Model.vue
Model renderer now displays the model and metadata for the model whose ID is specified in the URL.
I also removed the debugging pane that displayed the model JSON and made the graph pane bigger.
Resolves #165
1. Make sure gateway, hmi-server, hmi-client and data-service are running
2. Navigate to http://localhost:8078/app/#/projects/1/model/2 . You should see the graph and metadata for the model whose name starts with "Okuonghae2020"
3. Changing the `2` in the URL will display other models, e.g. `3` is for "Giordano2020"
> feat: 165 display selected model

- packages/client/hmi-client/src/assets/css/style.css
Before
After
Some controls would render illegibly depending on your OS color scheme settings.
This change forces all instances to use the same color scheme for now.
We can add support for dark mode if and when it becomes a priority, and when we can actually ensure pages look correct in both versions.
> fix: force one color scheme

- packages/client/hmi-client/src/components/Sidebar.vue
- packages/client/hmi-client/src/components/sidebar-panel/dataset-sidebar-panel.vue
- packages/client/hmi-client/src/components/sidebar-panel/model-sidebar-panel.vue
- packages/client/hmi-client/src/router/index.ts
- packages/client/hmi-client/src/router/routes.ts
- packages/client/hmi-client/src/views/Model.vue
- packages/client/hmi-client/src/views/Simulation.vue
Previously we couldn't import the `RouteName` enum into any of the views because it lived in `router/index.ts`. That file imports all of the views, so importing it into a view would create a dependency cycle.
Now the enum is extracted to its own file that can be safely imported in `router/index.ts` and each view that needs it.
- Can still jump to different views using the sidebar
- Can still jump to the Workflow page by clicking the button in the Model right side panel
- Can still jump to the simulation result page by clicking through the 9 sketches in the Workflow page.
> feat: extract route names to routes.ts

- packages/client/hmi-client/src/components/Sidebar.vue
- packages/client/hmi-client/src/router/routes.ts
- Re-Display the route title at the top of the side panel
- Extract route metadata to routes.ts
- Streamline sidebar template
> feat: display sidebar panel header

- packages/client/hmi-client/src/components/Sidebar.vue
- packages/client/hmi-client/src/components/articles/ArticlesCard.vue
- packages/client/hmi-client/src/components/articles/selected-article-pane.vue
- packages/client/hmi-client/src/views/Home.vue
Clean up carousel styles (images used to overflow card)
Clean up modal that opens when you click a card (and you can now click the dim background to close the modal)
Simplify selected-article-pane prop type.
Remove a bunch of unused styles.
Add Papers tab back to side bar (accidentally removed it recently)
Go to the home page.
Ensure cards load and their images don't overflow.
Click a card and ensure the modal looks alright.
Ensure the Papers tab is visible in the sidebar once more.
> feat: clean up home page carousel

- packages/client/hmi-client/src/components/Sidebar.vue
https://user-images.githubusercontent.com/16928557/206210072-4bc25784-ca30-4633-8509-2dde0876cff1.mov
Let route decide which sidebar button is active. This fixes the bug where navigating to different spaces without clicking the sidebar buttons wouldn't cause the sidebar to update.
Fix visual bug where panel title was still visible when panel is closed.
Navigate to a model, click "add to workflow". Side bar should update to workflows space.
Click the sketches, after the 9th, you should be taken to the matrix page and the sidebar should update.
Hide the sidebar and the panel title should not be visible
> fix: sidebar state and styles

- packages/client/hmi-client/src/components/articles/ArticlesCard.vue
- packages/client/hmi-client/src/components/articles/selected-article-pane.vue
- packages/client/hmi-client/src/components/projects/NewProjectCard.vue
- packages/client/hmi-client/src/components/projects/ProjectCard.vue
- packages/client/hmi-client/src/views/Home.vue
- packages/client/hmi-client/tests/e2e/base.spec.ts
https://user-images.githubusercontent.com/16928557/206247337-66662c68-029a-44bb-8bff-224137166c71.mov
- Don't show carousel rows for projects without papers.
- Apply card hover animation to all cards.
- Add arrow buttons to scroll through the list, remove scrollbar.
- Randomly select a green colour between `accent-light` and `accent-lighter` for each project card.
- Display new projects at the left of the list rather than the right
- Stop dropdown from being clipped after drilling down on a paper and selecting a project with a long name.
Note that there's some weird behaviour when you try to scroll a list farther to the right than it should be able to go, we'll probably need to wait till after the demo to address that.
> feat: home page refinements

- packages/client/hmi-client/src/stores/query.ts
- packages/client/hmi-client/src/stores/resources.ts
- packages/client/hmi-client/src/views/Home.vue
* Make sure that both the `Project` and `Query` informations are removed from the store.
* Added a `reset()` methods to both stores
* Called them on the homepage on mount
> feat: empty stores on homepage

- packages/client/hmi-client/README.md
- packages/client/hmi-client/package.json
- packages/client/hmi-client/src/assets/css/properties.css
- packages/client/hmi-client/src/assets/css/style.css
- packages/client/hmi-client/src/components/Header.vue
- packages/client/hmi-client/src/main.ts
- yarn.lock
* Implemented [Vuetify](https://next.vuetifyjs.com/en/) as design system
* Added a property css files to overwrite the Vuetify CSS properties with TERArium ones
* Change the _Data Explorer_ button in the header with Vuetify as first test.
> feat: vuetify integration

- packages/client/hmi-client/src/services/data.ts
fix broken xdd response when "fields" is specified as query param
> chore: fix broken xdd response when "fields" is specified as query param

- .github/workflows/publish.yaml
- .github/workflows/test-client-e2e.yaml
- .github/workflows/test-client.yaml
- docker-bake.hcl
This is a double PR that changes the following CI builds:
1. Adding a new group to the bake file for staging. When merging PRs to `main` it will ONLY build the client and regular server. Native server build will only be build when doing a tagged publish.
2. E2E tests will no longer be run on each PR, instead they will be run daily at 5am. Devs should check the action status/slack notification for errors
> ci: ci build optimizations

- packages/client/hmi-client/src/components/responsive-matrix/matrix.vue
- packages/client/hmi-client/src/types/ResponsiveMatrix.ts
Alt/Option key toggles between camera and selection modes with cursor changing styles to indicate mode. 
Should there be a label to additionally indicate active cursor mode?
> feat: update responsive matrix zoom to toggle between camera and selection modes

- .github/workflows/test-client-e2e.yaml
This runs the E2E tests at 10am eastern as opposed to midnight eastern.  It's more likely people will pay attention to any errors if they're run during work hours.
Resolves #427
> chore: run e2e tests at 10am eastern

- packages/client/hmi-client/src/views/Home.vue
This address a somewhat rare issue when the click event lands on svg:path instead of svg, which cause the parent element query to misfire
In the home view, scroll should work regardless of where the click is betting registered on the icon-button.
Close #341
> fix: target identity on scroll click event

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/ModelProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/SimulationProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/ModelResource.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/SimulationResource.java
Aligning API end points for models and simulations to that found in data service.
- /models/descriptions/{id} -> /models/{id}/descriptions
- /models/parameters/{id} -> /models/{id}/parameters
- /simulations/runs/descriptions/{id} -> /simulations/runs/{id}/descriptions
- /simulations/runs/parameters/{id} -> /simulations/runs/{id}/parameters
Resolves #434
> chore: fix REST subobject pattern

- packages/client/hmi-client/src/components/data-explorer/articles-listview.vue
- packages/client/hmi-client/src/components/data-explorer/search-results-list.vue
- packages/client/hmi-client/src/types/XDD.ts
- packages/client/hmi-client/src/types/common.ts
- packages/client/hmi-client/src/views/DataExplorer.vue
- packages/services/document-server/src/main/java/software/uncharted/terarium/documentserver/models/xdd/Extraction.java
- packages/services/document-server/src/main/java/software/uncharted/terarium/documentserver/proxies/xdd/ExtractionProxy.java
- packages/services/document-server/src/main/java/software/uncharted/terarium/documentserver/resources/xdd/ExtractionResource.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/xdd/Extraction.java
xDD has recently embedded documents metadata with each xDD extractions. This is particularly the case when searching Figures and Tables. So now we have the chance to quickly identify the source document where extractions have been pulled. The proposed change leverage the aforementioned to display the resulting Figure/Table search results as additional documents in the xDD search results.
NOTE styling is not the focus of this PR. But rather utilizing the new xDD feature wherein document metadata is now embedded as part of xDD extractions search result
Resolves #437
> feat: use embedded xdd doc in extractions & improve their display in explorer

- packages/client/hmi-client/src/services/project.ts
* Adding safety code here to handle `undefined` being passed in as a String value.
* There are a few related issues here like "why can this asset not be found" and "why have we hardcoded to look at the second document in the list and not the first" but those can be addressed later..... this safety code would be needed either way and solves the build issues at hand.
Resolves #455
> fix: bad document id given at load of application

- packages/client/hmi-client/src/components/data-explorer/articles-listview.vue
- packages/client/hmi-client/src/components/data-explorer/datasets-listview.vue
- packages/client/hmi-client/src/components/data-explorer/models-listview.vue
- packages/client/hmi-client/src/components/data-explorer/search-results-list.vue
- packages/client/hmi-client/src/components/data-explorer/search-results-matrix.vue
- packages/client/hmi-client/src/components/resources/resources-list.vue
- packages/client/hmi-client/src/services/data.ts
- packages/client/hmi-client/src/views/DataExplorer.vue
- packages/client/hmi-client/src/views/Document.vue
Small refactor within the data explorer, leveraging the "Document" view to show preview of search result items on click.
> chore: show preview of explorer search result items on click

- packages/client/hmi-client/src/views/DataExplorer.vue
- packages/client/hmi-client/src/views/Document.vue
This does a round of refactoring on the Document component, reorganizes the visual layout to be more aligned with the intended design specs.
Note the operations are a little awkward at the moment:
- This needs the collapsible panel which is not yet in place
- The design does not match to the data format that we are working with
Both of these points above will be dealt with in subsequent PRs.
This is available in both
- Data explorer, select a document search result item
- In the project overview, select from the paper menu in the sidebar
> chore: refactor and re-theming document component

- packages/client/hmi-client/src/components/articles/Document.vue
- packages/client/hmi-client/src/components/resources/resources-list.vue
- packages/client/hmi-client/src/router/index.ts
- packages/client/hmi-client/src/views/DataExplorer.vue
- packages/client/hmi-client/src/views/Dataset.vue
- packages/client/hmi-client/src/views/DocumentView.vue
- packages/client/hmi-client/src/views/ModelView.vue
- packages/client/hmi-client/src/views/Project.vue
This is a 2nd round of refactoring and restyling Document viewer
- Add a tab system similar to that of models, Document is moved to its own component and a "DocumentViewer" view is added.
- Clean up accordion as per design spec
- Make image sizing adaptive depending on available width, for data-explorer images will be smaller, for the full document view images will be larger
I placed the new component within "articles" folder for now,  we will probably want to reorg and have better nomenclatures soon.
In full viewer with tabs:
In data explorer:
- Go into project => papers and select a few documents, should be tabbed and able to switch between tabs
- Go into explorer and search for "covid", select and see documents in the right side pane
> chore: article reno work 2 - tabs, adaptive ui, and other tweaks

- packages/client/hmi-client/src/components/drilldown-panel/selected-resources-options-pane.vue
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/HomeResource.java
Also tagging on grabbing 50 projects instead of 5 for the home page. This will let us see up to 50 of our own projects. Not sure how to determine this number at the moment so hoping 50 is good
https://user-images.githubusercontent.com/17088680/213547692-12802ca1-eec4-4d44-b091-abfbe52944da.mov
#494
> feat: after adding project go to said project

- .github/workflows/publish.yaml
CI was failing to build and publish docker images. Yesterday there was a GH outage which caused some issues which also seems to have been a time where they updated their docker/buidx version. As a result the output of the bake file we were using changed and our script to extract the appropriate targets was incorrect. This update should resolve the issue to match the new output.
NOTE: not sure how we would be notified of buildx output format changes but this is a possible issue for future as well if it changes again.
> ci: update target extraction from bakefile

- packages/client/hmi-client/src/services/dataset.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/DatasetProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/DatasetResource.java
Adding the `row_limit` to the csv download api to limit the number of rows shown in the front end to not lock up the application.
Resolves #464
> feat(hmi-server): rowlimit added for csv preview

- packages/client/hmi-client/src/App.vue
- packages/client/hmi-client/src/router/index.ts
- packages/client/hmi-client/src/views/Unauthorized.vue
Throwing up a quickie unauthorized page, most likely this is a temporary or will be massively revamped later on.
Right now the purpose is to guide people who have been authenticated via Github but not yet authorized in Terarium
This is a bit difficult to test locally, what you can do is go into the hmi-server,  in HomeResource.java change
```
return Response
.status(Response.Status.OK)
.entity(allProjects)
.type(MediaType.APPLICATION_JSON)
.build();
```
To
```
return Response
.status(Response.Status.FORBIDDEN)
.entity(allProjects)
.type(MediaType.APPLICATION_JSON)
.build();
```
> feat: throwing up a quickie unauthorized page

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/RequestLoggingRequestFilter.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/RequestLoggingResponseFilter.java
This PR logs a message when requests are started and completed.  They include:
- request path
- request type
- requesting user
- duration (in the case of responses)
Eg:
```
2023-01-20 10:42:01,328 INFO  [org.key.ada.aut.PolicyEnforcer] (Quarkus Main Thread) Paths provided in configuration.
2023-01-20 10:42:02,156 INFO  [io.quarkus] (Quarkus Main Thread) hmi-server 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.14.2.Final) started in 4.128s. Listening on: http://localhost:3000
...
2023-01-20 10:42:10,056 INFO  [sof.unc.ter.hmi.RequestLoggingRequestFilter] (executor-thread-0) REQUEST STARTED | GET | http://localhost:3000/api/events?type=SEARCH | adam
2023-01-20 10:42:10,230 INFO  [sof.unc.ter.hmi.RequestLoggingResponseFilter] (executor-thread-0) REQUEST COMPLETED | GET | …
```
> feat: add request and response logging filters to hmi server

- .github/workflows/publish.yaml
Pinning version of buildkit being used to build and push images.
Reason:
Recent changes upgraded the buildx version which includes a newer version of buildkit, which in turn uses a new version of `containerd` which causes this root issue. It is not a GH issue per se but due to their recent upgrades it was introduced with the actions that were being used in the CI.
[Reference](https://github.com/docker/build-push-action/issues/761)
Resolution:
Pinning the buildkit version we are using for the build and publish step, this resolves the current issue.  Investigation of further places where we can pin the version is ongoing. Shared publish scripts have also been updated.
Tests:
Pushed a dummy tag to build the images with this fix and all images were successful.
> ci: set specific buildkit version

- packages/client/hmi-client/package.json
- packages/client/hmi-client/src/main.ts
- packages/client/hmi-client/src/utils/logger.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/loggingservice/LoggingService.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/loggingservice/LoggingResource.java
- yarn.lock
First part of the setting up a logging framework to capture user logs in a structured manner.  This will allow to measure user interactions and issues that occurred during usage.
Currently uses `vue-logger-plugin` and it's `afterHook` to buffer log messages and then post the messages periodically every 5 seconds.
Resolves the first part of setting up the instrumentation to
ship client calls to the server
the server saves structured logs
https://github.com/DARPA-ASKEM/TERArium/issues/462#event-8213619647
> feat: add client log shipping from hmi client to hmi server

- packages/client/hmi-client/src/components/articles/Document.vue
- packages/client/hmi-client/src/services/data.ts
- packages/client/hmi-client/src/types/XDD.ts
- packages/services/document-service/src/main/java/software/uncharted/terarium/documentserver/models/xdd/KnownEntities.java
- packages/services/document-service/src/main/java/software/uncharted/terarium/documentserver/models/xdd/XDDUrlExtraction.java
- packages/services/document-service/src/main/java/software/uncharted/terarium/documentserver/proxies/xdd/DocumentProxy.java
- packages/services/document-service/src/main/java/software/uncharted/terarium/documentserver/resources/xdd/DocumentResource.java
Provisional work to hook up snippets sections with summaries sections from xDD
Select documents within project artifacts or in data explorer, some of them will have summary extractions.
> chore: xDD known_entities fixes

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/Publication.java
Changing publication's naming to allow us to hit the /external/publications POST with the expected JSON formatting
https://user-images.githubusercontent.com/17088680/214401897-a077e3dc-f92d-4fd8-86fb-ebb35f79991d.mov
#528
> chore: correct naming for expected output

- packages/client/hmi-client/src/components/articles/Document.vue
- packages/client/hmi-client/src/components/data-explorer/preview-panel.vue
- packages/client/hmi-client/src/components/data-explorer/search-item.vue
Styling improvements for data explorer preview
Resolves #531
> style: no image stretch in preview, accordion fills width, clickable doi in preview

- packages/client/hmi-client/src/App.vue
- packages/client/hmi-client/src/components/Navbar.vue
- packages/client/hmi-client/src/components/projects/NewProjectCard.vue
- packages/client/hmi-client/src/services/project.ts
- packages/client/hmi-client/src/types/Project.ts
- packages/client/hmi-client/src/views/Project.vue
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/Project.java
- packages/services/hmi-server/src/main/resources/application.properties
- Persist username in project when it is created
- Show username in project view
- Allow user to edit project name in project page by clicking on menu and selecting edit
- Formatted date nicely
- Date does not get updated (should be handled by backend?)
- No feedback when inside/outside of editing mode (user can unfocus the text input and be unaware that they are still editing)
https://user-images.githubusercontent.com/16358728/214919649-d7a7368c-25f7-47b6-8fcf-f23266a4173c.mov
https://user-images.githubusercontent.com/16358728/214681844-44cbd54d-7b60-4150-bed7-bcf55c400a23.mov
@YohannParis @jamiewaese-uncharted
> feat: show username in project page; allow user to edit project page

- packages/services/hmi-server/build.gradle
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/entities/Event.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/EventType.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/EventResource.java
- packages/services/hmi-server/src/main/resources/application.properties
This PR adds Hibernate connection properties for persisting values to a database.  We add a simple `EventResource` endpoint that allows for creating of events and listing/search for previous events.  
The `EventType` can be specified as `persistent` meaning that records are stored in the database for the given user.  This is useful for recording things like searches, logins, logouts, etc.  Non-persistent events are logged for metrics and/or dashboarding after the fact (eg/ facet filter, add X to project, etc)
To create an event:
```bash
curl --location --request POST 'http://localhost:3000/api/events' \
--header 'Authorization: Bearer ...
--data-raw '{
"type": "SEARCH",
"projectId": 1,
"value": "covid-19"
}'
```
Results in the following event persisted to the database:
```json
{
"id": …
```
> feat: add endpoints for persisting and getting user events

- packages/client/hmi-client/src/App.vue
- packages/client/hmi-client/src/components/Navbar.vue
- packages/client/hmi-client/src/components/Slider.vue
- packages/client/hmi-client/src/components/data-explorer/search-bar.vue
- packages/client/hmi-client/src/components/data-explorer/slider-panel.vue
- packages/client/hmi-client/src/views/DataExplorer.vue
- Amount of items in cart is shown
- nav dropdown is adjusted
- Suggested terms list works and is restyled. 
There is a more backend related issue that should be solved in a future PR. When switching to a model or dataset you won't see suggested terms (as you should) but when you switch back to papers you won't see them anymore because the suggested terms are called along with the papers. Since the papers are already here the suggested terms are assumed to be here too but they are not. New suggested terms will only appear if something is freshly searched.
> style: adjust nav dropdown/suggested terms and add cart number

- packages/client/hmi-client/src/services/data.ts
- packages/services/document-service/src/main/java/software/uncharted/terarium/documentserver/resources/xdd/ExtractionResource.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/xdd/ExtractionProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/xdd/ExtractionResource.java
Simplifying the detection of doi's by the front end for extractions, and moving the whole thing to the back end. Changing API to remove seperate fields for search terms vs. DOI since it doesnt make a difference on our end.
* Extraction resource now does the doi vs query all detection on the back end.
* Changed document api to only handle a single search term.
Resolves #595
> fix(hmi-client): searching for doi in extractions uses wrong api params

- packages/client/graph-scaffolder/src/core/renderer.ts
Provide a `zoomRange` option. The zoomRange provides a `[minZoom, maxZoom]` input array.
Example:
```
const renderer = new SampleRenderer({
el: div,
useAStarRouting: true,
zoomRange: [0.1, 10],
runLayout: runLayout
});
```
A configuration of
- [0.5, 4] means you can pull-back by a factor of 2 and zoom-in by a factor of 4
- [0.1, 1] means you can pull-back by a factor of 10, and zoom-in is disabled
Can muck around with the example in "examples/src/index.ts"
```
npm run develop
```
> feat: zoomRange option

- packages/client/hmi-client/src/views/CodeView.vue
> fix: remove the print margin from code editor

- packages/client/hmi-client/index.html
If you want the title to all be lowercase let me know and I will change it
#657
> fix: title to correctly match test case

- packages/client/hmi-client/src/services/data.ts
Changed how we are returning data after filtering by a document facet.
Previously the facets bar would mistakenly remove facets that had no relevance to selected facets
#679
> fix: correcting return data for document facet

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/Project.java
Correcting jsonbproperty name for expected output for frontend to work with
Allows home page to correctly pull relatedDocuments for example
> chore: correcting property name

- packages/services/hmi-server/src/main/resources/application.properties
Update skema urls to point at deployment into staging kubernetes cluster.
Note that in aws deployed configurations, we use internal DNS for resolving these urls.  Thus, the production app will point at the production (pinned) skema pods
> chore: use staging deployment for skema

- packages/services/hmi-server/build.gradle
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/caching/CacheClearService.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/documentservice/DocumentProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/documentservice/DictionariesResource.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/documentservice/SetResource.java
Adding caching to xDD sets and dictionaries. Adding some super basic exception/error handling. It will be part of the exceptions task later to fill these out more. Cash will invalidate once an hour.
This is a remount of https://github.com/DARPA-ASKEM/TERArium/pull/677 and includes the PR feedback from @chris-dickson
Resolves #374
> feat(hmi-server): adding chaching to xDD sets and dictionaries

- packages/client/hmi-client/src/services/data.ts
- packages/client/hmi-client/src/types/Document.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/documentservice/Extraction.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/documentservice/ExtractionProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/documentservice/ExtractionResource.java
XDD has added highlights to extractions and changed it so attached documents to extractions also contain highlights when their extractions do.  We use the later feature here in this PR and technically didn't need to add the highlights field to extractions because thats ununsed.... but ive put it in should we ever want to take advantage of that
Resolves #555
> feat(hmi-server): highlights on extractions

- packages/client/graph-scaffolder/src/core/renderer.ts
- packages/client/hmi-client/src/page/ModelEditor.vue
- packages/client/hmi-client/src/page/ModelRunner.vue
- packages/client/hmi-client/src/services/graph.ts
Small changes and fixes based on chatter with Jamie
- Remove a temporary LR (left-right) vs TD (top-down) layout from hackathon, by default the layout will do LR.
- Fix a grid element duplication issue if useGrid option is enabled
Go to any model view, the graph structure should be flowing left-ight instead of top-down
> fix: undo temporary hackathon changes, fix grid duplicates

- packages/client/graph-scaffolder/src/core/renderer.ts
Add contextmenu event emitter
Usage, 
```
renderer.on('background-contextmenu', (_evtName: string, _evt: any, _selection: any, _renderer: any, v: any) => {
console.log(v);
});
```
where v is
```
{
"x": 140.26393561924868,
"y": 27.61464767074014,
"clientX": 52,
"clientY": 54
}
```
Not applicable, just adding a lib function
> feat: add contextmenu event

- .github/workflows/test-client-e2e.yaml
Nobody wants notifications on the weekends
> chore: only run e2e tests on weekdays

- .github/workflows/test-server-unit.yaml
- .github/workflows/test-server.yaml
- packages/services/hmi-server/README.md
- packages/services/hmi-server/src/test/java/software/uncharted/terarium/hmiserver/services/StructuredLogTests.java
This runs the quarkus tests on PRs and in main
When a file changes in the `packages/services/hmi-server` directory, this will trigger the workflow to run the quarkus tests:
> chore: add workflows for server unit tests

- packages/services/hmi-server/src/test/java/software/uncharted/terarium/hmiserver/proxies/DocumentProxyTests.java
- packages/services/hmi-server/src/test/java/software/uncharted/terarium/hmiserver/proxies/ExtractionProxyTests.java
This adds a simple integration test suite between Terarium and XDD.  This is intended to allow us to know if XDD has updated something that will break us.
Pros: We will get alerted when XDD changes their models
Cons: Our builds will fail if this happens or XDD goes down
We'll have to see if this becomes a nuisance.  Otherwise we can look into adding a global "allow 500 errors" for these tests if it happens often.
> chore: add a simple test suite for XDD proxies

- packages/services/hmi-server/src/main/resources/application.properties
Use the model service running in the staging account default.  This PR must coincide with https://github.com/DARPA-ASKEM/orchestration/pull/113
> chore: use model service in staging account by default

- packages/client/hmi-client/vite.config.local.ts
* Fixes an issue when running the docker compose setup where the Vue websocket is listening on the wrong port because I got the option name wrong.
> fix: issue with error in vite config for docker compose

- packages/client/hmi-client/src/components/documents/selected-document-pane.vue
- packages/client/hmi-client/src/page/data-explorer/components/selected-resources-header-pane.vue
- packages/client/hmi-client/src/page/project/components/tera-resource-sidebar.vue
- packages/client/hmi-client/src/services/external.ts
- packages/client/hmi-client/src/services/provenance.ts
- packages/client/hmi-client/src/types/Dataset.ts
- packages/client/hmi-client/src/types/Model.ts
- packages/client/hmi-client/src/types/Project.ts
- packages/client/hmi-client/src/types/Types.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/entities/Event.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/exceptions/HmiResponseExceptionMapper.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/Assets.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/DocumentAsset.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/ResourceType.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/ExternalProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/ExternalResource.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/HomeResource.java
• Updating back end to use same terminology as front end.
• Using new typescript generation to keep this file in sync with front end.
• Now when retrieving publications if a 404 is hit we change this to a 204 for our front end.
• Updating exception being used by back end to pass on response code.
• Front end now asks TDS for correct document asset before proceeding.
• Using generated DocumentAsset
Resolves #843
> fix: error determining provenance

- packages/client/hmi-client/src/assets/css/theme/_variables.scss
- packages/client/hmi-client/src/assets/css/theme/designer/components/panel/_card.scss
- packages/client/hmi-client/src/components/documents/DocumentCard.vue
- packages/client/hmi-client/src/components/projects/ProjectCard.vue
- packages/client/hmi-client/src/page/Home.vue
- removed bottom border of tabview
- added subtle border top of papers section
- added green linear gradient background to papers section
- removed extra padding around the first tabview (the projects section)
- softened the box-shadow behind Cards
- changed font size of project card footer to caption
- changed font size of stats at top of project cards and adjusted vertical alignment
- changed font size of journal and author names in paper cards
- reduced size of 3-dot menu on cards to 2rem
- added white border to cards
- added hover state for cards with transition effect to increase the box-shadow and change the border color
Resolve #836
> fix: home page design tweak

- packages/services/hmi-server/docker/Dockerfile.dev
Can't run tests that use docker inside docker while building a docker image, so skipping the tests on build.
> fix: do not run tests on docker compose build

- packages/client/hmi-client/src/page/data-explorer/components/search-bar.vue
* `MODELS AND DATASETS` to `Related Resources`
Resolves https://docs.google.com/presentation/d/18macftUe871RshB87QhEgNXY_14YrW0jVlaW-NRY1lQ/edit?disco=AAAAtHtVK5E
> fix: change copy on search by example

- packages/client/hmi-client/src/components/models/Model.vue
- packages/client/hmi-client/src/petrinet/petrinet-renderer.ts
- packages/client/hmi-client/src/petrinet/petrinet-service.ts
This makes a handful of tweaks and address some of the initial feedback to make the PetriNet renderer more usable.
- Add explicit state to turn edit on/off, change background colour to indicate editing state
- Remove a-star routing for now, this makes things too swiggly
- Pass in sizing configurations for petri-parsing to IGraph, this reduced hardwired numbers downstream
- Fix a few selection state issues (selected vs not-selected)
- Add a first pass of creating nodes though a context menu
- Tweak the edges and marker-ends to make the arrow a bit more visible
Note some of these changes do not exactly align with the design, we will get there in several iterations.
In the model tab, click "edit model" to enter edit mode (background changes to yellow), here you can
- Select a node and create …
> chore: various petrinet renderer tweaks

- packages/client/hmi-client/src/page/data-explorer/components/search-bar.vue
Dragging and dropping an asset into search bar opens search by example modal. 
https://user-images.githubusercontent.com/16358728/226952019-95a16513-868b-4b70-a4b9-351a0310eee3.mov
Resolves #786
> feat: drag asset directly into searchbar

- packages/client/hmi-client/src/App.vue
- packages/client/hmi-client/src/components/widgets/Modal.vue
- packages/client/hmi-client/src/components/widgets/tera-tab-group.vue
- packages/client/hmi-client/src/main.ts
- packages/client/hmi-client/src/page/Home.vue
- packages/client/hmi-client/src/page/project/components/tera-resource-sidebar.vue
- packages/client/hmi-client/src/page/project/tera-project.vue
- packages/client/hmi-client/src/types/common.ts
- Empty page behaviour when there are no tabs + remove empty tab case
- Remove buttons that aren't used (just keep delete button)
- Add "Are you sure" popup for removing an asset from project
- Tabs are identified more uniquely, some used to be identified as the same (eg. in the case where they have the same name)
https://user-images.githubusercontent.com/28237258/226956405-f6808f87-9a16-4c32-9fd6-9199d05672fb.mov
> feat: project page tweaks from slides

- packages/client/hmi-client/src/api/api.ts
* Stop the display of toast for network errors
* This needs to be triggered by an .env variable (c.f. #894)
> chore: hide toast from network errors

- packages/client/hmi-client/src/components/projects/ProjectCard.vue
- packages/client/hmi-client/src/page/Home.vue
- packages/client/hmi-client/src/services/project.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/HomeResource.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/ProjectResource.java
* Update `hmi-server` to not return _soft-deleted_ projects for the `/home` and `/projects` endpoints.
* Added a _Project Menu_ with a `Remove` option.
* Added a Confirmation dialog to prompt the user to remove the project.
* Show a toast in case of success or error of removal.
* Remove the project from the homepage by listening to the `removed` event emitted by the project card.
https://user-images.githubusercontent.com/636801/227049317-df358ac2-c097-4e8a-9314-3839d3196767.mov
> feat(hmi): delete a project

- packages/client/hmi-client/src/page/data-explorer/DataExplorer.vue
Fixing search by similar and search by related in data-explorer.
In terms of search by related it sends back a regular 100 with facets ect. I think these may be the same results but it is hitting the correct call
In terms of search by similar it is getting 10 back (I am assuming this is expected) and no facets (again assume expected) so I have just closed the facet bar when this is clicked as it wont be necessary 
https://user-images.githubusercontent.com/17088680/227028617-c2ac92e2-185b-4595-bb16-39a4d6317b02.mov
https://user-images.githubusercontent.com/17088680/227028672-bed0c316-061e-456b-ab30-44ad65b53a28.mov
#889
> fix: search by related similar is not working in data explorer

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/petrinet/SpeciesJsonDeserializer.java
A somewhat temporary fix so we don't assume mira_ids and mira_contexts are always there. 
The caveat is we have not settled upon a metadata representation so this is likely going to change, but the PR here will prevent unexpected errors in the meantime.
Should be able to fetch all models
```
curl -v -H "content-type: application/json" -XGET -H "${AUTHORIZATION_HEADER}" http://localhost:3000/api/models/{id}
```
> fix: parsing mira_ids and mira_context are optional

- packages/client/hmi-client/src/api/api.ts
- packages/client/hmi-client/tests/unit/api/api.spec.ts
Add poller utility for working with asynchronous requests. The key function is the `setPollAction` which sets a callback function that returns: 
```
{ data: T, error: any, progress: any }
```
Where, in precedence:
- A non-null `error` will trigger the the poller to fail
- A non-null `data` will return data and end the polling
- `progress` is currently not used but is meant to track and convey intermediate results
It is expected the callback function to follow this convention.
Basic tests can be exercised with 
```
yarn workspace hmi-client run test
```
> feat: polling utility

- .husky/pre-commit
- packages/client/hmi-client/src/services/data.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/Model.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/ModelProxy.java
* Add a Jackson setter to ignore non-existing and null values for the `description` property.
* Did a bit of clean-up here and there
* Added `yarn install` in the `.husky/pre-commit` file, as sometimes, `lint-staged` is not installed. @Nithos is this okay?
> fix: handle null values in model description property

- packages/client/hmi-client/src/api/api.ts
- packages/client/hmi-client/tests/unit/api/api.spec.ts
Clean up the interface a bit to have better typing information
Hook in logic for cancel
Run tests `yarn workspace hmi-client run test`
> chore: clean up, cancel-poll hook

- packages/client/hmi-client/src/components/documents/Document.vue
Open PDF button uses the generated link as a fallback
https://user-images.githubusercontent.com/28237258/229615788-c001f4ad-c8f4-4166-9fe4-10e6cad5219c.mov
> feat: open pdf button uses generated link as fallback

- packages/client/hmi-client/src/components/models/Model.vue
Dismiss the vue-context menu on background click
In model page:
- go into edit mode
- right click to get context menu
- click anywhere on the background to dismiss context menu
> fix: dismiss context meun on background click

- packages/client/hmi-client/src/components/models/Model.vue
- packages/client/hmi-client/src/page/project/tera-project.vue
Some change were lost  or squashed in previous merges, this PR restores these features
- Ability to run forecast with simulation service
> fix: restore lost changes

- packages/client/hmi-client/src/components/mathml/tera-math-editor.vue
- packages/client/hmi-client/src/components/models/Model.vue
Made the suggested updates by @jamiewaese-uncharted .
1)  Removed background and border from the non-edit mode, applied `edit` border around the entire frame of the math equation panel
2)  Repositioned "edit" button
3)  When resizing you can make the model diagram disappear.
4)  Vertical constraints
> fix: 954 math viewer design ux tweaks

- packages/client/hmi-client/src/components/models/Model.vue
Using primevue's toolbar component instead of the styling of my own
moving buttons around as Jamie wanted
Reset always visible
> chore: using primevue toolbar

- .github/CONTRIBUTING.md
Adding instructions to install ansible for secrets to work.
Resolves #984
> chore: add ansible install instructions

- packages/client/hmi-client/src/page/data-explorer/components/asset-card.vue
- packages/client/hmi-client/src/page/data-explorer/components/search-bar.vue
- packages/client/hmi-client/src/services/drag-drop.ts
The search by example popup is on if 
- an asset is being dragged
- an asset has just been successfully dropped in
- if the popup toggle is on.
https://user-images.githubusercontent.com/28237258/232125300-af2b9671-607e-42d5-a7f3-99604d4cd35b.mov
> feat: search by example pops up while asset is being dragged

- packages/client/hmi-client/src/assets/css/theme/_variables.scss
- packages/client/hmi-client/src/components/mathml/tera-math-editor.vue
- packages/client/hmi-client/src/components/models/Model.vue
- packages/client/hmi-client/src/petrinet/petrinet-renderer.ts
I cleaned up the toolbar buttons on the model diagram and math viewer. Also made the edit-mode borders consistent. Finally, I removed the gray background in edit mode of the math viewer.
> chore: model editor and math view style tweaks

- packages/client/hmi-client/src/services/models/simulation-service.ts
- packages/client/hmi-client/src/temp/TA2Playground.vue
- packages/client/hmi-client/src/types/Types.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/simulationservice/CalibrationParams.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/simulationservice/SimulationServiceProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/simulationservice/SimulationResource.java
Adding calibration endpoint to hmi-server.
Added a test button on ta2-playground just to run their test.
#1019
> chore: adding calibration end point to hmi-server

- packages/client/hmi-client/src/types/workflow.ts
- packages/client/hmi-client/tests/unit/workflow/workflow.spec.ts
Update definitions after discussion on generic vs specialized run cases. Mostly it introduces an `isRunnable` flag to allow flagging operations for custom executions. #1041 
Not sure if adding ids to ports made things better, the constructions are a bit more complicated so we will see.
`yarn workspace hmi-client run test`
> chore: update workflow related definitions per latest dicussion points

- packages/client/hmi-client/src/components/workflow/tera-simulation-workflow.vue
- packages/client/hmi-client/src/components/workflow/tera-workflow-node.vue
Add drag-related event listeners for the workflow nodes, you will be able to drag the nodes around the canvas.
Note this is sort of a stand-in replacement for using the vue3-draggable-resizable library, as it doesn't account for the transforms on the parent-container (dragging with zoom <> 1.0 is weird). We may switch out back to the lib later on, or to a different lib.
Create nodes on the workflow, you can drag nodes around.
> feat: dragging cavas objects

- packages/client/hmi-client/package.json
- packages/client/hmi-client/src/components/workflow/tera-simulation-workflow.vue
- packages/client/hmi-client/src/components/workflow/tera-workflow-node.vue
- packages/client/hmi-client/src/services/workflow.ts
- yarn.lock
This PR adds a workflow service to house the CRUD and execution functions for a workflow. For example: add/remove nodes/edges, run a node, run a subgraph, invalidation...etc.
Currently node/edges CRUD have been implemented.
Ids are generated via uuidv4
Made some modifications to testOperation to illustrate a working workflow
You need to `yarn install`.
This is a re-organization change, workflow canvas should work as before.
> feat: workflow service

- packages/client/hmi-client/src/components/widgets/tera-infinite-canvas.vue
- packages/client/hmi-client/src/components/workflow/tera-dataset-node.vue
- packages/client/hmi-client/src/components/workflow/tera-simulation-workflow.vue
- packages/client/hmi-client/src/components/workflow/tera-workflow-node.vue
- packages/client/hmi-client/src/services/workflow.ts
A around of tweaks:
- Adding edge arrow marker, make edges more distinct
- Make tera-workflow-node a bit closer to the design spec
No functional changes, workflow canvas should work as before.
> chore: a round of design-tweaks, add edge arrow marker

- Makefile
Trying to get the new `hmi-extraction-service` container to build and published to github so I can get the orchestration all hooked up.
I'm hoping this fixes this.
> fix: added extraction server to bakefile

- packages/client/hmi-client/src/components/models/tera-model.vue
- packages/client/hmi-client/src/page/data-explorer/components/tera-preview-panel.vue
- packages/client/hmi-client/src/page/project/components/code-editor.vue
- packages/client/hmi-client/src/page/project/components/tera-tab-content.vue
- packages/client/hmi-client/src/page/project/tera-project.vue
I have transferred some functions that were emitted from `tera-tab-content.vue` into an asset component into the actual component (`tera-model` and `code-editor`). Instead of emitting the functions the `project` prop had to be used in these asset components. Also some of the asset components were passed props that aren't even used so I got rid of those.
> refactor: move emit functions where they belong and pass appropriate props (merges into split view)

- packages/client/hmi-client/src/components/models/tera-forecast-launcher.vue
- packages/client/hmi-client/src/components/workflow/tera-calibration-node.vue
- packages/client/hmi-client/src/components/workflow/tera-simulate-node.vue
- packages/client/hmi-client/src/services/models/petri-shim.ts
This just groups the temporary hack in one place where we need to send a "model" over to the simulation-service. Once the model-representations are in and the various converters are in place, this should be removed and we should instead send in a model-id.
> chore: group temp model-clean hack in one place

- packages/client/hmi-client/src/page/project/tera-project.vue
This adds a guard to prevent quirky values getting sent into the API in the project-page.
For some reason the props can be `undefined` or empty string `""` depends on how one navigates to the page, the former will cause an error.
- Navigate from the Home page to Project page, open up publications accordion in the side-pane, no error should occur
- In the project page, refresh the page, open up publications accordion in the side-pane, no error should occur
> fix: add guard to prevent weird prop values

- packages/client/hmi-client/src/components/models/tera-model.vue
changed model math renderer back to live.
> fix: katex to live

- packages/client/hmi-client/src/components/models/tera-model.vue
- packages/client/hmi-client/src/page/project/components/tera-project-page.vue
- packages/client/hmi-client/src/temp/buckyAMR.ts
- packages/client/hmi-client/src/types/AskemModelRepresentation.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/pdfextractionservice/PDFExtractionServiceProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/pdfextractionservice/PDFExtractionResource.java
The Bucky Model is now using the new AMR extraction that we were provided for the thin-thread example.
[buckyAMR.webm](https://github.com/DARPA-ASKEM/Terarium/assets/98172806/c32fd841-5922-4bd1-818c-d4cf381b447a)
> feat: 1114 task add bucky amr thin thread example to model view

- packages/client/hmi-client/src/components/asset/tera-asset.vue
- packages/client/hmi-client/src/components/widgets/tera-tab-group.vue
- packages/client/hmi-client/src/page/project/components/tera-project-overview.vue
- packages/client/hmi-client/src/page/project/tera-project.vue
It was weird having to press the "open project overview" button when you enter a project. This fixes that.
Kudos to @shawnyama for the elegant solution.
> feat: automatically open the project overview page when you open a project

- packages/client/hmi-client/src/page/project/components/tera-project-overview.vue
- packages/client/hmi-client/src/services/project.ts
- packages/client/hmi-client/src/types/Types.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/dataset/Dataset.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/DatasetProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/DatasetResource.java
This fix correctly sends up the expected snake_case to TDS instead of camelCase. A few other odds and ends fixes here as well.
NOTE that this still requires a pt 2 fix in orchestration for setting up buckets correctly for local dev.
Resolves #1200
> fix(hmi): unable to add datasets

- packages/client/hmi-client/src/components/asset/tera-asset.vue
The content switcher was in a bad place. It was greedy for all the space beneath it, leading to situations like this:
This PR moves the content switcher to go beside the overline above the title (if there is one), or just beside the title (if there's no overline).
It doesn't seem to break anything on Models or Datasets
> fix: moved the edit button slot higher

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/dataset/DatasetColumn.java
I don't think this is being used anywhere yet in Terarium, so hopefully is safe to change.
Should match changes in
https://github.com/DARPA-ASKEM/data-service/pull/259.
Let me know if anything else needs to be fixed.
> fix: update dataset columns to reflect change in data service

- packages/client/hmi-client/src/components/dataset/tera-dataset-datatable.vue
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/DatasetResource.java
Adding pagination to dataset table. In addition there is a sneaky fix here for bucket counts on our histograms as requested by @jamiewaese-uncharted 
Resolves #1264
> fix(hmi-client): fixing performance of dataset preview

- packages/client/hmi-client/src/stores/auth.ts
CORS violation occurring on AJAX call for /ua/user.  The Keycloak server has been updated to contain `Web origins: https://app.staging.terarium.ai` but I added this additional code to the AJAX call just in case.
I cannot seem to test locally if this works or not (though it does not seem to produce any errors locally).  If this is needed for staging we will have to deploy and see what happens.
Might help resolve: 
https://github.com/DARPA-ASKEM/orchestration/issues/176
> fix: cors added to ajax call

- packages/client/hmi-client/src/components/widgets/tera-context-menu.vue
- packages/client/hmi-client/src/components/workflow/tera-simulate.vue
- packages/client/hmi-client/src/components/workflow/tera-simulation-workflow.vue
* Update workflow menu items list to differentiate between deterministic & probabilistic sim/calibrate.
* Use disabled menu items for not yet built probabilistic options
* Update simulate drilldown panel header to `Simulate (deterministic)`
Note: since `primevue/contextmenu` does not support headers in the context menu (which is required in the design), a workaround was used to allow the `primevue/menu` component to be used as a contextmenu.
> feat: update workflow menu items and context menu to match design

- packages/client/hmi-client/src/types/XDD.ts
Correct casing on GitHub
Resolves #1170
> fix(hmi-client): consistent formatting in GitHub Repositories facet name

- packages/client/hmi-client/src/page/data-explorer/components/tera-search-results-list.vue
Adding correct indicator.
Resolves #1255
> fix(hmi-client): show indicator on empty search

- packages/client/hmi-client/src/page/data-explorer/components/facets/tera-categorical-facet.vue
After design review with @jamiewaese-uncharted , opting to get rid of denominator since its just the document count and just keep the facet count
Resolves #1277
> fix(hmi-client): facet number wraps

- packages/client/hmi-client/src/components/workflow/tera-calibration-node.vue
Quality of life, model mapping is set upon a model configuration being added.
Watcher on input port -> emit change node's state
https://github.com/DARPA-ASKEM/Terarium/assets/17088680/a9692938-dbe3-4958-90f1-51f3f81eb9e2
> feat: pre populate model mapping

- packages/client/hmi-client/src/assets/css/theme/_variables.scss
- packages/client/hmi-client/src/petrinet/petrinet-renderer.ts
I made adjusted the styling of the nodes in the petrinet diagram:
- grey fill, same as border
- smaller stroke around the text
Also reduced the left and right padding of the input box so it's less annoying
> feat: adjusted styling of nodes in petrinet diagram

- packages/client/hmi-client/src/components/navbar/tera-navbar.vue
Yes, i used an `!important` to overwrite a min-width setting that this menu is inheriting from somewhere. I couldn't find where it was coming from. Feel free to suggest a better way to do this. In the meantime this works, and fixes the unnecessary line wrapping in the navigation menu.
BEFORE
NOW
> feat: fixed ugly line wrapping in navigation menu

- packages/client/hmi-client/src/App.vue
Four small things here: 
1) Made text buttons in footer smaller to make them less prominent
2) Capitalized them because everything in the app is sentence case.
3) Swapped the order of About and Documentation to be alphabetical, and in order of importance
4) I fixed a bug that occurs when you launch the About modal. Currently it tries to load a page in a new tab because of the` href="javascript:void;"` line. You then have to close that tab to see the modal. I removed that and everything's groovy.
ORIGINAL
WITH THIS PR
Here's that bug I fixed by removing the unwanted href:
> feat: smaller buttons in footer, fixed bug when launching About modal

- packages/client/hmi-client/src/components/models/tera-model-diagram.vue
- packages/client/hmi-client/src/components/models/tera-model.vue
* splits up the model page's model diagram and model equation components into 2 separate accordion tabs instead of keeping them side by side
* Video demo: https://capture.dropbox.com/lyE3NspRLCKKmtDR
> fix: separate model diagram and model equations

- packages/client/hmi-client/src/page/project/components/tera-resource-sidebar.vue
- packages/client/hmi-client/src/page/project/tera-project.vue
- packages/client/hmi-client/src/services/project.ts
* Set Resource panel width to 240px to match the width of the Notes panel
* Update the workflows icon
* Have all the Resource panel accordion tabs be "open" by default
* Video demo: https://capture.dropbox.com/DzfIbaqxqwVLjrlU
> fix: minor ui changes to resource sidebar

- packages/client/graph-scaffolder/src/core/renderer.ts
- packages/client/hmi-client/src/components/models/tera-model-diagram.vue
Fix stability and jumpiness issues with model editing via the graph. It seemed like sometime ago we removed the stability checks. This PR brings it back.
- To to a model, click edit, try to add nodes and edges - the viewport should not rest. 
- Cancel edit
> fix: stable zoom/pan

- packages/client/hmi-client/src/services/workflow.ts
Fix disconnect logic so the workflow node does not have weird status like this when you remove node/edge
- add model, add smulate
- connect model to simulate
- remove simulate
> fix: reset port connect status if there are no remaining connections

- packages/client/graph-scaffolder/src/core/renderer.ts
- packages/client/hmi-client/src/model-representation/petrinet/petrinet-renderer.ts
- packages/client/hmi-client/src/model-representation/petrinet/petrinet-service.ts
- fix graph zoom so that it now centers and showing the entire model diagram
- adding equations above the transition node for better visibility
Showing Transition Nodes
https://github.com/DARPA-ASKEM/Terarium/assets/33158416/866aa412-0c71-4b2d-8719-72bc06405c5e
Showing zoom fix
https://github.com/DARPA-ASKEM/Terarium/assets/33158416/0ca04f23-5c48-4786-afac-c4a471df1ef7
https://github.com/DARPA-ASKEM/Terarium/issues/1351
> fix: graph zoom and showing transition equations

- packages/client/hmi-client/src/types/XDD.ts
This is a temporary fix until xdd has paging fixed (And we implement paging).  Restricting our search to 20 items as objects are expensive/slow to retrieve.
> task(hmi-client): restrict xdd search results for performance reasons

- packages/client/hmi-client/src/components/navbar/tera-navbar.vue
- packages/client/hmi-client/src/components/navbar/tera-searchbar.vue
- packages/client/hmi-client/src/page/data-explorer/DataExplorer.vue
* ability to clear your search (search for an empty string)
* adding a url param to determine if we are searching by example or not in order to trigger a route change for the watcher to pickup.  This helps when clearing search when searching by example
https://github.com/DARPA-ASKEM/Terarium/assets/33158416/9a9f0c72-9a55-408d-aa7e-5f1ee539d598
> fix: clear explorer search

- packages/client/hmi-client/src/model-representation/petrinet/petrinet-renderer.ts
AFTER
Yes, I commented out the strokes for now.
> feat: style updates to text in petrinet

- packages/client/hmi-client/src/page/project/components/tera-project-overview.vue
A sticky banner on the overview page is annoying. It's only meant to provide a quick overview of the project contents.
fyi, This PR looks like more code change than there is. All I did was wrap everything in a new div with a class called `.scrollable` and set the `overflow-y` to `auto` and set the `scrollbar-width` to `none`.  I'm not sure why the dif checker is highlighting so many lines.
BEFORE
AFTER
> feat: removed sticky banner from overview page

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/annotations/LogRestClientTime.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/RestClientTimingInterceptor.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/ArtifactProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/ConceptProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/DatasetProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/ExternalProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/ModelConfigurationProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/ModelProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/PersonProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/ProjectProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/ProvenanceProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/SimulationProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/WorkflowProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/documentservice/DocumentProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/documentservice/ESSearchProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/documentservice/ExtractionProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/github/GithubProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/jsdelivr/JsDelivrProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/mira/DKGProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/mit/MitProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/modelservice/ModelServiceProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/simulationservice/SimulationServiceProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/skema/SkemaProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/skema/SkemaRustProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/services/StructuredLog.java
This adds an annotation for recording structured timing logs for all proxy calls in terarium. 
**NOTE: This is a bit annoying/manual but was unfortunately the cleanest way I could get this to work in Quarkus.**
Example usage:
```java
package software.uncharted.terarium.hmiserver.proxies.myservice;
@RegisterRestClient(configKey = "test")
@Path("/hello")
public interface ExternalPerformerProxy {
@Path("/world")
@POST
@LogRestClientTime(group = "external-performer-services")
Response foo(String bar);
}
```
Would output
```
PROXY_REQUEST | adam | foo | software.uncharted.terarium.hmiserver.proxies.myservice.ExternalPerformerProxy | /hello/world | POST | external-performer-services | 104
```
We log:
- `PROXY_REQUEST` identifier
- The username of the user making the proxy, `Anonymous` if it is …
> feat: add structured timing logs for all proxy calls

- packages/client/hmi-client/src/main.ts
- packages/client/hmi-client/src/types/Types.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/EventType.java
This adds a hook on route navigation the measures the time spent on each route and logs it as a transient event.  Example output:
```
2023-07-13 11:28:00,683 INFO  [sof.unc.ter.hmi.ser.StructuredLog] (executor-thread-7) EVENT | adam | Event(id=c47fdb8b-7d05-4b25-a9dc-6723bd9332d9, timestampMillis=1689262080683, projectId=1, username=adam, type=ROUTE_TIMING, value={"name":"project","path":"/projects/1","fullPath":"/projects/1","timeSpent":561})
```
In this case, the user spent 20 seconds on the home screen
> feat: add route timing

- packages/client/hmi-client/src/stores/auth.ts
add the user_id field with either the github user or the anonymous user from keycloak
> feat: add the userid to GA data

- packages/client/hmi-client/src/components/workflow/tera-workflow-node.vue
I added a 75ms transition effect to the box-shadow and node header when hovering over the workflow nodes.
For good performance, I created an ::after element with the box-shadow and then animate the opacity of that instead of animating the box-shadow properties directly. If you're interested, I found the technique here: [https://tobiasahlin.com/blog/how-to-animate-box-shadow/](https://tobiasahlin.com/blog/how-to-animate-box-shadow).
BEFORE
AFTER
It's subtle but it feels more "complete".
> Jamie subtle transition on mouseover of workflow nodes

- packages/client/hmi-client/src/components/models/tera-model.vue
Katex throws errors that prevent application from functioning. This should prevent the errors from being thrown and show the default text if they are not parsable.
> fix: prevent katex errors from crash application

- packages/client/hmi-client/src/components/models/tera-model-configuration.vue
* do not throw an error when the timeseries parameter is undefined
> fix: delete timeseries when undefined

- packages/client/hmi-client/src/components/models/tera-model-configuration.vue
* timeseries variables will now persist when there is no metadata key on the model configuration.  The metadata key will be created
https://github.com/DARPA-ASKEM/Terarium/assets/33158416/664d3ac4-403c-456d-ab1f-28587b931fc5
> fix: persists timeseries variable when there is no metadata on the configuration

- packages/client/graph-scaffolder/src/types/index.ts
- packages/client/hmi-client/src/components/mathml/tera-math-editor.vue
- packages/client/hmi-client/src/components/models/tera-model-diagram.vue
- packages/client/hmi-client/src/model-representation/petrinet/petrinet-service.ts
- packages/client/hmi-client/src/utils/math.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/extractionservice/ExtractionResource.java
Fixes the observable saving problem.  You **have to** make sure your equation contains an `=` sign in order for it to be valid.  It then assigns the left hand variables to the `ID` & `Name` for the `Observable`. 
Also includes other bug fixes such as double click to edit only enabled  in model editing mode and transitions equations not showing up after changing the transition id.
> fix: bug observables equations no saving name

- packages/client/hmi-client/src/components/dataset/tera-dataset-jupyter-panel.vue
Adds the "Auto-expand previews" checkbox to the dataset notebooks like on the models. Miss from last night.
> fix: Add auto-preview selection/default to dataset notebook

- packages/client/hmi-client/src/components/workflow/calibrate-operation-ciemss.ts
- packages/client/hmi-client/src/components/workflow/tera-calibration-ciemss.vue
- packages/client/hmi-client/src/components/workflow/tera-calibration-node-ciemss.vue
* Add timespan to simulate and calibrate node - it can now be populated from the sidepanel rather than it being statically added as `timespan: {start: 0, end: 90}`
> feat: add timespan to simulate and calibrate node

- packages/client/hmi-client/src/components/models/tera-model.vue
* Disable editing functionality for state variables until further discussion
> fix: disable state editing in model description 'State variables' chart

- packages/client/hmi-client/src/model-representation/petrinet/petrinet-service.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/modelservice/StratifyRequest.java
Patrick informed us that flux does not refer to a strata-model, but rather a specific type (location) of strata-model. This PR renames flux to strata to avoid overloading the terminology.
> fix: change flux naming

- packages/client/hmi-client/DEVELOPMENT.md
- packages/client/hmi-client/src/components/asset/tera-asset.vue
- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
- packages/client/hmi-client/src/components/documents/tera-document.vue
- packages/client/hmi-client/src/components/models/tera-model-configuration.vue
- packages/client/hmi-client/src/components/models/tera-model-diagram.vue
- packages/client/hmi-client/src/components/models/tera-model.vue
- packages/client/hmi-client/src/components/models/tera-stratified-model-configuration.vue
- packages/client/hmi-client/src/components/workflow/tera-calibration-ciemss.vue
- packages/client/hmi-client/src/components/workflow/tera-calibration-julia.vue
- packages/client/hmi-client/src/components/workflow/tera-dataset-workflow-wrapper.vue
- packages/client/hmi-client/src/components/workflow/tera-model-workflow-wrapper.vue
- packages/client/hmi-client/src/components/workflow/tera-simulate-ciemss.vue
- packages/client/hmi-client/src/page/data-explorer/components/tera-preview-panel.vue
- packages/client/hmi-client/src/page/project/components/code-editor.vue
- packages/client/hmi-client/src/page/project/components/tera-project-overview.vue
- packages/client/hmi-client/src/page/project/components/tera-project-page.vue
- packages/client/hmi-client/src/types/common.ts
Replace the prop `is-editable` with a `feature-config` object that is clearer and more customizable for configuring the features we want to use depending on the context.
> refactor: replace `is-editable` instances with `feature-config` prop

- packages/client/hmi-client/src/page/project/tera-project.vue
The previous assetName/tab changes accidentally removed the single-tab mechanism we currently have in the drilldown panel. This restores this functionality.
Note the drilldown is acting a bit strange, when opening with different zoom levels on the workflow canvas the tab can be rendered incorrectly. Not exactly sure why.
Goto workflow
- select a node and open drilldown
- should be able to close drilldown
> fix: drilldown tab not showing

- packages/client/hmi-client/src/components/models/tera-stratified-value-matrix.vue
- packages/client/hmi-client/src/model-representation/petrinet/catlab-petri.ts
- packages/client/hmi-client/src/model-representation/petrinet/mira-petri.ts
- packages/client/hmi-client/src/temp/AMRPetriTest.vue
Cleans up field name usage. Previous I have used `_id` and `_base` to avoid naming collisions, but I think this is causing additional confusions elsewhere while avoid a potential problem that is not likely to occur: it is unlikely someone will call a strata "base" or "id". 
I think it is worth the risk here to just use "id" and "base" and avoid developer confusions.
> resolve _id vs id, _base vs base

- packages/client/hmi-client/src/App.vue
- packages/client/hmi-client/src/components/documents/tera-selected-document-pane.vue
- packages/client/hmi-client/src/components/home/tera-project-card.vue
- packages/client/hmi-client/src/page/Home.vue
- packages/client/hmi-client/src/page/data-explorer/components/tera-selected-resources-header-pane.vue
- packages/client/hmi-client/src/page/data-explorer/components/tera-selected-resources-options-pane.vue
- packages/client/hmi-client/src/services/data.ts
- packages/client/hmi-client/src/services/project.ts
- packages/client/hmi-client/src/types/Types.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/Project.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/ProjectResource.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/documentservice/DocumentResource.java
* Change the calls made to `hmi-server` to only get projects, with some metadata about assets counts to avoid to do that job on the front-end
* Reduce to 3 the number of projects to which we fetch Related documents
* Reduct to 8 the number of related documents we fetch per project
Resolves #1668
> bug(client): related documents on home page broken

- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
* There's an issue where any dataset on a project will show all publications in that project under the related publications section
* I followed what we are currently doing with the model related publications which is showing an empty list
* It looks like enrichments for datasets and models aren't being handled correctly so far but this will be addressed in another PR
Showing nothing under related publications
https://github.com/DARPA-ASKEM/Terarium/issues/1670
> fix: dont show all related publications when a dataset is added to a project

- packages/client/hmi-client/src/components/workflow/tera-calibrate-ensemble-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/tera-calibration-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/tera-calibration-node-julia.vue
- packages/client/hmi-client/src/components/workflow/tera-simulate-ciemss-node.vue
- packages/client/hmi-client/src/components/workflow/tera-simulate-ensemble-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/tera-simulate-julia-node.vue
- packages/client/hmi-client/src/services/models/simulation-service.ts
- packages/client/hmi-client/src/types/workflow.ts
* handle poller states when they are not queued, running, or complete - we will create an error for now instead of the node running indefinitely
* some cleanup of the logic and unused variables
> fix: improved error handling on poller

- packages/client/hmi-client/src/components/widgets/tera-related-publications.vue
* send an artifact id when enriching a dataset/model 
* single selection until we can support sending multiple endpoints
https://github.com/DARPA-ASKEM/Terarium/assets/33158416/d19a6cf5-71d4-4fdc-801c-91acf545730b
> fix: send artifact id when enriching dataset

- packages/client/hmi-client/src/components/extracting/tera-drag-n-drop-importer.vue
- packages/client/hmi-client/src/components/widgets/tera-import-github-file.vue
- packages/client/hmi-client/src/components/widgets/tera-tab-group.vue
- packages/client/hmi-client/src/page/project/components/tera-project-overview.vue
- packages/client/hmi-client/src/page/project/components/tera-project-page.vue
- packages/client/hmi-client/src/page/project/components/tera-resource-sidebar.vue
- packages/client/hmi-client/src/page/project/tera-project.vue
- packages/client/hmi-client/src/router/routes.ts
- packages/client/hmi-client/src/services/code.ts
- packages/client/hmi-client/src/services/project.ts
- packages/client/hmi-client/src/types/Project.ts
- packages/client/hmi-client/src/types/Types.ts
- packages/client/hmi-client/src/types/common.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/code/GithubRepo.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/Artifact.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/Assets.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/code/Code.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/CodeProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/CodeResource.java
Adding a new code type asset in the back end, and hooking the front up as-is. This right now is very similar to the old code artifact.
Resolves #1167
> 1167 feat implement new code asset type in back end

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/documentservice/ExtractionProxy.java
For some reason this call returns no results on xdd prod. I've let the xdd team know to look into it
Resolves #1726
> bug(hmi): xDD extractions of images are not coming through

- packages/client/hmi-client/src/components/workflow/tera-calibrate-ensemble-ciemss.vue
- packages/client/hmi-client/src/components/workflow/tera-calibrate-ensemble-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/tera-calibration-ciemss.vue
- packages/client/hmi-client/src/components/workflow/tera-calibration-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/tera-calibration-node-julia.vue
- packages/client/hmi-client/src/components/workflow/tera-simulate-chart.vue
- packages/client/hmi-client/src/components/workflow/tera-simulate-ciemss-node.vue
- packages/client/hmi-client/src/components/workflow/tera-simulate-ciemss.vue
- packages/client/hmi-client/src/components/workflow/tera-simulate-ensemble-ciemss.vue
- packages/client/hmi-client/src/components/workflow/tera-simulate-ensemble-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/tera-simulate-julia-node.vue
- packages/client/hmi-client/src/components/workflow/tera-simulate-julia.vue
* Verified with Five that the `simulation.csv` filename should indeed always be `result.csv` (apparently the change was made about a month ago).
* Also updated some strings to use sentence case as per Jamie's request
> fix: update simulation.csv to result.csv

- packages/client/hmi-client/src/page/data-explorer/components/tera-selected-resources-header-pane.vue
* Fixed an issue where added publications to a project would cause duplicate an empty publication and a blank publication
* removed line of code which added the publications to the project locally but this is no necessary since the project page is reloaded when we navigate to the page
https://github.com/DARPA-ASKEM/Terarium/assets/33158416/7f2a8aed-4add-4445-9c73-57ebef2d5d35
> fix: issue where duplicate and blank publication appears when adding for the first time

- docker-compose.yaml
- packages/client/hmi-client/src/components/dataset/tera-dataset-jupyter-panel.vue
- packages/client/hmi-client/src/components/llm/tera-jupyter-chat.vue
- packages/client/hmi-client/src/components/llm/tera-jupyter-response.vue
- packages/client/hmi-client/src/components/models/tera-model-jupyter-panel.vue
On the dataset transform page, you can now define, preview, save as, and download multiple datasets. The preview and download/save as functions have a drop-down of identified dataframes in the environment.
The LLM will also be able to work with all the datasets, allowing you to ask the LLM to do things like asking the llm to merge two datasets or to compare them in various ways.
> Feature: Handling for multiple datasets

- packages/client/hmi-client/src/python/PyodideController.ts
- packages/client/hmi-client/src/python/PyodideWorker.ts
- packages/client/hmi-client/src/temp/PyodideTest.vue
Make pyodide into single instance, make usage examples a bit bettter
See http://localhost:8078/app/#/pyodide-test
> chore: clean up pyodide usage and initialization

- packages/client/hmi-client/src/components/model/petrinet/tera-model-description.vue
- packages/client/hmi-client/src/components/model/tera-model.vue
- packages/client/hmi-client/src/components/models/tera-model.vue
- packages/client/hmi-client/src/components/widgets/tera-tab-group.vue
- packages/client/hmi-client/src/components/workflow/tera-model-node.vue
- packages/client/hmi-client/src/components/workflow/tera-stratify.vue
- packages/client/hmi-client/src/examples/mira-petri.json
- packages/client/hmi-client/src/examples/sir.json
- packages/client/hmi-client/src/model-representation/petrinet/petrinet-service.ts
- packages/client/hmi-client/src/page/data-explorer/components/tera-asset-card.vue
- packages/client/hmi-client/src/page/project/components/tera-model-modal.vue
- packages/client/hmi-client/src/page/project/components/tera-project-overview.vue
- packages/client/hmi-client/src/page/project/components/tera-project-page.vue
- packages/client/hmi-client/src/page/project/components/tera-resource-sidebar.vue
- packages/client/hmi-client/src/services/data.ts
- packages/client/hmi-client/src/services/models/stratification-service.ts
- packages/client/hmi-client/src/types/Types.ts
- packages/client/hmi-client/src/utils/data-util.ts
- packages/client/hmi-client/src/utils/facets.ts
- packages/client/hmi-client/tests/unit/model-representation/petrinet/petrinet.spec.ts
- packages/client/hmi-client/tests/unit/services/stratification-service.spec.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/Model.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/modelparts/ModelHeader.java
This address various parts that need to be converted to use `amr.header` format.
Note the tabs/summary portions are rather janky, they need to be re-addressed by having a better unified summary endpoint instead of doing specialized parsing.
> chore: amr header fixes

- packages/client/hmi-client/src/components/model/petrinet/tera-model-equation.vue
- packages/client/hmi-client/src/components/models/tera-model-diagram.vue
- packages/client/hmi-client/src/services/knowledge.ts
- packages/client/hmi-client/src/types/Types.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/extractionservice/ExtractionResponse.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/extractionservice/ExtractionResponseResult.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/knowledgemiddleware/KnowledgeMiddlewareProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/knowledgemiddleware/KnowledgeResource.java
* Update the api to correctly call `/equations-to-amr` endpoint
Resolves #1770
> Equations to model

- packages/client/hmi-client/src/services/data.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/DatasetResource.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/ModelResource.java
- Increase page size limit so the client search can work, previously this was bringing back 100 models when we have over 400 models.
- Fix AMR header structure change for model search
Data-explore model search "works" in that it doesn't always return blank when you have a search term, e.g. "SIR".
> increase size limit to allieviate search issues

- packages/client/hmi-client/src/App.vue
* fix so that the project name  in the top left dropdown when navigating to the explorer
* a small sneaky fix here, since the active project is stored in the resource store we need to set the active project to null using the mutation rather than directly setting the project to null
BEFORE:
https://github.com/DARPA-ASKEM/Terarium/assets/33158416/ab0ca340-ed2d-45b6-8a80-c140d264a2a1
AFTER:
https://github.com/DARPA-ASKEM/Terarium/assets/33158416/3721b91d-2808-467d-aa91-9c370bd39ae6
https://github.com/DARPA-ASKEM/Terarium/issues/1674
> fix: explorer nav dropdown

- packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-node-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-julia/tera-calibrate-node-julia.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-node-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-julia/tera-simulate-node-julia.vue
The error messages are not on TDS for us to pull but at least this lets the user know that the simulation failed
> feat: toaster on node failure 

- packages/client/hmi-client/src/composables/project.ts
Avoids 404 error on home page when projects are fetched. Error was caused by passing an empty project id to `getAssets`
> fix: avoid passing empty project id to `getAssets`

- packages/client/hmi-client/src/components/widgets/tera-slider.vue
Proper border in side panel footer. Also using outline rule for panels is a lot more simpler - takes care of open and closed states.
Box shadow rule was determined by tera-asset headers box shadow.
> style: sidepanel footer css

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelConfigurationController.java
Was getting the following error when making a post request to `http://localhost:8080/api/model_configurations`:
```
{
"timestamp": "2023-10-04T18:34:02.816+00:00",
"status": 500,
"error": "Internal Server Error",
"trace": "java.lang.IllegalArgumentException: No serializer found for class java.lang.Object and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)...",
"message": "No serializer found for class java.lang.Object and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)",
"path": "/model_configurations"
}
```
Specifying the param type fixed it for me.
> fix model_configurations post request param type

- packages/client/hmi-client/src/api/api.ts
Ensure that we redirect to the login screen on 401's with the redirect URI back to where we currently are.
> fix: ensure we login after idle timeouts or on 401s

- packages/client/hmi-client/src/services/artifact.ts
Previously failing to create an artifact due to a client side typo
> fix: call type for artifacts

- hmiServerDev.sh
* Point start script to gradle wrapper instead of system gradle.
Resolves #1984
> fix(hmi-server): Use correct gradle for startup script

- packages/client/hmi-client/src/main.ts
This address a problem where refresh a page that is not the home-page results in a redirection back home.
- Login
- Goto any project page
- Refresh the page, should remain in the same project page with login/credentials intact
> fix: do not change route if name/path exists

- packages/client/hmi-client/src/components/documents/tera-document-asset.vue
- packages/client/hmi-client/src/page/project/components/tera-project-overview.vue
- packages/client/hmi-client/src/page/project/components/tera-upload-resources-modal.vue
- packages/client/hmi-client/src/services/document-assets.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DocumentController.java
Txt is now a document not an artifact:
Utilizing the code editor for txt files
> chore: project assets for text files are now documents (not artifacts)

- packages/server/src/main/resources/application.properties
* Increased the maximum size upload to 100MB
* Resolves #1995
> fix(hmi-server): Increase max upload size for files

- packages/client/hmi-client/src/page/data-explorer/components/tera-asset-card.vue
- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/documentservice/XDDDocumentController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/documentservice/Document.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/documentservice/KnownEntitiesCounts.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/proxies/documentservice/DocumentProxy.java
- packages/server/src/test/java/software/uncharted/terarium/hmiserver/controller/xdd/XDDTests.java
* Leveraging new xDD api to limit returned extractions
* Thumbnails are now limited to 5 with total extractions displayed in brackets
* Extractions in document are not affected.
* New Test
Resolves #1993
> 1993 feat limit xdd extraction previews for performance

- packages/client/hmi-client/src/components/asset/tera-asset.vue
- packages/client/hmi-client/src/page/project/components/tera-project-overview.vue
Note the background fills the bottom with white. Before the banner background was used as the main background. The banner background is moved to the header of `tera-asset.vue` when Overview is chosen.
> style: simplify overview page - make banner fit in the actual header

- packages/client/hmi-client/src/components/model/petrinet/tera-model-editor.vue
When the model diagram was closed and the model was changed via equations it would re-render the graph. The issue is the graphElement had height and width of 0 due to the acc being closed.
When reopened it would not re-render and the model changes were not displayed (specifically going from nothing to a model)
This tag means this section will only render when opened 
https://github.com/DARPA-ASKEM/terarium/assets/17088680/14359448-3693-42b3-9284-23949183cb64
> Fix: acc closed, diagram changed, acc opened, no change

- packages/client/hmi-client/src/page/project/components/tera-upload-resources-modal.vue
**It should be noted, that this does not solve the problem of viewing these assets. That is being done under a different issue and different branch.**
Some file types are not recognized.
For example .md files and .java files being read  as a `HTMLInputElement.files` has no `types`
Rather than checking this types field which is unreliable lets check the extension on the filename allowing us to actually handle these scenarios
> checking file extensions. some file types not rec

- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
- packages/client/hmi-client/src/components/model/tera-model.vue
- packages/client/hmi-client/src/composables/project.ts
- packages/client/hmi-client/src/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ciemss/tera-simulate-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-julia/tera-simulate-julia.vue
* Fix a bug where the project name is showing in the top left when navigating from a project to the home or explorer page.
* needed to set the active project as null when we navigate to these pages
* separate get and refresh function for a project in the useProjects composable.
https://github.com/DARPA-ASKEM/terarium/assets/33158416/5947f677-9c31-4167-9dee-7a113a6c78a7
> fix: project name nav

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/proxies/mira/MIRAProxy.java
* small issue where MIRA endpoints needs the `/api/` in their calls: http://34.230.33.149:8771/docs#/
> task: update MIRAProxy.java

- packages/client/hmi-client/src/components/model/petrinet/tera-model-configurations.vue
* fixed an issue where you couldn't edit the first model config
* close modal when updated model config
> fix: edit model configs

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DocumentController.java
* Added catch all exceptions rather than just IOExceptions.  This will make it so that errors in extracting images aren't blocking errors
* see this [thread](https://unchartedsoftware.slack.com/archives/C049E6PA16V/p1698332262399659), there seems to be an error in in staging only.  image -> equations will need to be addressed, but this is a fix so that it is non blocking
> fix: catch general document error if there's an error processing equation images

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ProjectController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/Project.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/ProjectProxy.java
Projects can now be renamed. The `@Override` in `Project.java` was the culprit - it was reformatting the request body. I don't know what that override could have been used for but it doesn't seem like it's used anywhere now.
https://github.com/DARPA-ASKEM/terarium/assets/28237258/bfd61441-07f9-4328-ae2c-1fbb4535b39f
> fix: project rename

- packages/client/hmi-client/src/components/asset/tera-asset.vue
- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
- packages/client/hmi-client/src/components/documents/tera-document-asset.vue
- packages/client/hmi-client/src/components/model/tera-model.vue
- packages/client/hmi-client/src/components/widgets/tera-progress-spinner.vue
- packages/client/hmi-client/src/workflow/tera-workflow.vue
* Adding a spinner when navigating to a document, this endpoint does take a while to show - so giving a sense of progress here.
* I figure it wouldn't hurt to add a simple spinner component here and we can define its size.
* Added a snippet of text for the scenario when pdf-extractions haven't completed.  This can probably be refactored when we work on [this](https://github.com/DARPA-ASKEM/terarium/issues/2069) and can listen to these async job properly
https://github.com/DARPA-ASKEM/terarium/assets/33158416/3d58f563-3b74-46eb-9fb9-cb050789a265
> task: spinner for documents

- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/funman/FunmanController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/funman/FunmanPostQueriesRequest.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/funman/parts/FunmanConfig.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/proxies/funman/FunmanProxy.java
- packages/server/src/main/resources/application.properties
- Replacement for the other 1889 PR this aims to simplify by not trying to keep up with the "fluid" responses and just use jsonnode
- Changing config -> parts and using base folder for request type to follow convention
- Keeping other PR available rather than overwriting is as im currently having trouble connecting to and testing Funman. Safety is handy
> Task: Adding FUNMAN basic APIs into hmiserver.

- packages/client/hmi-client/src/components/documents/tera-document-asset.vue
- packages/client/hmi-client/src/components/documents/tera-external-publication.vue
Non paywall papers stop spinning
Showing the github link and other lacking attributes in the project view is a part of a bigger problem that should be handled in its own PR. 
When a document is added to a project is gets processed through the function `createDocumentFromXDD`. This adds the document into the project in a different format than what is seen in the Data Explorer. It turns a `Document` into a `DocumentAsset`. `DocumentAsset` doesn't have a property for github urls and it isn't clear where it and other properties would belong.
https://github.com/DARPA-ASKEM/terarium/assets/28237258/3ee3379c-f22c-45f8-bcb3-014daef7485c
> fix: shows if non unpaywall paper is not found

- packages/client/hmi-client/src/components/widgets/tera-related-documents.vue
- packages/client/hmi-client/src/services/knowledge.ts
* Separate variable extraction from alignment
* Offer the choice of running either SKEMA or MIT extraction
> task: separate enrichement alignement and extractions

- packages/client/hmi-client/index.html
- packages/client/hmi-client/src/main.ts
There is a race condition in vue-router that can cause it to leave keycloak hash state laying around.  A proposed solution
(https://github.com/keycloak/keycloak/issues/14742#issuecomment-1312547429) suggests moving the keycloak initialization into a `<script>` element.  This works and, as an added bonus, seems to really improve the performance of the application.
> fix: ensure keycloak-js and vue-router do not interfere with eachother

- packages/client/hmi-client/src/page/project/components/tera-resource-sidebar.vue
This can happen when assets of different types share the same id:
I had to check for `pageType` so now the proper one will be highlighted
> fix: recognize page type when an asset is highlighted on the sidebar

- packages/client/hmi-client/src/page/project/components/tera-project-overview.vue
- packages/client/hmi-client/src/page/project/components/tera-resource-sidebar.vue
Maintain open and closed resource tabs with localstorage. I investigated other methods but they didn't work. 
Also fixed how the overview page opens assets - extra unused params were being passed before.
https://github.com/DARPA-ASKEM/terarium/assets/28237258/2362dce2-7dde-477c-b79c-2be8c22902b8
> feat: maintain open closed resource tabs using localstorage

- packages/client/hmi-client/src/services/model.ts
- packages/client/hmi-client/src/services/models/simulation-service.ts
Provisional support for running stock-and-flow and regnet model frameworks through the simulate operation. Technically this can be merged without impacting any existing functions, to to actually run RegNet and StockFlow it depends on the CIEMSS refactor. 
RegNet and StockFlow simulate can be tested with this branch from CIEMSS here:
https://github.com/DARPA-ASKEM/pyciemss-service/pull/50
> Provisional regnet stockflow support

- packages/client/hmi-client/src/services/models/simulation-service.ts
- packages/client/hmi-client/src/types/Types.ts
- packages/client/hmi-client/src/workflow/ops/calibrate-julia/tera-calibrate-node-julia.vue
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/SimulationController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/simulationservice/ScimlStatusUpdate.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/SimulationEventService.java
* Changing sse for sciml calibrate to not broadcast to everyone, but instead, only broadcast to specific users.
* Created a POJO for the intermediate results for sciml calibrate to make it a bit easier to manage queues on the back end (And the front end gets a nice object too!)
* This will have to be replicated to pyciemss when we get there.
Because of the stabiltiy issues on the staging sciml, @Jami159 has helped me debug and confirm this is working as expected.
Resolves #2165
> 2165 finishing sse feedback

- packages/client/hmi-client/src/main.ts
- packages/client/hmi-client/src/services/ClientEventService.ts
* For some reasons the `hmi-server` might answer a 503 to the `hmi-client` to the `/api/client-event` endpoint.
* I updated the error status code test to include all `5XX`.
* I added a couple of console.log to explain the issue with the retry times.
* I removed the `init()` call in `main.ts` as the *reconnecting* heartbeat does it anyway, which might produce some conflict.
> fix: sse reconnecting too often

- packages/client/hmi-client/src/services/ClientEventService.ts
- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/configuration/Config.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/ClientEventService.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/SimulationEventService.java
- packages/server/src/main/resources/application.properties
* Removing the silencing of some errors. these errors mean something!
* Reverting change to ClientEventService.ts which resulted in `init()` being spammed every second
* Queues should not be exclusive. This will require us to blow away queues on rabbitmq after this merge
* Queues are not durable.
* Maps of connections and users should be concurrent safe.
> SSE and mq improvements

- packages/client/hmi-client/src/services/workflow.ts
- packages/client/hmi-client/src/utils/emitter.ts
- packages/client/hmi-client/tests/unit/utils/emitter.spec.ts
Factor out the event-emitter into its own class and added a few unit tests. 
Aside from better separation of concerns,  we may also want to consider using an event-emitter to wrap a better closure around events we send to the beaker_kernel: because requests and responses are asynchronous, it isn't entirely obvious which response match to which request.  With an event-bus like mechanism, we may be able to do something like this:
```
sendKernelRequest( createStratifyRequest( ... ) )
.on('stratification-response', updateCodeCallback)
.on('model-preview', updateModelCallback);
```
Run `yarn workspace hmi-client run test`
> chore: factor out event-emitter, add unit tests

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DocumentController.java
* Fixed an issue where null images on an XDD image would break the `createDocumentFromXDD` endpoint
> fix: null image extractions

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/documentservice/XDDDocumentController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/proxies/documentservice/DocumentProxy.java
* Parameter Name Change
Resolves #2218
> [fix: hmi-server] Use askem_object_limit instead of entity_limit with xdd

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/permissions/UsersController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/security/KeycloakJwtAuthenticationConverter.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/DataInitializationService.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/utils/rebac/ReBACService.java
Keycloak is the canonical source of Users and Roles.  The extra overhead of duplicating this in an additional Postgres is curious, but the fact that Keycloak is not treated as the canonical source is troubling.
> treat keycloak as canonical source

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/configuration/TerariumEnvPostProcessor.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/ClientEventType.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/ClientEventService.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/SimulationEventService.java
- packages/server/src/main/resources/application.properties
This is some back end legwork.
* Adding safety to message parsing
* Better error message for problems parsing
* Sciml and pyciemss now use individual queues
* Some safety code in case someone's hostname is staging or production. This isn't an exhaustive safety plan but enough to stop an accident ;)
* Note that this will break sciml messages from coming in in the current form as the sciml service is hard coded against a specific queue name. However since thats all broken anyway, its not a big loss ;)
@Jami159 you'll need to hard code your queue name locally though until part two of this is in
Resolves #2239
> [fix: hmi-server] Add safety code to sciml message reading

- packages/client/hmi-client/src/components/code/tera-code.vue
- packages/client/hmi-client/src/components/code/tera-directory.vue
* just some small tweaks so that the filter header on the directory and the header for the code container are fixed to the top
https://github.com/DARPA-ASKEM/terarium/assets/33158416/4c2f969d-7ff7-4d7b-b664-6fce9a4162ef
> chore: code asset styling tweaks

- packages/client/hmi-client/src/page/project/components/tera-resource-sidebar.vue
- packages/client/hmi-client/src/page/project/tera-project.vue
If you remove an asset that is currently opened it will now redirect to the overview page instead of staying at the deleted asset.
https://github.com/DARPA-ASKEM/terarium/assets/28237258/1c2d0e68-1ac9-4939-b595-fe9b92794b6f
> fix: redirect to overview page if you removed an asset that's currently opened

- packages/client/hmi-client/src/services/workflow.ts
- packages/client/hmi-client/src/workflow/operator/tera-operator-inputs.vue
- packages/client/hmi-client/src/workflow/operator/tera-operator-outputs.vue
- packages/client/hmi-client/src/workflow/ops/dataset/tera-dataset-node.vue
- packages/client/hmi-client/src/workflow/tera-operator.vue
Addressing @YohannParis comments from after the merge https://github.com/DARPA-ASKEM/terarium/pull/2276
Instead of using `isEmpty` I do a `display: none` for inputs/outputs when they are empty since they add there own padding/margin regardless
> refactor: tweaks to operator outputs

- packages/client/hmi-client/src/utils/emitter.ts
- packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-node-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-julia/tera-calibrate-julia.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-julia/tera-calibrate-node-julia.vue
- packages/client/hmi-client/src/workflow/ops/dataset-transformer/tera-dataset-transformer.vue
- packages/client/hmi-client/src/workflow/ops/model-transformer/tera-model-transformer.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ciemss/tera-simulate-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-node-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-julia/tera-simulate-julia.vue
- packages/client/hmi-client/src/workflow/ops/simulate-julia/tera-simulate-node-julia.vue
- packages/client/hmi-client/src/workflow/ops/stratify-mira/tera-stratify-mira.vue
- packages/client/hmi-client/src/workflow/tera-workflow.vue
Mostly consolidate how events are passed - right now we have a mix of using event-emitters for bubbling up events, and using an event-bus for broadcasting across the Vue-app. This is a legacy architecture when some components were co-located and some where not.
Here we consolidate as much as we can, favouring using the vue-emit rather than the event-bus.
They are kind of the same thing with respect to the designs we have at this stage, but the idea is to pick a single method to make the logic and implementation easier to follow, less error-prone, and to indicate a more de-facto way of handling things rather than having mixed modalities. 
TODO: Once this has been achieved we can then further refactor and significantly simplify the vue-templates, and also make things more systematic to add …
> start consolidating events

- packages/client/hmi-client/src/services/workflow.ts
- packages/client/hmi-client/src/types/workflow.ts
- packages/client/hmi-client/src/workflow/tera-workflow.vue
`isOptional` property for the `WorkflowPort` is a mandatory property now.
> fix: `isOptional` prop for `WorkflowPort` is not optional

- packages/client/hmi-client/src/workflow/ops/code-asset/tera-code-asset-node.vue
- packages/client/hmi-client/src/workflow/ops/dataset/tera-dataset-node.vue
- packages/client/hmi-client/src/workflow/ops/model/tera-model-node.vue
- packages/client/hmi-client/src/workflow/tera-workflow.vue
Using `<component>` to instantiate the drilldown-components dynamically. This will:
- Keep the size of the template section nearly constant
- Allows for a more plug-and-play style: we can import components at runtime via `await import(path_to_component)` and add them into the registry
- Better enforcement of behaviours across components
Next up are the operation-nodes, they will need to go through some major refactoring, as some of them have the the core-logic embedded in the nodes and need to be shifted to the drilldowns. 
Also: 
- I also cleaned out the Julia stratify from the workflow.
- Cleaned out droppedAssetId hook to set the state, we can directly set the state on node-creation
No functional changes, workflow should work as before.
> feat: dynamic component routing for operation drilldown

- packages/client/hmi-client/src/workflow/ops/code-asset/tera-code-asset-node.vue
- packages/client/hmi-client/src/workflow/ops/dataset/tera-dataset-node.vue
- packages/client/hmi-client/src/workflow/ops/model/tera-model-node.vue
- packages/client/hmi-client/src/workflow/tera-workflow.vue
This PR continues previous clean ups to have the operations beahviours closer to each so they can be reasoned with at a higher level and not be worried about the inner-workings.
- Cleans up bespoked events, such as `select-code-asset`, `select-dataset` and rolls them under the common messaging scheme (update-state, append-output-port, append-input-port).
- Cleans up special props, project specific resources are derived within the operations rather than outside.
TODO: The registry introduced in previous PR (https://github.com/DARPA-ASKEM/terarium/pull/2300) will be expanded to house the operation-nodes as well
No functional changes. Workflow will behave in the same manner as before.
> chore: workflow project resource cleanup

- packages/client/hmi-client/src/components/stratification/tera-stratification-group-form.vue
- packages/client/hmi-client/src/workflow/ops/stratify-mira/stratify-mira-operation.ts
- packages/client/hmi-client/src/workflow/ops/stratify-mira/tera-stratify-mira.vue
This PR adds the ability to stratify a model via the drilldown using the wizard or the notebook.
- if model is stratified via the wizard, then the executed code is reflected in the notebook
- if model is stratified via the notebook, then it is not reflected in the wizard -> there is a warning box stating this
- if models are stratified either via wizard or notebook, then a new output port is added to the stratify node
- if models are explicitly saved, then they are added to the project
Demo video: https://capture.dropbox.com/SBfR4JKnqO5xBEV0
Resolves #2279
> Add notebook functionality to Mira Stratify

- packages/client/hmi-client/src/services/workflow.ts
- packages/client/hmi-client/src/workflow/tera-workflow.vue
Use the registry to encapsulate all components we have on the workflow.
Minor clean up of leftover workflowEventBus callbacks
No functional changes unless I made a typo somewhere when registering the components. Workflow should behave the same as before.
> feat: workflow operation registry

- packages/client/hmi-client/src/components/drilldown/tera-drilldown-preview.vue
- packages/client/hmi-client/src/components/drilldown/tera-drilldown.vue
- packages/client/hmi-client/src/components/drilldown/tera-ops-preview.vue
- packages/client/hmi-client/src/workflow/tera-workflow.vue
* Layout & behaviour for tera-drilldown
* Preview section for tera-drilldown
This idea for this ticket is to create a generalized format for the `tera-drilldown `component
We can add as many tabs as we want by adding the `tabName` prop to a top level element under `tera-drilldown` 
In this example we have added three tabs to the drilldown called ("Tab 1", "Tab 2", "Tab 3")
```
<tera-drilldown>
<div tabName="Tab 1"></div>
<section tabName="Tab 2"></section>
<section tabName="Tab 3"></section>
</tera-drilldown>
```
Taking this further inside each tab, every top level component will be shown in its own evenly-space columns:
In this example. Tab 1 would be split into 3 evenly spaced columns, Tab 2 into 2 evenly spaced columns, and Tab 3 in one column which takes up the entire drilldown.
``` …
```
> Drilldown layout, behaviour, and preview

- packages/client/hmi-client/src/workflow/ops/funman/tera-funman.vue
* Just surrounding funman with a single div so that the layout is okay with the new tera-drilldown component
> fix: funman layout

- packages/client/hmi-client/src/workflow/tera-operator.vue
- packages/client/hmi-client/src/workflow/tera-workflow.vue
For some odd reason, `canDrag` prop is causing unnecessary refreshes within the operator components (embedded tera-simulate-charts are refreshing when moving-in  and moving-out of the canvas). 
While the refreshing problem is still under investigation, upon closer look we can remove and simplify the canDrag logic; and also removed unused props while I am in the area.
No functional changess, can drag operator nodes as normal.
> chore: cleanup drag in tera-operator

- packages/client/hmi-client/src/types/workflow.ts
- packages/client/hmi-client/src/workflow/ops/model-config/mod.ts
- packages/client/hmi-client/src/workflow/ops/model-config/model-config-operation.ts
- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config-node.vue
- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config.vue
- packages/client/hmi-client/src/workflow/ops/model/model-operation.ts
- packages/client/hmi-client/src/workflow/ops/model/tera-model-node.vue
- packages/client/hmi-client/src/workflow/ops/model/tera-model-workflow-wrapper.vue
- packages/client/hmi-client/src/workflow/tera-workflow.vue
Just the plumbings for the model-configuration operator. 
We still need to
- Implement config operator-node
- Implement config operator-drilldown 
- Amend model operator-drilldown
Note I introduced a new import syntax/semantic to try to make things a bit more readable in tera-workflow component (e.g. cleaner import). Let me know if this sits well with everyone.
```
import { ModelConfigOperation as operation } from './model-config-operation';
import node from './tera-model-config-node.vue';
import drilldown from './tera-model-config.vue';
const name = operation.name;
export { name, operation, node, drilldown };
```
> feat: model config operator

- packages/client/hmi-client/src/workflow/tera-operator.vue
We have to use the :deep selector to apply the same styles to the children. We want the styles to just be applied to the direct list element child not all children. Using native css nesting helps managing this easier.
> style: use native css nesting for easier operator input/output style management

- packages/client/hmi-client/src/assets/css/theme/_variables.scss
- packages/client/hmi-client/src/components/drilldown/tera-drilldown-header.vue
- packages/client/hmi-client/src/components/drilldown/tera-drilldown.vue
* Fix the drilldown header height and move the documentation link based on wether there are tabs or not
* documentation link is optional
https://github.com/DARPA-ASKEM/terarium/assets/33158416/da8d7a82-b283-4719-b008-b8dcc217f680
> Fix drilldown header height

- packages/client/hmi-client/src/components/model/tera-model-jupyter-panel.vue
- packages/client/hmi-client/src/workflow/ops/model-transformer/model-transformer-operation.ts
- packages/client/hmi-client/src/workflow/ops/model-transformer/tera-model-transformer.vue
- packages/client/hmi-client/src/workflow/ops/stratify-mira/stratify-mira-operation.ts
- packages/client/hmi-client/src/workflow/ops/stratify-mira/tera-stratify-mira.vue
This PR aims to resolve some of the logical discrepancies between model and model-configuration. 
For example, to change the model structure we are passing the operators the model-configuration, but in the operators we are using the model-configurations to get their respective models anyway. 
Impacted operators:
- model-transform
- mira-stratification
Can make connections from model to the operators specified above.  Note because of stability issues the operators may not be running properly.
> fix: rewire operations to use modelId instead of modelConfigurationId

- packages/client/hmi-client/src/services/workflow.ts
- packages/client/hmi-client/src/workflow/ops/code-asset/code-asset-operation.ts
- packages/client/hmi-client/src/workflow/ops/code-asset/tera-code-asset-node.vue
- packages/client/hmi-client/src/workflow/ops/dataset/tera-dataset-node.vue
- packages/client/hmi-client/src/workflow/ops/model-from-code/model-from-code-operation.ts
- packages/client/hmi-client/src/workflow/ops/model/tera-model-node.vue
- packages/client/hmi-client/src/workflow/tera-workflow.vue
> feat: code to model accepts code id

- .vscode/extensions.json
- .vscode/launch.json
- .vscode/settings.json
- README.md
- hmiServerDev.sh
This adds the recommended extensions to properly run the project in VSCode, as well as disabling the gradle extensions build server which causes lots of headaches with the debugger.
Fix issue in hmiServerDev.sh pulling the wrong containers depending on the deployment arg.
> docs: update readme, add vscode project files.

- packages/client/hmi-client/src/workflow/ops/stratify-mira/tera-stratify-mira.vue
This makes it possible to use the models out of mira-stratify operator
Connect model to stratify, run stratify, save-model.
The saved model should be both available in the output of the operator, as well as within the project resources.
> feat: output port for mira-stratify

- packages/client/hmi-client/src/services/workflow.ts
- packages/client/hmi-client/src/workflow/tera-workflow.vue
Generate context menu from specification rather than manually spec'ing them out, this reduces replicated code and also unifies the displayed names of operators across different application context. 
Note the number of menu items are growing, and we will need to revisit the designs, however it is considered to be out-of-scope here in this PR.
Some naming may have changes (e.g. capitalization) due to using standard `operator.displayName`, but otherwise no functional changes. Workflow behaves in the same manner as before.
> refactor: generate context menu from specification

- packages/client/hmi-client/src/workflow/ops/model-from-code/tera-model-from-code.vue
* generate model from code asset in model from code operator
https://github.com/DARPA-ASKEM/terarium/assets/33158416/5491c718-16ad-49c6-a8aa-3d942b2eeb84
> task: generate model from code asset

- packages/client/hmi-client/src/services/models/funman-service.ts
Funman traj was pushing a lot of incorrect timesteps due to ugly string manip to get timesteps
Change how we are getting these trajs
> task: fix funman traj manip

- packages/client/hmi-client/src/assets/css/theme/_fonts.scss
- packages/client/hmi-client/src/assets/css/theme/_variables.scss
- packages/client/hmi-client/src/assets/css/theme/designer/components/panel/_accordion.scss
- packages/client/hmi-client/src/assets/css/theme/extensions/_accordion.scss
- packages/client/hmi-client/src/components/model/petrinet/model-diagrams/tera-model-diagram.vue
- packages/client/hmi-client/src/components/navbar/tera-navbar.vue
- packages/client/hmi-client/src/components/operator/tera-operator-header.vue
- packages/client/hmi-client/src/components/widgets/tera-slider-panel.vue
- packages/client/hmi-client/src/page/Home.vue
- packages/client/hmi-client/src/page/data-explorer/DataExplorer.vue
- packages/client/hmi-client/src/page/data-explorer/components/tera-filter-bar.vue
- packages/client/hmi-client/src/page/project/components/tera-resource-sidebar.vue
- packages/client/hmi-client/src/page/project/tera-project.vue
* Work with @jamiewaese-uncharted to fix small paper-cuts
* Move the search bar from the header to the data-explorer
> Design paper-cuts

- packages/client/hmi-client/src/services/jupyter.ts
- packages/client/hmi-client/src/workflow/ops/model-coupling/tera-model-coupling.vue
- packages/client/hmi-client/src/workflow/ops/model-edit/tera-model-edit.vue
- packages/client/hmi-client/src/workflow/ops/model-from-code/tera-model-from-code.vue
- packages/client/hmi-client/src/workflow/ops/stratify-mira/tera-stratify-mira.vue
This PR handles two things:
- Instead of returning null if kernel-session-manager's sendMessage fails, throw an error. This makes the fluent interface a bit less gnarly to read. Instead of `sendMessage(...)?.register`, now it is just `sendMessage(...).register`
- I noticed we send a lot of extra, unneeded messages (e.g. reset) for model-edit, this cleans them up
No functional changes, can test with one or more operators that leverages the kernel session manager. 
For model-edit: 
- pipe in a model to model-edit operator, 
- in the notebook we can override with an empty mira-model-template
```
model = TemplateModel(
templates = [],
parameters = {},
initials = {},
observables = {},
time = Time(name = "t", units = None),
annotations = Annotations(name = "PetriNet model created by a user")) …
```
> fix: fluent interface kernel session

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/TerariumApplication.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/configuration/TerariumWebConfiguration.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/configuration/TrustedEndpointsFilter.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/internal/InternalController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/security/SecurityConfig.java
- packages/server/src/main/resources/application.properties
Stands up the `hmi-server` listening on two ports (by default `3000` (secure) and `3001` (insecure))
Adds `InternalController` that serves requests to URL that start with `/internal/`
Adds functionality to allow only calls on `3001` to route to `/internal/`
Calls to `/internal/` from `3000` will fail (with 403)
Calls to not `/internal/` from `3001` will fail (with 403)
To test: `curl -v localhost:3001/internal/projects/<project-id> | jq`
> Inital proof of concept

- packages/client/hmi-client/src/workflow/ops/model-coupling/tera-model-coupling.vue
Instead of using model_0, model_1, ... model_n as variables, derive more meaningful names from the model header and output information as code comment into the notebook tab.
Also did a few general cleanup in the space.
No functional change, below code should still work - you may need to change the names to match.
```
ice_dynamics_composition_diagram = @relation () begin
dynamics(Γ,n)
stress(Γ,n)
end
ice_dynamics_cospan = oapply(ice_dynamics_composition_diagram,
[
Open(halfar, [:Γ,:n]),
Open(glen, [:Γ,:n])
]
)
decapode = apex(ice_dynamics_cospan)
```
> chore: general clean up, show available names in comments

- packages/client/hmi-client/src/workflow/tera-workflow.vue
The current relinking scheme has a bug, that for a given port, it finds the "first" bad edge and fixes its position, it should find "all" bad edges and relink all of them.
You can test this scenario if you directly change the edge attributes in the workflow document in ElasticSearch, as the instances I found have been fixed already via testing.
> fix: edge relink skipping candidate edges

- packages/client/hmi-client/src/workflow/ops/funman/tera-funman.vue
Slowly getting beefing up Funman, the first part is to make it easier to setup tests, the next parts will be to improve output-UI and get the output dropdown into the drildown component.
- Bring Funman operator to a state where we can repeatedly test it (using last element instead of 0-th element in the output)
- Use poller instead of hand-rolled setTimeout, poller has better mechanisms to self terminate if something goes awry
> chore: funman cleanup

- packages/client/hmi-client/src/workflow/ops/funman/funman-operation.ts
- packages/client/hmi-client/src/workflow/ops/funman/tera-funman.vue
Bring Funman closer to existing operator paradigm and the design specification.
- Adding in the output dropdown/switcher
- UI tweak to make selecting "interested variables" more usable using a multi-select
- Fix state saving and restoration bugs, add requestParameters into saved state spec
- Harden some of the state typing; remove extraneous checks
- Consolidate usage between model-configuration and model - we don't really need to fetch model
- Misc cleanups
There is a bit of a change in terms of how states are handles, rather than proxying state directly, state values are copied into separate refs, and are initialized in the setModelOptions function. This is to facilitate switching between different output-ports, as well it makes it a little easier to write changes back into the actual …
> chore: funman hardening part 2

- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config-editor.vue
Decimal input wasn't working for what seems to be a known issue with primevue InputNumber: https://github.com/primefaces/primevue/issues/1881
Resolves #2493
> Fix decimal input not working for model config drilldown

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/proxies/funman/FunmanProxy.java
- packages/server/src/main/resources/application.properties
Modify the URL to match how the param/var are passed in in orchestration configs.
@dgauldie @dvince2 This need to be ported to the migration branch.
> fix: reroute funman-url to match orchestration

- packages/client/hmi-client/src/App.vue
- packages/client/hmi-client/src/components/navbar/tera-navbar.vue
* A fix to allow the scroll position in the asset nav sidebar to persist, we now directly go to the overview page when clicking on a nav item.  Removing the key attribute will no longer make the component refresh so it keeps the scroll position
BEFORE:
https://github.com/DARPA-ASKEM/terarium/assets/33158416/bb50851d-e15d-46a4-8759-f381fc196d75
AFTER:
https://github.com/DARPA-ASKEM/terarium/assets/33158416/4f70789e-4335-4a9e-9d9f-376d69fca665
> fix: sidepanel scroll persists

- packages/client/hmi-client/src/components/code/tera-code.vue
remove model from code button from code asset
> rm model from code button

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ProjectAssetService.java
Because of the underlying data structure, we apparently don't need to set this project field on asset because setting asset field on project takes care of this for us. More specifically, we *can't* set this field because an unsupported operation exception is thrown!
> Broken test cases

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/AssetController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/AssetType.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/repository/data/ProjectAssetRepository.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ProjectAssetService.java
- packages/server/src/test/java/software/uncharted/terarium/hmiserver/controller/dataservice/AssetControllerTests.java
Adding a new endpoint to the server to check if an asset already exists with that name. This can optionally be done within the scope of a specific project or across all entries of that asset type.  In addition, blowing away old unused `toString()` functionality inside of AssetType as it was a nightmare to work with and unused.
**NOTE**
This is being merged into the new dataservice branch as it makes use of new database calls, and will be a part of `main` once that branch is merged in.
Resolves #2465
> feat(hmi-server): add endpoint to see if name already exists

- packages/client/hmi-client/src/model-representation/petrinet/petrinet-service.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/TransformController.java
When a new model is created, there is a `watch` call to `/ascet-to-latex` which results in a 500 error because the model is empty.  Arguably this call shouldn't be happening at all in the empty state, but, we should at least handle the empty case better. Thats whats happening here - we short circuit the request and return a 204.
> fix(hmi): 500 error on new models

- packages/client/hmi-client/src/components/funman/tera-funman-boundary-chart.vue
- packages/client/hmi-client/src/components/funman/tera-funman-output.vue
- packages/client/hmi-client/src/services/models/funman-service.ts
- packages/client/hmi-client/src/workflow/ops/funman/tera-funman.vue
Continue to add to Funman features
- Add in drilldown for the boundary chart, and interactions to select a specific box
- Add in a (temporary) solution with Funman exits and zero-fills the remainder timestamps, we need to remove the zeros
- Add in parameters to constraint groups, and conversely filter out initial state-values
- Small stylistic tweaks
> Funman drilldown boundary chart

- packages/client/hmi-client/src/components/funman/tera-constraint-group-form.vue
- packages/client/hmi-client/src/components/funman/tera-funman-output.vue
- packages/client/hmi-client/src/services/models/funman-service.ts
- packages/client/hmi-client/src/workflow/ops/funman/tera-funman.vue
This fix various issues with Funman, the main one being be able to run constraint on a linear combination of state-variables (note parameters may not work properly because they seem to require a different data structure).
Also fixes a few interaction issues, and clean up HTML warnings from using the same "id" over and over.
- Fix reactivity bug where the boundary-charts do not change when changing output
- Fix selectedBox cannot be unselected
- Fix weights initializer always go back to 1.0
- Fix linear combination request (use additive_bounds instead of interval)
- Fix HTML warnings
- Add bounding box on trajectory chart (single variable constraint)
> Funman ui and ux tweaks

- containers/docker-compose-local-lean.yml
- hmiServerDev.sh
- packages/server/build.gradle
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/configuration/CacheConfiguration.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/UserService.java
- packages/server/src/test/java/software/uncharted/terarium/hmiserver/service/UserServiceTests.java
Adds caches to user table in a hope to reduce request load to PostGres as this is processed for every request to the server and will almost never change
To see caching hits/missed in the logs add the following to application.properties:
`logging.level.org.springframework.cache=TRACE`
if the incorrect ENVIRONMENT is supplied to `hmiServerDev.sh` then the script errors as `break` is called inappropriately, this corrects that.  Also adds a lean local variant for when one's docker disk is too small for normal local
> Cache user fetching

- packages/client/hmi-client/src/components/operator/tera-operator-header.vue
- packages/client/hmi-client/src/components/operator/tera-operator.vue
- packages/client/hmi-client/src/services/workflow.ts
- packages/client/hmi-client/src/workflow/tera-workflow.vue
Hook up the branch-duplication feature, effectively this just calls the `workflowService.branchWorkflow(...)` function.
Also fixed a few bugs as there were a few places where the identifier-reassignment were missed - e.g. node.active field.
Duplicate option:
After example, the duplicated branch is slightly shifted down.
Using the "duplicate" option on any operator will duplicate itself, and all downstream operator(s).
> feat: provisionally working branch duplication interaction

- packages/client/hmi-client/vite.config.local.ts
Fixing port to 8080 for client
> fix(hmi-client): Incorrect port for `yarn local`

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/SimulationController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/simulation/Simulation.java
The services return a datetime object with a slightly different format. Adding support for this format in parsing. Also updating docs to explain a 404 from `PUT simulations/{id}`
> fix(hmi-server): Fixing datetime format for Simulation

- packages/client/hmi-client/src/workflow/ops/simulate-ciemss/tera-simulate-ciemss.vue
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/simulationservice/SimulationRequestController.java
Fix double creating problem with forecast calls. Simulate is created by the external services into hmi-server, so hmi-server does not need to create a copy of it.
> fix double simulations get doubly created

- packages/client/hmi-client/src/workflow/ops/model-transformer/tera-model-transformer-node.vue
The data-transform-node was relying on a state that is not being updated to pull a model.
This resulted in the node never having a model and not being able to access the drill down (due to the if)
This change is to rely on the node's input instead of the state that is not being updated:
> Fix: Data-transform-node 

- packages/client/hmi-client/src/components/model-template/tera-model-template-editor.vue
- packages/client/hmi-client/src/components/model-template/tera-model-template.vue
- packages/client/hmi-client/src/services/model-templating.ts
- packages/client/hmi-client/src/temp/model-template-test.vue
- packages/client/hmi-client/src/types/model-templating.ts
- packages/client/hmi-client/vite.config.local.ts
https://github.com/DARPA-ASKEM/terarium/assets/28237258/ff0be308-d6af-494f-8d5d-9cf8cf3c1fce
- call `amr_to_template` from beaker
- flat view and flattened model state are available
- rearranged sidebar layout
Put a valid model id into `model-template-test.vue` and go to `http://localhost:8080/model-template-test`
> feat: call amr to template and add flat view

- packages/client/hmi-client/src/services/graph.ts
Better camera positioning to capture entire graph, this solves the problems where sometimes the nodes are chopped off because the dimensionalities of the nodes themselves are not accounted for in the final bounding box.
SIR: 
SEIRD:
> fix: better default camera positioning

- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/configuration/ElasticsearchConfiguration.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DecapodesConfigurationController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DecapodesContextController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/model/ModelConfiguration.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/multiphysics/Configuration.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/multiphysics/ConfigurationCondition.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/multiphysics/ConfigurationDataset.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/multiphysics/ConfigurationDatasetFile.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/multiphysics/ConfigurationHeader.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/multiphysics/ConfigurationParameter.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/multiphysics/Context.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/multiphysics/ContextConstant.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/multiphysics/ContextFile.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/multiphysics/ContextHeader.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/multiphysics/ContextMesh.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/multiphysics/ContextMeshSubmeshRelation.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/multiphysics/ContextPrimalDualRelation.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/multiphysics/DecapodesConfiguration.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/multiphysics/DecapodesContext.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/DecapodesConfigurationService.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/DecapodesContextService.java
- packages/server/src/main/resources/application.properties
- packages/server/src/main/resources/static/es/index-templates/tds_1.0_decapodes_configuration_index_template.json
- packages/server/src/main/resources/static/es/index-templates/tds_1.0_decapodes_context_index_template.json
Add objects for decapode configuration and decapodes context and decapodes configuration.
Some fields are captured as Object, since the fields captures disjunctive typing. e.g. `{ value: 123, format: 'x' }` or `{ uri: 'abc' }` or `8` ... they can be typed out more carefully if needed, but most of these objects are just pass-throughs.
CRUD operations of configuration/context through swagger-ui.
> chore: decapodes data structures

- packages/client/hmi-client/src/services/models/simulation-service.ts
- packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/calibrate-operation.ts
- packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss.vue
- packages/client/hmi-client/src/workflow/util.ts
Getting CIEMSS calibrate inline with other operator designs, and working with dill blob. 
This is the first part:
- Get CIEMSS calibrate back in order as it has been months since we updated the design
- Using and accessing inferred_parameters (the dill file) for a projection
The second part will be hooking up the loss-values (send via rabbitMQ) and gettng the CIEMSS-simulate to optionally accept an inferrred_paramter (the dill file) to run.
Note because we are still doing two parts (calibrate, then simulate), the state object had to be augmented to keep track of both types of simulation ids (calibration-id, forecast-id). The naming here is a bit tangled up with the existing nomenclature, suggestions welcome but might be dealt with in later PRs.
CIEMSS calibrate runs
> Update pyciemss calibrate

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/TDSCodeController.java
New end point to download code from.
Resolves #2671
> feat(hmi-server): download code

- packages/server/src/test/java/software/uncharted/terarium/hmiserver/service/TaskServiceTest.java
- packages/taskrunner/docker/Dockerfile.GoLLM
- packages/taskrunner/src/main/java/software/uncharted/terarium/taskrunner/service/Task.java
- packages/taskrunner/src/test/java/software/uncharted/terarium/taskrunner/service/TaskTests.java
The issue @blanchco  was encountering is because the dockerfile layer that pulls the GoLLM repo was getting cached, so it was running code that was out of date :)
Ideally we want to actually hardcode a GoLLM release, but for now, since we are iterating so quickly its nice to just use the latest by default.
> Small fixes. Add cache bust to puill latest GoLLM in taskrunner build

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/configuration/OpenAPI3Configuration.java
- packages/server/src/main/resources/application.properties
> update openapi configuration

- .vscode/launch.json
- README.md
- Added an instruction to start the client connecting to the server running locally in README
- Added an instruction to configure VSCode for debugging the client 
- Added vscode launch configuration to start the client
> docs: updated readme

- packages/client/hmi-client/src/assets/css/theme/_variables.scss
- packages/client/hmi-client/src/components/llm/tera-notebook-jupyter-input.vue
- packages/client/hmi-client/src/services/jupyter.ts
- packages/client/hmi-client/src/workflow/ops/model-edit/tera-model-edit.vue
1. Adding dropdown of preset options as an option for juypter input component.
Using this new option for the model edit page
2. Adding status to the juypter input component
Anyone have tips for this ugliness?
> adding dropdown, adding status for kernel manager

- packages/client/hmi-client/src/page/project/components/tera-upload-resources-modal.vue
- packages/client/hmi-client/src/services/document-assets.ts
- packages/client/hmi-client/src/services/goLLM.ts
- packages/client/hmi-client/src/services/knowledge.ts
- packages/client/hmi-client/src/services/model.ts
- packages/client/hmi-client/src/types/Types.ts
- packages/client/hmi-client/src/workflow/ops/model-from-code/tera-model-from-code.vue
- packages/client/hmi-client/src/workflow/ops/model-from-document/tera-model-from-document-drilldown.vue
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/gollm/GoLLMController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/modelparts/ModelMetadata.java
* GOLLM model card generated on model upload.
* Im not entirely happy with how to implement this but we will need to move the pdfextractions calls to the backend and have everything run there for the ideal UX.  For now gollm needs to wait for pdfextractions to finished in order to get the text to runs the card.
> model card on document upload

- packages/client/hmi-client/src/workflow/tera-workflow.vue
This tries to ensure we have a chance to save before the page is unloaded, e.g. by hard-refreshing for because of the keycloak revnewal
This is a bit hard to test because of non-blocking, probably the easiest way to convince this works is to add logging to WorkflowController#updateWorkflow and check it is firing on page refresh.
> fix: ensure workflow save on unload

- packages/client/hmi-client/src/components/dataset/tera-dataset-description.vue
- packages/client/hmi-client/src/components/dataset/tera-dataset-overview-table.vue
- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
- packages/client/hmi-client/src/components/model/petrinet/tera-model-semantic-tables.vue
- packages/client/hmi-client/src/services/concept.ts
- packages/client/hmi-client/src/services/dataset.ts
* Concept searching dataset
https://github.com/DARPA-ASKEM/terarium/assets/33158416/0193300c-1bc0-4ca6-a901-f38230bca667
> concept search dataset

- packages/client/hmi-client/src/services/models/simulation-service.ts
- packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-node-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-julia/tera-calibrate-julia.vue
- packages/client/hmi-client/src/workflow/ops/code-asset/tera-code-asset-node.vue
- packages/client/hmi-client/src/workflow/ops/dataset-transformer/tera-dataset-transformer.vue
- packages/client/hmi-client/src/workflow/ops/dataset/tera-dataset-node.vue
- packages/client/hmi-client/src/workflow/ops/document/tera-document-operation-node.vue
- packages/client/hmi-client/src/workflow/ops/funman/tera-funman.vue
- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config-node.vue
- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config.vue
- packages/client/hmi-client/src/workflow/ops/model-coupling/tera-model-coupling-node.vue
- packages/client/hmi-client/src/workflow/ops/model-coupling/tera-model-coupling.vue
- packages/client/hmi-client/src/workflow/ops/model-edit/tera-model-edit.vue
- packages/client/hmi-client/src/workflow/ops/model-from-code/tera-model-from-code.vue
- packages/client/hmi-client/src/workflow/ops/model-from-document/model-from-document-operation.ts
- packages/client/hmi-client/src/workflow/ops/model-from-document/tera-model-from-document-drilldown.vue
- packages/client/hmi-client/src/workflow/ops/model-optimize/tera-model-optimize.vue
- packages/client/hmi-client/src/workflow/ops/model-transformer/tera-model-transformer.vue
- packages/client/hmi-client/src/workflow/ops/model/tera-model-node.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ciemss/tera-simulate-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-node-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-julia/tera-simulate-julia.vue
- packages/client/hmi-client/src/workflow/ops/stratify-mira/tera-stratify-mira.vue
- packages/client/hmi-client/src/workflow/tera-workflow.vue
This modifies the behaviour such that a successful run of an operator will make that operator the active output. Moreover, because we agreed to have a singular exposed output per operator, the emission `append-output-port` is renamed to `append-output` to better reflect what is actually happening.
```
I am going to take a crack at harmonizing the behaviour of the preview-dropdown we have in the operators, just chitchatting with Pascale
- if we run something, the output should be selected automatically, currently this seems to be a mix of auto and manual selection after "run" is clicked
- successive runs will replace the existing output. 
- when selected output changes it will propagate the carried value downstream and mark downstream operators as invalid (to be done later but before eval) …
```
> operator active output behaviour

- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config.vue
Fix model configuration display issues because it is treating the model as if it is stratified when it is not. This ends up hiding parameters that have underscores in their names that arose naturally, as oppose to underscores that arose from stratifications through MIRA.
Fixes: https://github.com/DARPA-ASKEM/terarium/issues/2753
> fix initials/parameters display due to incorrect stratification usage

- packages/client/hmi-client/src/components/stratification/tera-stratification-group-form.vue
- packages/client/hmi-client/src/workflow/ops/stratify-mira/stratify-mira-operation.ts
- packages/client/hmi-client/src/workflow/ops/stratify-mira/tera-stratify-mira.vue
This enables fuller MIRA stratify capabilities, and try to use an easier to understand language.
- directed: this is hidden and assume to be true
- structure: this is proxied by useStructure (true | false), where `true = None = all combinations` and `false = [] = nothing`
Cartesian =~ Allow existing transitions to involve multiple strata
Structure =~ Create new transitions between strata
Structure toggle works, you need to have beaker instance running.
> Clearer stratify

- containers/scripts/docker-compose-data-services.yml
* Remove the `platform` requirement in the docker compose file.
* Works as expected on an ARM environment (MacBook Pro M2 Pro)
> Allow the use of the ARM image for beaker locally

- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config.vue
- packages/client/hmi-client/src/workflow/ops/model-edit/tera-model-edit.vue
Init was being called twice due to some immediate = true + onMounted silliness.
Also whenever output dropdown was changed we were creating new instance without shutting down old first.
Opening + closing node, checking beaker logs
Opening + changing output + closing node, checking beaker logs
Ensuring the output dropdown still has correct init with changes
> Beaker correction

- packages/client/hmi-client/src/components/drilldown/tera-drilldown-preview.vue
- packages/client/hmi-client/src/components/drilldown/tera-output-dropdown.vue
- packages/client/hmi-client/src/services/workflow.ts
- packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/funman/tera-funman.vue
- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config.vue
- packages/client/hmi-client/src/workflow/ops/model-edit/tera-model-edit.vue
- packages/client/hmi-client/src/workflow/ops/model-from-code/tera-model-from-code.vue
- packages/client/hmi-client/src/workflow/ops/model-from-document/tera-model-from-document-drilldown.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ciemss/tera-simulate-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-julia/tera-simulate-julia.vue
- packages/client/hmi-client/src/workflow/ops/stratify-mira/tera-stratify-mira.vue
- packages/client/hmi-client/src/workflow/ops/stratify-mira/tera-stratify-node-mira.vue
- packages/client/hmi-client/src/workflow/tera-workflow.vue
This cleans up the update-port and select-port semantic in the workflow operators. There are numerous instances where the signals are crisscrossed and hard to figure out whether the intention is to select output or update the output-port's attributes.
Also remove the multi-select from the preview drilldown, only a single output will be exposed by any given operator.
> cleanup preview and selection

- packages/client/hmi-client/src/workflow/ops/simulate-ciemss/simulate-ciemss-operation.ts
Minor update to the simulate-ciemss-operation. 
I noticed that it can now take an optional calibrationSimulationId.
Just marking this off as `isOptional`
> minor update

- packages/client/hmi-client/src/workflow/ops/model/tera-model-node.vue
Using beaker to generate model preview. For:
- petrinet: use our own renderer
- stock and flow: use MMT preview
- regnet: use MMT preview
For example: Stock and flow SIR model
Requires beaker, you can get an example stock-n-flow from: https://raw.githubusercontent.com/DARPA-ASKEM/simulation-integration/main/data/models/SEIR_stockflow.json
> mira model template preview for regnet/stockflow framework types

- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/services/DownloadService.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/documentservice/KnownEntities.java
There are two bugs found here.
* The first is that we incorrectly assumed the type of `summaries` on the `KnownEntities` model. This may be the first time we've seen this be populated, or, xdd may have changed the schema without telling us, but, lets just assume we had it wrong here.
* The second was an issue with URL encoding if the pdfs had spaces in them.
This is just the back end work. Our front end will now need to accommodate this new type of summary
Resolves #2840
> fix[hmi-server]: incorrect parsing of some xdd documents

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/services/DownloadService.java
We don't actually need to do a full encode here as most of the URLS given are coming from unpaywall and are good to go. What we mostly need to do is just replace whitespace with `%20`. This feels a little hacky to do but thats cowboy coding, baby! This works for random spot tests on PDFs as well as the previously problematic article with a DOI of 10.1101/2020.07.30.20164921
Resolves #2850
> fix[hmi-server]: incorrect parsing of some pdf urls

- packages/client/hmi-client/src/components/dataset/tera-dataset-description.vue
- packages/client/hmi-client/src/components/model/petrinet/tera-model-description.vue
- packages/client/hmi-client/src/components/model/tera-model.vue
- packages/client/hmi-client/src/components/widgets/tera-related-documents.vue
- packages/client/hmi-client/src/page/data-explorer/DataExplorer.vue
- packages/client/hmi-client/src/page/data-explorer/components/tera-filter-bar.vue
* Allow user to display the document in the project to select for enrichment and extractions
> Model card from document

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/gollm/GoLLMController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/TaskService.java
- packages/server/src/main/resources/application.properties
- packages/server/src/test/java/software/uncharted/terarium/hmiserver/service/TaskServiceTest.java
- packages/taskrunner/src/main/java/software/uncharted/terarium/taskrunner/service/TaskRunnerService.java
- packages/taskrunner/src/main/resources/application.properties
- packages/taskrunner/src/test/java/software/uncharted/terarium/taskrunner/service/TaskRunnerServiceTests.java
- packages/taskrunner/src/test/resources/application-test.properties
Previously the response handlers (which should execute once, regardless of how many hmi-servers are running), would execute per hmi-server instance. This fixes that.
Response handlers should only run once, previously they would run once per hmi-server instance. This PR fixes that.
Catch response handler errors and dispatch those any relevant SSE Emitters.
> Add way to propagate task response handler errors to users. Fix scaling issue for response handlers.

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DatasetController.java
This is actually the fix for incorrect column information after a beaker-driven transform too. There is a corresponding change on beaker that blows away column data (https://github.com/DARPA-ASKEM/beaker-kernel/pull/95) since columns and/or data will have changed in modified datasets. Then on a GET call we repopulate the column data because its empty.  This will also cover any situation where a CSV/dataset was some how uploaded and the column data was empty too. In addition, this centralizes some code around getting CSV files and updating headers.
Resolves #2784
> fix[hmi-server]: Dataset extract columns, doing it on GET if not present

- packages/client/hmi-client/src/model-representation/petrinet/petrinet-service.ts
Update heuristics
- only consider stratified if there are more than 1 stratas
- ignore specific keywords
> update heuristic to distinguish regular and stratified petrinets

- packages/client/hmi-client/src/components/model/petrinet/model-configurations/tera-stratified-matrix-modal.vue
- packages/client/hmi-client/src/components/model/petrinet/model-configurations/tera-stratified-matrix.vue
I set the evaluate expressions to false by default so that we don't run into blank cells for now. You can see in the video that Pyodide is throwing errors on the Carcoine model but not the SIR.
It seems to not like the variable names:
```
pyodide.asm.js:9 Uncaught PythonError: Traceback (most recent call last):
File "/lib/python311.zip/_pyodide/_base.py", line 460, in eval_code
CodeRunner(
File "/lib/python311.zip/_pyodide/_base.py", line 248, in __init__
self.ast = next(self._gen)
^^^^^^^^^^^^^^^
File "/lib/python311.zip/_pyodide/_base.py", line 144, in _parse_and_compile_gen
mod = compile(source, filename, mode, flags | ast.PyCF_ONLY_AST)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<exec>", line 2
beta_0,beta_1,beta_2,beta_3,epsilon_0,epsilon_1,gamma_0,gamma_1,alpha_ …
```
> fix: stratified matrix expressions

- packages/client/hmi-client/src/model-representation/petrinet/nested-petrinet-renderer.ts
- packages/client/hmi-client/src/model-representation/petrinet/petrinet-renderer.ts
Previously the y-position of the text was hard coded because the font size was hard coded as 18px. When I added the variable font size, I forgot that the y-position needs to be adjusted too.
BEFORE
AFTER
> Update text position in PetrinetRenderer

- packages/client/hmi-client/src/services/goLLM.ts
- packages/client/hmi-client/src/workflow/ops/model-config/model-config-operation.ts
- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config.vue
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/gollm/GoLLMController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ProvenanceSearchService.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/ConfigureFromDatasetResponseHandler.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/ConfigureModelResponseHandler.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/TaskService.java
- packages/server/src/main/resources/graph_relations.json
* create model configurations from dataset with gollm
https://github.com/DARPA-ASKEM/terarium/assets/33158416/e5778724-71fa-4f74-b48f-c74377d50a7e
> configure model from dataset

- packages/client/hmi-client/src/assets/css/theme/designer/components/messages/_toast.scss
> darker text for the toast messages == easier to read

- packages/client/hmi-client/src/workflow/ops/simulate-julia/simulate-julia-operation.ts
- packages/client/hmi-client/src/workflow/ops/simulate-julia/tera-simulate-julia.vue
- packages/client/hmi-client/src/workflow/ops/simulate-julia/tera-simulate-node-julia.vue
This covers the Simulate operators, Calibrate and Ensemble will be dealt with in different PRs.
There are two themes to the PR here
- Reorganization and simplification of the operator logic, we no longer need to support multiple concurrent simulations within the same operator, and this means we can simplify state management and remove logic that never quite worked completely. 
- Enable a preview on the workflow within the operator node, the nodes will poll and update in a similar manner as the drilldown.
> reorg sciml simulate

- packages/client/hmi-client/src/components/dataset/tera-save-dataset-from-simulation.vue
save from dataset can handle undefined simulationRunId without spitting out a warning
> Fix: save from dataset can handle undefined

- packages/client/hmi-client/src/api/api.ts
- packages/client/hmi-client/src/services/goLLM.ts
- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config.vue
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/gollm/GoLLMController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/mira/MiraController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/task/TaskRequest.java
* changes to the taskhanlder now that it is using a new event source library
* bugfix to gollm controller
* model config improvements
> gollm fixes and improvements

- packages/client/hmi-client/src/services/notebook-session.ts
- packages/client/hmi-client/src/workflow/tera-workflow.vue
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/NotebookSessionController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/TerariumAssetService.java
DataTransform has a `state.notebookSessionId` field that links to an ES document representing the notebook session, this means when we branch, subsequent modifications are written into the same doc from multiple sources creating weird inconsistencies. 
This PR breaks this by adding a "clone" method, when branching happens DataTransform sessions are cloned are reassigned new ids.
- Add a dataset to the workflow
- Attach the dataset to a data-transform node
- Branch the data-transform node
- Do something, e.g. adding a column in one of the data-transform node
- The two data-transforms should be separate entities and showing different data
> clone dataset-transform session on branching action

- packages/client/hmi-client/src/api/api.ts
- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
- packages/client/hmi-client/src/components/documents/tera-document-asset.vue
- packages/client/hmi-client/src/components/model/tera-model.vue
- packages/client/hmi-client/src/components/widgets/tera-common-modal-dialogs.vue
- packages/client/hmi-client/src/page/data-explorer/components/tera-search-results-list.vue
- packages/client/hmi-client/src/page/project/components/tera-model-modal.vue
- packages/client/hmi-client/src/page/project/tera-project.vue
- packages/client/hmi-client/src/services/artifact.ts
- packages/client/hmi-client/src/services/code.ts
- packages/client/hmi-client/src/services/data.ts
- packages/client/hmi-client/src/services/dataset.ts
- packages/client/hmi-client/src/services/document-assets.ts
- packages/client/hmi-client/src/services/knowledge.ts
- packages/client/hmi-client/src/types/ServerError.ts
- packages/client/hmi-client/src/workflow/ops/model-from-document/tera-model-from-document-drilldown.vue
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ArtifactController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/AssetController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ConceptController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DatasetController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DecapodesConfigurationController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DecapodesContextController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DocumentController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/EquationController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/FrameworkController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelConfigurationController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/NotebookSessionController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ProjectController.java
* `api.ts` no longer swallows error messages but rather will pop up a toast error message with the error code.
* Front end toasts that were just logging a null have been removed because the toast will catch that now. Error messages that were front end specific or as a part of a `catch` have been kept in.
* Some clean up on the dataservice side of hmi server
*  _NOTE_: This may surface some old bugs that had gone unseen because now 404 and 500 errors will pop to the front. We should deal with those problems as their own separately logged issues and not revert this change!!!
Resolves #2947
> 2947 feat improve error logging from the back end to the client

- packages/client/hmi-client/docker/timeouts.conf
- packages/client/hmi-client/src/services/artifact.ts
- packages/client/hmi-client/src/services/code.ts
- packages/client/hmi-client/src/services/dataset.ts
- packages/client/hmi-client/src/services/document-assets.ts
> Change upload timeout on client nginx

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/gollm/GoLLMController.java
*Strip metadata in models before sending to gollm, fixes an issue where metadata being too big will cause gollm to fail.
> strip metadata before sending to gollm

- packages/client/hmi-client/src/App.vue
- packages/client/hmi-client/src/assets/css/theme/designer/components/messages/_toast.scss
- packages/client/hmi-client/src/services/toast.ts
* Display the toast in the center to avoid blocking actions button from the UI (i.e. drilldowns close button)
* Make the toast slightly wider.
> Put the toast in the center and wider

- packages/client/hmi-client/src/components/widgets/tera-pdf-embed.vue
BEFORE
You can't scroll in the workflow document drilldown
AFTER
Now you can... though I can only test it for about a second on my local host... should work fine on staging/prod
> fix broken PDF viewer in workflow document drilldown

- packages/client/hmi-client/src/workflow/ops/funman/tera-funman.vue
We cannot use reserved keywords as left-hand-side assignments, such as lambda. This is a problem because we are building a symbolics lookup table: `{ v1 => 321, v2 => 123 ... }` and the key cannot be reserved keyword in the language such as "lambda".
This PR works around the issue of mass evaluation by appending an underscore suffix.
Models with "lambda" in one or more of its expressions will not error out in the Funman operator.
> fix: rename reserved keywords

- packages/client/hmi-client/src/components/drilldown/tera-output-dropdown.vue
- packages/client/hmi-client/src/workflow/tera-workflow.vue
Before when a new output was generated it appeared to be the chosen one once the output list was updated. In reality it was just a side effect of the list changing. I now select the new output after a new one is added (within `appendOutput()`)
In the old version the new output looked like it was the selected one after a Run. However it was missing the connected label that should have been beside it. 
https://github.com/DARPA-ASKEM/terarium/assets/28237258/388c6f29-895c-4e24-ae54-1c94ff67fa70
> fix: once a new output is generated update the selected output to it

- packages/client/hmi-client/src/workflow/ops/model-comparison/tera-model-comparison.vue
> Jamie add legend to compare models chart

- packages/client/hmi-client/src/workflow/tera-workflow.vue
BEFORE
After selecting 'Rename' you need to click in the input box before you begin typing. And it's not clear how to submit -- you can press enter or escape, but there's no signifier.
AFTER
Now we open the input box in focus mode. I also added a check mark that you can click, which runs the same 'updateWorkflowName' function as the enter and escape keys do.
> Open rename workflow text field in focus mode

- packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/calibrate-operation.ts
- packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
- packages/client/hmi-client/src/workflow/util.ts
- Sync ciemss-calibrate drilldown/node interactions and add in resuming logic for long running calibrations
- Tidy up code
Note unlike other operators, ciemss-calibrate is a two-stage process, so we need to track extra data, namely
- inProgressCalibrateId, which points to the dill file, and
- inProgressForecastId, which points to the simulation result
TODO in other PR(s)
- better handling of loss values and chart's variable selections, there seemed to be a few bugs 
- figure out what is going on with the state names coming back, we used to parse for `_state` but they don't seem to be there anymore, however @Tom-Szendrey is reporting parsing for `_state` in his optimization changes, so there may be some inconsistent naming issues we need to report.
> reorganize ciemss calibrate

- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/simulate-ensemble-ciemss-operation.ts
- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-node-ciemss.vue
Rather than 1 port that accepts multiple inputs, update the design for simulate ensemble to have appending ports
> Feat: simulate ensemble appending ports

- packages/client/hmi-client/src/model-representation/mira/mira-util.ts
We have assumed that the children-parameters of some parameter beta: beta_0, beta_1, beta_2 ... etc can all be slotted into a singular type of matrix out of the three we have
- subject-outcome
- subject-controller
- outcome-controller
That isn't exactly always the case, it may be that beta_1 is subject-outcome and beta_2 is none of those 3. It could be that our 3-matrix approach is not exactly right when it comes to bio-models, or that someone had manually adjusted model. Anyway this PR adds escape hatches to the generation process so we don't error out when this scenario happens.
> accommodate mixed types

- packages/client/hmi-client/src/services/knowledge.ts
- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/extractionservice/ExtractionStatusUpdate.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/ExtractionService.java
Optional PR that modifies the extraction progress to be even more generic, and created an `estimated` progress value of t using a logarithmic easing function so that the first 50% takes n seconds, the next 25% takes n, next 12.5% takes n... etc.
Coupled with a css transition it behaves really nicely:
https://jsfiddle.net/hwpdb6yv/1/
The main motivation for this is that it is less error prone since it doesn't rely on hardcoding exactly how many updates will be sent, and can be used in cases where that number isn't known ahead of time.
> Update to more generic progress

- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/simulate-ensemble-ciemss-operation.ts
- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss.vue
Removing `modelConfigIds` from state. 
These are already stored in the input ports and there is no need to also store them in the state. 
Removing `listModelIds` as it is an additional variable that is just adding noise to this file. 
Will be updating line 46 next PR to have labels instead of IDs
> ensemble cleanups 2

- packages/client/hmi-client/src/components/model/petrinet/model-configurations/tera-stratified-matrix.vue
Matrix generation: adding a guard to prevent any falsy checks down the line from the expression being `0`
e.g. a_5 is 0 and will be evaluated as "0.0"
> fix cases where 0 doesn't show up

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/TaskService.java
- packages/server/src/test/java/software/uncharted/terarium/hmiserver/service/tasks/TaskServiceTest.java
I believe this to be the cause of the stalled requests that @mwdchang experienced.
If the `hmi-server` was shutdown between writing the initial `TaskStatus.QUEUED` state of the task to redis but _before_ it actually sent the request to rabbitmq, then any subsequent request would simply wait for a non-existent task to finish. 
This is consistent with the logs as no request was sent, but it did timeout waiting for the response.
This switches the logic to write out the `TaskStatus.QUEUED` state _after_ it is dispatched. If the server is shutdown after it dispatches to redis but before that state is set, then the subsequent requests will simply re-send it.
Another small issue is that failed task id's were never re-written in the task SHA -> task id lookup. So after a task failed subsequent …
> Fix issue with stalled requests if shutdown

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/climatedata/ClimateDataService.java
If a task is saved to the database and then not retreived in good time (IE hmi server gets shut down?) the climate data service will delete the status. However rather than returning a 404, they return a 200 with a body of 404 which blows everything up.
> fix[hmi-client]: Handle Missing Queued Task

- packages/client/hmi-client/src/workflow/ops/dataset/tera-dataset-drilldown.vue
In a dataset drilldown, we should show the preview image
> fix[hmi-client]: Show preview in drilldown

- packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-julia/tera-calibrate-julia.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-julia/tera-calibrate-node-julia.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ciemss/tera-simulate-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-node-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-julia/tera-simulate-julia.vue
- packages/client/hmi-client/src/workflow/ops/simulate-julia/tera-simulate-node-julia.vue
- packages/client/hmi-client/src/workflow/tera-simulate-chart.vue
- packages/client/hmi-client/src/workflow/util.ts
Cleaning up chart related matters, this goes over all TA3 operators with the exception of 
- ensemble-simulate
- ensemble-calibrate
- optmize
which are still under construction to adopt new designs and communication paradigm.
This PR does several things
- Resize charts across drilldowns and previews
- Fix problem with state-references in chartProxy
- Remove pills the chart variable selector
> chore: operator chart clean up

- packages/client/hmi-client/src/workflow/ops/calibrate-ensemble-ciemss/calibrate-ensemble-ciemss-operation.ts
- packages/client/hmi-client/src/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-node-ciemss.vue
-Proxy chart 
-drilldown components
-start looking to see if knobs object can help add a bit organization to this mess
-update extras object to be in line with pyciemss-service interface
-Sorry for the long PR but I promise a lot of it is just the reformatting for drilldown components
-This should be considered a WIP I will have more follow up PRs to move the run button to the footer of drill down and reorg to new paradigm just trying to keep PRs relatively focused
> calibrate ensemble 2

- containers/docker-compose-actions.yml
- containers/docker-compose-full.yml
- containers/docker-compose-lean.yml
- containers/docker-compose-local-lean.yml
- containers/docker-compose-local.yml
- containers/scripts/docker-compose-common.yml
- containers/scripts/docker-compose-data-services.yml
- containers/scripts/docker-compose-hmi.yml
- containers/scripts/docker-compose-keycloak.yml
- containers/scripts/docker-compose-local-keycloak.yml
- containers/scripts/docker-compose-sim-services.yml
- containers/scripts/docker-compose-taskrunner.yml
Also remove `version` tag that causes warnings:
```
WARN[0000] /home/user/workspace/terarium/containers/scripts/docker-compose-common.yml: `version` is obsolete 
WARN[0000] /home/user/workspace/terarium/containers/scripts/docker-compose-taskrunner.yml: `version` is obsolete 
WARN[0000] /home/user/workspace/terarium/containers/scripts/docker-compose-data-services.yml: `version` is obsolete 
WARN[0000] /home/user/workspace/terarium/containers/scripts/docker-compose-sim-services.yml: `version` is obsolete 
WARN[0000] /home/user/workspace/terarium/containers/docker-compose-local.yml: `version` is obsolete 
```
> Remove knowledge-middleware container from local docker-compose

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/climateData/ClimateDataPreview.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/climateData/ClimateDataSubset.java
Error seen when an error is returned from climate-data service
If an error is returned the application is incapable of storing that due to Hibernate believing it is the 1970s and variable disk space is expensive
> change column from 255 to 4096

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/climatedata/ClimateDataController.java
Setting the metadata now that its available to us.
> fix[hmi-server]: Pack metadata on climate dataset

- packages/client/hmi-client/src/api/api.ts
- packages/server/src/main/resources/application.properties
Allow error messages to pass (without their stack traces). Also removing the path from the errors because it feels like too much/not safe
> fix[hmi-server]: Allowing errors to pass

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/documentservice/DictionariesController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/documentservice/ExtractionController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/documentservice/RelatedController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/documentservice/SetController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/documentservice/XDDDocumentController.java
Improving the errors from xdd document and extraction search. If xDD gives us an exception we return that status code to the front end with an error message. In all other cases it's a server error, so we return 500
> fix[hmi-server]: Improving xDD errors

- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss.vue
General prettification. Made the mapping section more better.
@mwdchang I did not apply your changes to the simulation output chart. This is still the version that doesn't fill the container.
**BEFORE**
**AFTER**
> Jamie prettify ensemble simulate

- packages/client/hmi-client/src/components/model/petrinet/tera-initial-table.vue
- packages/client/hmi-client/src/components/model/petrinet/tera-parameter-table.vue
I removed the green background and futzed with the column widths of the initial and parameter tables. I think the table is less chaotic looking now, but the columns for the nested tables are still somewhat misaligned. One thing at a time...
**BEFORE**
**AFTER**
> Jamie remove green from parameter tables

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/User.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/security/LoggingAccessDeniedHandler.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/security/LoggingAuthenticationEntryPoint.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/security/SecurityConfig.java
> add logging of 403 and 401 errors

- packages/client/hmi-client/src/components/documents/tera-document-asset.vue
- packages/client/hmi-client/src/composables/project.ts
- packages/client/hmi-client/src/page/data-explorer/components/tera-preview-panel.vue
- packages/client/hmi-client/src/services/document-assets.ts
- packages/client/hmi-client/src/workflow/ops/document/tera-document-operation-node.vue
* Do not open on the PDF tab right away
* Remove blocking file download to open the asset
* Remove highlight search
> Small document asset fixes

- packages/client/hmi-client/src/components/dataset/tera-dataset-jupyter-regridding-panel.vue
- packages/client/hmi-client/src/workflow/ops/regridding/tera-regridding.vue
May want to restyle the contextInfo on vue.
Also will need to clear out console.logs
> Correct regrid context.

- packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/optimize-ciemss/optimize-ciemss-operation.ts
- packages/client/hmi-client/src/workflow/ops/optimize-ciemss/tera-optimize-ciemss.vue
- Can now use a calibration result in the optimize box similar to how we can do this in simulate ciemss
This will add inferred params
- Minor updates afer speaking with pyciemss team
> Optimize update - inf params, minor interface update

- packages/client/hmi-client/src/components/operator/tera-operator-annotation.vue
> Added an edit icon to the annotation note to indicate that it's editable

- packages/client/hmi-client/src/components/navbar/tera-navbar.vue
- packages/client/hmi-client/src/components/widgets/tera-related-documents.vue
- packages/client/hmi-client/src/services/knowledge.ts
- packages/client/hmi-client/src/workflow/ops/document/tera-document-operation-node.vue
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/GlobalExceptionControllerAdvice.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DocumentController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/proxies/skema/SkemaUnifiedProxy.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/ExtractionService.java
- packages/server/src/test/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeControllerTests.java
- packages/server/src/test/java/software/uncharted/terarium/hmiserver/service/ExtractionServiceTests.java
* Clean up some issue with the scenario form
* Update how we call the knowledgeController
* Move the extraction call into a runnable like PDF extraction
* Remove the optionals `annotateSkema` and `annotateMit` as Skema unified has them on by default.
* Remove the call to MIT as this is handle by the Skeme unified endpoint
* TODO - Move the align AMR into the extractionService
* TODO - Call align AMR after variable extraction if a model was provided
* TODO - Getting 500 when calling  SKEMA unified`link_amr`
> Fix Align AMR

- packages/client/hmi-client/src/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss.vue
I made this prettier. Heads up, the code is pretty hacky. It's an HTML table that is only one row, with loops generating multiple elements within each <td>. I didn't change anything... just aligned stuff better.
**BEFORE**
**AFTER**
> Jamie fix calibrate ensemble mapping columns

- packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
Fix problem where the chart is stuck when switching output in ciemss-calibrate, this is because the state is not written to the output properly.
> fix ciemss calibrate output switching

- packages/client/hmi-client/src/page/data-explorer/components/tera-search-results-list.vue
- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/climatedata/ClimateDataController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DatasetController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/dataset/Dataset.java
Adding support for downloading the original netcdf files from the source service. If there are download urls set this will take precidence over s3 stored assets, but we _should_ never have both set as subset datasets are new datasets without the dataset urls field set.
Resolves #3206
> fix[hmi-server]: Download netcdf assets

- packages/client/hmi-client/src/assets/css/theme/designer/components/input/_editor.scss
- packages/client/hmi-client/src/components/asset/tera-asset.vue
- packages/client/hmi-client/src/page/project/components/tera-project-overview.vue
Removed top left and right corner radius from text editor toolbar and removed bottom border from banner (not needed, looked weird).
**BEFORE**
**AFTER**
> Removed corner radius from overview text edit toolbar, removed bottom border from banner

- packages/client/hmi-client/src/components/drilldown/tera-drilldown-header.vue
- packages/client/hmi-client/src/components/operator/tera-operator-annotation.vue
Operator node and drill-down header annotation text has been darkened (changed from subdued to primary). Removed the unwanted indentation on a drill-down header annotation when there are no tabs in the header. 
**BEFORE**
**AFTER**
> Darkened operator annotation text, removed indent

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/evaluation/EvaluationController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/funman/FunmanController.java
Catching exceptions thrown by the proxy service for funman operations. Also small code cleanup in eval controller.
> fix[hmi-server]: Improved Funman Errors

- packages/client/hmi-client/src/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-node-ciemss.vue
Not sure why the imports for primevue number was missing in these files?
Also updating when we add charts so we dont have a chart prior to running ensemble-simualte
> Ensemble - missing imports?

- packages/client/hmi-client/src/components/model/petrinet/tera-parameter-table.vue
Show the configuration column in the tera-parameter-table.vue
Resolves #3243
> fix[hmi-client]: Configuration column in parameter table

- packages/client/hmi-client/src/services/models/simulation-service.ts
Remove unused functions, these were utility functions for running multiple runs simultaneously , which we no longer support as it makes actually working with the operator a lot more complicated.
> chore: remove unused functions

- packages/client/hmi-client/src/services/calibrate-workflow.ts
- packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-ensemble-ciemss/calibrate-ensemble-ciemss-operation.ts
- packages/client/hmi-client/src/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-julia/tera-calibrate-julia.vue
- packages/client/hmi-client/src/workflow/util.ts
- Updating mapping provided to ensemble calibrate
- Correcting `timespan` value in ensemble calibrate
- Adding optional input to `getTimespan` and using an interface for easier use of optional params.
- Updating default num particles to 1
Running a regular calibrate to ensure the timespan changes are not breaking anything unexpectedly
Running ensemble calibrate with two different models with no indexes being titled the same
Pyciemss-service wants the dataset mapping as follows
{dataset timestamp col name}: "timestamp",
{X dataset column used}: {X dataset column used},
...
Example:
```
{
"time": "timestamp",
"S": "S",
"I": "I"
}
```
> calibrate ensemble mapping

- packages/client/hmi-client/src/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue
If (aNumber) returns false if that number is 0.
I had a check to see if values existed in a list when i knew it has to Just remove this check to not fail when the value is 0.
> Optimize interventions:

- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config.vue
- Rename a function to something a bit more accurate
- Apply a model config will now also append it to the output so user does not need to hit run and create a new config 
Making a few distinct configs where changes can be easily seen.
Checking that the state is being properly updated when changing between outputs and is saved
Checking that output that is appended is updated correctly
https://github.com/DARPA-ASKEM/terarium/assets/17088680/a4b9c60d-c50f-4838-98d5-3cc781afcf78
> Model config apply config also appends to node

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/ExtractionService.java
wish we used proper constructors and not hope developers know how to use objects
POJOs "constructed" with `@Data` and 100% the most garbage of annotations `@Accessors(chain = true)` which should never be used unless one can produce a 50 page documenting why it is better than a proper constructor... .
> NPE accessing a document assets "optional" Metadata

- packages/client/hmi-client/src/services/project.ts
For first time users with no projects the screen would be stuck on a isLoading state.
I was caused by a null being passed by the `getAll()` in the `projectService`
> remove null casuing empty state

- packages/client/hmi-client/src/components/funman/tera-funman-output.vue
- packages/client/hmi-client/src/workflow/ops/funman/funman-operation.ts
- packages/client/hmi-client/src/workflow/ops/funman/tera-funman-node.vue
- packages/client/hmi-client/src/workflow/ops/funman/tera-funman.vue
UI tweaks to show min/max and selected range from constraint bounds. So we have parameter min/max, and selected min/max. Note it is rather difficult to advance on this front for selected min/max, as it seems any non-compartmental constraints result in 504 errors timing out, though the job is still in-flight - basically it is hard currently to generate multiple boxes that would result in parameter and selected having different ranges. This will be done subsequently, and also to update it to be closer to the design sketches.
Made funman a little more resilient, in that you can close the drilldown and it will keep track of the validation in progress - similar to how the TAS3 operators are tracking the in-flight simulation runs.
In funman, start a validation process and leave the drilldown, …
> feat: improve bound range indicators

- packages/client/hmi-client/src/components/model/petrinet/tera-initial-table.vue
- packages/client/hmi-client/src/components/model/petrinet/tera-parameter-table.vue
- packages/client/hmi-client/src/model-representation/service.ts
- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config.vue
* just creating some functions to access and update model values
> model function for getting and updating values

- packages/client/hmi-client/src/components/workflow/ops/model-edit/tera-model-edit.vue
The executed code saved in model edit wasn't saved entirely. The code to be appended to the notebook was being saved. Now the entire notebook is saved.
> fix(model-edit): executed code is saved properly

- packages/client/hmi-client/src/components/dataset/tera-dataset-overview-table.vue
- packages/client/hmi-client/src/services/knowledge.ts
Adding back value for missing datatype. The missing concept value will need a backend change in another ticket
> Small fix for missing datatype after Enrich Dataset

- packages/client/hmi-client/src/components/widgets/share-project/tera-share-project.vue
Issue: sharing input field was clearing on every input. 
Moved the clear into the if `selectedUser` if condition
> fix for sharing input clearing

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/simulation/Simulation.java
The ``@Convert` annotation was a hold over from when we were using object here and was resulting in issues with serialization
> fix[hmi-server] - broken simulation runs

- packages/client/hmi-client/src/components/model/petrinet/model-diagrams/tera-model-diagram.vue
- packages/client/hmi-client/src/model-representation/petrinet/nested-petrinet-renderer.ts
- packages/client/hmi-client/src/model-representation/petrinet/petrinet-renderer.ts
- packages/client/hmi-client/src/model-representation/petrinet/petrinet-service.ts
Clicking on a regular transition triggered opening a stratified transition matrix which threw an error. 
Now I make sure to check if the transition being hovered on is stratified. This is more accurate than checking if the model is stratified since there could be some transitions that are regular and some that are stratified in the same model.
> fix(model-diagram): check if transition node is stratified

- packages/client/hmi-client/src/utils/number.ts
- packages/client/hmi-client/tests/unit/utils/number.spec.ts
1. Created some functions to do some conversions for the new input field:
- number -> exponential
- exponential -> number
- number -> NIST
- NIST -> number
- displaying a number (this depends on the length)
2. I have made the input for all these functions a string, since we can deal with very small or very large numbers it can lead to precision issues if we were to use the Number library to manipulate these inputs
3. UNIT TESTS!!
> Number utils

- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config.vue
Issue was previously that if the `value` and you swapped the configs then it would update the underlying object but not update the UI. A refresh would be required to see the `value` get updated correctly.
https://github.com/DARPA-ASKEM/terarium/assets/17088680/39f7d17c-50dd-48f2-88f8-1bdc56be4771
> correcting behaviour with key update

- packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratify-mira.vue
Add llm toolbar to stratify operator for code generation
Note:
- Not all prompts work, however this template of `show me code to stratify model abc by region named xyz and zzz` had worked more consistently
- The code generated is not precisely correct, it should be "model = stratify(..." instead of "stratified_model = stratify(...". However this is outside of the scope of this PR to address.
> Llm stratify

- packages/client/hmi-client/src/services/knowledge.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
When the user tries to enrich a document in a model. If the document is still being processed, an null error would appear.
> handled error when doc is still processing

- packages/client/hmi-client/src/components/documents/tera-text-editor.vue
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DatasetController.java
Two issues at play here.  Firstly, the front end treated text as HTML and broke when there was `<` `>` characters in the body. Secondly, quotes weren't being stripped from headers.  WE SHOULD REALLY NOT BE CONSUMING CSVS LIKE THIS... but that may be for another issue...
Resolves #3555
> 3555 bug unable to enrich dataset with a text extraction only contains an abstract

- packages/client/hmi-client/src/components/workflow/tera-workflow.vue
For some reason we forgot to flag workflow to be saved on 
- operator node removal
- branch workflow
Remove a node in a workflow, then quick navigate away, and come back, note the removed node should not reappear.
> flag workflow to be saved on remove-node and duplicate-branch

- packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman.vue
`requestParameter` is saved into the operator state, but when upstream configuration changes it needs to be refreshed.
- Create a simple funman workflow, e.g. `SIR => model-config => funman`
- Select beta/gamma are parameters of interest under "additional options"
- Run funman
- Goto model-config operator, change beta/gamma upper/lower ranges
- Goto funman operator, run funman
- Compare the two results, verify that they have different output ranges based on the model configuration settings.
> fix cache not refresh upper and lower bound on upstream change

- packages/client/hmi-client/src/components/operator/tera-operator-inputs.vue
- packages/client/hmi-client/src/components/operator/tera-operator-outputs.vue
* A small fix to address the bug where dragging an operator from a label will cause wonky arrows to appear.  Now you cannot drag when clicking a label (see attached bug ticket from additional details)
> do not drag operators when clicking on the input or output ports

- packages/client/hmi-client/src/components/workflow/ops/model-edit/tera-model-edit.vue
The notebook code was only saved once the new output model was created. Any edits after that were not saved.
Now the code is saved properly.
BEFORE:
https://github.com/DARPA-ASKEM/terarium/assets/28237258/59439e70-ba39-49f3-ba77-e161f3c772ea
AFTER:
https://github.com/DARPA-ASKEM/terarium/assets/28237258/eace54c6-33c2-4638-ae15-b64dcd00f1c6
> fix(model-edit): code is saved properly in output state

- packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman.vue
The constraint-group keys were too loosely generated that they refresh every time the underlying data changes, this hooks up a parent-surrogate key, so it will re-render when switching output, but not constantly refresh if values are changed.
Within a funman-operator
- verify that you can enter the numeric constraints
Run a couple of scenarios with different constraints, verify you can switch between these and the UI is reflecting the changes.
> fix funman contraint-group-key generation

- packages/client/hmi-client/src/components/workflow/ops/funman/funman-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-output.vue
- packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman.vue
Remember the selected trajectory-state in funman output, this will be saved to the operator's state, and shared across the operator's output.
In funman operator with several outputs
- change the shown trajectory state
- switch to different output, verify trajectory state did not change
- exit the operator and come back, verify trajectory state is restored
> remember selected traj-state in funman output

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DatasetController.java
Small fix to stop filenames from duplicating
> Dataset filenames repeating

- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config.vue
On the Model Config the save option should not be in the menu. It should be a button under it in the drill down section.
> move menu save option to a button

- packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman.vue
Fix pyodide errors that arose because parameters have no values - for now default to 0. 
May need to revisit in the future to sample distribution if provided.
> default to 0 if no value found for pyodide paramters-map gen

- packages/client/hmi-client/src/components/navbar/tera-navbar.vue
- packages/client/hmi-client/src/page/data-explorer/components/tera-search-results-list.vue
sorting wasn't handling different cases
> sorting case-sensitive fix

- packages/client/hmi-client/src/components/dataset/tera-save-dataset-from-simulation.vue
- packages/client/hmi-client/src/components/dataset/utils.ts
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss.vue
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-julia/tera-simulate-julia.vue
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/SimulationController.java
Parameters sent to this `isSaveDatasetDisabled` were incorrect resulting in never being able to save a dataset :( 
-Rename to have dataset not be camel cased as 2 works
-Change parameter from boolean to the value it wants
-remove the appending of "result dataset" for every file when user did not specify
-move logger success to after it actually succeeds
> [Fix]: Save dataset was always disabled due to mismatching types in function call

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/TaskNotificationEventTypes.java
- testing/manual/test-workflow-interactions.md
Add a logger for when we do not have an event type found. 
This will help us update our enums accordingly and have a bit more information when this scenario happens
```
2024-06-11 10:38:19 [WARN] Event type not found for task: mira_task:amr_to_mmt [software.uncharted.terarium.hmiserver.service.tasks.TaskNotificationEventTypes:21]
2024-06-11 10:38:19 [INFO] Sending client event with type TASK_UNDEFINED_EVENT for task befe548e-adf3-4614-8eec-26378b0f9b4f  [software.uncharted.terarium.hmiserver.service.tasks.TaskService:452]
```
> Task runner log: check for null type and log

- packages/client/hmi-client/src/components/widgets/tera-input.vue
* made some small tweaks to the tera-input component based on some comments with @jamiewaese-uncharted 
* label now outside of input box
* some other minor css tweaks
> tera input changes

- containers/scripts/docker-compose-taskrunner.yml
We need to use the builder image, so it cannot be pulled.
> Build images locally for taskrunner rather than pulling

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/repository/data/ModelConfigRepository.java
* I started with a big spike branch things were getting messy, but Im going to integrate things piece by piece now into the spike branch.  Anyways here's an updated function to get all model configurations by model id.  This is used in the model configuration drilldown when listing all configurations
> find model configs by model id

- packages/client/hmi-client/src/components/widgets/tera-columnar-panel.vue
- packages/client/hmi-client/src/components/workflow/ops/model/tera-model-workflow-wrapper.vue
* With the recent changes to the model some css changes broke scrolling on some drilldown components.  This should fix it.
* surrounding `<tera-model>` with `<tera-drilldown-section>` allows unmount to be called
> fix drilldown styles

- packages/client/hmi-client/src/components/workflow/tera-workflow.vue
Hide operators that are no longer in active use
- model transformer
- decapodes
- model-coupling
Existing workflows with the operators mentioned above may fail.
> hide unused operators

- packages/client/hmi-client/src/model-representation/mira/mira-common.ts
- packages/client/hmi-client/src/services/model.ts
- packages/mira/tasks/amr_to_mmt.py
MMT's observable contains an expression string that is a bit more difficult to work with in javascript space, we will add a transformer/summarizer at the task runner stage to make downstream consumption a little easier.
TLDR: This is effectively a subset of the mmt.observables section, but with better access to linked states.
The new object defn at hand, 
```
export interface ObservableSummary {
[key: string]: {
name: string;
display_name: string;
description: string;
expression: string;
references: string[];
};
}
```
amr-to-mmt should have a new section for obsrvable summary
> add a mira observable summary section for amr-to-mmt task

- packages/client/hmi-client/src/services/jupyter.ts
- Avoids hanging jupyter sessions
- If the user unloads the page the session still exists, now it is shutdown
- The way we've been shutting down the session is limited to the component level - eg. in `tera-model-edit` the `onUnmounted(() => kernelManager.shutdown)` only triggers if you close the drilldown
https://github.com/DARPA-ASKEM/terarium/assets/28237258/65e7a01d-1d49-41a0-91f6-5780a586ec08
> fix: shutdown jupyter session on page unload

- packages/server/src/main/resources/messages.properties
Copy edits to Terarium error messages easier to understand. Below are some suggestions for adding to and maintaining these going forward.
- Use informal conversational language wherever possible.
- Use contractions ("can't" instead of "cannot").
- Use active voice instead of passive (instead of "the service **was terminated**…" try "**We terminated** the service…").
- Avoid software development jargon that users may not understand ("UUID," "curies").
- Don't introduce backend terms that users never see in the UI. For example, avoid terms like "artifacts" and "assets" if users only see "resources" in the UI.
- Consider whether it's necessary to name a backend service that users never see. Instead of referencing "SKEMA," determine whether it would be clearer to refer to our "model service." …
> Copy edits for error messages

- packages/client/hmi-client/src/components/widgets/tera-input.vue
- packages/client/hmi-client/src/components/workflow/ops/interventions/tera-intervention-card.vue
- packages/client/hmi-client/src/components/workflow/ops/interventions/tera-interventions-drilldown.vue
- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/simulationservice/interventions/Intervention.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/simulationservice/interventions/InterventionSemanticType.java
* Use states instead of parameters for target in dynamic interventions as per this [thread](https://unchartedsoftware.slack.com/archives/C03S02YH3D5/p1720047460929369?thread_ts=1720042002.213279&cid=C03S02YH3D5)
* switched threshold and value around
* added intervention semantic type (variable, parameter) selection
> switch threshold and value, use states

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/TerariumAssetServiceWithSearch.java
Since this kicks off in a separate thread, which is required to prevent a deadlock in the task service, we cannot check if the asset exists, because the original transcation creating the asset may not have committed by then.
The check isn't needed anyway.
> Remove the check that causes a race condition

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
Mostly plumbing to generate summary for calibrate
By default an LLM-generated summary will be provided for calibration run. You can overwrite it with human crafted summary.
> generate calibrate operation output summary

- packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss.vue
"decimal" is an invalid option that gets routed to produce string-type, which then create problems for downstream consumers.
> fix "decimal" tera-input type

- packages/client/hmi-client/src/model-representation/mira/mira.ts
* Fixes an edge cases issue where initials have an underscore AND that are not stratified the initial is renamed to something unrecognized.
* The fix is if there is only 1 child initial when we collapse the initials, we rename the root to the child initial which is recognized
Example:
We have `Cumulative_cases` which is an initial target, but this is not a stratified initial:
before fix collapseInitials:
```
{"Cumulative" => Array(1)}
key: "Cumulative"
value: ['Cumulative_cases']
```
On the model config node it will look for `Cumulative` to edit which does not exist
after fix :
```
{"Cumulative_cases" => Array(1)}
key: "Cumulative_cases"
value: ['Cumulative_cases']
```
On the model config node it will look for `Cumulative_cases` to edit which does exist
An example where this was causing …
> fix collapse initials

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ModelConfigurationService.java
* If a number gets stored as an integer we can't just cast to a double. Go the long way around.
> Cast exception when recalling model config

- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
* We want to display the risk tolerance the opposite of how `alpha` is being sent to `pyciemss-service`
> Change riskTolerance to be a negative of alpha for pyciemss-service

- packages/client/hmi-client/src/services/models/simulation-service.ts
In `getRunResultCiemss` we establish how PyCIEMSS result should map back to the model, our mapping logic seem to be out-of-date for observable variables, which cause the ground-truth not not appear in calibrate operation.
This PR should fix the logic, but also mark getRunResultCiemss as deprecated as we start to replace the chart.js charts with Vegalite, which generally wants a more simplified data format that is closer to the raw produced data.
- Do a calibrate operation, the mapping should map an observed variable in the model to the grounding data
- When calibrate finishes, chart the observed variable, should see both the forecast-values and ground-truth-values
> fix observable mapping

- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/optimize-ciemss-operation.ts
This `getOptimizedInterventions` is kindve ugly. We should consider moving it later but while everything is in flux this fix should allow us to leave this alone for a bit.
> Intervention created from FE needs snake -> camel caes

- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config.vue
- packages/client/hmi-client/src/services/charts.ts
* Fixes an issue where success criteria charts wouldn't render when incoming data would be of size 1 or the min and max values in the dataset are the same.
> success criteria chart fix

- packages/client/hmi-client/src/components/drilldown/tera-drilldown.vue
- packages/client/hmi-client/src/components/operator/tera-operator-port-icon.vue
* Set the `pi-cog` icon as the default icons for input chips in drilldown header
* Some clean up and changes requested by design team
> Set basic icons for input pills

- packages/client/hmi-client/src/components/workflow/tera-workflow.vue
When using `index` as the key in v-for, changes in the list can alter the index order, causing refs to point to incorrect items. This results in `teraNode = teraOperatorRefs.value.find((operatorNode) => operatorNode.id === node.id);` returning the wrong node.
This change fixes the issue. 
https://github.com/user-attachments/assets/a7d84643-89c5-421d-bd73-a36d74279a0d
Resolves #4120
> Fixed node drag bug

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-julia/tera-calibrate-node-julia.vue
- packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-node.vue
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-julia/tera-simulate-node-julia.vue
- packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratify-mira.vue
- packages/client/hmi-client/src/components/workflow/util.ts
This is an attempt to fix and harmonize operator output numbering, where they are used. The numbering system is now generated in a util function rather than having each operator roll their own length check.
Not clear where we will go in terms of naming and design, but for now this will fix confusions in the TA3 realm where outputs are generally named "output-1, output-2, output-3 ... etc".
We should generate the numbers in sequence, and not have 2 output-2s
> fix workflow output numbering

- packages/client/hmi-client/src/services/charts.ts
Don't render charts if there are no variables, trying to render with a 0-length variable list can cause transform problems that later results in infinity-warnings.
> do not render chart is there are no variables

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/calibrate-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
Add in plumbings to support doing a "before" simulate with what is in model-configuration, and an "after" simulate with altered parameters from calibrate.
No UI changes for now, calibrate should work as before, but before/after simulationIds will be recorded.
> Calibration, support before and after simulations for comparisions

- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/optimize-ciemss-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
-Allow user to disconnect an intervention and correctly update the optimize intervention groups.
Previously we were checking is state of input ID === input ID.
This will never work, state is updated when input is updated.
#Testing
https://github.com/user-attachments/assets/320e2d30-7953-4785-b238-262bbc508350
> FIX: Optimize setInterventionPolicyGroups re-init correctly.

- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
> add pyciemss-api call to notebook.

- packages/client/hmi-client/src/services/workflow.ts
- packages/client/hmi-client/src/types/workflow.ts
- packages/client/hmi-client/tests/unit/services/workflow.spec.ts
Initial work to support operator output that can contain more than one type. For example calibrate run create a dataset + config. The way this is handled is to piggy back on the current notion where we "accept" one or more types.
```
type: 'datasetId | modelConfigId`
```
and the value of the output being an object keyed by the type:
```
value = [{
datasetId: 'abcdefg',
modelConfigId: 'aaaaabbbbbb'
}]
```
I largely removed the "allowMultiple" idea, as it isn't been used from what I can gather and it creates a boatload of edge cases that we would need to deal with.
In unit tests
```
yarn workspace hmi-client run test workflow
```
> support operator output with multiple types

- packages/client/hmi-client/src/services/charts.ts
Tweaks palette and y-axis formatting
> tweak categorical color palette and y-label format

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue
* just showing axes labels on the nodes (same labels as the bigger charts in the drilldowns)
* Im having a lot of issues trying to show the legend in the node view, so decided to get these axes labels in there
> node axes labels

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ProjectController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/project/ProjectAsset.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/notification/NotificationEvent.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/notification/NotificationGroup.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/repository/PSCrudSoftDeleteRepository.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/repository/data/FrameworkRepository.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/repository/data/ProjectRepository.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ProjectService.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/utils/rebac/ReBACService.java
- packages/server/src/main/resources/db/migration/V15__Remove_Project_Asset_Aggregation_Index.sql
Unfortunately there isn't support in hibernate for partial indixes. Ideally we would index on `IS NULL` for `deletedOn` to speed those up.
We can put those in flyway, but due to how we setup the `baselineVersion` stuff, it would skip those.
> Add PG indexes

- packages/client/hmi-client/src/components/model/tera-model-parts.vue
- packages/client/hmi-client/src/components/model/tera-model.vue
- packages/client/hmi-client/src/page/data-explorer/components/tera-asset-card.vue
* Save as saves the current edited state of the model as a new model
* Reset resets the edited state to the original model
https://github.com/user-attachments/assets/97253e5c-f535-4ad8-a4a1-5d020dc2e4c6
> feat: reset and save as for model page

- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
> fix: Put the failed-run indicator on the output border

- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelConfigurationController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/modelparts/ModelDistribution.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ModelConfigurationService.java
* After creating a new model configuration, we weren't properly selecting it from the the list of model configs. As a result the output and the download would be the last selected/created config even though it *looked* like it shouldn't be.
* In addition I've found more casting exceptions because of the presence of `Object` in the back end. This should be `Number` but that could break our python services down stream, and requires a migration and I just want to get it in.
* Lastly, we should return the new model we've created ;)
> Fixing wrong model configuration selection

- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
When we have a successful run we should not be showing a red border
With this we will update our border for both pass and failed runs rather than just for failed runs
https://github.com/user-attachments/assets/7711319a-6171-4ece-a994-6937979c5065
> Optimize red border now removed when successful run.

- packages/client/hmi-client/src/components/widgets/tera-slider-panel.vue
**BEFORE**
I don't like how text is cut off at an arbitrary point here.
**AFTER**
I added an @scroll listener to the resource panel, and if the user scrolls down, we add a class to the header that adds a shadow.
> added subtle shadow to header when panel is scrolled

- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
Resolved the fixme comment to use `getModelByModelConfigurationId` for fetching model from model configuration id
> Resolved FIXME to fetch model from model configuration id

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
We misinterpreted progress as a percentage progression, it is  number of completed iterations, so we need to instead do:
```
100 * progress / max-iteration
```
> fix misinterpretation of progress as percentage-progress

- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue
`_.uniq`  causing a problem splitting a single variable string into a character-array
> fix yaxis label extraction expression

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelConfigurationController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/model/configurations/InferredParameterSemantic.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/model/configurations/ModelConfiguration.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/model/configurations/SemanticType.java
- packages/server/src/main/resources/db/migration/V16_semantic_constraint.sql
`POST /model-configuration` is janky due to a handful of issues, while the object is created in the DB, it is missing bits and pieces, and at times will pull back incorrect data.
- Fix a chicken-and-egg problem problem with model-configuration-id, this was causing children to be orphaned
- Yes, `InferredParameterSemantic` is exactly the same as `ParameterSemantic`, hibernate shoves children objects into the same table (via the dtype column), so you cannot have `List<Foo> a, List<Foo> b`, the lists need to be of different class types otherwise it will end up fetching the wrong thing
- As a consequence of the above, we need to do data migration - took this opportunity to remove the extra calibration-run-id column
- Fix places where we missed setting a few needed fields
> fix POST /model-configuration endpoint logic

- packages/client/hmi-client/src/components/drilldown/tera-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-julia/calibrate-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/decapodes/decapodes-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/model-coupling/model-coupling-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/simulate-julia/simulate-julia-operation.ts
- packages/client/hmi-client/src/page/WorkflowNode.vue
- packages/client/hmi-client/src/types/workflow.ts
- packages/client/hmi-client/tests/unit/services/workflow.spec.ts
Enums are useful for capturing controlled a vocabulary, things that do not change very often or are static in nature.
Since we are adding and removing operators at a fairly quick cadence this is not an appropriate data structure, especially if we want to model this in the DB which will likely mean a data-migration every time we add or remove operators.
In additional, while the keys are unique,  there is no guarantee on the value so there isn't really a safe guarantee.
Change this to a frozen-object, and the datatype of operator name to just a string.
I removed a few references to operators that are deprecated, otherwise no functional changes, app should work as before.
> remove operation-type enum

- packages/client/hmi-client/DEVELOPMENT.md
- packages/client/hmi-client/src/components/asset/tera-asset.vue
- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
- packages/client/hmi-client/src/components/workflow/ops/model-comparison/tera-model-comparison.vue
- packages/client/hmi-client/src/page/data-explorer/components/tera-asset-card.vue
- packages/client/hmi-client/src/page/data-explorer/components/tera-preview-panel.vue
* When testing compare models the add to project button was missing when I was searching for the models to compare
* I know we are getting rid of search but this still will be helpful for a while
* Also cleaned up some unused props
> fix: add + button back into asset card

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
Adding initials and observables into calibrated model-config.
initials are meant to be readonly ... you "could" modify them but it kind of voids the calibration effort.
observations need to be carried forward from the base-configuration, as the base-config observables can be different than that of the observables on the model iteself.
See also: https://github.com/DARPA-ASKEM/terarium/pull/4377
Example of calibrated-model-config, with initials and observables filled in.
```
{
"id": "ba967f5c-dee2-46ec-8768-702c14544abc",
"createdOn": "2024-08-08T16:38:14.549+00:00",
"updatedOn": "2024-08-08T16:38:14.549+00:00",
"name": "Calibrated: Default Configuration",
"description": "Calibrated: This is a default configuration.",
"fileNames": [],
"temporary": false,
"publicAsset": false,
"modelId": …
```
> Add initials and observables into calibrated model-configs

- packages/client/hmi-client/src/components/home/tera-project-menu.vue
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ProjectController.java
Two issues are going on:
1) ProjectController.makeProjectPublic was converting meaningful ResponseStatusExceptions into a generic meaningless SERVICE_UNAVAILABLE
2) Users with only "writer" permissions cannot share a project.
> Sharing project causes 503

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/WorkflowService.java
- packages/server/src/test/java/software/uncharted/terarium/hmiserver/controller/dataservice/WorkflowControllerTests.java
- packages/server/src/test/java/software/uncharted/terarium/hmiserver/service/data/TerariumAssetCloneServiceTests.java
- packages/server/src/test/java/software/uncharted/terarium/hmiserver/service/data/WorkflowServiceTests.java
Remove ES-mirroring, this speeds up the total round-trip time for workflow update by about 30-35 tiems, since it was waiting for ES to refresh. 
We have moved to PG, ES is no longer the primary data storage and this mirroring is not needed.
> Do not mirror workflow

- packages/client/hmi-client/src/services/workflow.ts
We cannot just do `nodeA = Object.assign(nodeA, update)` because some of our operators are written to be very reactive - in their watcher they do not check if the new/old values are equivalent. So when we sync up with the database it triggers, among other things, unwanted append-output cycles, which itself invalidates downstream and marks the workflow dirty in order to trigger another update ... and so the cycle repeats.
So instead we need to update node piecemeal
> another attempt at fixing workflow bugs

- packages/client/hmi-client/src/components/widgets/tera-toggleable-input.vue
- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
* An empty name was rejected by typescript, now I have to specifically check if a `string` exists
* I wonder if we can just make the `name` be of type `string` instead of `string | undefined`, that we don't need the `v-if` at all
https://github.com/user-attachments/assets/acd1c79e-f379-4b9a-8b2d-661ea4ca9403
> fix: render toggleable input as long as the value is a `string`

- packages/client/hmi-client/src/components/widgets/tera-canvas-item.vue
- packages/client/hmi-client/src/components/workflow/tera-workflow.vue
- Avoid save/update cycle when node being dragged, which can create weird jitter effects and disconnected edges
- Ensure save is called when changing between workflows
Make some change to existing workflow, navigate away immediately, come back to save workflow and check the change persisted.
> better workflow save/update timing

- packages/client/hmi-client/src/components/drilldown/tera-drilldown-section.vue
- packages/client/hmi-client/src/components/widgets/tera-toggleable-input.vue
- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-card.vue
- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue
Using `flex-1` to fill in the space for the input field. Shifted around some html to accommodate this.
BEFORE: 
AFTER:
https://github.com/user-attachments/assets/131751bc-2bcc-4cb6-9d67-3be9cc88e3ca
> style: stretch toggleable input to fill space

- packages/client/hmi-client/src/services/workflow.ts
The generator is faulty because it only looks at the first item from the outputMap, but there can be multiple items when an operator produces 2 or more different asset types (e.g. calibration). This PR reworks the logic to take this into account.
> fix menuitem generation logic

- packages/client/hmi-client/src/components/asset/tera-asset.vue
- packages/client/hmi-client/src/components/model/model-parts/tera-model-part-entry.vue
This page tends to be cut off when there are long stratified variables. This quickly addresses the issue.
https://github.com/user-attachments/assets/c1c6f881-1866-42ce-88fc-413e66d5d3f7
> style: fix overflow in asset pages and model entry

- packages/client/hmi-client/src/components/workflow/ops/model-config/model-config-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-node.vue
Add spinner to model config node when user extracts inputs
> show spinner for model-config extraction

- packages/client/hmi-client/src/components/navbar/tera-notification-panel.vue
- packages/client/hmi-client/src/composables/notificationManager.ts
There was an issue that error state notification appeared as normal and can't be cleared out from the notification panel. 
This fixes the issue.
E.g ^ notification errored out but looks fine and wasn't being cleared out when clear notification was clicked. 
> Handle error state for the notification

- packages/client/hmi-client/src/components/workflow/ops/model-edit/tera-model-edit.vue
- model edit drilldown defaults to notebook
- wizard is disabled if there are more than 50 transitions (every transition is a template that triggers an `amr-to-mmt` call)
> fix: disable wizard for complex models

- packages/client/hmi-client/src/model-representation/petrinet/nested-petrinet-renderer.ts
- packages/client/hmi-client/src/model-representation/service.ts
Fixes #4578 
The problem is the margin is hardcoded, which means in deeper levels the radii go negative and although they are "rendered" they do not show up.
Use `yarn staging` for this one.
Goto http://localhost:8080/projects/34e7b955-f408-4e8b-be27-9429480ad6aa/model/7508b278-caea-4d35-bb17-097bdd463f07
Verify that state-S has 5 levels
> fix hardcoded margin causing nested levels to have negative radius

- packages/client/hmi-client/src/services/workflow.ts
I can't think of a scenario of why this might happen, but just in case we will verify the ids are the same before allowing update to continue.
> extra workflow update guard

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/mira/MiraController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/TaskService.java
- We weren't executing task response handlers on cached responses
- We weren't creating events for cached responses
- We weren't cleaning up amr-to-mmt payloads for caching
> FINALLY fix the task caching

- packages/client/hmi-client/src/services/workflow.ts
Should alleviate the issue when trying to delete nodes in quick succession, and causing the DB/client to become de-synced with each other.
The problem is getNodes/getEdges more excludes deleted elements, and we should use the full list when sync'ing
> address sync problem of deletes within a short interval

- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/simulationservice/OptimizeRequestCiemss.java
see https://github.com/DARPA-ASKEM/pyciemss-service/pull/115
To test run the pyciemss-service branch found in the PR above locally
Feel free to run simulations that include any combination of state/parameter and dynamic/static interventions
as well as no interventions.
> Rename optimize static interventions.

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ModelService.java
Lack of observables in a model becomes a null-field. This creates problems downstream. To solve the issue we will convert them into empty array
Upload the following AMR, when viewing it there shouldn't be any mira-task errors and the model-diagram should be visible
[dris.json](https://github.com/user-attachments/files/16802629/dris.json)
> force observable field to exist

- packages/mira/tasks/amr_to_mmt.py
Improve error tracing, the error wasn't sufficient enough to debug the issue effectively.
From
```
root@mira-taskrunner-5ddb8fb849-mdq7p:/tmp# mira_task\:amr_to_mmt --id xyz --input_pipe IN --output_pipe OUT --self_destruct_timeout_seconds 9999
Reading input from input pipe
Error: 'NoneType' object has no attribute 'items'
Shutting down
```
To
```
root@f6a2276abec3:/tmp# mira_task\:amr_to_mmt --id xyz --input_pipe IN --output_pipe OUT --self_destruct_timeout_seconds 9999
Reading input from input pipe
Error: 'NoneType' object has no attribute 'items'
Traceback (most recent call last):
File "/mira_task/tasks/amr_to_mmt.py", line 24, in main
mmt = model_from_json(amr)
File "/usr/local/lib/python3.8/dist-packages/mira/sources/amr/__init__.py", line 67, in model_from_json
return …
```
> improve error stack trace for amr-to-mmt task

- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue
* fixed a bug where showing the name for parameters and states would lead to confusion for stratified models in the intervention policy operator. 
* now we show the id in the UI rather than the name
> use id in intervention dropdown

- packages/client/hmi-client/src/components/widgets/tera-canvas-item.vue
Didn't realize we also had a drag-end event hooked into document click/mousemove - this creates unnecessary update-requests when moving around in the operator-drilldown space.
Fixes #4633
> fix drag-end emission

- packages/client/hmi-client/src/components/project/tera-resource-sidebar.vue
When asset have long name, the ressource panel is too small to display the full name. Now the title will display the full name as well as the creation time
> Add asset name on ressource panel hover title

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/gollm/GoLLMController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/TaskNotificationEventTypes.java
Put back removed generate summary handler to the notification type and added missing GenerateResponse handler to the gollm controller. 
> Put back removed generate summary handler

- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-node.vue
- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-node.vue
* Adding an extra guard here for the watcher on the model config and intervention policy nodes.  The extra guard will not change the `state` if the incoming input model id is the same as the model config's/ intervention policy's `state` `modelID`
> guard inputs changes for model configuration and intervention policy

- packages/client/hmi-client/src/components/asset/tera-asset.vue
- packages/client/hmi-client/src/components/dataset/tera-dataset-datatable.vue
- packages/client/hmi-client/src/components/dataset/tera-dataset-overview-table.vue
- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
- packages/client/hmi-client/src/components/widgets/tera-asset-enrichment.vue
Misc styling tweaks to the dataset page
- also corrected the mis-counted number of rows in the dataset datatable
> Jamie dataset design tweaks

- packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-boundary-chart.vue
- packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman.vue
- packages/client/hmi-client/src/services/models/funman-service.ts
Change parsing to use upper-bound instead of lower bound, previous assumption that for each box timestep's lb===ub is not correct.
Remove menuItem save-as, since we will be reworking the designs anyway.
Closes #4394 
False boxes, if applicable, should be showing up in funman model-config validations.
> funman false-boxes parsing, remove save-as UI until redesign

- packages/client/hmi-client/src/components/drilldown/tera-drilldown.vue
- packages/client/hmi-client/src/components/operator/tera-operator-inputs.vue
- packages/client/hmi-client/src/components/operator/tera-operator-outputs.vue
- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-node.vue
- packages/client/hmi-client/src/services/save-asset.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/TerariumAssetServices.java
* propagate asset renaming in nodes
* node label now depends on the project asset name and falls back to the label name
* model configurations and intervention policies can now be added to projects
https://github.com/user-attachments/assets/c0facde2-30f1-4ec6-86dc-077d8b411db3
> propagate asset renaming

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ModelService.java
It seems like in some cases ODE is null when doing equations-to-model, this adds an extra guard so we do not end up with null-pointer exceptions.
Was reported by Holly - but lacking detail to reproduce the error.
> modelservice getOde null guard

- packages/client/hmi-client/src/components/model/model-parts/tera-model-part-entry.vue
- packages/client/hmi-client/src/model-representation/service.ts
- When adding the concept input to `tera-dataset`'s `tera-column-info`  I found that going back to an empty concept or accepting a valid input (without choosing an autocomplete option) wasn't accepted as a valid edit
- Here is the fix done for the model page
- Also cleaned up a conditional button
https://github.com/user-attachments/assets/2b3d6410-3371-443c-bf39-aaa09554e46c
> fix(model concept editing): accept empty value and input value

- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/optimize-ciemss-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue
- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/simulationservice/CiemssStatusUpdate.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/simulationservice/statusupdates/CiemssCalibrateStatusUpdate.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/simulationservice/statusupdates/CiemssOptimizeStatusUpdate.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/simulationservice/statusupdates/CiemssStatusType.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/simulationservice/statusupdates/CiemssStatusUpdate.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/SimulationEventService.java
- Allow for optimize's intermediate results to be captured in `CiemssStatusUpdate` by adding optional fields
- Adding `currentProgress` to optimize state
- Adding % message to optimize node and drilldown based off of the optimize iteration step.
- Adding a static message when forecast runs are running.
https://github.com/DARPA-ASKEM/pyciemss-service/pull/116
-Running the above pyciemss-service branch we can run optimize which will now have intermediate results sent to rabbitmq
-We can also confirm the type change has no impact on calibration's intermediate results
> Optimize spinner progress

- packages/client/hmi-client/src/services/workflow.ts
`WorkflowWrapper#selectOutput(...)` is used to propagate output changes, this was copying the values directly which does not work for compounded outputs such as calibrate. 
The following sequence of actions to build a workflow should work and not crash
- add calibrate
- add simulate
- connect calibrate => simulate
- run calibarate
- run simulate
> fix compound type propagation for selectOutput

- packages/client/hmi-client/src/components/widgets/tera-canvas-item.vue
Clicking events on operators, such as opening the hamburger menu or annotations are interpreted as drag events, This is not desirable as these events queue up unnecessary workflow updates that get sent to the server. This PR adds an extra "mousedown" flag to better track state changes.
> prevent click from being interpreted as drag event

- packages/client/hmi-client/src/components/model/model-parts/tera-model-part.vue
Change onMounted to a watcher to recompute `parentEditingState.value` because props.items can change, which results in  invalid index access.
> accommodate for props.items change for model attribute displays

- packages/client/hmi-client/src/components/drilldown/tera-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratify-mira.vue
- packages/client/hmi-client/src/services/workflow.ts
There are sync'ing issues when an output-creation is split into multiple stages, where each stage end up invoking workflow-updates. For example here when stratify finishes:
- update the state with the code written
- save a new model and append output
because the two not grouped together it means at the time we are ready to update the new output, it could have been overwritten by the response from the update-state. This PR adds logic to try to guard against these cases.
- Tweak the model creation ordering, so we don't update the preview unless we have successfully create a model
- Group code-state update and appending output together 
- Add a few FIXMES for workflow-logic, and deprecation in tera-drilldown
- Better default output port labels (model-names)
Ideally I think update-state and …
> work around workflow de-sync problem in stratify

- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-node.vue
here is a watcher on model config that will append a new output on every input change.
Issue is:
user plugs in a new model (1)
user plugs in a new document/dataset to enrich with (2)
user plugs in a new document/dataset to enrich with (3)
We already have 3 essentially duplicate outputs appended to our node.
This is causing unnecessarily large nodes
Here we check for the value as our default output will be assigned and its value is null.
> Model Config only append to output when we dont yet have one.

- packages/client/hmi-client/src/services/workflow.ts
There is a bug with branching when the subgraph forms a diamond, the upstream edges are not calculated correctly.
Before: note one of the simulate is disconnected from its upstream model-config
After:
In a workflow
- add model, model-config, intervention-policy, simulate
- connect model=>model-config, model=>intervention-policy, {intervention-policy, model-config} => simulate
- branch on either the intervention-policy or model-config node
The resulting new subgraph should still form a diamond formation with the existing graph
Fixes: https://github.com/DARPA-ASKEM/terarium/issues/4562
> fix branching workflow in diamond arrangement

- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue
Some long running optimizations will take more than the 500 seconds provided in this poller.
This is causing errors for the demo videos.
https://app.staging.terarium.ai/projects/55901a7a-4e6b-4b9e-a07a-58c3a248c9fa/workflow/b913936f-5eb3-458c-af58-de7c9bd8e5cb
I am bumping our threshold to 350 as that should be more than enough time.
Later I can discuss a more dynamic approach to these values with Daniel
> Optimize threshold from 100 -> 350

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/AdobeController.java
* Was using the default Orgin header, but axios uses Referer instead
* Update our controller to test that header instead
> Change Adobe key test from Origin to Referer

- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
- packages/client/hmi-client/src/services/charts.ts
It looks like there's no way to filter or select data columns to reduce the size of the data using only vegalite chart spec. So , I just chopped off the unused variables from the datasets before passing it to the chart. 
Before we had an issue of browser crashing when more than 3 variables are selected. Now more variables can be selected. 
Note: We still have issues when too many variables are selected with large dataset. For this particular example (https://app.staging.terarium.ai/projects/f6a5af08-8d19-4462-bc5b-c12a9d6f6616/workflow/d7bf01c5-7c6e-4503-800c-f2d03dea9d1e?operator=bff38ac4-ca7a-44c4-8eca-e82f2a69dccb) , it will still crash the browser when all variables are selected. We may want to introduce the limit on the chart to prevent user from selecting too many variables. …
> Select only relavant variables for the chart

- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue
provisionally Include interventions in summary generation. 
Relates to: https://github.com/DARPA-ASKEM/terarium/issues/4850
> include interventions in summary generation

- packages/client/hmi-client/src/components/workflow/tera-workflow.vue
- packages/client/hmi-client/src/services/workflow.ts
Saving the active project id in the workflow, as when we unmount this component we lose this injection later on.
Resolves #3672
> [BUG]: 400 error occurs when navigating from workflow to home

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss-drilldown.vue
There are about a dozen warnings of invalid HTML in the ensemble operators - This PR just aims to clean things up so other potentially more serious problems are not getting hidden because of these.
e.g.
```
5:29:28 p.m. [vite] warning: <td> cannot be child of <tbody>, according to HTML specifications. This can cause hydration errors or potentially disrupt future functionality.
139|  									<tera-input-number class="w-full" v-model="timeSpan.start" />
140|  								</td>
141|  								<td>
|          ^^^^
142|  									<tera-input-number class="w-full" v-model="timeSpan.end" />
|  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
143|  								</td>
|  ^^^^^^^^^^^^^
Plugin: vite:vue
File: /Users/dchang/workspace/askem/Terarium/packages/client/hmi-client/src/components/ …
```
> fix invalid htmls

- packages/client/hmi-client/src/components/workflow/tera-simulate-chart.vue
- packages/client/hmi-client/src/components/workflow/util.ts
- packages/client/hmi-client/src/types/SimulateConfig.ts
Removing run type as we no longer have julia
> remove runType

- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
Change the order of variable updates for presets to take effect
- Select a model with some parameter value variability (with lower/upper bound not equal). 
- Hook up model => model-config => simulate
- Run "normal" simulation, then run "fast" simulation, it should be obvious the two runs are different as the former has significantly more samples than the latter.
Fixes: https://github.com/DARPA-ASKEM/terarium/issues/4848
> fix simulate preset selection not triggering update

- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-card.vue
Only the first timestep was updating.
This fix should update the others when a new static intervention is created
> fix for timestep

- packages/client/hmi-client/src/components/model/petrinet/tera-model-description.vue
This pull request includes several changes to the `tera-model-description.vue` component to enhance the handling of model descriptions by introducing base64 encoding and decoding. The key changes involve importing necessary utility functions, updating the editor content initialization, and modifying the watch function to ensure consistent encoding and decoding of the model descriptions.
* [`packages/client/hmi-client/src/components/model/petrinet/tera-model-description.vue`](diffhunk://#diff-37bb08775f7fb2755f7c1843e1bb763eadfb08f535faf6a4962809fc91bc0f4bR33-R40): Imported `b64DecodeUnicode` and `b64EncodeUnicode` from `@/utils/binary` to handle encoding and decoding of model descriptions.
* [`packages/client/hmi-client/src/components/model/petrinet/tera-model-description.vue`](diffhunk:// …
> Add base64 decode/encode to model description

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
- testing/manual/dataset-enrichment.md
I do not see this section in the test anywhere I am assuming this is just out of date?
Maybe i am also just missing it on the page?
https://app.staging.terarium.ai/projects/f8501b9d-31ab-4551-bdef-c8e8cd3c7491/dataset/5f916cb1-5ee6-4cb0-9b34-3e520ba7fa0c
> Remove provenance from test

- packages/client/hmi-client/src/components/model/tera-model.vue
This pull request includes changes to the `tera-model.vue` component to enhance user experience by adding a tooltip and ensuring that changes are saved when renaming a model.
* Added a tooltip to the rename button to inform users that renaming the model will save all current changes.
* Modified the `updateModelName` function to call `onSave()` after renaming the model, ensuring that all changes are saved.
> Renaming model save edit too

- packages/client/hmi-client/src/components/workflow/ops/document/tera-document-operation-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue
Issue:
When a user clicks on an equation, all of the equations input field appear. This is due to the equations all sharing the same name:
Change:
Add the array index of the equation to the name parameter.
Testing:
Add 2 equations using the add equation field and select one of the equations. Only one input field should appear.
> multiple input field open when selecting one

- packages/client/hmi-client/src/components/documents/tera-document-asset.vue
- packages/client/hmi-client/src/components/workflow/ops/document/tera-document-operation-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue
Design Change: 
- Remove the extraction from the document viewer and document drill down
- Only enable extractions in the drill down 
Testing:
- Opening a PDF document from the resources panel or  drill down the extraction option should not appear
- When opening Model from Equations, all extracted equations should appear here
> Remove extractions from document asset n drilldown

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-node.vue
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue
- packages/client/hmi-client/src/services/charts.ts
There was issues in multiple drilldown caused by wrong use of groupBy on intervention array data. 
For example, 
```
interface Intervention {
name: string;
staticInterventions: StaticIntervention[];
dynamicInterventions: DynamicIntervention[];
}
const groupedInterventions = _.groupBy(interventions, 'appliedTo'); // interventions as Intervention[]
```
We were doing groupby 'appliedTo` field while the top level Intervention object doesn't have it. 
In this change, I fixed issues caused by ^ in multiple operators. 
**Simulation operator**
**BEFORE:**
**AFTER:**
**Intervention policy operator**
**BEFORE:**
**AFTER:**
> Fix bug on grouping interventions

- packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratification-group-form.vue
This pull request includes a small change to the `tera-stratification-group-form.vue` file. The change simplifies the label for entering a comma-separated list of labels by removing the additional text about the maximum number of labels.
> Update tera-stratification-group-form to remove Max 100

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/utils/JsonToHTML.java
This pull request includes several changes to the `JsonToHTML` utility class to improve the formatting of JSON data when rendered as HTML. The most important changes include modifying the indentation level, updating the title formatting method, and enhancing the title formatting logic.
* Changed the initial indentation level from 0 to 2 in the `renderJsonToHTML` method.
* Replaced the `capitalizeFirstLetter` method with `formatTitle` to improve title formatting by splitting camel case words and capitalizing the first letter of the resulting title.
* Updated the `renderObject` method to use the new `formatTitle` method instead of `capitalizeFirstLetter`.
> Update model card description to be prettier

- packages/client/hmi-client/src/components/llm/tera-notebook-jupyter-input.vue
Add the LLM prompt to the beginning of the code generated
Testing: After generating the code, the prompt should appear at the top of the generated code
> Add llm prompt to generated code

- packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue
Issue
- The equations after starting a new project and uploading a new doc would not appear. This was caused by assigning the equations to a unused ref
Testing:
- Open a new project and upload a new PDF.
- Add doc to workflow and connect model from equation node
- open node and the extracted equations should appear
> fix with equations not appearing

- packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue
Issue:
- when the equations longer then the asset block the full panel including all of the different equation becomes scrollable. 
Testing:
Add an equation longer then the asset block. The scrollbar show appear under the one longer equation. The full panel should no longer be scrollable.
> Add equation scroll bar

- packages/client/hmi-client/src/components/workflow/ops/code-asset/tera-code-asset-wrapper.vue
- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/model-edit/tera-model-edit.vue
- packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratify-mira.vue
- packages/client/hmi-client/src/components/workflow/tera-workflow.vue
- packages/client/hmi-client/src/services/workflow.ts
This pull request includes several changes focused on standardizing the event names in the `tera` components and improving code clarity. The changes primarily involve renaming the `update-output-port` event to `update-output` across various components and updating related function names accordingly.
Event name standardization:
* [`tera-code-asset-wrapper.vue`](diffhunk://#diff-87c6953826aa0eda7464920fac516185b0b9b8360e86d3053c702ce7a070f7b7L28-R35): Renamed the event `update-output-port` to `update-output` and updated the corresponding emit call in the `onApplyChanges` function.
* [`tera-intervention-policy-drilldown.vue`](diffhunk://#diff-54c31526a779022f9231558c720e27ce9e02ed6da5df3ff490e94bd8bc891248L208-R208): Removed the `update-output-port` event from the `defineEmits` call.
* …
> Rename update output port

- packages/client/hmi-client/src/components/widgets/tera-signal-bars.vue
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/optimize-ciemss-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-dynamic-intervention-policy-group.vue
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-static-intervention-policy-group.vue
- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/simulationservice/parts/OptimizeInterventions.java
* adding weighted interventions to optimize
Old optimize nodes will not be functional after this is merged
https://github.com/DARPA-ASKEM/pyciemss-service/pull/121
> weighted interventions for optimize

- packages/client/hmi-client/src/components/widgets/tera-slider-panel.vue
Before:
After:
Fixed the issue when chart settings overlay was scrolling along with the content behind it.
> Fixed scroll weirdness

- packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue
Design change:
- Have the Output Panel close when drill down is open and model has not been run.
- remove equation name but leave page number
> ux equation style change

- packages/client/hmi-client/src/components/project/tera-resource-sidebar.vue
- packages/client/hmi-client/src/types/Project.ts
This pull request includes changes to the `tera-resource-sidebar.vue` component and the `Project.ts` types to improve the user interface and update asset type handling. The most important changes include simplifying the header template, updating the asset type filtering, and refining the drag-and-drop functionality.
Improvements to user interface:
* [`packages/client/hmi-client/src/components/project/tera-resource-sidebar.vue`](diffhunk://#diff-1125f9c09f1cc74700a2612655a5f2f52aa0fd8a2507aa2ff7a5ad4c087d9033L52-L70): Simplified the header template by removing conditional templates and using a single template with `capitalize(type)` for displaying asset types.
* [`packages/client/hmi-client/src/components/project/tera-resource-sidebar.vue`](diffhunk://#diff-1125f9c09f1cc74700a2612655a5f2f52 …
> Remove code files from resources panel

- packages/client/hmi-client/src/components/workflow/ops/model-comparison/model-comparison-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/model-comparison/tera-model-comparison.vue
Design Change:
- When a user compares multiple models generating a graph. There were no titles added to the image generated.
Code Changes:
- added a KernelManager message to to request the title pair(s) of the compared models 
> Add titles to generated compare models graphs

- packages/client/hmi-client/src/components/documents/tera-document-asset.vue
- packages/client/hmi-client/src/page/tera-project.vue
This pull request includes significant changes to the `tera-document-asset.vue` and `tera-project.vue` components, primarily focusing on code cleanup, refactoring, and simplification. The most important changes include the removal of unused imports and event subscriptions, simplification of the `tera-project.vue` component, and minor style adjustments.
Code cleanup and refactoring:
* [`tera-document-asset.vue`](diffhunk://#diff-fd38dbc513e3960e3813b4ce85cee8a5ebc51fa7e7f6b9f8c3472eb2b24d0a21L4-L7): Removed unused imports, event subscriptions, and methods related to document extraction status updates. Simplified the `watch` function to avoid unnecessary re-fetching of document assets. [[1]](diffhunk://#diff-fd38dbc513e3960e3813b4ce85cee8a5ebc51fa7e7f6b9f8c3472eb2b24d0a21L4-L7) …
> More cleaning up!

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
* Update right side panel in calibrate to match the current designs
Resolves #5026
> 5026 feat cleanup calibrate settings panel

- packages/client/hmi-client/src/components/model-template/tera-model-template.vue
- packages/client/hmi-client/src/components/model/petrinet/tera-model-description.vue
- packages/client/hmi-client/src/components/model/petrinet/tera-model-diagram.vue
- packages/client/hmi-client/src/components/model/tera-model-parts.vue
- packages/client/hmi-client/src/components/operator/tera-operator-model-preview.vue
- packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-output.vue
- packages/client/hmi-client/src/components/workflow/ops/model-comparison/tera-model-comparison.vue
- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/model/tera-model-node.vue
- packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratify-node.vue
- packages/client/hmi-client/src/services/model.ts
- packages/client/hmi-client/src/temp/AMRPetriTest.vue
- packages/client/hmi-client/src/temp/Clipboard.vue
- packages/client/hmi-client/src/utils/observer.ts
* Fix how the model diagram was not rendering on resizing on hiding the element. So now we have a ResizeObserver that will re-render the graph has needed.
* This PR also some cleaning explained below, [for the ResizeObserver just look at the last commit](https://github.com/DARPA-ASKEM/terarium/pull/5146/commits/ab001b488ab35649c06273c63eaff02d28f2a620).
https://github.com/user-attachments/assets/a477d7f0-a56e-46d5-8f62-8a034ae703e8
* `tera-model-description.vue`: Removed unused `teraModelDiagramRef`. 
* `tera-model-diagram.vue`: Renamed from `model-diagrams/tera-model-diagram.vue` and added new imports.
* Updated import paths for `TeraModelDiagram` in various other components:
- `tera-operator-model-preview.vue`
- `tera-funman-output.vue`
- `tera-model-comparison.vue`
- …
> 5139 diagram does not show up automatically when on create output

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/utils/rebac/askem/RebacUser.java
This pull request includes a change to the `getPermissionFor` method in the `RebacUser` class to simplify the permission checking logic.
Codebase simplification:
* [`packages/server/src/main/java/software/uncharted/terarium/hmiserver/utils/rebac/askem/RebacUser.java`](diffhunk://#diff-3365cf1dba4e234022f64a5ab0f140ae916d2d44654d961603c51873b07ed1a1L77-R84): Refactored the `getPermissionFor` method to streamline the permission checks by consolidating the admin-related conditions into a single check.
> only make a project admin if necessary

- packages/client/hmi-client/src/model-representation/mira/mira.ts
This address an incorrect assumption we made earlier that a transition's signature/key can be calculated from its input and output component, for the purpose of calculating transition groups. This is not the case, e.g we can have this scenario:
```
transition1_xx: [ input: [a], output: [b] }
transition2_yy: [ input: [a], output: [b] }
```
Where we would want to keep these transitions as different groups. To do this we add the base transition name as part of the key.
The model 
[pascale-strata-problem-templates.json](https://github.com/user-attachments/files/17383266/pascale-strata-problem-templates.json), when loaded into Terarium should look like
Instead of:
Note the correct version should have 4 transition matrices instead of 3.
> additional heuristic for template parsing handling multiple outputs

- packages/client/hmi-client/src/model-representation/mira/mira-util.ts
This is an addendum to https://github.com/DARPA-ASKEM/terarium/pull/5157, addressing the model-diagram not rendering the correct matrix configurations. When controller is present we should use a subject-controller configuration instead of a suject-outcome configuration.
Load this given model 
[pascale-strata-problem-templates.json](https://github.com/user-attachments/files/17398164/pascale-strata-problem-templates.json) the model diagram should have 2 diagonal matrices and 2 full 3x3 matrices. Originally they were all diagonal matrices.
Note: there are known sympy parsing issues with this particular model. It will be dealt with separately as this touches our pyodide utilities and is out of scope w.r.t this PR.
> extend MMT template-matrix to have subject-controller/subject-outcome configurations

- packages/client/hmi-client/src/components/model/petrinet/tera-model-diagram.vue
It looks like with the resize-observer getting kicked off right away, it is possible to render a graph without the correct dependencies and this eventually result in JS errors that partially break the UI. This is a quick-and-dirty fix to add a sanity check to exit the rendering function if things are not in place.
Adding a model onto the cavas should not result in any vue-warnings or js-errors
> prevent rendering if data dependencies are not ready

- packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratify-drilldown.vue
- packages/client/hmi-client/src/services/model.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/model/Model.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/modelparts/ModelMetadata.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/utils/JsonUtil.java
> Apply metadata from the pre-MIRA model to the post-MIRA model if the name of variables matches

- packages/client/hmi-client/src/components/model/model-parts/tera-model-part-entry.vue
* removed grid and used flex in model entry form
Resolves #4574
> Layout of model entry form is broken when latex expressions are too long

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
* Hides loss chart along with the others while calibration is running
Resolves #5055
> fix flickering loss chart during calibration

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
- packages/client/hmi-client/src/services/concept.ts
- Allow the user to hit a "reset" button to change the state back to it was for its latest output result.
- Calibrate Automap will now return length one with nothing filled in rather than length 0 (screenshot below)
> Reset state feature for calibrate

- packages/server/docker/Dockerfile
This pull request includes a change to the `Dockerfile` in the `packages/server/docker` directory, focusing on memory allocation for the Java process during the extraction phase.
Memory allocation update:
* [`packages/server/docker/Dockerfile`](diffhunk://#diff-93508b50dc34e3e2d39091055329099500547273845aa012ace7e65ca07af069L13-R13): Updated the `RUN` command to allocate initial and maximum memory (`-Xms1024m -Xmx4096m`) for the Java process to improve performance during the extraction of the JAR file.
> Expand hmi-server heap space

- packages/client/hmi-client/src/main.ts
This hack is not necessary anymore, two years later, vite and vue caught up.
> Remove hack to have CSS custom properties

- packages/funman/tasks/validate_modelconfig.py
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/SimulationController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/ValidateModelConfigHandler.java
Tidy up Funman task runner to be more complete, and update the python task as it seemed like the interface we are hitting against had changed a little bit.
- Add a onFailure to mark the funman-simulation as failed
- Fix python update datetime error in validation task's update hook, there is a date comparison that needs start_time to be initialized
@shawnyama The progression may not be "smooth" but you should have some progress number coming back after this PR, you just need to hook it up, it is part of the simulation object being polled. `simulation.progress` field. 
Run funman process to validate a model-configuration. Note you may need to exec into the funman-taskrunner container and do:
```
cd /funman_task/
pip install  -e .
```
To refresh the installed tasks.
If funman runs …
> funman: add onFailure hook, fix update-hook python error

- packages/client/hmi-client/src/services/calibrate-workflow.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/DatasetService.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/SimulationService.java
This will allow the user to plug in a simulation node to a calirbation node without it getting permanently stuck on `Please wait...` for the mapping section.
Previously when we created dataset assets from the simulation results we were not filling in the column metadata field.
This means that our columns field was empty and when we went to get datasetOptions from this we would instead return empty causing our dataset dropdown to never have options for the user to select
> Calibrate handle simulation results

- packages/client/hmi-client/src/components/widgets/VegaChart.vue
* Removes large number of errors in console. 
* Associated performance increase makes the bug impossible to reproduce.
Resolves #5182
> 5182 bug-multi-add-for-chart-specification-unselects-the-checks-variables

- packages/client/hmi-client/src/components/model/petrinet/tera-model-diagram.vue
This is an attempt to resolve the insertBefore Vue warnings/errors that can partially break the application in unexpected ways. It seem like the primary culprit is us adding/removing DOM elements that are not inline with how Vue is working. In this PR we perform a couple of clean ups:
- Move the spinner out of the container element for graph-renderer, since graph-renderer will take full control of the element and will not respect Vue components.
- Cleaner way to manage slots
```
chunk-L65O5BSU.js?v=0e6c8aa7:10445 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertBefore')
at insert (chunk-L65O5BSU.js?v=0e6c8aa7:10445:12)
at processCommentNode (chunk-L65O5BSU.js?v=0e6c8aa7:6789:7)
at patch (chunk-L65O5BSU.js?v=0e6c8aa7:6692:9)
at patchBlockChildren …
```
> attempt to resolve vue-warnings/errors in tera-model-diagram

- packages/client/hmi-client/src/components/widgets/tera-input-number.vue
- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-card.vue
- testing/manual/intervention-policy.md
* Expands the element validation to some negative timesteps as invalid
* Also fixes some formatting in the test description
> show negative timesteps as invalid in the intervention policy drilldown

- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-criterion-group-form.vue
If you have any styling suggestions such as
If you think all of the invalid inputs should be red bordered as in the screenshot below let me know!
https://github.com/user-attachments/assets/8182c9ab-faa0-4b8e-bfcb-34f56481b908
> Optimize user guardrails

- packages/client/hmi-client/src/components/workflow/ops/dataset/tera-dataset-node.vue
There is no limit on the preview in the dataset node.
This leads to HILARIOUS previews that make the node hard to work with and insane.
https://github.com/user-attachments/assets/556ba80c-52a7-4668-bbe3-68e8fcfb7e7d
> [Small]: Limit preview on dataset node

- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/optimize-ciemss-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue
- packages/client/hmi-client/src/services/intervention-policy.ts
As the hmiserver can fail to create an intervention it is important that our client's service can as well.
This update is propagated to optimize as well where technically the result can be failed to create
This will now better handle this fail case
> Intervention service minor update

- packages/client/hmi-client/src/services/concept.ts
Allow for the following to successfully automap (note no concepts were used in this automapping)
> Automap string comparison should not care for casing

- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
* Model config select in the sidebar wasn't working
* Remove guard expecting a document
> fix(model-config-operator): rm guard preventing config select

- packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-drilldown.vue
- packages/client/hmi-client/src/services/charts.ts
- timepoints are rounded to third decimal place instead of rounded down to 0
- limit y axis on graph to not go so far that it goes to NaN
https://github.com/user-attachments/assets/15bfa00e-c3dc-4574-9965-38c7b2f9c34e
> fix(funman): limit y range and round timepoints to third decimal place in preview

- packages/client/hmi-client/src/components/intervention-policy/tera-intervention-summary-card.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
Issue: 
The unit value for states when the user switches to the a dynamic intervention was missing.
Testing:
- Add a Model
- create a model config
- create a intervention policy with dynamic intervention using state
- connect to simulate
> Simulate - add state units to dynamic intervention

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
Just sort the data points with respect to progression manually, as they are still coming back in seemingly random order
Instead of
We should have
> manually sort loss data points

- packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-drilldown.vue
* Old funman outputs that were saved don't have a model config id which causes an undefined config to be fetched
* This just check that the id is in the output before we fetch
> fix(funman): make sure model config id exists in funman output

- packages/client/hmi-client/src/components/llm/tera-beaker-code-cell-output.vue
https://github.com/user-attachments/assets/1ca90e53-10f9-40bc-8349-59b6664099ba
Issues: Images in the Dataset Transformation node could be dragged, and would create a new node.
Testing: 
- https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/transform-dataset.md
- Create a new dataset transformation and show a graph image on the node
- Try dragging image
> bug: stop image from being dragged off of node

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ProjectController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/permissions/GroupsController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ProjectPermissionsService.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/utils/rebac/ReBACService.java
Should deal with bad user ids accidentially inserted into SpiceDB
On Staging one cannot view the users in the Public group (in the admin panel)
> Erronious user in spicedb

- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/simulationservice/OptimizeRequestCiemss.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/simulationservice/parts/OptimizeInterventions.java
1) It is hard to follow what is going on as we are throwing all optimize interventions into one big blob.
2) Our optimize intervention type (find new start time, param value ect) was being incorrectly assigned when multiple types were given all but the first were ignored.
- Re-organize how we are sending in the interventions to be optimized.
- Rather than sending one big messy blob send a list of `InterventionObjective`
- Utilize `intervention_func_combinator` to allow us to intervene on two interventions with different types.
- Previously if we sent the screenshot below both of the interventions were incorrectly using `new start time`
https://github.com/DARPA-ASKEM/pyciemss-service/pull/124
Previously these two inputs settings were incorrectly not treated identically.
> Update Optimize API optimize_interventions to list

- packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-drilldown.vue
- packages/client/hmi-client/src/services/code.ts
- packages/client/hmi-client/src/services/models/funman-service.ts
* Having the `props.node.state.runId` in a watcher array and doing the `update-state` emit within that watcher was infinitely triggering it
* Not having it in an array works fine so I adjusted the logic for it to work
* Also the json is formatted nicely in the notebook tab now 
* Removed an unused watcher and some variables
> fix(funman): no more watcher loop, format json in notebook

- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
* Better UI and reduced some backend calls for the model configuration drilldown to improve the user experience
> model config performance improvements

- packages/client/hmi-client/src/components/model/tera-model.vue
- packages/client/hmi-client/src/components/project/tera-save-asset-modal.vue
- packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
* Addressed the attached ticket where we wanted to split the update and save functions from the `tera-save-asset-modal` component.  I've kept the same functionality for all the components that use this component, but we can use different functions for either save or update if we want in the future
> split save and update functions

- packages/client/hmi-client/src/components/llm/tera-jupyter-chat.vue
* The `+ Add a cell` button towards the top of the Transform Dataset drill down works as expected again
> 5350 [part 1] fixes the add a cell button

- packages/client/hmi-client/src/model-representation/petrinet/nested-petrinet-renderer.ts
We precomputed circle pack up to 75 groups, so if we go higher the renderer will fail. 
This PR adds a cap condition check and exits if we exceed the threshold, here is diagram showing 190+ groups.
Note: While we can go higher in terms of the precompute it will increase the size of the application/payload non-linearly.
> prevent nested groups from going over prestashed circle pack limits

- packages/client/hmi-client/src/components/workflow/ops/dataset-transformer/tera-dataset-transformer.vue
- packages/client/hmi-client/src/services/workflow.ts
* Fixes the permanent invalid state of the node to allow saving
* Preserves the ability to disable saving when actually invalid
> 5350 [part 2] fixes permanently disabled "save for reuse" button

- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/simulate-ensemble-ciemss-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/simulate-ensemble-util.ts
- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss-drilldown.vue
- Update our mapping to new type to clean -> The same will be done with ensemble calibrate shortly.
- Add weights as its own object -> The same will be done with ensemble calibrate shortly.
- Utilize Cole's new type -> pyciemss-service payload converter
- adding knobs for cleaner reading
You should be able to run an ensemble simulate as before, there should be no functional differences
> Ensemble simulate prep

- packages/client/hmi-client/src/assets/css/theme/_variables.scss
- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
- packages/client/hmi-client/src/utils/text.ts
- User will know if they will lose changes to name and description now. Also I decided to make the wording more concise and clear
- As a side cleanup I changed `originalModelConfig` to a regular variable instead of a `ref`
https://github.com/user-attachments/assets/ba14ca6c-f4b0-4c29-afe1-422f6f4647a0
> clearer unsaved changes message in model config

- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/simulate-ensemble-ciemss-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-node-ciemss.vue
- Adding sliders for input and output panels
- Updating weights UI 
- Updating Mapping UI
- Update Other Settings UI (formatting/presets/ect)
- minor corrections
- update pyciemss and EnsembleSimulationCiemssRequest to not take a timespan but just an endTime.
- update output panel
- update charts
- update `SimulateEnsembleMappingRow` type so that `modelConfigurationMappings` is a `map` not a `list`
> Simulate Ensemble UI Updates

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
* Calibrate will not show old errors when loading or running new calibrations
> Calibrate does not show old errors

- packages/client/hmi-client/src/services/concept.ts
Fixing the automap.
note that currently models are set up to use the `DKG` class(es) while dataset is set up to use `Identifier` which are basically the same thing. Going to look into cleaning this up soon
Resolves #5381
> auto config mapping #5381

- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/simulate-ensemble-ciemss-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/simulate-ensemble-util.ts
- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss-drilldown.vue
- Ensemble simulate now has the same mapping type as the calibration does.
- Now requires unique inputs
- provide a type for `modelConfigIdToNameMap`
- correct state updater via knobs as `watcher` should be `deep` not `immediate`
> Ensemble Simulate - same typing as ensemble calibrate

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-node-ciemss.vue
- We had calibration chart `!lossChartRef.value?.view` as well as `v-if="!_.isEmpty(lossValues)"` 
so we wont fill the data unless we have the reference assigned, but we wont assign the reference unless we have data
- Take loss chart outside of inner result template in the node.
- [Minor]: Do not await a const when using `updateLossChartSpec`
> Calibration loss chart missing

- packages/client/hmi-client/src/assets/css/style.scss
- packages/client/hmi-client/src/components/drilldown/tera-drilldown-header.vue
- packages/client/hmi-client/src/components/operator/tera-operator-annotation.vue
- packages/client/hmi-client/src/components/operator/tera-operator-output-summary.vue
- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-node.vue
- packages/client/hmi-client/src/components/workflow/tera-workflow.vue
Minor style updates, mostly relating to font sizes and padding.
Before:
After:
---------------------------------------------
Before:
After:
---------------------------------------------
Before:
After:
---------------------------------------------
Before:
After:
---------------------------------------------
Before:
After:
---------------------------------------------
Before:
I didn't take a screenshot... font size was 14px. 
After: 
It's now caption.
> Jamie style updates nov 13

- packages/client/hmi-client/src/components/widgets/tera-input-number.vue
- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue
Previously the workflow for creating a new intervention is that we would POST a blank intervention and any updates would then allow the user to update this newly created intervention.
This is not a valid workflow as the blank intervention is not a valid intervention (It has no timestep and no value) thus it fails HMIServer's validation.
The new workflow is that we will reset the interface on the frontend and wait for the user to hit `Save` or `Save as...` before trying to POST this intervention 
https://github.com/user-attachments/assets/b273d284-f482-4bca-8e6c-d3749facb795
> New intervention not working

- packages/client/hmi-client/src/components/widgets/tera-pdf-panel.vue
- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
https://github.com/user-attachments/assets/1ab6315e-b41e-4747-ba25-808428983cdc
Issue: 
- If there are multiple pdfs when the user selects a model config, the pdf viewer will always stay on the current selected pdf
Testing:
- Add a document & model to a workflow
- create a model config and extract the inputs
-  selecting a different config from different doc to open the correct doc
> Switch between pdfs

- packages/client/hmi-client/src/components/workflow/ops/dataset-transformer/tera-dataset-transformer.vue
The operator status can be a bit finicky and is not 100% relevant to this functionality
Rather than relying on this status lets allow the user to save for reuse so long as theyre connected and have a selected dataset.
> Data Transformer - Update when user can save

- packages/client/hmi-client/src/components/asset/tera-asset.vue
- packages/client/hmi-client/src/components/model/petrinet/tera-model-description.vue
- packages/client/hmi-client/src/components/model/petrinet/tera-model-diagram.vue
A temporary scrollbar spawns while opening/closing the transition accordion causing the model diagram to rerender due to its resize observer. This causes the transition accordion to lag. In order to minimize rerenders I:
* Added a debounce to the model diagram's resize observer
* Removed the uneeded y scrollbar that sometimes gets added to a section in `tera-asset`
> fix transition accordion lag

- packages/client/hmi-client/src/components/widgets/tera-signal-bars.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/calibrate-ensemble-util.ts
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/simulate-ensemble-util.ts
- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss-drilldown.vue
- Ensemble weighting are `dirichlet_alpha` and should not be normalized.
- They also should not have the option for 0.
In order to accommodate this I have updated `tera-signal-bars` to allow for a min and max number for more flexibility
> Ensemble weights to not be normalized

- packages/client/hmi-client/src/services/workflow.ts
- packages/client/hmi-client/src/types/workflow.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/workflow/WorkflowEdge.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/workflow/WorkflowNode.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/WorkflowService.java
Fix a potential problem where a delete node/edge may get undeleted.
Remove outdated version shim
Add createdBy auditing to better track when nodes/edges are created to better debug synchronization issues
> workflow clean up

- packages/mira/tasks/amr_to_mmt.py
A workaround for amr-to-mmt task failing because unit-expressions are blank
You need to  run/rebuild mira-taskrunner locally
Goto http://localhost:8080/amr-petri-test and paste in the amr bellow, there should be no errors and the model-diagram should render.
[bad-amr-to-mmt.json](https://github.com/user-attachments/files/17830889/bad-amr-to-mmt.json)
> empty mathML workaround

- packages/client/hmi-client/src/components/workflow/ops/funman/tera-constraint-group-form.vue
- packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-drilldown.vue
- packages/client/hmi-client/src/services/models/funman-service.ts
- packages/client/hmi-client/src/utils/number.ts
- packages/client/hmi-client/tests/unit/services/funman-constraint-expression.spec.ts
Issue: 
- The list of parameters & initial states were not following the layout and just printing in a single line.
- Same would happen to the dropdown when selecting multiple options
Testing:
- Create a model-config with a large amount of parameters
- Create a new Validate configuration
- They should list the items and stay within the layout
> Validate config katex layout

- packages/client/hmi-client/src/assets/css/style.scss
- packages/client/hmi-client/src/assets/css/theme/_variables.scss
- packages/client/hmi-client/src/components/dataset/tera-column-info.vue
- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
- packages/client/hmi-client/src/components/drilldown/tera-drilldown-header.vue
- packages/client/hmi-client/src/components/drilldown/tera-notebook-error.vue
- packages/client/hmi-client/src/components/navbar/tera-navbar.vue
- packages/client/hmi-client/src/components/widgets/tera-input-number.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/funman/tera-constraint-group-form.vue
- packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
- packages/client/hmi-client/src/page/Home.vue
More style tweaks a visual bugs fixed
BEFORE
AFTER
---------------------------------
BEFORE
AFTER
---------------------------------
BEFORE
AFTER
---------------------------------
** I worked with Michael Crouch on this
BEFORE
AFTER
---------------------------------
BEFORE
AFTER
---------------------------------
BEFORE
AFTER
---------------------------------
BEFORE
AFTER
---------------------------------
BEFORE
AFTER
---------------------------------
BEFORE
AFTER
---------------------------------
BEFORE
AFTER
> Jamie style tweaks nov 18

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
Issue: When a user updates the dropdown value we are not actually saving the state's mapping. We have a watcher on knobs but this does not cover it.
Video of issue:
https://github.com/user-attachments/assets/4376143d-c427-479a-a375-44cce4685b99
> Calibration Map save on change

- packages/client/hmi-client/src/api/api.ts
The issue looks like `activeProjectId` might return an empty string which does not trigger the `||` OR condition when loading the page on an hard refresh.
I added an `isEmtpty` test to make sure we do not have an empty string.
> Hard refresh brings back the first project on a users list.

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
We only save mapping on model mapping update as I missed this line here
This means if we update the dataset and close it will not save
If we update dataset then model then close it will save
Uploading Screen Recording 2024-11-21 at 12.03.37 PM.mov…
> Previous change missed the dataset dropdown.

- packages/client/hmi-client/src/services/charts.ts
* Starts the labels at the same vertical position and truncates as requested
Resolves #5487
> [BUG]: Intervention charts look like crap #5487

- packages/client/hmi-client/src/components/dataset/tera-dataset-datatable.vue
* Must create components for all columns always, then flag them as hidden when not selected. Otherwise it just changes the column header for the different columns and keeps the data unchanged
Resolves #5529
> Hiding a column in a dataset removes the header, but leaves the data values

- testing/manual/scenario-templates.md
* new tests for scenario templates
> scenario templates tests

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/calibrate-ensemble-ciemss-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-node-ciemss.vue
- Add error messages to ensemble calibrate if we run into a failure.
- Update cancelId to include all sim ids
- if we stop the poller we do not need to also check for errors. This should be `else if` not `if`
> Ensemble Calibrate fix up stop button

- packages/client/hmi-client/src/components/llm/tera-jupyter-chat.vue
* Persist llm query after editing the prompt in the dataset transformer
> persist llm query after edit

- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/simulate-ensemble-util.ts
- packages/client/hmi-client/src/services/models/simulation-service.ts
This will help us map ensemble output to our model configurations provided
The issue this is solving is that the output for ensemble is `model_0/S` and we have no reference to what model 0 is, this will provide a map from model_0 -> the model configurations uuid
If you believe this should be written somewhere else please let me know
> Ensemble map from model_# to uuid

- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/DatasetService.java
* Column info used to be generated every time a dataset was added
* Now if it is already set we don't readd it
> column info isn't duplicated when dataset is transferred to another project

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/simulationservice/SimulationRequestController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/TerariumAssetServices.java
Project-export is broken, partially because simulations are not extracted into the archive. Moreover they are not a part of project-asset that the exporter iterates over.
This PR adds project-asset entries and does a bit of cleanup of redundant setters
- Create project
- Create workflow with model => model-config => simulate, run a simulate, plot some variables
- Export the project into an archive
- Check archive contains the simulation result files (eg result.csv result-summary.csv ... etc), it is just a zip stream, so use whatever extractor is in macos or `unzip -l <archive>` in CLI
- Rename the project
- Import the project, wait 5-10 seconds
- Go into the imported project, verify that workflow is there, we can fetch simulation results and the charts are visible
> exporting project: add simulation to project-assets, cleanup

- packages/client/hmi-client/src/components/dataset/tera-dataset-jupyter-panel.vue
- packages/client/hmi-client/src/types/common.ts
In data transform, disable langugage = Julia since it was removed from beraker
Closes https://github.com/DARPA-ASKEM/terarium/issues/5614
> disable option for languanage dropdown

- packages/client/hmi-client/src/components/dataset/tera-dataset-jupyter-panel.vue
- packages/client/hmi-client/src/components/llm/tera-beaker-code-cell.vue
- packages/client/hmi-client/src/components/llm/tera-jupyter-chat.vue
- packages/client/hmi-client/src/components/llm/tera-jupyter-response.vue
- moved the warning message from the tera-beaker-chat to tera-dataset-jupyter-panel
New
Show rerun cells header when:
- each time the dataset transformer is opened (everytime it is opened a new session starts)
- pressing the reset kernel button
Close when:
- explicitly pressing the close button on the header
- pressing the re-run cells button
> dataset transformer rerun header fix

- packages/client/hmi-client/src/components/model/petrinet/tera-initial-entry.vue
- packages/client/hmi-client/src/components/widgets/tera-input-text.vue
- packages/client/hmi-client/src/services/model-configurations.ts
* It looks like initials were forced to be evaluated as numbers, I've lifted that restriction in this PR
* Initials will only be "empty" when there is no value
* initial now updated on blur, which should reduce some api calls
> fix model config initial error state

- packages/client/hmi-client/src/components/workflow/tera-workflow.vue
Remove regrid and subset-dataset operators from workflow. This remove the registration only, the actual operators are still in-place and will be removed at a later date after next hackathon/eval.
Closes https://github.com/DARPA-ASKEM/terarium/issues/5575
> remove data-grid and subset-dataset from workflow

- packages/client/hmi-client/src/components/widgets/VegaChart.vue
- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-node.vue
- Switch to PNG instead of interactive graph for intervention policy. 
- Make PNG non-interactive to prevent weird dragging effect onto canvas
- Made vegalite watcher immedate, there seem to be cases where it doesn't trigger if we slightly tweak the props because of timing or race issues.
> Render png for intervention-policy nodes

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-node-ciemss.vue
- When we have an error message in our state we should show it as we are doing in other nodes
- Reset error message when we start polling aka new run
> Add error message to ensemble calibrate drilldown

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
- New default from 5 -> 1 
- Need 2+ model configurations to enable run button. We will want to update the run button message similar to Optimize if we keep adding logic to it that may not be apparent to the user
> Ensemble calibrate new default "weight"

- packages/client/hmi-client/src/components/model/petrinet/tera-parameter-entry.vue
- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
Issue: in model config inferred parameter appear as an empty input
Testing:
- Use the manual test for model calibration
> fix for missing count on inferred type

- packages/client/hmi-client/src/components/model/petrinet/tera-petrinet-parts.vue
> observables appear now in model page

- packages/client/hmi-client/src/services/graph.ts
The ortho edge routing's global bound was misconfigured, also added a manual edge-points if algorithm fails.
Before: 
Note D and E ends in transition which is incorrect
After:
Now D and E routes back onto themselves (this is location change within the same state)
Use the following, paste the content into http://localhost:8080/amr-petri-test or upload it as a model and view the diagram
[pp-bad-amr-render.json](https://github.com/user-attachments/files/18004396/pp-bad-amr-render.json)
> fix model-diagram layout option global bounds

- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ProjectController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/TerariumAssetEmbeddingType.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/document/DocumentAsset.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/model/Model.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/project/Project.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ProjectSearchService.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/TerariumAssetServices.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/elasticsearch/ElasticsearchService.java
Enhancements to project search functionality:
* [`Types.ts`](diffhunk://#diff-401d2f2b7e10e894067dc566f3a3c955c6bb70a62a7872a4ab2f416831169a9eR12-R25): Added `ProjectSearchResult` and `ProjectSearchResultAsset` interfaces to represent search results, and `TerariumAssetEmbeddingType` enum to categorize asset embeddings.
* [`ProjectController.java`](diffhunk://#diff-86712ae74e79cfa17607573213ad7f0dd36863a3ef9eac66ef20cdb0c4fecfe7R1020-R1045): Introduced `ProjectSearchResult` and `ProjectSearchResultAsset` classes to encapsulate project search results and their assets. Updated the `projectKnnSearch` method to return a list of `ProjectSearchResult` instead of `ProjectSearchResponse`. 
Refactoring and code improvements:
* [`TerariumAssetEmbeddingType.java`](diffhunk://#diff-f44980fa91f01bc1ebe2 …
> Update project search

- packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue
Bug: 
- in the model from equation drill down
- newline characters back to back are being saved as an equation 
Testing:
1. Paste in this list of equations
```
\frac{d S}{d t} = - \beta_w I_w S - \beta_a I_a S - \beta_d I_d S + \mu N - \mu S + \eta_R R_F + \eta_R R_w + \eta_R R_a + \eta_R R_d
\frac{d V_1}{d t} = \omega_1 S - \mu V_1
\frac{d I_w}{d t} = \beta_w I_w S - \gamma_w I_w - \mu_w I_w
\frac{d I_a}{d t} = \beta_a I_a S - \gamma_a I_a - \mu_a I_a
\frac{d I_d}{d t} = \beta_d I_d S - \gamma_d I_d - \mu_a I_a
\frac{d R_w}{d t} = \gamma_w I_w - R_w \beta_{Ra} I_a - R_w \beta_{Rd} I_d - \eta_R R_w - \mu R_w 
\frac{d R_a}{d t} = \gamma_a I_a - R_a \beta_{Rw} I_w - R_a \beta_{Rd} I_d - \eta_R R_a - \mu R_a 
\frac{d R_d}{d t} = \gamma_d I_d - R_d \beta_{Rw} I_w - R_d \beta_{Ra} I_a - \eta_R …
```
> remove blank equation

- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/intervention-policy-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-node.vue
Design Change:
- enable the add the summary cards for the interventions
- enable user to choose which charts to show on the intervention node
- 
Testing:
- Create a few new interventions
- select the charts you wish to see on the node
- all interventions should appear as summary with the selected charts
> Intervention node - show summary card and selectable node chart

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/simulationservice/SimulationRequestController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/notification/SimulationRequestStatusNotifier.java
There is a mismatch where the client-event subscription is by userId, but the simulation notification is setting userId to null
It is not quite clear how the notification system is meant to work, but this will allow simulate event to go through and not spin forever.
Run a simulation, it should finish in a timely order and not spin forever.
> link simulate with simulate notification event through user id

- packages/client/hmi-client/src/services/graph.ts
Do not reroute large graphs with lots of edges
> don't reroute large graphs

- packages/client/hmi-client/src/components/workflow/scenario-templates/sensitivity-analysis/sensitivity-analysis-scenario.ts
* Since we have the sensitivity analysis charts in the simulate node, the dataset transformer is no longer needed in the template creation
> remove dataset transformer from sensitivity analysis scenario

- packages/client/hmi-client/src/components/home/tera-project-table.vue
- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ProjectController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/model/Model.java
On search results we want to always display the description of an asset.
> Display shortDescription

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/NotebookSessionController.java
* When duplicating a data transform the notebook clone call would not actually create a new notebook session but just send back a clone of the session, nothing was done with this.  Now we are creating the new notebook session and sending it back
> create notebook session when cloning

- packages/client/hmi-client/src/model-representation/mira/mira.ts
Closes: https://github.com/DARPA-ASKEM/terarium/issues/5785
Our parsing assumes assumes number-of-inputs = number-of-outputs and slots controller parsing in one of them, this is not true and controllers should be parsed independently, in order for controlled-group production/degradation to happen.
Test model from nelson 
[non_mass_conserved.json](https://github.com/user-attachments/files/18080793/non_mass_conserved.json)
> parse controller independently of subject/outcome

- packages/gollm/gollm_openai/prompts/latex_style_guide.py
* Only changed one rule in the style guide
* Use "*" instead of whitespace to denote multiplication (i.e. `a x + b` -> `a * x + b`)
* Necessary to avoid SymPy `parse_latex` edge cases like `a b (1 - g) I(t)` being interpreted as `a * b(t = 1 - g) * I(t)`  (where `b` is a function) instead of `a * b * (1 - g) * I(t)`
Resolves #5811
> Update LaTeX equation style guide to use "*" for multiplication

- packages/client/hmi-client/src/router/index.ts
- packages/client/hmi-client/src/temp/Equations.vue
- packages/mira/tasks/latex_to_amr.py
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
This PR does two things
- Change the mira taskrunner task to return both the AMR and the string-sympy equations. Also change the format from string to JSON.
- Add in an engineering/debugging interface at `/equations` for debugging/tracing equation-to-amr issues
Test that knowledge controller `/equations-to-model` is still working, as it had to accommodate both structural and format change from the task runner. You can try this payload:
```
{
"equations": [
"\\frac{d S(t)}{d t} = - b_q S(t) I(t)",
"\\frac{d E(t)}{d t} = b_q S(t) I(t) - r_X E(t)",
"\\frac{d I(t)}{d t} = r_X E(t) - g_p_q I(t)",
"\\frac{d R(t)}{d t} = g_p_q I(t)"
]
}
```
> Equations engineering UI

- packages/client/hmi-client/src/model-representation/petrinet/petrinet-renderer.ts
- packages/client/hmi-client/src/services/graph.ts
- packages/client/hmi-client/src/utils/svg.ts
Making tweaks to model-diagram rendering
- Do not consider controller edges in initial layout pass, this is an attempt to "preserve" a coherent layout structure in a layered layout
- Make arrow heads larger
- More precise edge/arrow rendering to minimize overlap and translucent artifacts
Before:
After:
View a few models, they should, subjectively speaking, have a more "left-to-right" flow
> discount controllers in model-diagram layout pass

- packages/client/hmi-client/src/components/workflow/scenario-templates/horizon-scanning/horizon-scanning-scenario.ts
- packages/client/hmi-client/src/components/workflow/scenario-templates/horizon-scanning/tera-horizon-scanning-template.vue
- packages/client/hmi-client/src/components/workflow/scenario-templates/scenario-template-utils.ts
- packages/client/hmi-client/src/components/workflow/scenario-templates/sensitivity-analysis/sensitivity-analysis-scenario.ts
- packages/client/hmi-client/src/components/workflow/scenario-templates/sensitivity-analysis/tera-sensitivity-analysis-template.vue
- packages/client/hmi-client/src/components/workflow/scenario-templates/value-of-information/tera-value-of-information-template.vue
- packages/client/hmi-client/src/components/workflow/scenario-templates/value-of-information/value-of-information-scenario.ts
- packages/client/hmi-client/src/components/workflow/tera-create-workflow-modal.vue
- packages/client/hmi-client/src/utils/math.ts
* New value of information scenario template
* A user can select x number of interventions and y number of parameters with a low and high value.
* For each parameter a new model config with be created with that value as a uniform distribution. For example selecting beta and gamma with min and max value will create 2 new model configurations
* These new configurations will each be attached to a simulate node with each intervention node.
* some minor improvements to reduce repeated code between templates
> value of information scenario template

- packages/client/hmi-client/src/components/workflow/ops/model-comparison/model-comparison-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/model-comparison/tera-model-comparison.vue
* Move the rendering of the comparison cached version first onMounted as it is higher priority.
* Bust cache by adding a UUID to the goal query if the user wants a different comparison analysis.
* Keep cache version if the user hasn't requested a new analysis.
> Improve re running compare model

- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-configuration-item.vue
Issue:
- When opening the context menu for the different configurations one after the other. The previously opened  context menu will stay open.
Testing:
- open more then one context menu
- previously opened context menu should close 
> Bug: Model Config Context Menu

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
We are manually sorting the progress coming and then taking the first each time.
Resulting in the first progress % being the only % we see the entire run:
> Fix: Calibrate always showing 1%

- packages/client/hmi-client/src/components/widgets/tera-chart-settings-panel.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
- packages/client/hmi-client/src/composables/useChartSettings.ts
- packages/client/hmi-client/src/services/chart-settings.ts
Some refactoring related to usChartSettings and active chart settings panel
- Expose `activeChartSettings` as computed property instead of ref to prevent direct modification from components
- `setActiveChartSettings` method to set or unset active chart settings
- `findAndUpdateChartSettingsById` method to find and update chart settings with partial payload instead of having own update method for each chart setting property. 
- Make sure `activeChartSettings` is reactive and updated properly when `chartSettings` update.
- Added default primary color to the new settings
> Refactor and improve active chart settings panel and useChartSettings composable 

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
When we run we should ensure that the loss chart is open
Not only is it weird to have it stay closed as then we have nothing to look at, but it has also caused confusion to user
> Open calibrate loss tab on run

- packages/client/hmi-client/src/components/pyciemss/tera-pyciemss-cancel-button.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue
This addresses a few minor things
> Minor poll updates

- packages/client/hmi-client/src/temp/Equations.vue
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/mira/MiraController.java
Replace `latex => sympy.parse_latex => mira` pipeline with `latex => gollm => mira` pipeline.
This is the 2nd part to: https://github.com/DARPA-ASKEM/terarium/pull/5846
This PR also clean up the mira-endpoint.
`/mira/latex-to-amr` => `/knowledge/equations-to-model-debug`
POST `/knowledge/equations-to-model` should return a model-id, which in turn should reflect the equations.
```
{
"equations": [
"\\frac{d S(t)}{d t} = - b_q S(t) I(t)",
"\\frac{d E(t)}{d t} = b_q S(t) I(t) - r_X E(t)",
"\\frac{d I(t)}{d t} = r_X E(t) - g_p_q I(t)",
"\\frac{d R(t)}{d t} = g_p_q I(t)"
]
}
```
> use gollm=>mira equation to amr pipeline

- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
- packages/client/hmi-client/src/components/workflow/ops/compare-datasets/tera-compare-datasets-drilldown.vue
- packages/client/hmi-client/src/composables/useCharts.ts
- packages/client/hmi-client/src/services/dataset.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DatasetController.java
* the result_summary is read in the compare dataset instead of the beginning of the sample results
* Improved dataset downloading
> get all csv rows of result_summary and not sample data for compare dataset

- packages/gollm/gollm_openai/prompts/latex_style_guide.py
Minor change to ensure that the multiplication `*` is bracketed by whitespace (` * `). This would avoid the LaTeX spellchecker in Terarium from putting red underlines in expressions like `a*b` (as opposed to `a * b`).
> Update latex_style_guide.py to accommodate overzealous LaTeX spellchecker

- packages/client/hmi-client/src/components/asset/tera-asset.vue
- packages/client/hmi-client/src/components/documents/tera-document-asset.vue
Issue: 
- The text editor for a non-pdf document does not appear
Testing:
- Add a non pdf document to the project
- Open the resource 
> bug: text editor not appearing

- packages/mira/tasks/sympy_to_amr.py
* Update sympy_to_amr.py 
* Added definition of initials missing in MMT model returned by MIRA
* Set default values to model parameters
* Allows users to not have run a "Edit model" before configuring the model
> Add default initials and parameter values to model returned by MIRA

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/calibrate-ensemble-ciemss-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-node-ciemss.vue
This can lead to user confusion if theyre not familiar with the operator.
We should include tooltips similar to how we have done in the optimize-drilldown to help guide the user.
New node:
> Calibrate ensemble minor UI tweaks for user

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ModelConfigurationService.java
When we have a calibrated model configuration we do not necessarily have `matchingConfigParameter.getDistribution().getParameters().value()` which is referenced in `setModelParameters`.
Rather than trying to set the resulting AMR's parameter value just to not use it (as we will use the inferred parameter's value) lets just not try to set it.
Add both this model + model configuration your project.
Try to utilize the model configuration with any operation that relies on /model-configurations/as-configured-model/{id}
or directly hit this endpoint.
Prior to this change you will run into a  `503 - Service Unavailable`
[Model With Date.json](https://github.com/user-attachments/files/18199183/Model.With.Date.json)
[Calibrated Config With …
> Calibrated Configs failing createAMRFromConfiguration

- packages/client/hmi-client/src/components/model/petrinet/tera-model-diagram.vue
Resize observer causes double rendering pass, often times with no visible changes to the rendering. 
This disables the resize observer in preview mode to speed up loading time in the workflow canvas.
If you put a console.log into tera-model-diagram#renderGraph() you can track how many times render happens.
> don't enable resize-observer in model-diagram if in preview mode

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/calibrate-ensemble-ciemss-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/optimize-ciemss-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/simulate-ciemss-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/simulate-ensemble-ciemss-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss-drilldown.vue
Update pyciemss operator defaults:
-Fast is always euler with 0.1 step size
-Normal/quality is always dopri5 (no step size required)
- **Add step size to operators that it was missing from (This means some operator states are being updated please be aware demo is finished prior to merge)**
- Disable step size input when euler is not the selected method
Note that stepsize is no longer integer only but is able and in fact defaulted to be 0.1
> Pyciemss defaults

- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/tera-simulate-chart.vue
Issue:
- Simulate Ensemble Chart dropdown options do not appear without reloading the drill down
Testing
- add 2 model to a workflow
- create 2 model configs
- create a new simulate ensemble 
- add a chart
- dropdown options should appear
> fix for dropdown not working

- packages/client/hmi-client/src/components/home/tera-project-card.vue
- packages/client/hmi-client/src/components/home/tera-project-table.vue
- packages/client/hmi-client/src/components/widgets/tera-input-text.vue
- packages/client/hmi-client/src/page/tera-home.vue
Four small tweaks to the home page.
1) The Search button in the toolbar shouldn't be primary if the field is empty. Fixed by conditionally disabling it.
2) The Search field shouldn't have a blue background. 
Fixed by turning off the browser autocomplete. See above GIF to see the fix.
3) The table view search results had poor alignment. 
Fixed.
4) Fixed the project cards so they show the author name by default.
Here's the new:
> Jamie home page style updates

- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/scenario-templates/decision-making/decision-making-scenario.ts
- packages/client/hmi-client/src/components/workflow/scenario-templates/horizon-scanning/horizon-scanning-scenario.ts
- packages/client/hmi-client/src/components/workflow/scenario-templates/scenario-template-utils.ts
- packages/client/hmi-client/src/components/workflow/scenario-templates/value-of-information/value-of-information-scenario.ts
* default compare dataset charts when creating a scenario template.  This is included in the decision making, horizon scanning, and value of information templates.
* it will be default select the `mean` variables so:
state -> {metric}_state_mean
observable -> {metric}_observable_state_mean
> default chart settings for the compare dataset operator

- packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue
Issue:
- Long equations in Model from equations are being cut off
Testing:
- Open a model from equation drill down
- Add long equation
Resolves #5920
> Bug: Model from Equation - long equations cut off

- packages/client/hmi-client/src/components/dataset/tera-dataset-jupyter-panel.vue
* show the datset warning banner only when any cell has been executed
> dont show warning on dataset transformer first open

- packages/mira/tasks/sympy_to_amr.py
* MIRA `template_model_from_sympy_odes` creates models with a lot of missing values
* Assume some defaults and apply them on the model
* Examples: missing initial condition, time units, display names, parameter values
* Ensure unique template names/ids and readable display names
> Apply missing defaults onto models created from equations and MIRA

- packages/mira/tasks/generate_model_latex.py
* The generated LaTeX did not include the `(t)` for the model variables
* The LaTeX consumed in "Create model from equations" has these `(t)` to help the SymPy-to-MIRA step
* Aligning the model page equations with those of the "Edited by AI" equations help users check if the generated model's math match with the input math
> Add missing "(t)" to all the model variables in the generated LaTeX to align input/output math in the "Create model from equation" operator

- packages/client/hmi-client/src/model-representation/petrinet/petrinet-renderer.ts
Tweak to how a terminal transition (degradation) looks
Before:
After:
> style tweaks for degradation transitions

- packages/client/hmi-client/src/components/model/model-parts/tera-model-part-entry.vue
- packages/client/hmi-client/src/model-representation/service.ts
Closes: https://github.com/DARPA-ASKEM/terarium/issues/5882
The predicate `input && output` is incorrect because the sides can be imbalanced. A transition does not necessarily need to have an input (a production) or an output (a degradation). Added a fixme note to address the disjunctive typings.
Before, note the "units" are showing for some transitions, which doesn't make sense as units are on the states.
After:
View the transition table for the model here, that has a a mix up production and degradation transitions:
[non_mass_conserved.json](https://github.com/user-attachments/files/18294121/non_mass_conserved.json)
> fix transition input/output not showing up, add fixme note

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue
We are queuing up workflow-update actions regardless of whether there are progress changes or not, this is wasteful. This PR adds guards to only update if progress actually changed.
Run any of Calibrate, Optimize, Ensemble-Calibrate and check the network tab, we should only send updates if progress changes.
> Add guard against unnecessary workflow updates

- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue
This will fix simulations that have interventions connected to them
- When running simulate we should only `processResult` for `forecastId`. The previous set up was not waiting for the poller to be done correctly.
- Run a simulation with intervention plugged in. With main you will see 404 error if the base forecast finishes first (it should on vast majority of runs)
- Run again with this branch - no longer 404 as well as seeing 1 result added to the output node that can correctly be worked with
> Simulate With Interventions correction

- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue
The previous two watchers acting independently both calling `pollResult` was an issue.
This is because `pollResult` overwrites the `pollAction` for our ONE poller. 
This means that whichever watcher was triggered second would be the only simulation we would truly be checking the status for.
As we care about both simulations being completed before moving forward we move forward we can check the status one after the other.
We do not want to create two pollers both spamming the network at the same time
> Correction To Simulation Pollers

- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/intervention-policy-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue
- packages/client/hmi-client/src/components/workflow/scenario-templates/decision-making/decision-making-scenario.ts
- packages/client/hmi-client/src/components/workflow/scenario-templates/decision-making/tera-decision-making-template.vue
- packages/client/hmi-client/src/components/workflow/scenario-templates/horizon-scanning/horizon-scanning-scenario.ts
- packages/client/hmi-client/src/components/workflow/scenario-templates/horizon-scanning/tera-horizon-scanning-template.vue
- packages/client/hmi-client/src/components/workflow/scenario-templates/scenario-template-utils.ts
- packages/client/hmi-client/src/components/workflow/scenario-templates/tera-new-policy-modal.vue
- packages/client/hmi-client/src/components/workflow/scenario-templates/value-of-information/tera-value-of-information-template.vue
- packages/client/hmi-client/src/components/workflow/scenario-templates/value-of-information/value-of-information-scenario.ts
- packages/client/hmi-client/src/services/intervention-policy.ts
- packages/client/hmi-client/src/utils/date.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/InterventionController.java
We can add a new intervention policy within a template:
* open an intervention dropdown
* click create policy button
* policies will not be saved to the project until the create button for the template is pressed AND it is acutally used within the template
* these will be set as blank intervention policies and the user can add the them as needed within the workflow
Added for templates: 
* Value of Information
* Horizontal Scanning
* Decision Making
> add new intervention policy in templates

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/TaskService.java
- packages/server/src/main/resources/messages.properties
* Improves the error message when MIRA fails to create a model from equasions, made to be the same as SKEMA
Resolves #5902
> improve error message; fix typo

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ProjectPermissionsService.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/utils/rebac/ReBACService.java
Should add Admin Group users to reader contributors list (as opposed to the group itself).
Should evict the cached reader's list when permissions for a project change.
This is untested as currently I am failing to connect to S3 (I assume all are failing, but incase you can test without...)
> modify readers to have admins, evict cache when permissions changed

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/ops/compare-datasets/tera-compare-datasets-drilldown.vue
- packages/client/hmi-client/src/services/calibrate-workflow.ts
- packages/client/hmi-client/src/services/dataset.ts
- packages/client/hmi-client/src/utils/csv.ts
Some refactoring and clean up related to the function that does csv asset fetching. 
- Cache csv assets similar to what we do for the simulation results
- Move `parseCsvAsset` to its own `csv.ts` util file from `calibrate-workflow.ts`
- Move logics to fetch csv assets from dataset to `dataset.ts` service
> Refactor and clean up of functions related to csv asssets

- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-node.vue
The Create intervention policy node displayed both the placeholder illustration as well as the intervention summary card.
> removed intervention node placeholder illustration

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/util.ts
- packages/client/hmi-client/src/services/calibrate-workflow.ts
- packages/client/hmi-client/src/services/dataset.ts
1. Calibration and Ensemble-Calibration rely on a helper `getTimespan`. This helper has been made out of date as we are moving away from CsvAsset and we have removed the stats from this type.
2. Remove the useless helper function for cleaning up and to avoid having people use this in the future `setupDatasetInput`
3. As we are now holding dataset in a shallowRef we should update how we are getting and storing the dataset column information to be consistent. 
You should be able to
> Fix: Correct getTimespan 

- packages/client/hmi-client/src/components/drilldown/tera-drilldown-preview.vue
- packages/client/hmi-client/src/components/widgets/tera-slider-panel.vue
- packages/client/hmi-client/src/components/widgets/tera-slider.vue
- packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue
* If the tera-model-diagram is within a collapsed slider it renders itself without having a width to work with
* Now with the `v-if` I added it will mount once the slider is opened
* Fix is [here](https://github.com/DARPA-ASKEM/terarium/pull/6027/files#diff-2f796b404e2219b0045f6ee5141b6caa46be4372ebd0720307afca92e0b412f2) the rest is just some css clean up related the slider components
https://github.com/user-attachments/assets/53905006-f265-48b0-897b-47f9d447632e
> fix model diagram pan/zoom in create model from equations op

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ProjectController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/TerariumAssetCloneService.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/TerariumAssetServices.java
- packages/server/src/test/java/software/uncharted/terarium/hmiserver/service/data/TerariumAssetCloneServiceTests.java
Manually checking for a model to be copied, then check for intervention policies or configurations associated with that model to clone. The manual check has to be done because currently we walk the json of the `model` in a one-direction way, but models don't contain references to their configs/interventions... thats the other way around. This was a quicker fix for a deadline. Better fix would be to have models include references outward and then this problem goes away.
Resolves #5739
> [FEAT]: Copy model interventions and configs with model #5739

- packages/client/hmi-client/src/components/model/model-parts/tera-model-part.vue
* Editing entries were based on list index instead of id
* Now the same list index of a different page can be uniquely edited
Before: 
https://github.com/user-attachments/assets/ba904583-274a-4384-b834-0819fd2b56ca
After:
https://github.com/user-attachments/assets/a43c3275-a54e-4a60-b22b-db4a792b9de4
> fix: model page entry key should be id instead of index

- packages/client/hmi-client/src/components/workflow/tera-workflow.vue
Force edges to re-evaluate when adding connecting operators through the quick-menu.  This is a new problem due to splitting apart the updates APIs, and some certain actions no longer trigger edge evaluations because things are done piece-wise.
Add a model to workflow
- Connect to model-config
- From the quick-menu in model-config (the "+" button), create a connection to calibrate and calibrante-ensemble
Both the calibrate/calibrate-ensemble node and connecting edge should be shown.
> fix rendering edges that are created through quick-menu

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
This is related to this morning's PR about updating dataset columns. We should filter based off of our current dataset now so we are not showing risk.json's dataset columns as options for the user
Pre change:
Post change:
> Calibrate Mapping Options: Filter dataset columns on filename.

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
Fix debugger endpoint logic. Reminder we need a special debugger endpoint because `/equations-to-model` performs a lot of extra logic aside from converting equations to AMR, and has side effects.
Factor out common functions to serve both terarium-operator and debug endpoints, in running order:
- createLatexToSympyTask
- extractCodeFromLatexToSympy
- createSympyToAMRTask
Test feeding in equations in `http://localhost:8080/equations`
```
[
"\\frac{d S(t)}{d t} = - \\frac{\\beta * S(t) * I(t)}{N}",
"\\frac{d I(t)}{d t} = \\frac{\\beta * S(t) * I(t)}{N} - \\gamma * I(t)",
"\\frac{d R(t)}{d t} = \\gamma * I(t)"
]
```
> refactor equation-to-amr to share same sub methods

- packages/gollm/common/prompts/latex_style_guide.py
* Large systems of ODEs tend to cause MIRA to produce mathematically correct but structurally dissociated models (conversions -> production + degradation)
* This is an attempt at patching this issue by instructing the LLM agent to expand out algebraic expressions in the equations, making it easier for MIRA to do term-by-term matching
* For example, `S(t) * (a * I(t) + b * A(t)) -> a * S(t) * I(t) + b * S(t) * A(t)`
> Update equation style guide to avoid broken models

- packages/client/hmi-client/src/components/workflow/scenario-templates/decision-making/decision-making-scenario.ts
- packages/client/hmi-client/src/components/workflow/scenario-templates/horizon-scanning/horizon-scanning-scenario.ts
- packages/client/hmi-client/src/components/workflow/scenario-templates/scenario-template-utils.ts
- packages/client/hmi-client/src/components/workflow/scenario-templates/value-of-information/value-of-information-scenario.ts
* A recent change to the chart selection in compare dataset caused the template default selection to break since we were selecting different variables, this is now fixed with this changed
* removed now unused functions
> fix compare dataset charts from template

- packages/client/hmi-client/src/components/workflow/tera-workflow.vue
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/WorkflowService.java
This PR address a couple of sync issues
1. In part-1 https://github.com/DARPA-ASKEM/terarium/pull/5979 we changed appendOutput to also include a state, mostly this was because the state changes were done in part-2 https://github.com/DARPA-ASKEM/terarium/pull/6019 and it acted as a kind of polyfill. Basically in part-2 I forgot to remove it. Here we take this out but left adding a state as an option as it is probably a better way to handle new outputs and we can migrate slowly.
2. We introduced a bug with ☝️ in workflowservice.java checking nulls where we need to check for json-nulls on top of it.
3. To actually address the problem @Tom-Szendrey  found. There are scenarios where update-state event are emitted back-to-back-to-back programmatically. In order to ensure state variable …
> Workflow sync fix part 3

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-node-ciemss.vue
- Chart settings should not be stored in output's state as per a quick conversation in the design channel.
- make sure that simulate follows the same set up as the rest of the TA3
> Simulate - Save Solver Step Size with output

- packages/client/hmi-client/src/components/workflow/tera-workflow.vue
- packages/client/hmi-client/src/services/workflow.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/WorkflowController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/WorkflowService.java
Closes https://github.com/DARPA-ASKEM/terarium/issues/6031
`append-input` event wasn't wired up correctly. It only changes the client's version of the workflow, so the server's version does not have any of the newly created ports. This PR should address that.
Note: Things are a bit messy currently, as there is the workflow-wrapper, that functionally overlaps with the server logic. While the workflow-wrapper is more or less deprecated with respect to terarium-workflow.vue, it is used in the scenariot-templates. I marked a couple of areas where we should start tidying up things but these are out of scope here.
> hook up append-input event in workflow to server workflow update

- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
Design Change:
- Remove Pdf goto page function from Model Config & Intervention drill down.
Testing:
- Create a model config and connect a pdf document
- extract inputs
- pdf page shouldn't change when selecting different configs
- Create a intervention policy and connect a pdf document & model
- extract inputs
- pdf page shouldn't change when switching between interventions 
> removed goto for  model config and intervention

- packages/client/hmi-client/src/composables/useCharts.ts
- packages/client/hmi-client/src/services/charts.ts
The weight plots share the same x axis 0-1
**Before**
**After**
Resolves #5897
> Updated weight chart extent

- packages/client/hmi-client/src/services/workflow.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/WorkflowController.java
More consistent and resource oriented REST API route names. Try to adhere to:
```
/resource/:resource-id/sub-resource/:sub-resource-id/sub-sub-resource ... 
```
No real function changes, workflow should behave the same as before.
> better route naming convention

- packages/client/hmi-client/src/composables/project.ts
This pull request includes a change to the `useProjects` function in the `packages/client/hmi-client/src/composables/project.ts` file to improve the sorting of projects. The most important change is the addition of a sorting mechanism to order the projects by name.
fix #6070
> Display project in add to project menu in alphabetical order

- packages/gollm/common/prompts/latex_style_guide.py
* In one case, `N^{-1}` broke MIRA's SymPy-to-model function
* Rewriting these to `\frac{1}{N}` avoids this issue.
> Update LaTeX style guide to handle N^{-1}

- packages/client/hmi-client/src/components/workflow/scenario-templates/calibrate-ensemble/calibrate-ensemble-scenario.ts
Layout arrangement for ensemble calibrate. Each model-modelconfig-simulate-calibrate is a row.
> layout for calibrate ensemble

- packages/mira/tasks/generate_model_latex.py
* Jamie reported an error with the [Fang2020 model](https://github.com/user-attachments/files/18481276/Fang2020.1.json)
* Issue is caused by the state variable `Total_population` having no associated rate law, leading to an expression `d X / d t = 0` which the model latex generator does not account for.
* Fix is applied by adding an attribute check (if no `atoms` attribute, don't try to substitute `Y` with `Y(t)`)
> Patch model LaTeX generator to account for case where a state variable has no rate law

- packages/client/hmi-client/src/components/widgets/VegaChart.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/ops/tera-node-preview.vue
- packages/client/hmi-client/src/composables/useCharts.ts
1. Fixed small multiples layout
**Before**
**After**
2. Make sure comparison small multipes charts appear as single chart on the simulate node
3. Minor styling and layout updates
> Comparison charts improvments

- packages/mira/tasks/generate_model_latex.py
Fixing
```
Error: local variable 't' referenced before assignment
Traceback (most recent call last):
File "/mira_task/tasks/generate_model_latex.py", line 30, in main
var = t.subject.name
UnboundLocalError: local variable 't' referenced before assignment
```
> generate_model_latex typo

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/workflow/InputPort.java
Add back removed "accepMultiple" field to satisfy old workflows still in the system
> add back in unused field for backwards compatibility

- packages/client/hmi-client/src/services/charts.ts
* As per request the ordering of the sensitivty charts has changed to be like this format:
|  | `lambda` | `alpha` | ... | `j` |
| -------- | ------- | --- | --- | --- |
| `lambda`  | (`x = lambda, y = lambda`) | (`x = alpha, y = lambda`) | ... | (`x = j, y = lambda`) | 
| `alpha` | (`x = lambda, y = alpha`)     | (`x = alpha, y = alpha`) | ... | (`x = j, y = alpha`) | 
| ...  | ...  | ... | ... | (`x = j, y = ...`) | 
| `i` | (`x = lambda, y = i`) | (`x = alpha, y = i`) | (`x = ..., y = i`) | (`x = j, y = i`) |
> change order of sensitivity charts

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ProjectController.java
When fetching ALL the projects, we do not need the `overviewContent` at all.
The overview is fetched when it need to be displayed.
> Get all project bit faster.

- packages/client/hmi-client/src/services/charts.ts
Filter out unused variables from the label expression. 
This should prevent to have very long label expression which causes `Maximum call stack size exceeded ` error from the chart when there's a lot of variables in the operator. 
> Filter out unused variables from the label expression

- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
* Switching between datasets would add another "Download" option to the ellipses menu.  
* The fix now clears all down options before another one is pushed in
> fix dataset multiple menu items

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/TerariumAssetCloneService.java
Some legacy assets can exist in multiple projects. This weird edge case resulted in a scenario where a model can exist in project A yet have configs laying around in project B, C, D, etc. This filtering fixes this edge case
Resolves #6143
> [BUG]: Can't copy a project anymore #6143

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
Bug: 
- X-axis ground truth not being set correctly
Testing:
- Add a model and dataset 
- create a model config
- create a calibrate from the model config & dataset
-  ground truth points should be in the correct x-axis locations
> Bug - Calibrate ground truth set incorrectly

- packages/gollm/common/prompts/latex_style_guide.py
* The SIDARTHE model continued to be extracted incorrectly
* The issue lies with incomplete parenthesis term expansion
* Terms like `(a + b) * R(t)` were not expanded to `a * R(t) + b * R(t)` due to conflicting instruction
* The conflicting instruction has been removed and more examples provided on correct behaviour
* Eventually, we will hit the problem of terms like `a * (b + 1) * R(t)` that should not be expanded...
> Update to equation style guide to solve SIDARTHE issue

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/calibrate-ensemble-util.ts
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-drilldown.vue
- packages/client/hmi-client/src/composables/useCharts.ts
- packages/client/hmi-client/src/services/model-configurations.ts
- _unrelated_ datasetColumn options should be restricted to current file 
- Update getAsConfiguredModel to be a more user friendly interface
- Add mapping to `getSelectedOutputEnsembleMapping` to also include not selected mapping
- Rename `getSelectedOutputEnsembleMapping` to be more accurate
- By default do not show ensemble charts in drilldown.
Looking into:
- Remove _other_ chart all together?
- Ground truth not being shown in small multiples
https://github.com/user-attachments/assets/95e8f02a-e049-4334-aa49-8310261b8152
> Calibrate ensemble chart to allow variables not mapped

- packages/gollm/common/prompts/latex_style_guide.py
* The agent continues to not always expanding parenthesis expressions
* It seems to make this mistake depending on whether multiplication whitespaces ` ` have been replaced already by ` * `
* The style guide is reordered and more examples of the `(...)` expansion are added
> Update LaTeX style guide to avoid agent misbehaviour 

- packages/gollm/common/prompts/latex_to_sympy.py
* Follow-up to the tweaks to the equation style guide instructions
* In case the agent fails to do proper algebra (expanding/distributing parenthesis expressions), ask SymPy to do it
> Update latex_to_sympy.py to forcibly expand all the parentheses in the SymPy expressions

- packages/client/hmi-client/src/components/model/petrinet/tera-model-equation.vue
In discussion with jaehwan, pascale and tom on perf and stabilization, we decided to not run genreate_model_latex task if there are too many expressions that need to be parsed in sympy, which is the bottleneck. We proxy this idea by restricting the number of equations (number of states + number of observables). 
The 250 is just a somewhat reasonable max that a modeller might go through.
If you don't have a large model handy, lower the 250 threshold to 2.
> do not generate equations if num states + num observables > 100

- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/scenario-templates/horizon-scanning/horizon-scanning-scenario.ts
* Some name changes for the horizon scanning created model configurations
* Added a baseline configuration for the horizon scanning template (selected config w/o interventions)
* Simulation results name now like `Configuration (intervention)` so that this can be carried into downstream nodes
> horizon scanning tweaks

- packages/mira/tasks/sympy_to_amr.py
* Need to reduce complexity for the config extraction agent
* Created model will not have by default an initial expression `X0` and a parameter `X0 = 0.0`
* Instead, all the initial expressions will be just `0.0` and no parameter `X0`
> Update to "Create model from equations" - Disable default initial parameters

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/WorkflowService.java
We are incorrectly cascading in this scenario when either B or C is unlinked/removed, because cascade starts "source node" when B is removed C is invalidated, and when C is removed B is invalidated.
```
/==== B
A ==   
\==== C
```
This PR switches to use "target node"
On a workflow, connect multiple model-configs to a model operator, remove or unlink one of the model-config operators, the other model-configs should remain "valid".
> switch to target-cascade instead of source-cascade

- packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue
Change from updating-state at every keystroke to an update flush when the drilldown component is unmounted. Unconstrained calls to update-state can cause issues since they are now API bound and possible to get out of sync if there are streams of updates.
> tweak update-state pattern

- packages/client/hmi-client/src/components/drilldown/tera-drilldown-header.vue
- packages/client/hmi-client/src/components/drilldown/tera-drilldown.vue
- packages/client/hmi-client/src/components/drilldown/tera-output-dropdown.vue
* Added a thin scroll for the chips
> chips dont cover close button in drilldown

- packages/client/hmi-client/src/components/workflow/scenario-templates/decision-making/decision-making-scenario.ts
- packages/client/hmi-client/src/components/workflow/scenario-templates/horizon-scanning/horizon-scanning-scenario.ts
- packages/client/hmi-client/src/components/workflow/scenario-templates/value-of-information/value-of-information-scenario.ts
- packages/client/hmi-client/src/services/save-asset.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/InterventionController.java
* Fixes an issue where a new model would be added to the resources page when an intervention policy was created
* This seems to be a caveat of the cloning process.  Looking at the backend if we add an asset to the project when it already exists it will clone it and it's dependent assets hence why the model was cloned.  Since we are already adding the intervention policy in the backend when it is created we do not need to add it in the front end and this cloning is prevented
***EDIT***
* After a chat with Dan, going to keep things consistent here and I've removed the adding of the asset to the project in the backend.  I will be adding that functionality to the templates themselves for consistencies sake
> fix dupe model creation on intervention policy creation

- packages/client/hmi-client/src/components/workflow/ops/compare-datasets/compare-datasets-utils.ts
> base config in ranking

- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/ConfigureModelFromDatasetResponseHandler.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/ConfigureModelFromDocumentResponseHandler.java
* Saves extraction document id to the model configuration. 
* Model config drilldown checks for existing extraction document ids before requesting more extractions.
Resolves #6197
> 6197 task do not re extract configurations from existing inputs which were already extracted just extract new inputs

- packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratify-drilldown.vue
Previously we were calling `update-state` (within saveCodeToState) only after our `append-output` (within handleModelPreview) 
This changes the timing such that we call `update-state` with our executed code whenever we get the response
And we call `append-output` whenever we get our preview 
https://github.com/user-attachments/assets/12d63b23-ed42-459f-9a78-4bb1df7b3a8f
> Correct timing on when we save code to state

- packages/client/hmi-client/src/components/model/petrinet/model-configurations/tera-stratified-matrix-preview.vue
- packages/client/hmi-client/src/components/model/petrinet/model-configurations/tera-stratified-matrix.vue
- packages/client/hmi-client/src/components/model/petrinet/tera-model-diagram.vue
- packages/client/hmi-client/src/components/widgets/tera-tooltip.vue
- packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratification-group-form.vue
This is not a z-index issue. The problem is the tooltip is too close to the top of the section that it's in, so the top goes out of bounds. We would have to add a bunch of top padding to the section to see it, but that would be weird.
Instead of positioning the tooltip above the trigger, I centered it over the trigger. This moves it down a fair amount. It may still get cut off if it's large, but this is a decent temporary solution.
A better solution would be to move the tooltip to the top level layer, like app.vue, and then trigger it there. But that feels a bit drastic just as we're about to begin the eval. 
I also made the text smaller in two places:
Oh, and I changed the field in the Stratify operator for naming the strata groups from a regular input to a Textarea that grows if the …
> 6228 bug matrix popup from a stratified model appears cutoff

- packages/client/hmi-client/src/components/model/model-parts/tera-model-part-entry.vue
There's something wrong with the logic on the description field of tera-model-parts. It is displaying the description text twice. It's weird.
The v-if on the description field was incorrect. It was displaying when when NOT the preview mode was true. That's wrong. In preview mode we want to show the text version. In not-preview mode we only want to show the input text field.
> Fixed Model-parts bug where the description was displayed twice

- packages/client/hmi-client/src/components/workflow/ops/compare-datasets/compare-datasets-utils.ts
* Fixes an issue where compare dataset assumes that the input always has a value.  Cases like from scenario templates or just simply connecting an empty sim node to a compare dataset operator results in a console error
```
compare-datasets-utils.ts:348 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
at compare-datasets-utils.ts:348:72
at Array.map (<anonymous>)
at initialize (compare-datasets-utils.ts:348:40)
at tera-compare-datasets-node.vue:68:2
```
> fix compare dataset initialization

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
When using new and old values for your watchers if this is not for a string or number you should watch a copy of the object instead.
More details can be found in this helpful thread: 
https://stackoverflow.com/questions/62729380/vue-watch-outputs-same-oldvalue-and-newvalue
Update the endTime knob, refresh page, see that your change was actually saved.
> correction to calibration watcher.

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/scenario-templates/decision-making/decision-making-scenario.ts
- packages/client/hmi-client/src/components/workflow/scenario-templates/horizon-scanning/horizon-scanning-scenario.ts
- packages/client/hmi-client/src/components/workflow/scenario-templates/value-of-information/value-of-information-scenario.ts
* fixes an issue in some scenarios where intervention policy chart select would just be blank.
Fixes:
* do not add intervention policies chart selection if the policy is blank
* added chart selection support for horzion scanning and value of information templates
> fix intervention policy scenario chart selection

- packages/client/hmi-client/src/components/workflow/ops/tera-node-preview.vue
- This will show charts again in nodes if it is removed
- This is helpful for demos but we have more things afoot to look into
- Matt has an issue somewhere to look into this further in the meantime we can merge this to get our charts back at the cost of thumbnails (which his initial issue was looking into)
#6266
> Remove filter to show charts in nodes

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
- Correct prop name for node-preview. This will remove a warning we are seeing.
- Remove default parameter selection as this is causing many charts to be produced that the user likely wont care about and will need to remove - slowly.
> Calibrate minor updates

- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-dynamic-intervention-policy-group.vue
- Do not assume units as theyre not guaranteed and we are not reading them from anywhere
- Correct ordering for threshold vs value.
Provided the following: 
**From:** 
**To:**
> Correction to dynamic intervention wording

- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/scenario-templates/sensitivity-analysis/sensitivity-analysis-scenario.ts
* Now that we have the simulation settings in the scenario template, we can set it as the end time point indicated by the template
> set time point to end time in sensitivity analysis template

- packages/client/hmi-client/src/services/charts.ts
Fixes following console error from the chart
> Fix `legend_selection` signal missing error from the forecast chart

- packages/client/hmi-client/src/components/workflow/scenario-templates/horizon-scanning/horizon-scanning-scenario.ts
- packages/client/hmi-client/src/components/workflow/scenario-templates/value-of-information/value-of-information-scenario.ts
* Add a base simulation node for each generated  model configuration in the horizon scanning and value of information templates
Now looks like this 😄 
Testing: 
* Create a horizon scanning and/or a value of information workflow
* see that there are base simulation nodes (no interventions) for each generated configuration
> add a base simulation for each config in scenario templates

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/workflow/InputPort.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/workflow/OutputPort.java
Existing objects in DB have the "version" fields that do not deserialize
> serialization fix for inputport and outputport

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/calibrate-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/optimize-ciemss-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/simulate-ciemss-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss-drilldown.vue
- packages/client/hmi-client/src/services/models/simulation-service.ts
- Update states to have method type to ciemss method's enum 
- Update enum to include rk4
- Ensure when rk4 or euler are selected user can write in `step_size`
> Ta3 operators to include rk4 as a solver option

- packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-node.vue
- Remove extra "Starting time step" text so it only appear once
> design change intervention node

- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/simulate-utils.ts
- packages/client/hmi-client/src/composables/useCharts.ts
- Fix issue that quantile baseline not showing up with normalize option
- Fix the baseline label missing the variable name
**Before**
**After**
> Fix issue that quantile baseline not showing up with normalize

- packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue
* Fixes an issue in the model from equations node where the state was not being saved while editing equations
Testing:
Open a model from equations drilldown and edit equations that you want.  Uncheck/check whether you want to include the equations or not.  You should see that the edited equations should keep their edit value rather than reverted to its original state
> fix model from equations text state saving

- packages/client/hmi-client/src/services/graph.ts
Lower threshold for using ortho-edge routing to make model-diagram-loading faster for medium/large sized models (ones with 50+ edges).
> reduce initial routing threshold

- packages/client/hmi-client/src/components/workflow/ops/stratify-mira/stratify-mira-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratify-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratify-node.vue
Allow stratification via a model-configuration to carry forward the values of the config, as oppose to the values of the original model.
Start with an SIR model
- Create from it a new model-configuration with a different starting S0 value, say 123456
- Feed this model-config into stratify operator, and run a stratification that includes the S-state by say 3-groups
- Feed the stratify output into another model-config operator, verify that the S0 is 123456 and not the S0 value from the origin model
> Stratify model with model config

- packages/client/hmi-client/src/components/documents/tera-document-asset.vue
- packages/client/hmi-client/src/components/extracting/tera-drag-n-drop-importer.vue
- packages/client/hmi-client/src/components/project/tera-upload-resources-modal.vue
There were a few instances where extensions on the front end weren't `toLowerCase()`ed. Arguably we shouldn't be using hardcoded ".pdf" everywhere and instead should use the `AcceptedTypes.PDF` type but thats another time...
Resolves #6356
> [BUG]: Uploading a .PDF instead of a .pdf fail

- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-node.vue
A more efficient way to update both output and state at the same time in model-config operator. 
This should reduce the flickering due to updates happening back-to-back
Where we used to have this sequence of events (you can see it in the dev-console)
```
append-output
update-position
update-state
update-position
```
This is now
```
append-output
update-position
```
Connect model => model-config, the model-config operator node should be relatively stable.
> optimize how model-configuration communicates update events

- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
- Create a optimize run that has multiple criteria
- check the QoI charts.
Previously the data would be duplicated and thus incorrect for not first chart
> Optimize Success chart should be correct for more than first criteria.

- packages/client/hmi-client/src/components/workflow/ops/compare-datasets/tera-compare-datasets-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/compare-datasets/tera-compare-datasets-node.vue
- packages/client/hmi-client/src/composables/useCharts.ts
* When no interventions are present in the inputs to compare datasets, use the old coloring scheme in the charts.
> restore coloring when all inputs share an intervention, including none

- .eslintrc.cjs
- packages/client/hmi-client/tests/setup.ts
- packages/client/hmi-client/vite.config.ts
* Add a `/tests/setup.ts` script to `vite.config.ts`.
* Add a mock `Worker` for Vite test run in node.js.
* Add a TS lint rule to allow variable with an underscore to be unused. _i.e. `_message` can be unused in the function_
> Fix Vite test on main

- packages/client/hmi-client/src/components/workflow/ops/dataset/tera-dataset-node.vue
- packages/client/hmi-client/src/components/workflow/ops/model/tera-model-node.vue
Small tweaks to model and dataset operators, so nodes are initialized with a single append-output instead append-output + update-state events.
Model and dataset operators should work as normal
> Operator initialization tweaks

- .github/workflows/publish-client.yml
- .github/workflows/publish-equation-extraction-taskrunner.yml
- .github/workflows/publish-funman-taskrunner.yml
- .github/workflows/publish-gollm-taskrunner.yml
- .github/workflows/publish-mira-taskrunner.yml
- .github/workflows/publish-server.yml
- .github/workflows/publish-table-extraction-taskrunner.yml
- .github/workflows/publish-text-extraction-taskrunner.yml
- packages/text_extraction/Dockerfile
* remove arm64-emulation for CI builds. We now run on native arm64 runners
* Pinned pyMuPDF to version 1.25.2
Resolves #6481
> 6481 text-extraction fails on arm64 machines

- packages/client/hmi-client/src/components/widgets/tera-chart-settings.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/scenario-templates/sensitivity-analysis/sensitivity-analysis-scenario.ts
- packages/client/hmi-client/src/composables/useChartSettings.ts
- packages/client/hmi-client/src/composables/useCharts.ts
- packages/client/hmi-client/src/services/chart-settings.ts
- packages/client/hmi-client/src/services/charts.ts
- packages/client/hmi-client/src/types/common.ts
* Heatmaps for sensitivity charts
* ability to switch between sensitivity charts and heatmaps
https://github.com/user-attachments/assets/4015595a-5027-40c1-9b17-bb79b181119f
> heatmap scatter switch for sensitivity-charts

- packages/client/hmi-client/src/components/workflow/tera-workflow.vue
- packages/client/hmi-client/src/services/workflow.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/WorkflowController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/workflow/InputPort.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/workflow/OutputPort.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/workflow/WorkflowEdge.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/workflow/WorkflowNode.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/WorkflowService.java
This PR ports the branching logic from server/workflow.ts => WorkflowService.java. This should completely move the user-initiated workflow CRUD operations to the API layer and have a more consistent update pattern.
Create some sample workflow (eg model => stratify => model-config => simulate), the "duplicate" operation on a given node should branch the node itself and everything down stream of it, plus the first-order uptream edges.
> port branch workflow logic to api server

- packages/client/hmi-client/src/components/widgets/tera-common-modal-dialogs.vue
Issue: 
- When copying a project on the home, the default input isn't correct
Testing:
- try copying a project on the home page
- default name should look like 
- `Copy of <Name>`
> fix for copying project name

- packages/client/hmi-client/src/components/widgets/VegaChart.vue
- packages/client/hmi-client/src/services/charts.ts
Clean up and small tweaks based on feedback 
- True global font instead of redeclaration all over the place
- Font size tweak
Before:
After:
> chart tweaks

- packages/client/hmi-client/src/components/workflow/ops/model-edit/tera-model-edit-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratify-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratify-node.vue
- packages/client/hmi-client/src/services/model.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelConfigurationController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/mira/MiraController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ModelConfigurationService.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/ValidateModelConfigHandler.java
- packages/server/src/test/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelControllerTests.java
* as per a suggestion by @mwdchang it might be better to send in an optional model config id and try to populate the temporal data in the default configuration in the backend
* A request for when we attach a model configuration node to a stratify operator we want that model configuration's temporal context to be carried over to the output's temporal context.  Since this temporal context is not apart of the AMR, we need to get the temporal context of the input model configuration and use the temporal context in the created default configuration
* Added an optional model config id to the create model and create new from old model endpoints to take metadata from and populate
> stratify use input temporal context in output

- packages/client/hmi-client/src/components/model/model-parts/tera-model-part-entry.vue
Closes: https://github.com/DARPA-ASKEM/terarium/issues/6409
Have separate debouncers for each field so the queued up emit-events from field-A are not overwritten by event from fieldB.
In model page, try to change variable's description, unit, name, ... etc. Should all work as expected and not lose previous edits.
> Use different debouncer for each field so they do not override each other

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/ClientEventService.java
When exception happens in the fail over, we print out the bytes array stream, it is not particularly useful, especially if the content is large and it will completely overwhelm the server logging.
This PR caps to the first 10k bytes.
You can test this by uploading or viewing a very large AMR, eg the one that is 25MB from the eval. This will blow up the jackson serialization (a different issue) but also client-event. The byte-printing should last 2-3 pages and the actual useful exception trace is printed.
```
...snipped...
88, 50, 49, 102, 77, 72, 82, 118, 78, 86, 57, 110, 77, 122, 69, 105, 88, 88, 48, 115, 73, 67, 74, 48, 77, 70, 57, 50, 88, 51, 90, 102, 98, 86, 57, 116, 88, 122, 66, 48, 98, 122, 86, 102, 77, 72, 82, 118, 78, 86, 57, 110, 77, 68, 70, 102, 90, 122, 77, 121, 73, 106, 111, …
```
> only print the first 10k in byte array to prevent log from blowing up

- packages/client/hmi-client/src/services/charts.ts
- Fixed errors by making sure we don't pass `undefined` to `calculate` transform for the date tooltip.
- Also reverted the changes that made value tooltip to show x value instead of y value
> Fix chart error caused by `undefined` passed to the date tooltip transform

- packages/gollm/common/prompts/latex_style_guide.py
- packages/gollm/common/prompts/latex_to_sympy.py
> Integrate MIRA support of branching ratios in equation-to-model feature

- packages/client/hmi-client/src/components/widgets/VegaChart.vue
It seems like we are not really using the custom formatters specified in the vegalite global config, and they disrupt the chart-export because the custom code fragments are not exported. I have comment this out for now.
You should be able to click on the hamburger-option (...) and select "open in vega editor", and you should be able to export and interact with the chart outside of Terarium. You may need to refresh once or twice, I think the volume of data we usually have in simulate makes the editor a bit chunky, but it should show up without errors.
> remove custom formatter in vegalite

- packages/client/hmi-client/src/components/model/model-parts/tera-model-part-entry.vue
- packages/client/hmi-client/src/components/model/model-parts/tera-model-part.vue
- packages/client/hmi-client/src/components/model/petrinet/tera-petrinet-parts.vue
- packages/client/hmi-client/src/model-representation/mira/mira-util.ts
- packages/client/hmi-client/src/model-representation/service.ts
- packages/client/hmi-client/src/types/Model.ts
Closes: https://github.com/DARPA-ASKEM/terarium/issues/6445
- Remove concept search/entries as transition concepts do not exist
- Split **input/output** => **subject/output/controllers** per Nelson request
- Start to split apart "createPartsList(...)", this function seemingly treats state/transition/parameter as if they are the same object, which they are not. It makes it difficult to modify/tweak things. 
- Minor clean up in tera-model-part-entry for unused props
Where models are displayed:
- Input/Output becomes Subject/Outcome/Controllers in transition table
- No more concepts in the transition table
> transition table: add controllers, remove concepts

- packages/client/hmi-client/src/model-representation/service.ts
Add a check to see if the system is closed (preserves constant population). This is not an error but something to be called out for, as it can lead to overflow/underflow in simulations. 
This is potentially part of the suite of checks to be deployed into the operators.
Can test with this model 
[no-mass.json](https://github.com/user-attachments/files/18907661/no-mass.json)
and pasting the content into http://localhost:8080/amr-petri-test
> model sanity check: check for closed system

- packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue
Closes https://github.com/DARPA-ASKEM/terarium/issues/6621
Fix intervention indexing due to pagination wrap-around
In intervention-policy operator, add 9 or more interventions , eg:
- time=1, beta=1
- time=2, beta=2
- time=3, beta=3
- ...
- time=10, beta=10
Check that editing the 9th or 10th intervention does not affect the first page. Check that intervention can be saved.
> fix issue with indexing across pages

- packages/client/hmi-client/src/components/model/model-parts/tera-model-part.vue
- packages/client/hmi-client/src/components/model/petrinet/tera-petrinet-parts.vue
Simplify props for tera-model-part component, we are seemingly passing in redundant data structures
Find a stratified model, the operations `add xyz to all children` should work, eg update all state units for a stratified state V.
> clean up redundant prop collapsed-items

- packages/mira/tasks/generate_model_latex.py
* Fix the "align" env rending failure, possibly due to lack of support for `align*`
* Fix error caused by `dX/dt = 0` case, https://github.com/DARPA-ASKEM/terarium/issues/6693
> Fix two issues with Model page's LaTeX equations

- packages/client/hmi-client/src/components/model/tera-model.vue
Fix #6680 
The change simplifies the function by removing the conditional logic that checked for semantic changes to update the MMT before updating the model.
> Stop refreshing MMT on Model metadata updates

- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-configuration-item.vue
Resolves #6719 
Adding the modal made the `@click` event lost, so added back to the right place and remove duplicate event.
> 6719 bug cannot select configuration in configure model op

- packages/client/hmi-client/src/components/extracting/tera-drag-n-drop-importer.vue
* There used to be warnings when uploading documents because the validation was comparing arrays in the wrong direction.
* This PR fixes that
Before:
> fix warnings in drag and drop validation

- packages/gollm/common/prompts/latex_to_sympy.py
Should be `from sympy.abc import _clash` instead of `from sympy import _clash`
> Fix incorrect example in GoLLM prompt for LaTeX-to-SymPy

- packages/mira/tasks/generate_model_latex.py
Update our latex to not include the & after the = 
**Before**:
**After**: 
- You will need to run the gollm task runner locally
- Just open up a model page and see the latex equation
> remove the & from latex equation

- packages/gollm/common/prompts/latex_to_sympy.py
* Previously, the prompt did not explicitly require `equation_output` to be used
* Added extra instruction to that effect
> Update latex-to-sympy prompt to enforce `equation_output` return

- packages/mira/tasks/generate_model_latex.py
When latex equations are more than 5 characters we were wrapping them to the next line.
This would be clear and helpful if we were to be rendering the entire latex at once but as we are sending individual equations via our model drilldown this is not the case.
> Latex - Remove wrap on longer lines

- packages/client/hmi-client/src/components/model/petrinet/tera-petrinet-parts.vue
After selecting a time interval from the Time drop down on the model page, the drop down input does not display the updated value the user selected.
Fixed by making the related properties passed to the `tera-model-part` and `tera-model-part-entry` components  computed and hence reactive.
Resolves #6691
> fix: #6691 cannot actually change the unit of time in the model page 

- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/optimize-utils.ts
Correct the sorting used to determine the average risk so that we have the correctly our value.
Note that the sorting was using the default sort which will sort as though we are looking at strings and not in number order
New:
Old:
Run `yarn staging` and check out my optimize node:
`/projects/43693d8d-b162-413d-b119-0610f61c9e70/workflow/e8fb32d1-f0b3-4afe-9fa9-aff8ebfe6e3d?operator=512d4ff4-a7d7-4121-acf3-8b7bcc129adf`
[new sort.txt](https://github.com/user-attachments/files/19215221/new.sort.txt)
[Old Sort.txt](https://github.com/user-attachments/files/19215222/Old.Sort.txt)
> Fix: Correct Optimize Chart Label

- packages/client/hmi-client/src/components/workflow/ops/model-config/model-config-operation.ts
When the user is editing the configuration, the initial value of the mathml expression has a value of  
`<ci>I0</ci>` 
(at least in the example cited in the bug).  Then, when the user tabs away from the initial expression input, we make a call to `pythonInstance.parseExpression` to get a more detailed mathml, resulting in: 
`<ci><mml:msub><mml:mi>I</mml:mi><mml:mi>0</mml:mi></mml:msub></ci>`.  
This causes the disabling of the save button because the `isModelConfigValuesEqual` fn flags this as being a difference in the 'critical' values of the configuration.  However, the mathml expression should not affect the behaviour of downstream operators.  So, omit the mathml expressions from the comparison of 'critical' model configuration values.
Resolves #6772
> fix: 6772 - In 'Configure model', 'Save' button gets disabled unexpectedly when a focused expression input box loose the focus.

- packages/client/hmi-client/src/components/model/model-parts/tera-model-part-entry.vue
- packages/client/hmi-client/src/components/widgets/tera-timestep-calendar.vue
- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
- packages/client/hmi-client/src/services/charts.ts
- packages/client/hmi-client/src/services/model.ts
- packages/client/hmi-client/src/types/common.ts
- packages/client/hmi-client/src/utils/date.ts
Support "week" intervals for model and simulations. 
https://github.com/user-attachments/assets/def735fb-ea63-496d-b723-8bb1f766f153
Our notion for the "start of the week" is whatever date the modeller chose in the model-configuration operator. If the modeller goes backward (using the calendar to set timestep), we assume they will select the same weekday as they had originally selected on the model-configuration operator.
- Save a model with timeunit = week
- Create a config and pick a starting date/day
- Run a simulation, verify that the intervals for setting "end time" and the chart's data points are multiples of seven days
> supporting week-interval for model and simulations

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-node.vue
When a calibration is finished running we will run two simulations. A before and an after calibration.
Both of these should include any interventions applied to the calibration.
> Fix: Add intervention to calibration forecast runs.

- packages/gollm/common/utils.py
* Fixes an issue with equations to image not working
* we were passing an invalid image url to the LLM, replace the ':' with ';' fixes this
> fix format typos in equations from image

- packages/client/hmi-client/src/services/charts.ts
- Format chart tooltip number using `displayNumber` formatter that's used in other places in the app. 
- It's done by adding formatted number field to the data in advance before rendering the chart. 
> Format tooltip numbers using displayValue formatter

- packages/client/hmi-client/src/components/model/tera-model.vue
Instead of info + green text for button we will use warning (yellow) and blue text for button.
> Update simplify banner colours

- packages/gollm/llms/azure/AzureTools.py
- packages/gollm/llms/llama/LlamaTools.py
- packages/gollm/llms/openai/OpenAiTools.py
It looks like the cleanup equation task was erroring out (at least for me locally) due to the model card prompt being removed.
The script was still looking for this unused import and erroring out.  Removing the import will fix this
> fix unused model card prompt import

- packages/client/hmi-client/src/components/workflow/ops/compare-datasets/compare-datasets-operation.ts
- packages/client/hmi-client/src/composables/useCharts.ts
- Rename TimepointOption  `OVERALL` to `PEAK` as to not be confused with the new `AVERAGE` option. 
Correct logic for the follow:
- PEAK -> Should find each dataset variable's peak independently. 
- LAST -> should not assume each dataset has the same length.
- FIRST -> Just reduce the size of the payload to be only the relevant data.
Add logic for:
- AVERAGE -> this will find the average value for a variable within the each dataset independently. 
I am not sure if cleaning this up any further is worth it. If you have suggestions or believe it is please let me know.
If you find this hard to follow or read please let me know
Here I have set up two SIR simulation runs. The only difference here is that one runs for 20 timesteps and the other for 90.
**Before:** …
> Compare Dataset Criteria fixes

- packages/client/hmi-client/src/components/model/petrinet/tera-parameter-entry.vue
- packages/client/hmi-client/src/components/model/petrinet/tera-parameter-table.vue
- packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratification-group-form.vue
- packages/client/hmi-client/src/services/model-configurations.ts
Correct logic around the warning colour for parameters within a stratified model. 
Previously if any of the parameters within a group were set to constant it would warn user that values were missing.
- Move helper function `isParameterInputEmpty` and utilize it for both stratified and non stratified parameters.
Before:
After
> Fix: Model Config warnings for stratified parameters

- packages/client/hmi-client/src/types/Types.ts
- packages/gollm/tasks/enrich_dataset.py
- packages/ocr_extraction/src/server.py
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/extraction/BBox.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/extraction/Extraction.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/extraction/ExtractionItem.java
The first two points here were geared for tabular lookups in DBs so we wouldn't need to resort to json-queries, I don't think we will go these route, but whether these attrs are nested or flattened shouldn't do too much harm.
- Denormalize data structure to make page and source attributes more readily accessible in ExtractionItem
- For similar reason above, flatten provenance
- Introduce type and subType rather than explicit text/picture/table sections
- Java data models
- Added the idea of "rawText" and "text", this is to support secondary processes. For example we have latex-string and cleaned-latex-string
> denormalize extraction data structure

- packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratification-group-form.vue
There is an issue with updating the stratify group form too quickly.
This issue is because we had some weird logic such that we would update the local variable twice per user interaction.
This was causing issues where if a user were to update the multi select more quickly than the update-state then we could end up over writting the user's changes via the watcher.
Using the selectedVariables as an example 
We would update via a `MultiSelect` v-model. 
This will then trigger an update state to update the state's version of `selectedVariables`
This update state will then trigger a watcher within this group form. 
This watcher will then set this `selectedVariables` to be the value provided by the node's state
As we have already updated this local `selectedVariables` with the multiselect we …
> Fix: Stratify Group Form

- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DocumentController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/document/DocumentAsset.java
- packages/server/src/main/resources/db/migration/V21__drop_document_assset_assets_column.sql
- packages/server/src/test/java/software/uncharted/terarium/hmiserver/service/data/DocumentServiceTests.java
- packages/server/src/test/java/software/uncharted/terarium/hmiserver/service/data/TerariumAssetCloneServiceTests.java
Remove deprecated column "assets" and associated clean ups, as well as migration script to drop the column from the DB.
Makes the code a little leaner and easier to understand.
- Start as normal `./hmiServerDev.sh start staging run` and check in DB column is dropped. 
- App should work normally (eg, view pdf document)
> remove deprecated document_asset.assets

- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-node.vue
When running a calibrate we should keep the temporal context.
> Keep date context in calibrated model

- packages/client/hmi-client/src/components/pyciemss/tera-pyciemss-cancel-button.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-node.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-node-ciemss.vue
Update the ta3 operators to have their cancel id logic slightly cleaner.
We can provide a list of ids, so where relevant we will send a list of any ids that pass `Boolean(id)` aka not `""`
> TA3 operators to have correct cancel ids

- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
As described in [this issue](https://github.com/DARPA-ASKEM/terarium/issues/6642) it can be disorienting when a dataset has many many columns.
Here I have added a paginator as suggested
> Dataset Drilldown - Add paginator to column info section

- packages/client/hmi-client/src/components/model/petrinet/tera-petrinet-parts.vue
- packages/client/hmi-client/src/model-representation/service.ts
Previously we were using the `mmt` when reading for the transitions. However we were using the `model` when writing to the transitions.
Here I am merging the two when reading in order to get the `model`'s description.
Previously if you write into a transition description it will not be shown.
If you extract into one it will also not be shown.
Now if you write into it you should see it saved:
> FIX: Model Transition descriptions should now be visible

- packages/client/hmi-client/src/components/model/petrinet/tera-equation-container.vue
- packages/client/hmi-client/src/components/model/petrinet/tera-model-description.vue
- packages/client/hmi-client/src/components/model/petrinet/tera-model-equation.vue
- packages/client/hmi-client/src/components/operator/tera-operator-model-preview.vue
- packages/client/hmi-client/src/components/workflow/ops/model-from-equations/model-from-equations-operation.ts
- packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/model/tera-model-node.vue
- packages/client/hmi-client/src/services/knowledge.ts
- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
* Hookup _new_ OCR formulas to model from equations drilldown
* modified `EquationBlock` data structure accordingly to hold a provenance reference, addtional info can be lookedup in a map (i.e bounding boxes, page number, etc...)
* OCR formulas are already edited by AI, so will no longer be cleaning equations on the front end
* removed some unused function related to the `old` equations-to-model endpoint
* removed the old equations-to-model endpoint entirely
> Hookup OCR equations to model from equations

- packages/server/src/test/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeControllerTests.java
* There is an issue with the knowledge controller tests after recent changes removing the text attribute for the DocumentAsset.  This should allow the tests to pass again
> fix backend units tests for knowledge controller

- packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-node-ciemss.vue
We were missing the following from simulate ensemble's polling. 
This was causing an issue where if the simulation failed in this way we would keep polling/not reset the inprogressid
> Simulate ensemble fail gracefully

- packages/client/hmi-client/src/model-representation/service.ts
* `RegNetVertex` is no longer a type so I have removed it so the client tests will pass again
> fix non exisiting type

- packages/gollm/common/prompts/latex_to_sympy.py
Remove extra `)` that causes the code to error out.
> Fix typo in latex_to_sympy.py

- packages/client/hmi-client/src/components/code/tera-code.vue
- packages/client/hmi-client/src/components/code/tera-directory.vue
- packages/client/hmi-client/src/components/drilldown/tera-drilldown.vue
- packages/client/hmi-client/src/components/home/tera-project-menu.vue
- packages/client/hmi-client/src/components/llm/tera-beaker-code-cell.vue
- packages/client/hmi-client/src/components/llm/tera-jupyter-response.vue
- packages/client/hmi-client/src/components/navbar/tera-navbar.vue
- packages/client/hmi-client/src/components/widgets/tera-import-github-file.vue
- packages/client/hmi-client/src/components/workflow/ops/model-comparison/tera-model-comparison-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/model-edit/tera-model-edit-drilldown.vue
- packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratify-drilldown.vue
- packages/client/hmi-client/src/components/workflow/tera-workflow.vue
Use type import to fix warnings
To test:
1.  Delete existing client `node_modules`
2. `yarn install`
3. Start vite / dev server
4. Fail to observe the aforementioned  warnings
> bug: Client warnings - dependies imported but not resolved #6964
