packages/client/hmi-client/src/components/model/petrinet/model-configurations/tera-stratified-matrix.vue

Remember and restore the last matrix configuration type.

remember matrix configuration of last edit action

---

packages/client/hmi-client/src/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue

adding chart to node

---

packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/calibrate-operation.ts
packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss.vue
packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue

Adding end time to pyciemss calibrate

---

packages/client/hmi-client/src/workflow/ops/optimize-ciemss/tera-optimize-ciemss.vue

missing field in save state

---

packages/client/hmi-client/src/page/project/components/tera-project-overview.vue

My first commit! :)
Made the project description text primary dark.
**BEFORE**
**AFTER**

Made the project description text primary dark

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/climatedata/ClimateDataController.java

Catching exceptions thrown by the proxy service for subset operation and preview fetching.

fix[hmi-server]: Improved Climate Errors

---

packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/calibrate-operation.ts
packages/client/hmi-client/src/workflow/ops/optimize-ciemss/optimize-ciemss-operation.ts
packages/client/hmi-client/src/workflow/ops/optimize-ciemss/tera-optimize-ciemss.vue
packages/client/hmi-client/src/workflow/ops/simulate-ciemss/simulate-ciemss-operation.ts

Reduce num samples/num iterations for default run time

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/mira/MiraController.java

Catching exceptions thrown by the MIRA proxy. Small cleanup in KMC

fix[hmi-server]: Improved Mira Errors

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/AnnotationController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/EventController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/ImageController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/TGPTController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/permissions/GroupsController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/permissions/RolesController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/permissions/UsersController.java

Minor cleanup of some controllers using the old `@Autowired` annotation.

fix[hmi-server]: Controller Cleanup

---

packages/client/hmi-client/src/page/project/components/tera-resource-sidebar.vue

* Simplified new buttons in resource side bar

refactor: tidy up resource bar new buttons

---

packages/client/hmi-client/src/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue

Like the optimize call forecast should include the calibration inferred params if provided

forecast should include the calibration like opt

---

packages/client/hmi-client/src/workflow/ops/funman/tera-funman.vue

fix: import inputnumber

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/gollm/GoLLMController.java

Like a responsible fisher, I'm going to catch and throw back all these exceptions

fix[hmi-server]: GoLLM exception handling

---

packages/client/hmi-client/src/components/funman/tera-constraint-group-form.vue
packages/client/hmi-client/src/workflow/ops/funman/tera-funman.vue

monotonicity changes

---

packages/client/hmi-client/src/components/model/petrinet/tera-other-concepts-table.vue
packages/client/hmi-client/src/components/model/petrinet/tera-petrinet-tables.vue
packages/client/hmi-client/src/types/Types.ts
packages/client/hmi-client/src/workflow/ops/model-config/model-config-operation.ts
packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config-node.vue
packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config.vue
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/modelparts/ModelMetadata.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/gollm/ScenarioExtraction.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/ConfigureModelResponseHandler.java

* Clean up of the node operator
* Small typo in the `suggestedConfigurationContext` function
* Add a new ModelMetadata field to store GoLLM extractions results
* Display them in a model page
Resolves #3265

Display GoLLM unalign extractions in the other concept accordion

---

packages/client/hmi-client/src/components/drilldown/tera-drilldown-header.vue
packages/client/hmi-client/src/components/drilldown/tera-drilldown.vue
packages/client/hmi-client/src/components/operator/tera-operator-port-icon.vue
packages/client/hmi-client/src/workflow/ops/simulate-ciemss/tera-simulate-ciemss.vue

controversial input pills on header

feat: input chips in drilldown header

---

packages/client/hmi-client/src/components/operator/tera-operator-port-icon.vue

fix: vue components don't like it when you import `Component`

---

packages/client/hmi-client/src/components/operator/tera-operator-port-icon.vue

fix: forget about using `Component` for now

---

README.md

Update the readme with WSL install instructions for window users

Readme - WSL install instruction

---

packages/client/hmi-client/src/workflow/ops/stratify-mira/tera-stratify-mira.vue

- stock ids == initial targets and state ids == initial targets so I am collecting them from `semantics.ode`

feat(stratify): select stockflow variables

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java

add name to placeholder document

---

packages/client/hmi-client/src/services/github-import.ts

* The parameter names for this were changed on our back end but the front end didn't change.
Resolves #3304

bug[hmi-client]: Unable to save github repo as code asset

---

packages/client/hmi-client/src/workflow/ops/calibrate-julia/tera-calibrate-julia.vue

- Save loss values in state
**Note, this can be quite large (eg 2,000 elements of {iteration, value}). Is this a concern? I understand the state was not intended to just shove everything into**
- render graph onMount (watch immediate does not work for this referencing of HTML elements)
- while throwing this into the onMount I may as well throw other things into this initialize section to clean up a bit

Save sciml calibrate loss func

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/ExtractionService.java

Missed return statement from https://github.com/DARPA-ASKEM/terarium/pull/3315/files#diff-80e38ab553e5a0328da640e922927aa66ab9443318196830c5928d622311d3d0R113 by the commit created from github suggest change feature. 
And this PR fixes it. 

Fixed missing return statement

---

packages/client/hmi-client/src/api/api.ts
packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config.vue

* fixed issue where we would get infinite green success panels of extraction from document
* atob for base64 decoding rather than Textdecoder
* close connection on error

fix infinite succes on extractions

---

packages/server/src/test/java/software/uncharted/terarium/hmiserver/controller/xdd/XDDTests.java

* Those tests are blocking the build

Fix xDD tests not working

---

packages/client/hmi-client/src/components/dataset/tera-dataset.vue
packages/client/hmi-client/src/components/model/tera-model.vue
packages/client/hmi-client/src/components/operator/tera-operator-annotation.vue

initial edit state:
on mouse hover state:

add missing checkmark for input

---

packages/client/hmi-client/src/main.ts
packages/client/hmi-client/src/services/ClientEventService.ts
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/ClientEventService.java

refactor removal into send

---

packages/server/src/test/java/software/uncharted/terarium/hmiserver/service/notification/NotificationServiceTests.java

Hopefully this means 3 == 3 and not 3 != 6

remove notification test

---

packages/client/hmi-client/src/components/pyciemss/tera-pyciemss-cancel-button.vue
packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss.vue
packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss.vue

Updating label to be "Stop"
Moving to the left side along with the run button

Pyciemss Cancel button styling

---

Makefile

Missing funman build config/info

fix: missing makefile entries

---

packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config.vue

* Fix an issue where when you open model config it will give a 500 since the model that was being sent was null

fix broken mmt call

---

packages/client/hmi-client/vite.config.ts

fix(vite config): beaker urls

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/DataMigrationESToPG.java

* Actually do the migration of sims to pg
* Fixing some potential bugs around object equality

migration_of_sims

---

packages/client/hmi-client/src/components/home/tera-project-table.vue
packages/client/hmi-client/src/page/Home.vue
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ProjectController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/TerariumAsset.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/project/Project.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ProjectService.java

3443 bug owner does not show up in table view on the homepage

---

testing/model-extraction.md

* Created a folder `testing` to host all the Markdown manual scenarios.
* Created a folder `testing` on Google Drive to host the data used for the testing (PDF, etc.)
* Created first test __Model extraction__
Those are kept simple for now, we are taking a minimum viable product approach. Once we have enough step and some parts looks robust enough, I will move to automated end to end testing.

First pass at manual testing

---

packages/client/hmi-client/src/components/navbar/tera-notification-panel.vue

Made some adjustments to the UI design of the Notifications panel to better align with the original design.
**BEFORE:**
**AFTER:**

UX adjustments and refinement to Notifications panel

---

.github/workflows/publish-funman-taskrunner.yml
.github/workflows/publish-gollm-taskrunner.yml
.github/workflows/publish-mira-taskrunner.yml
Makefile

fix CI builds for taskrunners

---

packages/client/hmi-client/src/App.vue
packages/client/hmi-client/src/components/dataset/tera-dataset-jupyter-panel.vue
packages/client/hmi-client/src/components/dataset/tera-dataset-jupyter-regridding-panel.vue
packages/client/hmi-client/src/components/llm/tera-jupyter-chat.vue
packages/client/hmi-client/src/components/model/tera-model-jupyter-panel.vue
packages/client/hmi-client/src/components/workflow/ops/dataset-transformer/dataset-transformer-operation.ts
packages/client/hmi-client/src/components/workflow/ops/dataset-transformer/tera-dataset-transformer.vue
packages/client/hmi-client/src/types/common.ts

* Ability to change programming languages in data transform
* fixed an issue where the ConfirmDialog was popping up multiple times when used, this should be defined at the root of the project
https://github.com/DARPA-ASKEM/terarium/assets/33158416/22e3141e-5491-4585-aad6-a4c447773eff

change data transform language

---

packages/server/src/main/resources/db/migration/V5__Alter_simulation_constraints.sql

add new migration to add OPTIMIZATION simulation type

---

packages/client/hmi-client/src/components/home/tera-project-card.vue

small fix for date - had to close and delete the old branch for this task.

Incorrect date for Project card

---

packages/client/hmi-client/src/page/Home.vue

Add search field that filters out projects based on `name`, `userName` or and `description`
Before Search input:
After Search input:

3445 task add searchfiltering on home page

---

packages/client/hmi-client/src/services/project.ts
packages/client/hmi-client/src/types/Types.ts
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ProjectController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/TDSCodeController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/code/Code.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/code/CodeFile.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/code/Dynamics.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/code/ProgrammingLanguage.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/project/Project.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/repository/data/CodeRepository.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/CodeService.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/DataMigrationESToPG.java

* Migrating the code asset from ES to PG
Resolves #3345

3345 task migrate code to postgres from es

---

testing/model-extraction.md
testing/validate-model-configuration.md

* Include a script to test _Validate configuration_ operator.

Add FUNMAN test

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/TaskService.java

Small fixes that were made during a meeting about Task Runner.
* Small typos
* Remove unused private variables
* Added extra warning on cache configuration

fix typos on TaskService.java

---

packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratify-mira.vue
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ModelService.java
testing/data/Configured SIR.json

* We were too strict on model schema test.
* Change back-end to make sure this is save as lowercase.

Fix model schema test

---

README.md

* Improving docs for running server in debug.

improving debug instructions for back end

---

packages/client/hmi-client/package.json
packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config.vue
packages/client/hmi-client/src/python/PyodideWorker.ts
yarn.lock

Upgrade pyodide and fix initial and parameter tables using expressions before the values are ready.

upgrade pyodide, fix mmt init problems

---

packages/client/hmi-client/src/components/model/petrinet/tera-parameter-table.vue

* fix const/distribution dropdowns
* remove concept and source columns

Const distrib fix

---

testing/pyciemss-simulate.md

Test notes for PyCIEMSS Simulate operator interface.

pyciemss simulate test notes

---

testing/pyciemss-calibrate.md

Notes for pyciemss calibration UI testing

pyciemss calibration notes

---

packages/client/hmi-client/package.json
packages/client/hmi-client/src/components/llm/tera-notebook-jupyter-input.vue
packages/client/hmi-client/src/components/llm/tera-notebook-jupyter-thought-output.vue
packages/client/hmi-client/src/components/model/petrinet/tera-parameter-table.vue
packages/client/hmi-client/src/components/workflow/ops/decapodes/tera-decapodes-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/model-comparison/tera-model-comparison.vue
packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config.vue
packages/client/hmi-client/src/components/workflow/ops/model-edit/tera-model-edit.vue
packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratify-mira.vue
packages/client/hmi-client/src/python/PyodideWorker.ts
yarn.lock

Sync over fixes and changes made for CHI demo
- LLM stratify first version
- Bandaid for fixing distribution/constant dropdown
- Upgarde pyodide, fix sympy errors
- LLM thoughts for model-edit
Do not remove/close this branch, we will continue to sync periodically back to `main` over the next few days

sync Release/chi demo May 08

---

packages/client/hmi-client/src/services/notificationEventHandlers.ts

It should fix the failing build

Replaced removed type

---

testing/ensemble-calibrate.md
testing/ensemble-simulate.md

Note: These tests are not validating correctness.
This utilizes files from: https://drive.google.com/drive/u/0/folders/1sU3-CG9g9GBuTda_30lahiHAXu7U2-Xt

adding some test scenarios for ensemble

---

.github/workflows/test-server.yaml
packages/client/hmi-client/src/composables/project.ts
packages/client/hmi-client/src/page/Home.vue
packages/client/hmi-client/src/page/project/components/tera-project-configuration-modal.vue
packages/client/hmi-client/src/services/project.ts
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ProjectController.java

* Require a title to create/edit a project.
* Remove the need to provide a `userId` to `hmi-server`.
* Disable the submit button if the title is empty.

Update Project to require a name.

---

testing/_template.md
testing/add-dataset-to-project.md
testing/add-model-to-project.md
testing/compare-two-models.md
testing/dataset-enrichment.md
testing/download-asset-from-project.md
testing/ensemble-calibrate.md
testing/ensemble-simulate.md
testing/model-configuration-extracting-variables.md
testing/model-configuration-input.md
testing/model-configuration-notebook.md
testing/model-edit.md
testing/model-enrichment.md
testing/model-extraction.md
testing/operator-annotations.md
testing/project-search-sort.md
testing/project-sharing.md
testing/pyciemss-calibrate.md
testing/pyciemss-simulate.md
testing/simulate-calibrate-model-configuration-w-sciml.md
testing/stratify-model.md
testing/stratify-notebook.md
testing/test-workflow-interactions.md
testing/transform-dataset.md

* Added `Estimated time to completion` field

Testing clean up

---

testing/stratify-notebook.md

Easier to read code in markdown file

more readable code in stratify-notebook test

---

packages/client/hmi-client/src/components/drilldown/tera-output-dropdown.vue
packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config.vue
packages/client/hmi-client/src/utils/date.ts

change for time label

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/simulationservice/SimulationRequestController.java

Simulation forecast does not have project id set

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DatasetController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DocumentController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ProjectService.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/utils/rebac/askem/RebacUser.java

None permission messes with services

---

packages/client/hmi-client/src/components/widgets/tera-input.vue
packages/client/hmi-client/src/utils/number.ts
packages/client/hmi-client/tests/unit/utils/number.spec.ts

* I want this function to return a number, not a string.
* This was causing our nist input to return a string instead of a number

nist to number fix

---

packages/client/hmi-client/src/components/model/petrinet/tera-parameter-entry.vue
packages/client/hmi-client/src/components/model/petrinet/tera-parameter-table-v2.vue
packages/client/hmi-client/src/components/widgets/tera-input.vue
packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config.vue
packages/client/hmi-client/src/services/model-configurations.ts

* Add uniform distributions to constants with uncertainties
* The changes seem pretty big for that attached ticket so I'll do the tooltips in another [ticket](https://github.com/DARPA-ASKEM/terarium/issues/3735)
https://github.com/DARPA-ASKEM/terarium/assets/33158416/83286e14-cf10-40f8-a48d-e9331e45f05d

add uncertainty values

---

testing/manual/Stratify-LLM-Tests.md

I believe that the test question here should have been written better to be more accurate and that the prompt actually doesnt need updating IMO

test question to better work with cart control

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/gollm/GoLLMController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
packages/server/src/main/resources/messages.properties

add error messages for gollm controller

---

packages/client/hmi-client/src/assets/css/theme/_variables.scss
packages/client/hmi-client/src/components/model/petrinet/tera-initial-entry.vue
packages/client/hmi-client/src/components/model/petrinet/tera-initial-table-v2.vue
packages/client/hmi-client/src/components/model/petrinet/tera-parameter-entry.vue
packages/client/hmi-client/src/components/model/petrinet/tera-parameter-table-v2.vue
packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config.vue
packages/client/hmi-client/src/model-representation/service.ts

* Add a dismissible information card when any data is missing from model or parameter
* I've now based name, description, and units on the entry based off the model.  This allowed model changes to be shown here

Missing metadata card

---

docs/workflow operations/Optimize Doc.md

If this does not give you a full enough picture please let me know.
Some confusing parts to focus on to be sure they are understandable:
-maxiter
-maxfeval

adding optimize doc explaining our interface

---

testing/manual/stratify-model.md

update stratify test

---

packages/server/src/main/resources/application.properties

Fixing basic auth for legacy model configs

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DatasetController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/dataset/DatasetColumn.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/TerariumAssetCloneService.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/DatasetService.java

Some of the datasets were missing columns from a previous bug. This re-runs the logic if creating from existing data.

Ensure columns are recreated on dataset creation

---

packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config.vue

Fix: minor correction

---

testing/manual/test-workflow-interactions.md

Added missing link to the test model JSON in the README

Add missing link to test model JSON in test-workflow-interactions.md

---

packages/funman/Dockerfile

Fix: building funman failing due to this

---

packages/client/hmi-client/src/components/dataset/tera-dataset-description.vue
packages/client/hmi-client/src/components/dataset/tera-dataset.vue
packages/client/hmi-client/src/components/widgets/tera-related-documents.vue

* Just had to pass the fetchDataset emit into `tera-related-documents`
* Did a lil clean up too
* Before you had to refresh the page to see the changes to the table, now its is updated properly
https://github.com/DARPA-ASKEM/terarium/assets/28237258/5579fe81-19db-43d8-b3d5-26dd6d68513f

fix: dataset enrichment appears without reload

---

packages/server/src/main/resources/application-staging-keycloak.properties
packages/server/src/main/resources/application-staging.properties

fixed issue with staging application properties

---

packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-node.vue

Fix an issue where stale cache is used in  model-config operator after disconnect/reconnect
- Add model-A to workflow, e.g. SIR model
- Add model-B to workflow, e.g. SIDARTHE model
- Connect model-A to a model-configuration-operator
- Drilldown to model-configuration, verify the parameters/initial sections make sense and reflects model-A
- Disconnect model-A with model-configuration-operator
- Connect model-B with model-configuration-operator
- Drilldown to model-configuration, verify the parameters/initial sections make sense and reflects model-B

reset model cache on upstream disconnect

---

packages/client/hmi-client/src/components/widgets/tera-input.vue

removing attrs as per Dan's suggestion
Allow us to pass type as prop

tera input type fix

---

packages/client/hmi-client/src/components/workflow/ops/model-comparison/tera-model-comparison.vue
packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config.vue

* I noticed the notebook styles for these 2 component were a little wacky from changes that were made to the drilldown styles, this should fix it

notebook style fix

---

packages/client/hmi-client/src/temp/Vegalite.vue

Fire brush selection event

---

packages/client/hmi-client/src/page/Home.vue

* While waiting for #3943 to be resolved, this is a temporary fix to make the app usable again.

Display Table on the home page

---

testing/manual/pyciemss-optimize.md

I have added an optimize test 
This could have some more details as to what to expect via the output
Some of the misc things are still being worked on with the optimize updates
I will add updates to this as I finish the optimize updates

add manual testing - optimize

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/SummaryController.java

PR feedback

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelConfigurationController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/mira/MiraController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ModelConfigurationService.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/ConfigureFromDatasetResponseHandler.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/ConfigureModelResponseHandler.java

* Null pointer fix
* Converting some methods to static where able to
* Extracting block of code to its own method to make reading easier.
Resolves #(noissue)

TASK: Small saftey fix and code cleanup

---

packages/client/hmi-client/package.json
yarn.lock

Remove unused dev-dependency `@types/p5`

clean up unused deps

---

packages/client/hmi-client/src/components/operator/tera-operator.vue
packages/client/hmi-client/src/components/workflow/tera-workflow.vue

Unable to drag select text from add note input field on a node. This causes the note to be dragged

fix for dragging bug

---

packages/client/hmi-client/src/components/asset/tera-asset.vue

small fix for spinner issue with the model node, I tested other assets too and this doesnt affect them

model spinner fix

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/model/Model.java

https://github.com/DARPA-ASKEM/terarium/issues/4015

Fix NPE when getting model config lists

---

packages/server/README.md
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/TransformController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/funman/FunmanController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/simulationservice/SimulationRequestController.java
packages/server/src/main/resources/application-local.properties
packages/server/src/main/resources/messages.properties

updated error messages for funman and sciml

---

packages/client/hmi-client/src/components/model/petrinet/tera-parameter-table.vue

* Fixes an issue where JS math would lead to many precision points, this may be an issue for very small numbers.
* See attached bug ticket for issue
https://github.com/DARPA-ASKEM/terarium/assets/33158416/668a5f85-6b2b-464f-b058-d4fec5a14148

fix precision

---

packages/client/hmi-client/src/components/home/tera-project-card.vue

* I hate Vite + Vue.js handling of assets.

fix homepage images

---

packages/client/hmi-client/src/components/widgets/tera-input.vue

* when the type of tera input is a number, it now emits the value as a parsed float

tera input number fix

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/simulationservice/SimulationRequestController.java

Removing outdated comments.
If we want we can create an issue to move all of the intervention logic from pyciemss-service to HMI. But this will involve more than just this todo comment and should also involve moving pyciemss-service  into a pure service.

Task: removing outdated TODO comments.

---

packages/client/hmi-client/src/components/widgets/share-project/tera-share-project.vue
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ProjectController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/model/Model.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ProjectPermissionsService.java

4049 bug setting project to restricted public doesnt seem to work

---

packages/client/hmi-client/src/components/model/petrinet/tera-model-description.vue

Part of the big PR branch of updating model page #3894

Remove Provenance from model page

---

packages/client/hmi-client/src/components/model/petrinet/tera-model-description.vue
packages/client/hmi-client/src/components/model/tera-model.vue

Remove model type from model header

---

packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss.vue

Summary generation plumbing for optimize operator outputs
Edit:
Closes #4095

output summary generation for optimize operator

---

testing/manual/validate-model-configuration.md

* The 90 bound makes no sense since the end time is set to 100

fix: Update validate-model-configuration.md

---

packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue
packages/server/src/main/java/software/uncharted/terarium/hmiserver/repository/data/ProjectRepository.java

4009 use output name for model from equations output port

---

packages/client/hmi-client/src/components/widgets/tera-input.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-constraint-group-form.vue

State will not update correctly without these changes unless the user utilizes a dropdown AFTER the input sections - ugh

Optimize drill down, dont use on-focus-out

---

packages/client/hmi-client/src/components/workflow/ops/interventions/tera-interventions-drilldown.vue
packages/client/hmi-client/src/utils/date.ts

* Created a small utility to sort dates DESC
* Sorted the filteres intervention
Resolves #4123

Change order from latest to oldest in intervention policies left panel

---

packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue
packages/server/src/main/resources/application-local.properties

**fix** 
the watcher to be checking a string value instead of a list of 2 strings as that was not correctly determining when they were changed causing this watcher to trigger on every state update which is of course not ideal.
**Cleanup**
Update the poller action to be the same as others more up to date format.

Optimize multiple outputs per run

---

packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/optimize-ciemss-operation.ts
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-criterion-group-form.vue

* Rename ContraintGroup to appropriate `Criterion`
* Remove the observables from the dropdown
* Clean up few things
Resolves #4149

4149 constraint drop down should not have observables these are broken in pyciemss at the moment

---

packages/server/build.gradle
packages/taskrunner/build.gradle

Fix the depracated features for Gradle 9.
https://docs.gradle.org/8.8/userguide/upgrading_version_8.html#java_convention_deprecation

Support for Gradle 9

---

packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-card.vue

* Fixes an issue where if interventions list was too short it would wrap to the right side as seen in this [thread](https://unchartedsoftware.slack.com/archives/C06FGLXB2CE/p1721308943409219)
* I just surrounded `<ul>` 100% width

intervention card style fix

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss.vue
packages/client/hmi-client/src/services/calibrate-workflow.ts
packages/client/hmi-client/src/services/charts.ts

Just some formatting of the Calibrate with PyCIEMMS page and charts

Jamie calibrate with pyciemss chart tweaks

---

packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-card.vue
packages/client/hmi-client/src/types/Types.ts
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/simulationservice/interventions/InterventionSemanticType.java

Updating value for future users of this
Updating key for future users of this
Updating intervention's label for me

Rename somewhat confusing label: Variable -> State

---

packages/client/hmi-client/package.json
yarn.lock

* A non breaking update did broke everything...
* Reverting to 3.43

Revert Prime-Vue

---

packages/client/hmi-client/src/components/widgets/tera-input.vue

Really we should stop watching the update and start using onblur now that its available. butttt

Fix an emit for tera-input

---

packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/optimize-ciemss-operation.ts
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue
packages/client/hmi-client/src/services/charts.ts

* Intervention charts
* adding labels to interventions
Interventions drilldown:
Optimize:

Interventions charts

---

packages/client/hmi-client/src/services/charts.ts

Changed optimize chart labels

---

packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue

Add default values to output settings

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/calibrate-operation.ts
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/simulate-ciemss-operation.ts
packages/client/hmi-client/src/components/workflow/tera-workflow.vue

* [Remove the SciML operators from the workflow add component menu](https://github.com/DARPA-ASKEM/terarium/commit/998436798844710c8a920ba398b7680f5eb4d4df)
* [Update names of PyCiemss operators](https://github.com/DARPA-ASKEM/terarium/commit/06c43f78982a4c2976bc272e251ce916096ef2fb)

Remove sciml operator from the menu

---

packages/client/hmi-client/src/services/charts.ts

chart label formatting tweaks

---

packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
packages/client/hmi-client/src/services/charts.ts

Show units on the axis for the optimize drilldown charts

4208 show units on the chart for optimize drilldown

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue
packages/client/hmi-client/src/services/charts.ts

* These legends are a pain in the ass to work with...😢 
* Did my best here - essentially compacted the legends so that they can be seen in the node view
* The drilldown chart view should be the same as before

legends-on-node-charts

---

packages/client/hmi-client/src/model-representation/service.ts

* Clean up unused function/method/constant
* Change where we get intials metadata, from the metadata properties to the model object

Display variable name and unit on model config operator

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue

fix for unit time bug

---

packages/client/hmi-client/src/services/charts.ts
packages/client/hmi-client/src/temp/Vegalite.vue

Added histogram chart

---

packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratify-mira.vue

Disable stratify button until request is completed

---

packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/optimize-ciemss-operation.ts
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue

* stores optimized policy id on state rather than on the object

store optimize policy id rather than object in state

---

packages/client/hmi-client/src/services/charts.ts

formatting, truncate strategy on axis, but show full number on tooltips

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/TransformController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/proxies/skema/SkemaRustProxy.java

* these endpoints are not being used anymore so I have removed them.
* a part of House cleaning #4033

task: remove mathml to acset

---

packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue

* fixes an issues with model configuration node where beaker was always be initialized twice causing some messy logs

fix: model config beaker initialization

---

packages/client/hmi-client/src/components/model/petrinet/tera-parameter-other-value-modal.vue
packages/client/hmi-client/src/services/model-configurations.ts

fix for other value type being place in wrong file which is auto generated

fix for other values type

---

packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/optimize-ciemss-operation.ts
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue

Use calibrated model-config instead of the special calibratedSimulationId

use calibrated model-config

---

packages/client/hmi-client/src/services/charts.ts
packages/client/hmi-client/src/temp/Vegalite.vue

Added error charts

---

packages/client/hmi-client/src/components/dataset/tera-dataset-overview-table.vue
packages/client/hmi-client/src/services/concept.ts
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/mira/MiraController.java

fixed issue with error being thrown with empty concepts

---

packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
packages/client/hmi-client/src/types/Types.ts
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/simulationservice/OptimizeRequestCiemss.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/simulationservice/parts/OptimizeExtra.java

Update optimize request to allow Derek to more easily utilize euler method.
https://github.com/DARPA-ASKEM/pyciemss-service/pull/110

Optimize request update

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/FileExport.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/simulation/Simulation.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/TerariumAssetCloneService.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ITerariumAssetService.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/NotebookSessionService.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/SimulationService.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/TerariumAssetServiceWithoutSearch.java
packages/server/src/main/resources/application.properties

Ensure result files are exported correctly.

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss.vue

Updating optimize to have presets

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/proxies/skema/SkemaUnifiedProxy.java

"Remove" Skema text reading from proxies

---

packages/client/hmi-client/src/components/workflow/ops/model-edit/tera-model-edit.vue

added new sample agent question for model edits

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/ExtractionService.java

do not use skema-tr for extraction

"Remove" skema-text-reading from extraction service

---

packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-node.vue
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/repository/data/ModelConfigRepository.java

* fix default config creation when there are no configs

model config fix

---

packages/client/hmi-client/src/api/api.ts
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue

- use promise all kick off multiple forecast runs.
- get forecast errors should there be any
- handle poller running into errors

Optimize poller updates

---

packages/client/hmi-client/src/assets/css/theme/designer/components/input/_inputswitch.scss
packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratification-group-form.vue

* Fix selector issue with the update

Fix issue with toggle switch not turning gree when true

---

packages/client/hmi-client/src/components/operator/tera-operator-inputs.vue
packages/client/hmi-client/src/components/operator/tera-operator-outputs.vue

* Ability to drag n drop edges in the workflow (clicking on the ports still works as well)
* Check out the branch and let me know what you think...I couldn't see any issues while testing it out 😄

ability to drag n drop edges in the workflow node

---

packages/client/hmi-client/src/components/dataset/tera-dataset-jupyter-panel.vue

* Save dataset when pressing enter on the dataset transformer
* Took the opportunity to replace the primevue dialog with our own here as well

save dataset on enter press

---

packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue

Thanks Dan for pointing that out!

Simulate Chart correct index.

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/climatedata/ClimateDataController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ProjectController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/ExtractionService.java

Trying to debug a staging issue but the error is gobbled and not reproducible locally

add log error when a 500 error is returned

---

packages/client/hmi-client/src/components/workflow/tera-workflow.vue
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/WorkflowService.java

Fix bad migration
You can rename an existing workflow.

fix workflow broken renaming logic

---

testing/manual/optimize.md

Minor description changes to avoid confusion around 5.3 on whether we are looking for a new value or new start time.

Optimize test update 

---

testing/manual/simulate.md

* I added some intervention steps to make sure we test whether Simulate works with an intervention policy

Update simulate.md to include interventions

---

packages/client/hmi-client/src/assets/css/style.scss
packages/client/hmi-client/src/components/drilldown/tera-drilldown.vue
packages/client/hmi-client/src/components/model/petrinet/model-diagrams/tera-model-diagram.vue
packages/client/hmi-client/src/components/widgets/tera-tooltip.vue

- Along with these style improvements, I made universal style rules for keyboard shortcuts
https://github.com/user-attachments/assets/6cd284f9-3e64-4195-9d7d-1f3dee52b3ce

style: prettier drilldown arrow nav

---

packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue

fix: show intervention policy name

---

packages/client/hmi-client/src/components/workflow/ops/model-edit/tera-model-edit.vue

disable model edit wizard

---

packages/client/hmi-client/src/components/workflow/ops/model-edit/tera-model-edit-node.vue
packages/client/hmi-client/src/components/workflow/ops/model-edit/tera-model-edit.vue

- Save a new model
- Add that model to the resources panel
https://github.com/user-attachments/assets/1f5e09f2-ca7c-45d0-9a35-5d593bb216ec

 task: save as for model edit

---

packages/client/hmi-client/src/services/concept.ts
packages/server/src/main/resources/application.properties

Open a model page that contains concepts.
Ensure that they are pulling from mira dkg correctly - you can check network tab for this
Go to a dataset and fill in a concept
Click the square to get taken to the concept's page:
http://mira-epi-dkg-lb-c7b58edea41524e6.elb.us-east-1.amazonaws.com/docs#/

Update mira endpoint

---

packages/mira/Dockerfile

Quality of life changes, and force runner to rebuild

add editor mira-taskrunner image

---

testing/manual/project-sharing.md

- clean up some of the unneeded points

tests: update project sharing test

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/modelparts/metadata/Annotations.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ModelService.java

Fix metadata.annotation format for downstream - the problem is null vs empty-list, we need to provide the latter and not the former

attempt to ensure annotation metadata is in correct format for downstream

---

containers/scripts/docker-compose-data-services.yml

updating mira rest url in beaker container

---

packages/client/hmi-client/src/components/drilldown/tera-drilldown.vue
packages/client/hmi-client/src/components/drilldown/tera-output-dropdown.vue
packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman.vue
packages/client/hmi-client/src/components/workflow/ops/model-edit/tera-model-edit.vue
packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue

Adjusted labels, position and fontWeight of timestamp

---

packages/client/hmi-client/src/components/drilldown/tera-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/model-edit/tera-model-edit.vue

Add Draft mode style
https://github.com/user-attachments/assets/746915ed-1bf3-452a-b84d-52e775ae3ac5

style: edit model draft mode

---

packages/client/hmi-client/src/components/project/tera-save-asset-modal.vue
packages/client/hmi-client/src/components/workflow/ops/intervention-policy/intervention-policy-operation.ts
packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-node.vue
packages/client/hmi-client/src/services/intervention-policy.ts
packages/client/hmi-client/src/services/save-asset.ts
packages/client/hmi-client/src/types/Project.ts
packages/client/hmi-client/src/types/Types.ts
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/AssetType.java

* save as for intervention policy

save as intervention policy

---

testing/data/SEIRHD Q1b added params.json
testing/manual/model-stratification.md

This updated manual test captures all the steps that the monthly demo scenario requires:
* stratify by many (>18) age groups
* customized stratify with notebook view to handle irreversible processes (e.g. `unvaccinated -> vaccinated` and not vice versa)
* stratify multiple times
* check the default configuration of a stratified model

Updated manual test for stratify

---

packages/client/hmi-client/src/assets/css/style.scss
packages/client/hmi-client/src/components/drilldown/tera-drilldown.vue
packages/client/hmi-client/src/components/operator/tera-operator-menu.vue
packages/client/hmi-client/src/components/operator/tera-operator-outputs.vue
packages/client/hmi-client/src/components/operator/tera-operator-port-icon.vue

A few small changes here:
CHECKBOXES
CHIP SIZE
MENU WIDTH

Jamie fix checkboxes and pills

---

testing/manual/Transform-dataset.md

Updated transform dataset manual test.

Updated transform dataset test: Add files via upload

---

packages/client/hmi-client/src/assets/css/style.scss
packages/client/hmi-client/src/components/workflow/ops/model-comparison/tera-model-comparison.vue

adjusted font sizes of markdown text

---

packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue

* Fix an issue where model config state was not resetting to the original config values
Fix:
https://github.com/user-attachments/assets/1d7016e8-f358-4393-9e1a-a7e5e3846a01

reset model config fix

---

packages/client/hmi-client/src/components/drilldown/tera-drilldown-header.vue
packages/client/hmi-client/src/components/drilldown/tera-output-dropdown.vue
packages/client/hmi-client/src/page/Home.vue
testing/manual/transform-dataset.md

Some minor padding / margin adjustments. 
- Home page - fixed space between projects search / filter
- Increased space between drilldown tabs and annotation 
- Increased space between output label and timestamp

Neil design tweaks 1

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue

Made the Calibrate drilldown look more like the recent designs:
- moved wizard into collapsable slider
- adjusted spacing and typography
-

Jamie calibrate design tweaks

---

packages/client/hmi-client/src/components/model/petrinet/tera-model-equation.vue
packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue
packages/client/hmi-client/src/services/knowledge.ts

* Add `documentId` of the original Document source of the equations.

Add documentId on eqautionsToAMR service request

---

packages/client/hmi-client/src/services/workflow.ts
packages/client/hmi-client/src/types/workflow.ts

Minor clean up of workflow related stuff, both tighten and simplify typing structure.

Workflow minor cleanups

---

packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue

* Was using the wrong variable to check ids, now fixed

save intervention policy fix

---

packages/server/src/main/resources/db/migration/V17__project_asset_constraint.sql

* script to update the project asset constraint to include `INTERVENTION_POLICY`

Update project asset constraint

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue

- Removing out dated menu items from ta3 operators
- We will add back any saving feature in the next task: https://github.com/DARPA-ASKEM/terarium/issues/4767

Removing out dated menu items from ta3 operators

---

packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-card.vue

limit update calls when name is change

fix: add debounce to intervention name change

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue

* similar to simulate, we are now showing intervention policies and annotation in calibrate
https://github.com/user-attachments/assets/d617b6e5-5f3b-444e-8eb3-8e86fb834d9f

show intervention policies on calibrate

---

packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-node.vue
packages/client/hmi-client/src/services/charts.ts

* Show intervention charts on nodes if available

show intervention charts on nodes

---

packages/client/hmi-client/src/components/dataset/tera-dataset-jupyter-panel.vue
packages/client/hmi-client/src/components/llm/tera-jupyter-chat.vue
packages/client/hmi-client/src/components/workflow/ops/dataset-transformer/tera-dataset-transformer.vue

Add default preview showing all attached datasets in comments

default preview code comments for dataset transformer

---

packages/client/hmi-client/src/components/documents/tera-document-asset.vue

Adding option to download document from ... menu

---

testing/manual/optimize.md

Fixed the links to the datasets and updated the formatting

Fixed broken links and formatting

---

docs/workflow operations/Optimize Doc.md
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue

A few questions were asked about optimize response json so i figured I would write them down here for future reference

Minor update to optimize doc

---

packages/client/hmi-client/src/components/model/petrinet/model-configurations/tera-stratified-matrix-modal.vue

Removing duplicate button with confusing label:

Stratify Matrix remove Cancel button

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
packages/client/hmi-client/src/services/charts.ts

**Before:**
**After:**
Resolves #4864

4864 histogram chart fix

---

packages/client/hmi-client/src/components/widgets/tera-asset-enrichment.vue

https://github.com/user-attachments/assets/e214a4ad-f704-47bc-842f-46d30361aa12

4822 bug the enrichment modal labels are not clickable

---

packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-node.vue
packages/client/hmi-client/src/services/charts.ts

* hide intervention labels on node

hide intervention labels on node

---

testing/manual/model-stratification.md

*Fixes typos in model stratification test

fix typos in model stratification test

---

packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
testing/manual/model-configuration-notebook.md

* show the llm response in model config
https://github.com/user-attachments/assets/8e7debc7-974c-4db6-863b-595a7f605b1f

show llm response in model config

---

packages/client/hmi-client/src/components/model/petrinet/model-diagrams/tera-model-diagram.vue

* Phew took me 4 hours to find this one 😢 
* Fixes an issue in model diagram where changing the model in preview node seems to cause some downstream issues which are difficult to debug (shown in screenshot)
* key based on the model id will force the `figure` to re-render in preview mode
* when these issues would happen the app would become buggy (sometimes unresponsive) when creating a new model or switching outputs in model from equations 
Screenshots:
The first time you either switched the model or create a model in the model from equations node you would get this 'insertBefore' error
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertBefore')
at insert (runtime-dom.esm-bundler.js:28:12)
at processCommentNode (runtime-core.esm-bundler.js:4679:7)
at patch …
```

fix model from equations

---

packages/client/hmi-client/src/components/workflow/ops/dataset/tera-dataset-node.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue

* Display column names in dataset node:
Plus a few changes for Pascale's demo:
* Wider side panel in optimize
* Add padding to simulate results panel
Resolves #4982

Display column names in dataset node

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue

Made calibrate chart sections collapsable

---

packages/client/hmi-client/src/components/widgets/tera-pdf-embed.vue
packages/client/hmi-client/src/components/workflow/ops/model-from-equations/model-from-equations-operation.ts
packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue

Design change
- when the user clicks on an equation the pdf's page will change to the page containing the equation.
Testing
- Should see the current selected equation in the pdf viewer

Link equations to page

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue

This typo broke the LLM generated annotation. :(
I fixed it. 

Fixed the typo for AI generated annotation

---

packages/client/hmi-client/src/types/Types.ts
packages/gollm/gollm_openai/prompts/amr_enrichment.py
packages/gollm/gollm_openai/schemas/amr_enrichment.json
packages/gollm/gollm_openai/tool_utils.py
packages/gollm/tasks/enrich_amr.py
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/gollm/GoLLMController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/modelparts/semantics/Initial.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/modelparts/semantics/Rate.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/EnrichAmrResponseHandler.java

5064 bug amr enrichment does not work as expected

---

packages/client/hmi-client/src/services/goLLM.ts

So it turns out that the events were already set up but we forgot to …remove the old task handler code. Removing that fixes the exceptions.
Resolves #5076

Fix messaging around GoLLM tasks #5076

---

packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue

https://github.com/user-attachments/assets/7ea3e84d-45c3-4ad9-8e14-b90d0258fdd0

fix: add arrows to simulate drilldown and add spinner to run button

---

packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratify-drilldown.vue
testing/manual/stratify-notebook.md

-Update sample questions for users to better understand structure
-Update test case to one that will pass.
Related to: https://github.com/DARPA-ASKEM/askem-beaker/pull/164

Stratify LLM correctly using structure

---

packages/client/hmi-client/src/services/knowledge.ts
testing/manual/model-from-equations.md

This pull request includes several updates to the `knowledge.ts` service file and a documentation update. The most important changes involve code cleanup, restructuring imports, and updating a manual test scenario.
Code cleanup and restructuring:
* [`packages/client/hmi-client/src/services/knowledge.ts`](diffhunk://#diff-1cadbdc206294108b809908967930771b445649801686db0e4302c037ad81ca1L58-L124): Removed multiple `console.debug` statements and unnecessary `console.group` calls to clean up the code.
* [`packages/client/hmi-client/src/services/knowledge.ts`](diffhunk://#diff-1cadbdc206294108b809908967930771b445649801686db0e4302c037ad81ca1L58-L124): Deleted the `codeToAMR` and `codeBlocksToAmr` functions, which were no longer needed.
* …

Model extractions update

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/EnrichAmrResponseHandler.java

Fix AMR enrichment to not overwrite default configurations for initial states

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/WorkflowService.java

Add more logging to better debug when/where things start to get de-synced. Add 
- nodeId
- nodeStatus
- output values
```
2024-10-17 15:09:35 [INFO] REQUEST STARTED | WorkflowController.updateWorkflow | method=PUT; uri=/workflows/40ef3d97-f537-4675-89b6-ba8c3fda22a0?project-id=3d7b0bff-5c55-48b4-bc4c-0dd7aa876967;  [software.uncharted.terarium.hmiserver.interceptors.RequestLoggingInterceptor:40]
2024-10-17 15:09:35 [INFO] Node id=397a512a-af24-43fd-8dd9-ae457e4ab6df,  status=success, deleted=false [software.uncharted.terarium.hmiserver.service.data.WorkflowService:102]
2024-10-17 15:09:35 [INFO]   Out: f863d6ec-7338-48ee-b30c-2408262d21b3 [software.uncharted.terarium.hmiserver.service.data.WorkflowService:106]
2024-10-17 15:09:35 [INFO] Node id=4edc3e27-92ec-4eab-8c7d-d331d526edc2, …
```

improve workflow update logging to capture more info

---

testing/manual/model-edit.md

* Typo fix
* Add test to check whether the code is running on the input or the output

Update to Model Edit manual test

---

packages/client/hmi-client/src/components/model/model-parts/tera-model-part-entry.vue
packages/client/hmi-client/src/components/model/model-parts/tera-model-part.vue
packages/client/hmi-client/src/components/model/model-parts/tera-time.vue
packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
packages/client/hmi-client/src/types/Types.ts
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/model/configurations/ModelConfiguration.java

Adding initial dates to model configuration to be used with timepoints, part 1/4
https://github.com/user-attachments/assets/71196d8b-3ce8-448c-a398-12e8be768b21

adding initial dates to model config pt1

---

packages/client/hmi-client/src/types/Types.ts
packages/gollm/gollm_openai/prompts/config_from_document.py
packages/gollm/gollm_openai/prompts/interventions_from_document.py
packages/gollm/gollm_openai/schemas/configuration.json
packages/gollm/gollm_openai/schemas/intervention_policy.json
packages/gollm/gollm_openai/tool_utils.py
packages/gollm/utils.py
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/gollm/GoLLMController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/model/configurations/ModelConfiguration.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/simulationservice/interventions/Intervention.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/ConfigureModelFromDocumentResponseHandler.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/InterventionsFromDocumentResponseHandler.java

5221 adding page references to model configurations

---

packages/server/src/main/resources/application.properties

add liveness and readiness probe support

---

packages/client/hmi-client/src/assets/css/theme/designer/components/input/_calendar.scss
packages/client/hmi-client/src/components/widgets/tera-timestep-calendar.vue
packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-static-intervention-policy-group.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
packages/client/hmi-client/src/utils/date.ts

* Created a component to handle the timestep/calendar interchangeability 
* Added functionality to calibrate and optimize
Optimize
Calibrate

add date/timestep interchangeability to calibrate and optimize

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
packages/client/hmi-client/src/components/workflow/ops/funman/funman-operation.ts
packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-node.vue

- funman progress is shown
https://github.com/user-attachments/assets/42ad9d1b-fdb6-4c1c-aed7-11bbbedd49c5

show funman progress

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/ExtractionService.java

Removing failing call to SKEMA as we no longer use this. Updating error messages

Removing unused SKEMA call

---

packages/client/hmi-client/src/assets/css/theme/designer/components/input/_editor.scss
packages/client/hmi-client/src/components/project/tera-project-overview-editor.vue

Before:  
https://github.com/user-attachments/assets/91e41f7f-f465-433a-a0d1-2181b9da5014
After: 
https://github.com/user-attachments/assets/bdc02f2a-8977-45df-b63a-ca19aab6837c

toolbar in overview page stays up, only the editor scrolls

---

packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue

optimize drilldown has nav arrows

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue

calibrate-drilldown arrows

---

packages/client/hmi-client/src/components/widgets/VegaChart.vue

add back tooltips

---

packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue

Plot samples for the base line as well

Plot samples for the baseline in simulate chart

---

containers/scripts/docker-compose-data-services.yml
packages/client/hmi-client/src/services/concept.ts
packages/server/src/main/resources/application.properties

They have updated epi dkg endpoint
https://github.com/DARPA-ASKEM/orchestration/pull/440

updating mira endpoints

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue

The calibration knobs will now update when we change our output selection 
https://github.com/user-attachments/assets/f43c54bc-d72a-4159-9715-106d26128cba

Calibrate knobs to update with output selection

---

packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-drilldown.vue
packages/client/hmi-client/src/types/Types.ts
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/funman/parts/FunmanConfig.java

Increase funman logging to help debugging and to determine liveliness

verbose funman logging

---

packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue

5338 bug intervention marker label mispositioned in simulate node

---

packages/client/hmi-client/src/components/asset/tera-asset.vue
packages/client/hmi-client/src/components/widgets/tera-slider-panel.vue
packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue
packages/client/hmi-client/src/types/Types.ts
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/gollm/GoLLMController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/model/Model.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/modelparts/ModelSemantics.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/modelparts/semantics/OdeSemantics.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ModelService.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/EnrichAmrResponseHandler.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/MdlToStockflowResponseHandler.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/SbmlToPetrinetResponseHandler.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/StellaToStockflowResponseHandler.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/TaskUtilities.java

5282 bug model from equations failure

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/TaskService.java

set prefetch count to 1

---

testing/manual/ensemble-simulate.md

Ensure that Cole and Jaehwan are able to run ensembles locally
Please do not approve until you have finished running locally!
I will update these more once we have updated UI and output
As for right now they are up to date!

minor update to simulate ensemble test

---

packages/client/hmi-client/src/components/widgets/tera-slider-panel.vue
packages/client/hmi-client/src/components/workflow/ops/funman/funman-operation.ts
packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-drilldown.vue

- notebook code can be used as a funman request
https://github.com/user-attachments/assets/8c5255f5-84c5-4775-840e-f83ba25af32c

funman notebook view

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/calibrate-ensemble-ciemss-operation.ts
packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/calibrate-ensemble-util.ts
packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-node-ciemss.vue

- Adding progress % to spinner
- Adding loss values
If you need files to use for testing I used default configs on the following two models and a sample dummy dataset
Please note that this is not necessarily the best use case to check the results. At the moment this is to ensure our functionality in the PR
[ensemble calibrate test dataset.csv](https://github.com/user-attachments/files/17650486/ensemble.calibrate.test.dataset.csv)
[Test SIR.json](https://github.com/user-attachments/files/17650495/Test.SIR.json)
[Giordano2020 - SIDARTHE model of COVID-19 spread in Italy.json](https://github.com/user-attachments/files/17650496/Giordano2020.-.SIDARTHE.model.of.COVID-19.spread.in.Italy.json)

Ensemble Calibrate - Intermediate Results

---

packages/client/hmi-client/src/assets/css/theme/designer/components/input/_terainput.scss

* gap variable names weren't updated

fix: tera-input padding fix

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/calibrate-ensemble-ciemss-operation.ts
packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/calibrate-ensemble-util.ts
packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-node-ciemss.vue

* Ensemble calibrate input UI update
https://github.com/user-attachments/assets/08fa3493-d325-4d84-b05f-810f7ed9f632

Calibrate ensemble inputs

---

packages/client/hmi-client/src/components/widgets/VegaChart.vue

https://github.com/user-attachments/assets/d9711c37-fae9-4dd1-9e5d-0318a00735c0
https://github.com/user-attachments/assets/cdfc3ee8-4fcb-4ee4-8868-ec85376760d7
Resolves #4757

Skip rendering the charts with unchanged chart spec

---

testing/manual/stratify-notebook.md

Include more detailed tests involving strata interacting selectively and whether to stratify or preserve certain states and parameters.

Update stratify-notebook.md to include more detailed tests of features

---

packages/client/hmi-client/src/assets/css/style.scss
packages/client/hmi-client/src/components/drilldown/tera-drilldown-header.vue
packages/client/hmi-client/src/components/extracting/tera-drag-n-drop-importer.vue
packages/client/hmi-client/src/components/operator/tera-operator-placeholder.vue
packages/client/hmi-client/src/components/project/tera-upload-project-modal.vue
packages/client/hmi-client/src/components/project/tera-upload-resources-modal.vue
packages/client/hmi-client/src/components/widgets/tera-common-modal-dialogs.vue
packages/client/hmi-client/src/components/widgets/tera-pdf-panel.vue
packages/client/hmi-client/src/components/widgets/tera-toggleable-input.vue
packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/model-comparison/tera-model-comparison.vue
packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue
packages/client/hmi-client/src/page/Home.vue

Bunch of small tweaks here.
--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
---------------------------------------------------------------------------- …

Jamie style updates nov 14

---

packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-node.vue
packages/client/hmi-client/src/types/Types.ts
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/funman/FunmanController.java

Increase Funman's time out to give it a better chance to finish, and better handling of situations when timeout happens

improve interactions when Funman times out

---

packages/client/hmi-client/src/components/documents/tera-extractions.vue
packages/client/hmi-client/src/components/model/petrinet/tera-initial-table.vue
packages/client/hmi-client/src/components/model/petrinet/tera-parameter-table.vue
packages/client/hmi-client/src/components/model/regnet/tera-regnet-parts.vue
packages/client/hmi-client/src/components/model/stockflow/tera-stockflow-parts.vue
packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/model-comparison/tera-model-comparison.vue
packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue

* make all accordion indicies refs

make all accordian incidices refs

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/mira/DKG.java

set null values as empty strings

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-drilldown.vue

* Fast/precise presets to quickly configure funman
* Made `requestParameters` part of the `BasicKnobs`
* parameters that should be part of the presets are determined in `setRequestParameters()`
https://github.com/user-attachments/assets/b5b18865-f6e2-414f-9a82-38d6a8f8c1a6

feat: preset configs for funman

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ModelService.java

This needs to be fixed long run.

Update ModelService to not run DKG search

---

packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue

- forgot to put `.value` since `pyciemssMap` is a ref/computed

fix data table in simulate

---

packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-static-intervention-policy-group.vue

Fix typo "closet"

---

packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss-drilldown.vue
testing/manual/ensemble-simulate.md

- Minor updates to ensemble simulate test file
- Add save for reuse to the ensemble simulate drilldown

Minor ensemble simulate updates

---

testing/manual/project-collaboration.md

* Manual testing of project collaboration amongst at least two simultaneous users
Resolves #5527

Add project collaboration manual test

---

packages/client/hmi-client/src/components/drilldown/tera-drilldown-header.vue
packages/client/hmi-client/src/components/navbar/tera-navbar.vue

Change copy from `Documentation` to `Help`

Documentation to help

---

packages/client/hmi-client/src/components/drilldown/tera-drilldown-header.vue
packages/client/hmi-client/src/components/navbar/tera-navbar.vue
packages/client/hmi-client/src/page/Home.vue

Simplify the hero banner to be tigher and simpler.

clean up the hero banner

---

packages/gollm/gollm_openai/tool_utils.py
packages/gollm/tasks/embedding.py
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/DKGController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/TerariumAssetEmbeddings.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/DKGService.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ModelService.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/elasticsearch/ElasticsearchService.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/gollm/EmbeddingService.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/TaskUtilities.java

* Significant improvement on generating embeddings for enrichment
Resolves #5634

5634 bulk embeddings generation

---

packages/client/hmi-client/src/components/project/tera-resource-sidebar.vue
packages/client/hmi-client/src/page/tera-project.vue

Remove "+ new model" in resource panel
Closes https://github.com/DARPA-ASKEM/terarium/issues/5576

remove new-model button from resource panel

---

testing/manual/project-export-import.md

Testing steps for project export/import
- Simple workflow involving simulate
- Simple workflow involving data-transform

project export/import test

---

packages/client/hmi-client/src/types/Project.ts

Remove notebook-session and project from ressource panel

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/ExtractionService.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/DKGService.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ProjectSearchService.java

add protections for embedding services

---

packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue

*ability to clear the temporal context in model configuration
https://github.com/user-attachments/assets/599bf643-ca1c-4352-a70b-7d441735b900

clear date button

---

packages/client/hmi-client/src/components/dataset/tera-dataset.vue

* This completely works but there is probably some backend work to do in terms of base64 stuff
https://github.com/user-attachments/assets/d81f9da6-b394-4867-b8d8-06fc318b527b

edit dataset description

---

packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue

Fixed issue the baseline doesn't show up in the simulate node

---

packages/client/hmi-client/src/components/workflow/ops/model-edit/tera-model-edit-drilldown.vue

new model edit prompt for adding time property to a model

new model edit prompt

---

packages/client/hmi-client/src/components/workflow/ops/model-comparison/tera-model-comparison.vue
packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/model-edit/tera-model-edit-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratify-drilldown.vue
packages/client/hmi-client/src/model-representation/service.ts

disable run if there is no code in notebook

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/calibrate-utils.ts
packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/calibrate-ensemble-util.ts
packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
packages/client/hmi-client/src/composables/useCharts.ts
packages/client/hmi-client/src/services/charts.ts

Ensemble calibrate error charts

---

packages/client/hmi-client/src/components/workflow/ops/model-comparison/tera-model-comparison.vue
packages/gollm/gollm_openai/prompts/model_meta_compare.py
packages/gollm/gollm_openai/tool_utils.py
packages/gollm/tasks/compare_models.py

fix broken compare models prompt

---

packages/client/hmi-client/src/components/workflow/scenario-templates/sensitivity-analysis/sensitivity-analysis-scenario.ts

* initialize sensitivity charts from sensitivity analysis template

init sensitivity chart settings

---

packages/client/hmi-client/src/utils/ortho-router.ts

Remove redundant call and minor clean up

clean up ortho edge router

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/TaskService.java

Remove exclusive queue

---

packages/client/hmi-client/src/components/extracting/tera-drag-n-drop-file-previewer.vue
packages/client/hmi-client/src/components/extracting/tera-drag-n-drop-importer.vue

There was an ugly bug when drag & dropping files to upload. This fixes that.
**BEFORE**
**AFTER**

Jamie fix upload container resize bug

---

packages/client/hmi-client/src/components/workflow/ops/compare-datasets/compare-datasets-operation.ts
packages/client/hmi-client/src/components/workflow/ops/compare-datasets/tera-compare-datasets-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-drilldown.vue
packages/client/hmi-client/src/services/charts.ts

- use the forecast chart to plot the simulate comparisons
- add output settings
- clean up code for calculating differences between simulations

Improve compare simulation charts

---

packages/client/hmi-client/src/components/workflow/ops/compare-datasets/tera-compare-datasets-drilldown.vue

rm prefix on simulation compare labels

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
packages/client/hmi-client/src/composables/useCharts.ts

Apply log scale option/logic to 
- calibrate
- optimize
- ensemble-calibrate

Patch graph log scale

---

packages/client/hmi-client/src/components/widgets/tera-chart-settings.vue
packages/client/hmi-client/src/components/widgets/tera-input-number.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
packages/client/hmi-client/src/composables/useChartSettings.ts
packages/client/hmi-client/src/composables/useCharts.ts
packages/client/hmi-client/src/services/chart-settings.ts
packages/client/hmi-client/src/services/charts.ts
packages/client/hmi-client/src/types/common.ts

* Added a new sensitivity line chart
* 7 colour quantiles
* There was some _hacking_ to make this work with the chart settings.  Each chart setting has its own parameters and timepoint but for now the controls use the first setting's parameters and timepoint and updates every chart setting with the selected parameters and timepoint.
* using the forecast chart to plot here, but some conditional logic was needed if there was bins.  It _might_ be worth it to make this it's own chart
* Polishing is needed, but this is wanted before the demo
https://github.com/user-attachments/assets/104f6590-825e-4f78-ba9f-cb5d476e8d5b

new sensitivity line chart

---

packages/client/hmi-client/src/components/workflow/ops/model-comparison/tera-model-comparison.vue

https://unchartedsoftware.slack.com/archives/C06FGLXB2CE/p1734440632859299

Fix issue where GoLLM Model Comparison response is not properly formatted

---

packages/client/hmi-client/src/components/workflow/scenario-templates/decision-making/tera-decision-making-template.vue
packages/client/hmi-client/src/components/workflow/scenario-templates/horizon-scanning/tera-horizon-scanning-template.vue
packages/client/hmi-client/src/components/workflow/scenario-templates/sensitivity-analysis/tera-sensitivity-analysis-template.vue
packages/client/hmi-client/src/components/workflow/scenario-templates/situational-awareness/tera-situational-awareness-template.vue
packages/client/hmi-client/src/components/workflow/scenario-templates/value-of-information/tera-value-of-information-template.vue

Address some bugs/improvements raised and attached the tickets:
* outputs now show the id on the label rather than the name to identify them uniquely
* parameters in some templates are sorted alphabetically and can be searched

scenario template improvements

---

packages/client/hmi-client/src/components/widgets/VegaChart.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
packages/client/hmi-client/src/composables/useChartSettings.ts
packages/client/hmi-client/src/composables/useCharts.ts
packages/client/hmi-client/src/services/chart-settings.ts
packages/client/hmi-client/src/services/charts.ts

Some improvements for sensitivity charts
* Can now plot observables in sensitivity line chart (was missing the translationMap)
* Default to max timepoint for sensitivity charts
* Using the tooltipFormatter for the label values
* Move chart expression functions from component -> `chart.ts`

sensitivity improvements

---

packages/client/hmi-client/src/components/model/model-parts/tera-model-part-entry.vue
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ModelService.java

* add time if it is not present when creating a model
* small css fix so that you can see the unit changer when the screen is smaller

add a time on model creation

---

packages/client/hmi-client/src/components/workflow/scenario-templates/horizon-scanning/tera-horizon-scanning-template.vue

From: how does extreme scenarios ...
To: How do extreme scenarios ...

Smallest PR you will approve - Horizon scanning template grammar

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue

- reduce complexity in run button being disabled
- add tooltips for user to understand why it is disabled

Adding disabled run button tooltips to calibrate

---

packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue

Design Change:
- change split button to a button and radio button

change switch button to toggle

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/project/Project.java

[BUG]: 400 on project import #5838

---

packages/client/hmi-client/src/assets/css/style.scss
packages/client/hmi-client/src/components/dataset/tera-dataset-jupyter-panel.vue
packages/client/hmi-client/src/components/operator/tera-operator-output-summary.vue
packages/client/hmi-client/src/components/widgets/tera-chart-settings-item.vue
packages/client/hmi-client/src/components/widgets/tera-chart-settings-panel.vue
packages/client/hmi-client/src/components/widgets/tera-chart-settings.vue
packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-node-ciemss.vue
packages/client/hmi-client/src/components/workflow/ops/compare-datasets/tera-compare-datasets-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/compare-datasets/tera-criteria-of-interest-card.vue
packages/client/hmi-client/src/components/workflow/ops/dataset-transformer/tera-dataset-transformer-node.vue
packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/model-edit/tera-model-edit-node.vue
packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-node.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue
packages/client/hmi-client/src/components/workflow/ops/regridding/tera-regridding-node.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-node-ciemss.vue
packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratify-node.vue
packages/client/hmi-client/src/components/workflow/tera-chart-control.vue
packages/client/hmi-client/src/components/workflow/tera-workflow.vue

All the usual, styling tweaks and whatnot. Too much to list here, all of minor consequence. :)

Jamie misc papercuts near end of year

---

packages/client/hmi-client/src/components/widgets/tera-chart-settings.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue
packages/client/hmi-client/src/components/workflow/scenario-templates/sensitivity-analysis/sensitivity-analysis-scenario.ts

* Pre-select parameters for sensitivity analysis when creating from template
* select last timepoint after run is finished

Default select sensitivity parameters

---

packages/client/hmi-client/src/components/widgets/tera-chart-settings.vue

* remove duplicate label in chart settings, seems to have been a merge conflict that wasnt resolved correctly

fix duplicate label

---

packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue

Only process result for main run not base run.

Simulation 1 output for 1 run 

---

packages/client/hmi-client/src/components/workflow/tera-workflow.vue
packages/client/hmi-client/src/services/workflow.ts
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/WorkflowService.java

Reverts DARPA-ASKEM/terarium#5848
Currently we are running into workflow sync issues.
We can hope that reverting this solves the ones we are running into while potentially introducing some older ones

Revert "simplify collab/sync"

---

packages/client/hmi-client/src/components/workflow/scenario-templates/horizon-scanning/tera-horizon-scanning-template.vue
packages/client/hmi-client/src/components/workflow/scenario-templates/value-of-information/tera-value-of-information-template.vue

* text change for scenario templates as requested

template text change

---

packages/client/hmi-client/src/services/chart-settings.ts

Fixed issue that annotation wasn't added properly

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/LatexToSympyResponseHandler.java
testing/manual/model-configuration-extracting-variables.md

Fix knowledge controller to work with gollm task

---

packages/client/hmi-client/src/services/dataset.ts

Fixing issues with the new Dataset statistics.

Remove unused functions

---

packages/client/hmi-client/src/components/dataset/tera-dataset-datatable.vue
packages/client/hmi-client/src/types/Types.ts
packages/gollm/tasks/dataset_statistics.py
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/dataset/DatasetColumnStats.java

Issues with the pandas stats created by LLM.
Fixing binning to be a proper representation.
FROM
TO

better distribution

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/model/configurations/InferredParameterSemantic.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/model/configurations/InitialSemantic.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/model/configurations/ObservableSemantic.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/model/configurations/ParameterSemantic.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/model/configurations/Semantic.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/modelparts/ModelParameter.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/modelparts/semantics/Observable.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/modelparts/semantics/State.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/modelparts/semantics/Transition.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/regnet/RegNetVertex.java

clean up compiler warnings

---

packages/client/hmi-client/src/components/workflow/ops/compare-datasets/compare-datasets-utils.ts
packages/client/hmi-client/src/composables/useCharts.ts

Plot samples on the chart

---

packages/client/hmi-client/src/components/workflow/scenario-templates/situational-awareness/tera-situational-awareness-template.vue

Fixed the typo described in #5961

fixed typo

---

packages/client/hmi-client/src/components/widgets/VegaChart.vue
packages/client/hmi-client/src/components/widgets/tera-csv-table.vue
packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/model-comparison/tera-model-comparison-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-configuration-item.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/scenario-templates/horizon-scanning/tera-horizon-scanning-template.vue
packages/client/hmi-client/src/components/workflow/scenario-templates/value-of-information/tera-value-of-information-template.vue

Jamie monday night papercuts

---

packages/client/hmi-client/src/components/workflow/ops/funman/tera-constraint-group-form.vue
packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-drilldown.vue

Updated text description of "Validate configuration" operator, as per #6014
Also took the opportunity to adjust some styling in the operator.

update text and adjust styling

---

packages/gollm/common/prompts/latex_style_guide.py

* Selectively expand algebraic expressions (only those with state variables -> avoids broken models)
* Do not expand those with just constants (try to retain terms like `(1 - c) * S(t)`) 
* Handle non-parenthesis brackets that show up

Update LaTeX style guide to deal with brackets

---

packages/client/hmi-client/src/components/model/petrinet/model-configurations/tera-stratified-matrix-modal.vue
packages/client/hmi-client/src/components/model/petrinet/model-configurations/tera-stratified-matrix.vue
packages/client/hmi-client/src/components/widgets/tera-modal.vue
packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue

* Filter rows and columns
* Changed keys to be the row/col number instead of the index
* Fixed matrix scrolling
https://github.com/user-attachments/assets/f23309d6-a3e7-4e0c-9377-20801f740be9

filter rows and columns in matrix

---

packages/client/hmi-client/src/components/workflow/scenario-templates/model-from-literature/model-from-literature-scenario.ts
packages/client/hmi-client/src/components/workflow/scenario-templates/model-from-literature/tera-model-from-literature-template.vue

* Fixes a couple issues with the model from literature scenario:
1. Can make a scenario with only 1 document selected (now hides goal if this is the case)
2. Edge misplacement fix, I needed to set the output value for this to work

model from literature fix

---

packages/client/hmi-client/src/components/workflow/scenario-templates/decision-making/decision-making-scenario.ts

Manual layout heuristic for decision-making scenario

layout for decison-making scenario

---

packages/gollm/common/prompts/dataset_enrichment.py
packages/gollm/schemas/dataset_enrichment.json
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/document/DocumentAsset.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/EnrichDatasetResponseHandler.java

fix issue where LLM makes up information when enriching datasets

---

packages/client/hmi-client/src/components/workflow/scenario-templates/value-of-information/value-of-information-scenario.ts

value of information layout, based on latest tweaks from https://github.com/DARPA-ASKEM/terarium/pull/6054
Layout-wise, this is identical to that of of `Decision making` template.

value of information layout

---

packages/client/hmi-client/src/components/workflow/scenario-templates/horizon-scanning/horizon-scanning-scenario.ts

Rectangular grid like with model-config rows and intervention-columns (if applicable)

horizon scanning layout

---

packages/client/hmi-client/src/components/workflow/scenario-templates/model-from-literature/model-from-literature-scenario.ts

Attach Document node to Model Config node(s) in the model from  literature template

attach document to model config node(s) in model from literature template

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/gollm/DatasetStatistics.java

Fix issue with simulate

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/TaskService.java

remove logging raw message in case it is very large

---

packages/client/hmi-client/src/components/model/petrinet/model-configurations/tera-stratified-matrix.vue

* The input fields expect a string and we used to be passing numbers to it when pasting into the matrix
* Passing strings now
https://github.com/user-attachments/assets/61a45ba3-ba95-4b39-9ee0-3568add24d84

have tera-input accept new values pasted in stratified matrix

---

packages/client/hmi-client/src/components/model/model-parts/tera-model-part-entry.vue
packages/client/hmi-client/src/components/model/petrinet/tera-petrinet-parts.vue

* new values from model enrichment need to be watched for the input fields to update

watch for `unitExpression` and `name` changes in `tera-model-part-entry`

---

packages/gollm/common/prompts/config_from_document.py

improved config from document prompt

---

packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-node-ciemss.vue

- Update Simulate ensemble poller to be more up to date.
- This allows us to not have looping outputs (see issue's ticket https://github.com/DARPA-ASKEM/terarium/issues/6106)
Should be able to run normally and have 1 output

Bug Fix - Simulate Ensemble 1 run is 1 output

---

packages/client/hmi-client/src/assets/css/theme/designer/components/input/_terainput.scss
packages/client/hmi-client/src/components/dataset/tera-column-info.vue
packages/client/hmi-client/src/components/drilldown/tera-drilldown-section.vue
packages/client/hmi-client/src/components/model/model-parts/tera-model-part-entry.vue
packages/client/hmi-client/src/components/widgets/tera-slider-panel.vue
packages/client/hmi-client/src/components/workflow/ops/intervention-policy/intervention-policy-operation.ts
packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-card.vue
packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-node.vue
packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratify-drilldown.vue
packages/client/hmi-client/src/services/intervention-policy.ts

[added max number of interventions and "+ 2 more" indicator](https://github.com/DARPA-ASKEM/terarium/commit/f6f9b8ebc27384387842165fb7a92ec3e3f97a78)
[proper fix of Stratify input column width](https://github.com/DARPA-ASKEM/terarium/commit/c884cf4041dd4ec6f9248ca37d6d48867176a45d)

Jamie jan 21 design tweaks

---

packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-drilldown.vue
packages/client/hmi-client/src/services/models/funman-service.ts
packages/client/hmi-client/src/types/common.ts

Bug:
- Observable chart in the validation configuration drill down was not appearing
Testing:
- create a model configuration with a observable
- connect node to a validation configuration node
- add constraint using observable and run
- observable chart & setting should appear

Observable Chart missing

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/workflow/OutputPort.java

Fixing exporting of projects with legacy workflows

---

packages/client/hmi-client/src/components/workflow/ops/compare-datasets/compare-datasets-utils.ts
packages/client/hmi-client/src/services/charts.ts

* fix some category issues that Pascale pointed out
Before
After

fix categorization of ranking results

---

testing/kraken/profiles/forecaster.py

A forecaster that makes random forecast simulation requests
eg spin up two forecasters
```
python kraken.py forecaster:2
```

stress test forecaster profile

---

packages/client/hmi-client/src/components/widgets/tera-chart-settings-panel.vue
packages/client/hmi-client/src/components/widgets/tera-slider-panel.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue

[fix visual gaffe when slider panel is closed (eg., Config & Intervent…](https://github.com/DARPA-ASKEM/terarium/commit/319d703a853033b9db070534960559f87b303624) 
[fix height issue better this time](https://github.com/DARPA-ASKEM/terarium/commit/be9b2272ee2bf997ad52506a3d4494400970995b)
[fixed issue with chart settings panel placement when invoked from bottom](https://github.com/DARPA-ASKEM/terarium/commit/89fa826d4367cf3ee9f82f33005d35aef38bcfae)

Jamie jan 23 design tweaks

---

packages/client/hmi-client/src/components/workflow/tera-workflow-annotation.vue
packages/client/hmi-client/src/components/workflow/tera-workflow.vue

styled the workflow annotations (aka text block)

---

packages/client/hmi-client/src/components/workflow/ops/compare-datasets/compare-datasets-operation.ts
packages/client/hmi-client/src/components/workflow/ops/compare-datasets/compare-datasets-utils.ts
packages/client/hmi-client/src/components/workflow/ops/compare-datasets/tera-criteria-of-interest-card.vue

* adjust meaning of ranking option

Fix overall option in ranking

---

packages/client/hmi-client/src/components/workflow/scenario-templates/model-from-literature/tera-model-from-literature-template.vue

This is a one line PR, addressing an issue Pascale sent me this morning via Slack:
I added the autoResize tag to the Textarea.

enable autoResize on Textarea component

---

packages/client/hmi-client/src/services/charts.ts

Changed "other" to "(baseline)"
https://github.com/user-attachments/assets/645192c6-bde6-4d50-bbbd-971cf264f8b9
Resolves #6220

changed "other" to "(baseline)"

---

packages/client/hmi-client/src/components/workflow/tera-workflow.vue

Closes: https://github.com/DARPA-ASKEM/terarium/issues/6195
This PR address a particular problem with scenario-templates where we leave the edge points as `(0, 0)` in their construction. 
While these edge are automatically adjusted when the workflow is loaded, it runs into the problem that we don't really know when the workflow, as a whole, has finished loading all of its operators. So we cannot determine exactly when the edge positions have settled down, and in turn we don't exactly know when the workflow is ready to be written back with updated edge-positions. 
With the current relinkEdge implementation, there are some optimization to both use the edge-positions in the workflow, and also recalculate positions based on the current DOM. So it is possible to pick up 0s and that ends up …

rework relink-edge

---

packages/client/hmi-client/src/components/workflow/ops/tera-node-preview.vue

* Fixes charts not showing for Compare Datasets node.
Resolves #6160

fix missing charts in compare datasets node

---

packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue

6218 bug charts missing in sensitivity analysis

---

packages/client/hmi-client/src/components/workflow/ops/tera-node-preview.vue

Remove dangling s from bottom of node-preview

---

packages/client/hmi-client/src/components/drilldown/tera-drilldown-section.vue
packages/client/hmi-client/src/components/workflow/ops/funman/funman-operation.ts
packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-node.vue

Design Change:
- display message if funman process % has been stuck on a process for over 5mins

User warning message for validate config

---

packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue

added text blurb

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/DocumentAssetService.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ModelService.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ProjectSearchService.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/TerariumAssetServiceWithSearch.java

* Temporary fix for performance issue. Disabling embeddings for now.
Resolves #6294

Temporary fix for performance issue. Disabling embeddings for now.

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/s3/DownloadStaticESIndexService.java
packages/server/src/main/resources/application.properties

link to new DKG index

---

packages/gollm/common/prompts/amr_enrichment.py

updated amr enrichment prompt to include stratification information

---

packages/client/hmi-client/src/components/widgets/tera-chart-settings-panel.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
packages/client/hmi-client/src/composables/useCharts.ts
packages/client/hmi-client/src/services/model.ts

Display normalize equations on the chart setting panel

---

packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
packages/client/hmi-client/src/composables/useCharts.ts
packages/client/hmi-client/src/python/PyodideController.ts
packages/client/hmi-client/src/python/PyodideWorker.ts
packages/client/hmi-client/src/services/charts.ts

* Sensitivity ranking score charts
https://github.com/user-attachments/assets/6f3ad987-177f-4390-8543-4cd07e197fba

Sensitivity ranking score charts

---

packages/client/hmi-client/src/components/model/petrinet/tera-parameter-table.vue
packages/client/hmi-client/src/components/workflow/ops/compare-datasets/tera-compare-datasets-drilldown.vue

Pascale sent me this papercut this morning
It's a pain to have to select lots of children manually.

added a checkbox with indeterminate status to stratified parameter parents

---

packages/client/hmi-client/src/router/index.ts
packages/client/hmi-client/src/temp/SympyAMR.vue
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/TaskService.java

Nelson and Pascale improved debugging interface for doing sympy code to AMR

Sympy backdoor

---

packages/client/hmi-client/src/components/workflow/ops/model-edit/tera-model-edit-drilldown.vue

Grabbing the configured model instead of the base model when given a model config for model edit.

[TASK]: Use configured model in model edit

---

packages/client/hmi-client/src/services/graph.ts

further reduce graph ortho threshold

further reduce

---

packages/client/hmi-client/src/components/model/model-parts/tera-model-part-entry.vue

Issue:
- On large Models, updating Parameters/Initials can take a long time to display input

input delay

---

packages/client/hmi-client/src/components/model/model-parts/tera-model-part-entry.vue
packages/client/hmi-client/src/components/model/petrinet/tera-initial-entry.vue
packages/client/hmi-client/src/components/model/petrinet/tera-initial-table.vue
packages/client/hmi-client/src/components/model/petrinet/tera-parameter-entry.vue
packages/client/hmi-client/src/components/model/petrinet/tera-parameter-table.vue
packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-node-ciemss.vue
packages/client/hmi-client/src/components/workflow/ops/compare-datasets/tera-compare-datasets-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-configuration-item.vue
packages/client/hmi-client/src/components/workflow/ops/model-edit/tera-model-edit-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-node.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-node-ciemss.vue
packages/client/hmi-client/src/components/workflow/ops/stratify-mira/stratify-mira-operation.ts
packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratify-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratify-node.vue
packages/client/hmi-client/src/components/workflow/tera-workflow-annotation.vue
packages/client/hmi-client/src/composables/useCharts.ts
packages/client/hmi-client/src/services/charts.ts
packages/client/hmi-client/src/services/graph.ts
packages/client/hmi-client/src/services/jupyter.ts
packages/client/hmi-client/src/utils/stats.ts
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ModelConfigurationService.java

merge 2.31.5 back into main

---

packages/client/hmi-client/src/components/model/petrinet/tera-distribution-input.vue

Disabled pop-up 
Issue:
- Popup does not disappear when expected.

Disable popup

---

packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue
packages/client/hmi-client/src/utils/clipboard.ts

Requested by users for the eval
https://github.com/user-attachments/assets/401cef0d-5152-4b6d-88b4-9f11ddced623

Download equations

---

packages/mira/tasks/sympy_to_amr.py

Changes default template names

---

packages/client/hmi-client/src/composables/useCharts.ts
packages/client/hmi-client/src/services/charts.ts

Fixed the bug that 'share y axis' doesn't work with the quantile charts

Fixed the bug that 'share y axis' doesn't work with the quantile charts

---

packages/client/hmi-client/src/model-representation/mira/mira.ts
packages/client/hmi-client/src/services/graph.ts

- Pascale would like the group numbering to start at 0 instead 1.
- Small comment cleanups

Start transition aggregate group at 0 instead of 1

---

packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-drilldown.vue
packages/client/hmi-client/src/services/calibrate-workflow.ts

* Wrong prop format for observables was passed to `tera-model-part` which was preventing the rest of the UI to be functional (notebook tab wasn't showing raw output)
Wizard:
Notebook:

Fix notebook view in funman

---

packages/client/hmi-client/src/components/widgets/tera-chart-settings-panel.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
packages/client/hmi-client/src/composables/useChartSettings.ts
packages/client/hmi-client/src/composables/useCharts.ts
packages/client/hmi-client/src/services/chart-settings.ts
packages/client/hmi-client/src/services/charts.ts

- Fix issue that picked colors get reset when changing selected variables
- Some clean ups

Fixes issue that color is resetting

---

README.md

Update with instruction to run individual server unit tests

instruction to run single server test

---

packages/client/hmi-client/src/components/widgets/tera-chart-settings.vue
packages/client/hmi-client/src/components/workflow/ops/stratify-mira/tera-stratification-group-form.vue

* Can now search for parameters in stratify and sensitivity chart paramarter dropdowns

filter parameter selection in stratify and simulate drilldown

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue

- Add save for reuse to calibrate ensemble.

Add save for reuse to calibrate ensemble

---

packages/client/hmi-client/src/components/model/petrinet/tera-model-description.vue
packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue

* Open the description by default on the model page.
Resolves #6337

6337 bug after enriching from create model from equations the descriptions should be expanded like before

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/compare-datasets/compare-datasets-utils.ts

- Ensemble calibrate flooding warnings on workflow fix
- Compare dataset should have error when dataset is not a simulation

Minor warning fixes

---

packages/client/hmi-client/src/model-representation/petrinet/mira-petri.ts
packages/client/hmi-client/src/router/index.ts
packages/client/hmi-client/src/router/routes.ts

clean up unused code fragments

---

packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-drilldown.vue
packages/client/hmi-client/src/composables/useChartSettings.ts

- Clean up some charts stuff from funman drilldown.
- No behaviour change is expected.

Cleanup chart related stuff from funman drilldown

---

testing/manual/model-error.md

manual testing notes for exercising ability to detect model errors

model error detection test notes

---

packages/client/hmi-client/src/components/widgets/tera-chart-settings.vue
packages/client/hmi-client/src/components/widgets/tera-sensitivity-chart-settings.vue
packages/client/hmi-client/src/types/SimulateConfig.ts

* Mad libs selection for the sensitivity output

select sensitivity outputs in a madlibs way

---

containers/scripts/docker-compose-data-services.yml

update data services docker compose file

---

packages/client/hmi-client/src/components/workflow/ops/model/tera-model-node.vue

fixes spinner warnings in the console

fix spinner warnings

---

packages/client/hmi-client/src/components/model/petrinet/tera-initial-entry.vue
packages/client/hmi-client/src/components/model/petrinet/tera-initial-other-value-modal.vue
packages/client/hmi-client/src/components/model/petrinet/tera-parameter-other-value-modal.vue
packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-card.vue
packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue

* Show 'Other Values' in the intervention policy operator
* Re-used the modals in model configuration but I am using a readonly prop so that we just see the table
https://github.com/user-attachments/assets/9d94c8a2-d84f-4275-80f0-c896afacb3e4

Show Other Values in the intervention policy operator

---

packages/client/hmi-client/src/components/widgets/tera-model-comparison-table.vue
packages/client/hmi-client/src/components/workflow/ops/model-comparison/tera-model-comparison-drilldown.vue

Add model names to concept comparison tables

---

.github/workflows/publish-equation-extraction-taskrunner.yml
.github/workflows/publish-funman-taskrunner.yml
.github/workflows/publish-gollm-taskrunner.yml
.github/workflows/publish-mira-taskrunner.yml
.github/workflows/publish-server.yml
.github/workflows/publish-table-extraction-taskrunner.yml
.github/workflows/publish-text-extraction-taskrunner.yml
.github/workflows/test-server.yaml
.github/workflows/test-taskrunner.yaml

replace Validate GradleW JAR with Setup Gradle

---

packages/client/hmi-client/src/components/widgets/tera-chart-settings-panel.vue
packages/client/hmi-client/src/composables/useCharts.ts
packages/client/hmi-client/src/services/charts.ts
packages/client/hmi-client/src/types/common.ts

- Clean up and refactor font configs and in chart.ts 
- Make font size configurable in the settings panel
Resolves #6679

Added font size setting in the settings panel

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/InterventionsFromDatasetResponseHandler.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/InterventionsFromDocumentResponseHandler.java

fix issue with interventions not being extracted

---

packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-node.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/optimize-ciemss-operation.ts
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/optimize-utils.ts
packages/client/hmi-client/src/components/workflow/scenario-templates/decision-making/decision-making-scenario.ts
packages/client/hmi-client/src/components/workflow/scenario-templates/horizon-scanning/horizon-scanning-scenario.ts
packages/client/hmi-client/src/components/workflow/scenario-templates/value-of-information/value-of-information-scenario.ts
packages/client/hmi-client/src/services/intervention-policy.ts
packages/client/hmi-client/src/types/Types.ts
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/simulationservice/interventions/Intervention.java

* fixes an issue with intervention policies where deleting an intervention card would cause some bugginess.
* we should not be using the array index as a key but instead this uuid

Fix intervention policy deletion

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ProjectController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ProjectService.java

*Locking down the project controller. This time the `#id` needs to be set specifically as the API expects `projectId` by default

6673 subtask 25 update project controller to use new permissions

---

packages/client/hmi-client/src/components/intervention-policy/tera-intervention-summary-card.vue
packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-card.vue
packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-policy-node.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/optimize-ciemss-operation.ts
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-dynamic-intervention-policy-group.vue
packages/client/hmi-client/src/types/Types.ts
packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/simulationservice/interventions/DynamicIntervention.java

* Similar to static intervention, we are now supporting percentage for dynamic interventions
Need to merge the corresponding pyciemss ticket as well: https://github.com/DARPA-ASKEM/pyciemss-service/pull/141

dynamic intervention percentage support

---

packages/gollm/common/prompts/interventions_from_dataset.py
packages/gollm/common/prompts/interventions_from_document.py
packages/gollm/schemas/intervention_policy.json
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/InterventionsFromDatasetResponseHandler.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/InterventionsFromDocumentResponseHandler.java

* @liunelson  noticed this issue when extracting from a dataset.  The intervention policy data structure in gollm needed to be updated to accomodate the structure with percentages

intervention policy extration fix

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/utils/GreekDictionary.java

* Was missing the uppercase letters

Update GreekDictionary.java to include uppercase Greek letters

---

packages/client/hmi-client/src/components/workflow/tera-workflow.vue

Decrease the state update/sync frequency so modeller that does a lot of interactions with a short period of time has less chance of getting interrupted by their own state changes.

attemp to decrease state-sync disruption onto itself

---

packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue

Add preset 'example' equations that can be added to a model bullt via 'Create Model from Equations'
Resolves #6809

feat: Add LaTeX equations from presets #6809

---

packages/client/hmi-client/src/components/widgets/tera-asset-enrichment.vue
packages/client/hmi-client/src/components/workflow/ops/dataset/tera-dataset-node.vue
packages/client/hmi-client/src/components/workflow/ops/model/tera-model-node.vue
packages/client/hmi-client/src/composables/useClientEvent.ts

* Fixes enrich dataset with document
Resolves #6685

6685 bug enrich dataset fail with document

---

packages/client/hmi-client/src/components/model/model-parts/tera-model-part-entry.vue
packages/client/hmi-client/src/components/model/petrinet/tera-petrinet-parts.vue
packages/client/hmi-client/src/components/model/tera-model.vue
packages/client/hmi-client/src/components/widgets/tera-asset-block.vue
packages/client/hmi-client/src/components/workflow/ops/model-from-equations/model-from-equations-operation.ts
packages/client/hmi-client/src/components/workflow/ops/model-from-equations/model-from-equations-utils.ts
packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/model-from-equations/tera-model-from-equations-node.vue
packages/client/hmi-client/src/model-representation/service.ts
packages/client/hmi-client/src/utils/text.ts
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/EnrichModelResponseHandler.java

* Review enrichments in the model from equations tab

HITL verificiation review enrichments

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/utils/GreekDictionary.java

* Somehow, "Kappa" causes problems so removing that line
Resolves #6819

Update GreekDictionary.java - Removed duplicate Kappa

---

.github/CODEOWNERS
packages/client/hmi-client/src/components/workflow/ops/model-from-equations/model-from-equations-utils.ts

Some linting error pass-through our CI, and it's poluting our PRs.

Tiny issue to remove typo

---

packages/client/hmi-client/src/components/model/petrinet/tera-initial-entry.vue
packages/client/hmi-client/src/components/model/petrinet/tera-parameter-entry.vue
packages/client/hmi-client/src/components/workflow/ops/intervention-policy/tera-intervention-card.vue

Change model button from `Other Values` to `Configuration Values`.
Resolves #6827

Change from `Other Values` to `Configuration Values`

---

packages/client/hmi-client/src/components/workflow/ops/model-from-equations/model-from-equations-utils.ts
packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/gollm/GoLLMController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/EnrichModelResponseHandler.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/TaskUtilities.java

* Clean up things around.
* Make sure we do not overwrite stratification information during Grounding.
Resolves #6824

6824 bug enriching a model can break the model

---

packages/client/hmi-client/src/components/workflow/ops/compare-datasets/compare-datasets-utils.ts
packages/client/hmi-client/src/components/workflow/ops/compare-datasets/tera-compare-datasets-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/compare-datasets/tera-compare-datasets-node.vue
packages/client/hmi-client/src/composables/useCharts.ts
packages/client/hmi-client/src/services/charts.ts
packages/client/hmi-client/src/services/models/simulation-service.ts

- Show dates for the quantile charts
- Show dates for the compare dataset operator charts

Show dates in the x axis on the comparable datasets charts

---

packages/client/hmi-client/src/components/model/tera-model.vue

The save button could still be disable because the temporaryValue might not be set properly.
So I bypassed the ref of a ref to set the temporaryValue to whatever the server returns directly.

Issue with Model asset save button

---

packages/client/hmi-client/src/model-representation/service.ts
packages/client/hmi-client/tests/unit/model-representation/service.spec.ts

- Address async issues in forEach
- Add time id to list of available symbols
- Add check where a parameter may be misidentified as a state

Improve model check

---

testing/manual/model-error.md

Update testings notes for
- state/parameter misclassification
- model simplification

update testing notes for model-error

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DatasetController.java
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ProjectService.java

* The legacy permission call here thew an exception and we can't have that. Changing to new API

Fixing dataset access for users who only have read access to a project.

---

packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelConfigurationController.java
packages/server/src/test/resources/application-test.properties

This needs read permission not write
Resolves #6785

Fixing one more endpoint permissions

---

packages/gollm/tasks/enrich_dataset.py

Resolve python syntax errors. Linter.

fix enrich dataset python errors

---

packages/ocr_extraction/setup.py
packages/ocr_extraction/tasks/ocr_extraction.py

ocr-extraction runs as a web-service, this is the python taskrunner wrapper that invokes said service functions

python invocation wrapper for ocr-extraction

---

packages/client/hmi-client/src/components/model/petrinet/model-configurations/tera-stratified-matrix.vue

6480 feat dont show na in parameter matrix   the gray color is sufficient

---

packages/client/hmi-client/src/components/widgets/tera-common-modal-dialogs.vue

* Use correct reference to project.
* Set project name

Broken project copy on home page

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss-drilldown.vue

Remove unimplemented notebooks from ta3 operators
Remove notebook from simulate which was slightly more implemented but not really utilized

Remove jupyter from ta3 operators

---

packages/ocr_extraction/src/server.py

Copy and paste error from other docling sections

set table rawText to empty string, not provided in docling

---

packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/calibrate-utils.ts
packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/optimize-utils.ts
packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss-drilldown.vue
packages/client/hmi-client/src/services/charts.ts

Added quantiles charts to optimize and calibrate operators

---

packages/client/hmi-client/src/types/Types.ts
packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/ExtractionService.java

Missed a commit for https://github.com/DARPA-ASKEM/terarium/pull/6887 to stash userID and not timeout auth

missed commit https://github.com/DARPA-ASKEM/terarium/pull/6887

---

testing/manual/optimize.md

The last test will show a result that does not pass success criteria. This is okay as the scenario asked is impossible. Dan pointed out that we should make this more clear to testers for what we are looking for.

Update optimize manual test

---

packages/client/hmi-client/src/components/workflow/tera-workflow.vue

Set common state change save interval.  Increase sync interval to 2 sec.

fix: Checkboxes get unchecked #6900

---

packages/client/hmi-client/src/components/widgets/tera-pdf-panel.vue
packages/client/hmi-client/src/components/widgets/tera-pdf-viewer.vue
packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue
packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-configuration-item.vue

https://github.com/user-attachments/assets/47720257-3e8f-49f7-85ad-a47c8ea88fe3

Select and highlight extracted items in a corresponding pdf document in model config operator
