DARPA-ASKEM/terarium

- README.md
- packages/server/package.json
- packages/server/src/app.ts
- yarn.lock
Add docker build/run notes and koa support for doing POST request.
```
yarn dev
curl  -XPOST -H"Content-type: application/json"  http://localhost:3000/api/test-post -d '{"name": 333123}'
```
> docs,feat: docker notes and add support of post request

- .editorconfig
- .github/workflows/ci-test.yml
- package.json
- yarn.lock
Basic GitHub CI that is triggered on PR and direct pushes to main. Will be augmented or replaced with GitLab configuration once those runners are available.
resolves #14
> chore(ci): initial CI configuration for GitHub

- .github/CODEOWNERS
Update the glob matcher to also match at the root level. Appologies for the bot spam...
None
> chore: relax the glob matcher

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/task-request.md
Adding template for general development tasks based on designs or requirements that do not require a full feature
> chore: add task request template

- packages/client/webapp/src/App.vue
- packages/client/webapp/src/router/index.ts
- packages/client/webapp/tests/e2e/base.spec.ts
Enumerated route paths and add a condition to render sidebar if the current route is not home. 
Resolves #118 
> feat: hide sidebar on home view

- kubernetes/local/gateway-httpd-deployment.yaml
- kubernetes/local/gateway-keycloak-deployment.yaml
- kubernetes/local/gateway.sh
Use container images as built by the Uncharted-Auth CI
Additionally use Deployment versus Pod in Kubernetes files, Deployment allows for more options for future customization.
> build: use new gateway images

- .github/workflows/auto-labeler.yml
Automatically add labels to new and reopened issues if they match the specified format. i.e starts with [FEAT] or [TASK].
This can be expanded in the future as needed. Although issue templates are present they are not triggered when the issues are generated from the project board so this is just to add them if they are missing.
Manually testing with blank issue generator. If a template was used the label should already be present and this should be a noop
> ci: workflow for auto labelling issues

- .github/workflows/auto-labeler.yml
Amendment to previous PR that missed the quotes on the variable extraction, causing it to be a literal command.
Manually tested the output script
> chore: add missing quotes in workflow

- gradle.properties
Thank you renovate bot
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
> [fix]: update gradle.properties

- renovate.json
Reduce the bot frequency back to weekly.
None, its a revert to old schedule
> chore: reduce frequency of renovate bot to weekly

- .github/workflows/auto-labeler.yml
- .github/workflows/commitlint.yml
- .github/workflows/lint_test.yml
- .github/workflows/playwright.yml
- .github/workflows/publish.yaml
- .hadolint.yml
- .yamllint
Fixing a number of small script issues that was breaking the workflow. Added some lint check as well based on the workflows in Orchestration (these are linked by sha).
Future TODO is rework the publish bit with more reusable workflows but due to the required builds cant reuse the existing one directly.
Tested manually on branch by forcing a tag.
> ci: fix script issue and using some reusable workflow

- packages/client/hmi-client/src/views/TA2Playground.vue
> fix: fix bad variables in merge

- .github/workflows/auto-labeler.yml
- .github/workflows/lint-client.yml
- .github/workflows/lint.yml
- .github/workflows/publish.yaml
- .github/workflows/test-client-e2e.yml
- .github/workflows/test-client-unit.yml
- .github/workflows/test-client.yml
- package.json
- packages/client/hmi-client/package.json
Decompose CI Workflows into smaller modular chunks. 
Add type checking as one of the client linting steps.
Manual runs on PR
> ci: add typecheck and refactor ci

- .github/CODEOWNERS
- .github/CONTRIBUTING.md
* Remove k8 information, as this is all within the `orchestration` repo.
* Change the `CODEOWNERS` file to:
* reflect the new folder structure
* add @chris-dickson as full-access
* add @dvince2 for the backend services
> fix: remove k8 information

- .github/workflows/auto-labeler.yml
- .github/workflows/lint-client.yml
- packages/client/hmi-client/package.json
- packages/client/hmi-client/src/views/Simulation.vue
Various linting related issues
> fix: linter issue

- docs/cURL.md
- docs/curl-test-endpoint.sh.template
Instructions on testing an API endpoint using cURL instead of Postman
- [ √ ] New feature (non-breaking change which adds functionality)
> chore: curl instructions

- docs/curl-test-endpoint.sh.template
misordered statements, checking if URL has been set before assigning parameters.
> chore: correct cURL script

- packages/client/hmi-client/src/components/Sidebar.vue
- packages/client/hmi-client/src/components/sidebar-panel/documents-sidebar-panel.vue
Small styling changes to document sidebar.
https://user-images.githubusercontent.com/16358728/203389127-cdd670c2-e8f7-453b-bcb4-de09353499b7.mov
Resolves #163
> style: document sidebar styling

- packages/client/hmi-client/src/components/responsive-matrix/matrix-grid.fs.glsl.ts
- packages/client/hmi-client/src/components/responsive-matrix/matrix.vue
Add a procedurally generated grid overlay to the responsive matrix component.
Resolves #59
> feat: add grid overlay to responsive matrix (#59)

- packages/client/hmi-client/src/components/responsive-matrix/cell-bar-container.vue
- packages/client/hmi-client/src/components/responsive-matrix/cell-bar-graph.vue
- packages/client/hmi-client/src/components/responsive-matrix/cell-line-container.vue
- packages/client/hmi-client/src/components/responsive-matrix/cell-line-graph.vue
- packages/client/hmi-client/src/components/responsive-matrix/matrix.vue
- packages/client/hmi-client/src/types/ResponsiveMatrix.ts
Add bar chart and line chart drilldowns to the responsive matrix.
Resolves #59 
> feat: add bar and line chart drilldowns to responsive matrix (#59)

- packages/client/hmi-client/src/App.vue
- packages/client/hmi-client/src/components/Header.vue
- packages/client/hmi-client/src/components/Sidebar.vue
- packages/client/hmi-client/src/services/project.ts
- packages/client/hmi-client/src/views/Project.vue
Change where and how we fetch the information about a project:
- Created the `sevice/projects.ts` to handle API call and everything related to Project manipulation.
- Now the call is made in `App.vue`, as this is only made once in the app.
- The Project is passed as a prop to all views
- All handled via the URL
- Updated the Header to display the proper name
- Make the sidebar closed by default
https://user-images.githubusercontent.com/636801/204052860-48e76b75-3d6a-4950-ae96-339c06b22332.mov
> feat: header fix

- packages/client/hmi-client/src/App.vue
- packages/client/hmi-client/src/services/project.ts
* Fix an issue where the Project API was not call on start
* Added a basic error handling on the Project Service API call
> fix: project setup on start

- packages/client/hmi-client/src/components/responsive-matrix/cell-bar-container.vue
- packages/client/hmi-client/src/components/responsive-matrix/cell-bar-graph.vue
- packages/client/hmi-client/src/components/responsive-matrix/cell-line-container.vue
- packages/client/hmi-client/src/components/responsive-matrix/cell-line-graph.vue
- packages/client/hmi-client/src/components/responsive-matrix/matrix.vue
Resolves shifted bars in drilldown issue. Also resolves the picking issue by using a "2D" matrix (stored in 1 dimension) to store and get cell status instead of using row/col status only (which produces edge cases). In addition, refactored some code to remove the need to store row and column arrays containing arrays of references to cells. Instead, replace this with an iterator which can automatically calculate the indexes corresponding to rows and columns stored in a 1D array, allowing cells corresponding to rows and cols to be easily accessed from the main cell data structure directly.
> fix: resolve shifted bars, picking issue bugs, and refactor to remove data structure duplication

- packages/client/hmi-client/src/assets/css/reset.css
- packages/client/hmi-client/src/assets/css/style.css
- packages/client/hmi-client/src/components/data-explorer/articles-listview.vue
- packages/client/hmi-client/src/components/data-explorer/facets-panel.vue
- packages/client/hmi-client/src/components/data-explorer/models-listview.vue
- packages/client/hmi-client/src/components/data-explorer/search-bar.vue
- packages/client/hmi-client/src/components/data-explorer/search-results-list.vue
- packages/client/hmi-client/src/components/drilldown-panel/selected-resources-options-pane.vue
- packages/client/hmi-client/src/components/widgets/autocomplete.vue
- packages/client/hmi-client/src/components/widgets/full-screen-modal-header.vue
- packages/client/hmi-client/src/styles/overrides.scss
- packages/client/hmi-client/src/views/DataExplorer.vue
- packages/client/hmi-client/src/views/Model.vue
Before:
After:
Numerous little styling tweaks to start to clean up the data explorer page.
Also removes some code copied over from world modelers that's not used here.
Click the button in the top right of any page to open the data explorer.
Use the toggles and inputs and make sure nothing's broken
> fix: first pass on restyling the data explorer

- README.md
Adding a badge to the main README for visibility purposes. Only added the publish badge so that it is more easily identifiable if the publish action fails.
> docs: adding publish badge for visibility

- packages/client/hmi-client/src/components/responsive-matrix/label-cols.vue
- packages/client/hmi-client/src/components/responsive-matrix/label-rows.vue
- packages/client/hmi-client/src/components/responsive-matrix/matrix-util.ts
- packages/client/hmi-client/src/components/responsive-matrix/matrix.vue
- packages/client/hmi-client/src/components/responsive-matrix/pixi-utils.ts
Initial draft of the addition of labels to responsive matrix.
> feat: add labels to the responsive matrix

- packages/client/hmi-client/src/assets/css/style.css
- packages/client/hmi-client/src/components/Modal.vue
- packages/client/hmi-client/src/components/projects/NewProjectCard.vue
- packages/client/hmi-client/src/services/project.ts
- packages/client/hmi-client/tests/component/Home.spec.ts
Updated the Create a new project form based on Pascale new design:
> fix: update the Create a new project form

- packages/services/hmi-server/src/main/resources/application.properties
In theory required changes to make production work
Nope - going to test in production
> fix: add protocol and port parameters

- packages/client/hmi-client/src/components/data-explorer/datasets-listview.vue
- packages/client/hmi-client/src/components/data-explorer/models-listview.vue
- packages/client/hmi-client/src/components/data-explorer/search-results-matrix.vue
- packages/client/hmi-client/src/services/data.ts
Implement matrix view in the data explorer for models and datasets with sorting of clusters.
> feat: implement explorer matrix view

- .github/workflows/commitlint.yaml
- .github/workflows/lint.yaml
Switch to used lint workflows that were moved to `.github` repo.
Add concurrency check where appropriate
> ci: switch to use shared workflows from .github

- packages/client/hmi-client/src/services/data.ts
- packages/client/hmi-client/src/views/DataExplorer.vue
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/Publication.java
fix a few bugs:
- explorer keyword search being case sensitive
- selected publication from explorer failed to be added to project because of data service endpoint update
- refine the data explorer labels
- fix keyword search to include searching against concepts
> chore: explorer bug fixes

- packages/client/hmi-client/src/components/Sidebar.vue
- packages/client/hmi-client/src/components/data-explorer/search-bar.vue
- packages/client/hmi-client/src/components/data-explorer/search-results-matrix.vue
- packages/client/hmi-client/src/components/models/Model.vue
- packages/client/hmi-client/src/components/tabs/Tab.vue
- packages/client/hmi-client/src/components/tabs/TabContainer.vue
- packages/client/hmi-client/src/styles/overrides.scss
- packages/client/hmi-client/src/styles/variables.scss
- packages/client/hmi-client/src/views/Dataset.vue
- packages/client/hmi-client/src/views/Document.vue
- packages/client/hmi-client/src/views/ModelView.vue
Several cleanup tweaks in preparation of the dec 8 demo, including:
Use caret icon instead of arrow for opening/closing side panel
Recenter search bar vertically after its styles were broken yesterday.
Remove the light blue background from the matrix search results table header
(Remove some unused world modelers variables from variables.scss and overrides.scss)
https://user-images.githubusercontent.com/16928557/206007122-1357cf9a-3a16-4c48-bc4a-4a89e089e25d.mov
Model page changes:
- Remove sidebar
- Move description and "Add to workflow" button to header
- Make description collapsible/expandable
- Expand graph responsively when sidebar closes
Add white background everywhere that it's relevant
Navigate to each of the changes above and make sure things look alright.
> feat: pre-demo app cleanup 2

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/Dataset.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/ProjectResource.java
fix issue preventing adding resources from explorer to project assets
> chore: fix issue preventing adding resources from explorer to project assets

- packages/client/hmi-client/src/components/data-explorer/search-results-matrix.vue
- packages/client/hmi-client/src/services/data.ts
- packages/client/hmi-client/src/services/dataset.ts
- packages/client/hmi-client/src/types/Dataset.ts
- packages/client/hmi-client/src/utils/data-util.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/DatasetProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/DatasetResource.java
- add dataset facets for filtering simulation-runs and non-simulation runs datasets
- refine the data explorer matrix view with selection capabilities
- - fixe other bugs
> feat: refine data explore matrix selection and facets for sim datasets

- packages/client/hmi-client/src/components/articles/selected-article-pane.vue
fix a bug preventing adding a paper from the Home page to a project
> chore: fix a bug preventing adding a paper from the Home page to a project

- packages/client/hmi-client/src/views/DataExplorer.vue
clear persistent filters when the data explorer is closed
> chore: clear persistent filters when the data explorer is closed

- packages/client/hmi-client/src/components/Sidebar.vue
- packages/client/hmi-client/src/components/sidebar-panel/documents-sidebar-panel.vue
- packages/client/hmi-client/src/router/index.ts
https://user-images.githubusercontent.com/16928557/206299759-11489b51-d41f-440b-a7a2-7513c0e49214.mov
Just needed to properly propagate the project ID for the document route like the other routes.
> fix: added papers don't show until refresh

- packages/client/hmi-client/src/components/Sidebar.vue
- packages/client/hmi-client/src/views/ModelView.vue
Do not display model #1 if no project is provided
#331 
Manually
> chore: do not display a model if empty project

- packages/client/hmi-client/src/views/SimulationResult.vue
2 line styling change requested by Pascale.
> feat: add white background to matrix page

- packages/client/hmi-client/src/components/sidebar-panel/artifact-list.vue
fix the issue of opening a paper after deleting it
> chore: fix the issue of opening a paper after deleting it

- packages/client/graph-scaffolder/README.md
- packages/client/graph-scaffolder/examples/src/index.ts
Better documentation and examples
> chore: improve doc and example

- packages/client/hmi-client/src/assets/css/style.css
Made the background light grey
> fix: changed background color

- packages/client/hmi-client/src/components/data-explorer/search-bar.vue
- packages/client/hmi-client/src/services/data.ts
- packages/client/hmi-client/src/types/XDD.ts
- packages/client/hmi-client/src/views/DataExplorer.vue
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/xdd/XDDSearchPayload.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/xdd/DocumentProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/xdd/DocumentResource.java
Utilize latest xdd parameters to enhance search and expand matching against title and abstract
Resolves #355 
> feat: enhance xdd search and expand matching against title and abstract

- packages/client/hmi-client/docker/Dockerfile
Clean up docker file and remove the tool versioning which caused issues previously
> build: remove tool versions in dockerfile

- .dockerignore
- .github/workflows/lint.yaml
- .github/workflows/publish.yaml
- Makefile
- docker-bake.hcl
- packages/client/hmi-client/docker/Dockerfile
- packages/services/hmi-server/docker/jvm/Dockerfile.jvm
- packages/services/hmi-server/docker/native/Dockerfile.native
- packages/services/hmi-server/src/main/resources/application.properties
Reverting the Docker multi-stage build work. Seems that the CI is extremely slow then.
> ci: revert the multistage builds

- packages/client/hmi-client/src/components/data-explorer/articles-listview.vue
- packages/client/hmi-client/src/services/data.ts
- packages/client/hmi-client/src/types/XDD.ts
- packages/client/hmi-client/src/views/DataExplorer.vue
- packages/client/hmi-client/src/views/Document.vue
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/xdd/XDDSearchPayload.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/xdd/DocumentProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/xdd/DocumentResource.java
Implement the first part of xDD URL extractions and display those whenever available in the Document view and the DataExplorer. Remaining work includes creating facets from URL extraction but this won't be done soon since URL extractions is still very poor at this moment.
(NOTE that because xDD URL extractions is very poor, most papers won't have URL extractions available)
Resolves #357 
> feat: initial integration of xdd URL extractions

- packages/client/hmi-client/src/components/responsive-matrix/cell-bar-container.vue
- packages/client/hmi-client/src/components/responsive-matrix/cell-bar-graph.vue
- packages/client/hmi-client/src/components/responsive-matrix/cell-line-container.vue
- packages/client/hmi-client/src/components/responsive-matrix/cell-line-graph.vue
- packages/client/hmi-client/src/components/responsive-matrix/matrix.vue
- packages/client/hmi-client/src/views/SimulationResult.vue
> feat: add differential drilldowns to simulation results page

- packages/client/hmi-client/src/components/data-explorer/articles-listview.vue
- packages/client/hmi-client/src/components/data-explorer/search-results-list.vue
- packages/client/hmi-client/src/services/data.ts
- packages/client/hmi-client/src/services/dataset.ts
- packages/client/hmi-client/src/types/XDD.ts
- packages/client/hmi-client/src/types/common.ts
- packages/client/hmi-client/src/views/DataExplorer.vue
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/xdd/XDDSearchPayload.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/xdd/DocumentProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/xdd/ExtractionProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/xdd/DocumentResource.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/xdd/ExtractionResource.java
initial pass integrating xDD object search for figures and tables. Once proper design work is done for cleaning up the data explorer, the implementation of this feature can be revisited to proper display xDD search extractions
Resolves #382 
> feat: initial pass integrating xDD object search for figures and tables

- .github/pull_request_template.md
Right now the PR template is too long and not user-friendly, so let's go back to simpler times.
Resolves #399 
Will see on the next PR once merged
> build: simplify PR template

- .github/CODEOWNERS
Remove @bencodrington from the CODEOWNERS 👋
> fix: farewell Ben

- packages/client/hmi-client/src/services/data.ts
- packages/client/hmi-client/src/types/common.ts
- packages/client/hmi-client/src/views/DataExplorer.vue
- Significantly improve the Data Explorer performance ~%50 or more increase
- Avoid timeout issues
No functionality changes, but working with the explorer explorer now should be much faster and smoother. 
A key observation is that the explorer now only fetches data as needed!
Resolves #365
> chore: refactor explorer optimize performance

- packages/client/hmi-client/README.md
Add Uncharted Design Tokens in the README.md
> docs: add Uncharted Design Tokens information

- packages/client/hmi-client/src/components/Header.vue
* Removed a class used for testing the header
* Now back in place
> fix: header e2e test

- packages/client/hmi-client/src/components/articles/selected-article-pane.vue
- packages/client/hmi-client/src/components/drilldown-panel/selected-resources-options-pane.vue
- packages/client/hmi-client/src/components/resources/resources-list.vue
- packages/client/hmi-client/src/components/sidebar-panel/documents-sidebar-panel.vue
- packages/client/hmi-client/src/services/project.ts
- packages/client/hmi-client/src/types/XDD.ts
- packages/client/hmi-client/src/views/DocumentView.vue
Correcting xddUri -> xdd_uri as expected by api 
allowing us to add papers to projects again
https://user-images.githubusercontent.com/17088680/213303734-c7cd0298-4a80-42f9-85cf-e30e643ba9f9.mov
#433
> fix: changing xdd type to what is expected by their api

- packages/client/hmi-client/src/components/articles/Document.vue
- packages/client/hmi-client/src/components/data-explorer/preview-panel.vue
- packages/client/hmi-client/src/views/DataExplorer.vue
- packages/services/document-service/src/main/java/software/uncharted/terarium/documentserver/models/xdd/Document.java
Clean up a handful of things based on feedback
- collapse/hide sections that don't have data
- move pdf/publisher link to button
Note: XDD API seemed to have breaking changes, we are not getting abstract text anymore
View document in data-explorer, view document within project
> chore: document preview tweaks

- README.md
* Just make it simpler for people to start the front-end job
> docs: update README.md on how to start hmi-client

- packages/client/hmi-client/src/components/articles/Document.vue
- packages/client/hmi-client/src/types/XDD.ts
- packages/services/document-service/src/main/java/software/uncharted/terarium/documentserver/models/xdd/Document.java
First pass reference listing. This gets the plumbings in place, the exact citation formatting style will be sorted out later on.
Note not all publications have `citation_list` available. In the project page, try "A data-driven model to describe and forecast the dynamics of COVID-19 transmission".
> feat: first pass at listing document references

- packages/services/document-service/src/main/java/software/uncharted/terarium/documentserver/models/xdd/Dictionary.java
- packages/services/document-service/src/main/java/software/uncharted/terarium/documentserver/models/xdd/Document.java
- packages/services/document-service/src/main/java/software/uncharted/terarium/documentserver/models/xdd/KnownEntities.java
Fixing copy/paste error method names.
Resolves #502
> refactor: fix method names

- packages/client/hmi-client/src/components/data-explorer/preview-panel.vue
https://user-images.githubusercontent.com/16358728/213773733-fde449ec-4aba-45b7-ad33-0d07002e6927.mov
> feat: add to cart footer in document preview panel

- packages/client/hmi-client/src/components/data-explorer/preview-panel.vue
- packages/client/hmi-client/src/components/models/Model.vue
- packages/client/hmi-client/src/types/Model.ts
Create a model preview in the style of document and dataset previews. 
Note some of the fields are not well formatted as they are deserialized-strings from python
> feat: model preview

- packages/client/hmi-client/src/components/data-explorer/preview-panel.vue
- packages/client/hmi-client/src/components/data-explorer/search-bar.vue
- packages/client/hmi-client/src/components/data-explorer/search-by-example.vue
- packages/client/hmi-client/src/components/drilldown-panel/selected-resources-options-pane.vue
Adjust footer in preview
Resolves #545
> style: adjust footer in preview

- packages/client/hmi-client/src/components/articles/Document.vue
- packages/client/hmi-client/src/components/data-explorer/slider-panel.vue
- packages/client/hmi-client/src/views/DataExplorer.vue
* Long sentences searches brakes.
* Fix the pill(s) on the resources panel
* Finish highlight issue on the paper and model preview.
Resolves #570 
Resolves #556 
Resolves #524
> fix: extra design changes

- packages/client/hmi-client/src/views/ModelRunner.vue
> fix: fix model runner img urls

- packages/client/hmi-client/src/components/Slider.vue
- packages/client/hmi-client/src/components/data-explorer/asset-card.vue
- packages/client/hmi-client/src/components/data-explorer/preview-panel.vue
Resolves #587
Resolves #588
Resolves #590
> chore: more styling tweaks

- packages/client/hmi-client/src/components/sidebar-panel/documents-sidebar-panel.vue
* xDD requested a button to get their id for the papers added to a project.
> feat: add buttons to displays projects papers xDD gddid

- packages/client/hmi-client/src/components/data-explorer/search-results-matrix.vue
Issue #351 was previously fixed by @YohannParis - this is just removing the FIXME comment.
Resolves #351
> style(hmi-client): removing unneeded comment

- packages/client/hmi-client/src/assets/css/theme/extensions/_button.scss
- packages/client/hmi-client/src/views/DataExplorer.vue
> fix: fixed css for buttons so that they don't wiggle and better align

- packages/client/hmi-client/src/components/data-explorer/facets-panel.vue
- packages/client/hmi-client/src/components/facets/categorical-facet.vue
> fix: order of year facets should be in chronological order

- packages/client/hmi-client/src/assets/css/theme/_variables.scss
- packages/client/hmi-client/src/assets/css/theme/designer/components/panel/_accordion.scss
- packages/client/hmi-client/src/assets/css/theme/extensions/_accordion.scss
> fix: fixed css to get accordians working like the figma designs

- packages/client/hmi-client/src/App.vue
- packages/client/hmi-client/src/components/Navbar.vue
- packages/client/hmi-client/src/components/data-explorer/search-bar.vue
Chips are clickable, I like this approach since it keeps editing the query string more in the search-bar component
> feat: clickable chips

- packages/client/hmi-client/src/assets/css/theme/_variables.scss
- packages/client/hmi-client/src/assets/css/theme/designer/components/misc/_chip.scss
- packages/client/hmi-client/src/assets/css/theme/designer/components/panel/_accordion.scss
- packages/client/hmi-client/src/components/data-explorer/search-bar.vue
- packages/client/hmi-client/src/components/data-explorer/search-results-list.vue
Move chip styling to theme to keep things consistent
> style: move chip styling to theme

- packages/client/hmi-client/src/types/XDD.ts
- packages/services/document-service/src/main/java/software/uncharted/terarium/documentserver/responses/xdd/XDDFacetsItemResponse.java
I'm opting to do these in several smaller changes in order to reduce confusion and make it easier to find breaking changes.
* Updating variable name to not include underscores
Resolves #376 (partially)
> refactor(document-service): cleaning field names to camel case

- packages/client/hmi-client/src/components/Navbar.vue
> feat: remove the explorer link from the navigation menu

- packages/client/hmi-client/src/components/Navbar.vue
> feat: make the terarium logo a link back to home

- packages/client/hmi-client/src/components/data-explorer/search-results-list.vue
> fix: adjust font size and text for search results count in the explorer page

- packages/client/hmi-client/src/components/resources/resources-list.vue
Fix missing null check in `resources-list` preventing project page from rendering and breaking the app.
Fix `resources-list` not loading the proper resources the first time you visit the project page from a different page. 
https://user-images.githubusercontent.com/16358728/217023136-905c94c1-cc75-44e9-af5e-f9c756495983.mov
Resolves #579
> fix: blank project page

- packages/client/hmi-client/src/assets/css/theme/_variables.scss
- packages/client/hmi-client/src/components/articles/Document.vue
- packages/client/hmi-client/src/components/data-explorer/search-results-list.vue
https://user-images.githubusercontent.com/16358728/217056755-b9c9447a-1467-4efe-b3e5-562a23dd4107.mov
Resolves #638
Resolves #639
> fix: make loading gif primary green; fix links in explorer article preview panel

- packages/client/hmi-client/DEVELOPMENT.md
* First iteration of Development guidelines
> docs: create DEVELOPMENT.md

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/documentservice/DocumentProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/documentservice/DocumentResource.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/documentservice/responses/DocumentsResponseOK.java
renaming old term for document.
Resolves #678
> refactor(hmi-server): renaming article to document

- packages/client/hmi-client/src/components/Navbar.vue
- packages/client/hmi-client/src/components/documents/Document.vue
* Learned that `>>>` is not used anymore and need to use `:deep()`
> fix: change >>> with :deep()

- .github/workflows/integration-issues.yml
* This allows any issues to be tagged with integration label. Once tagged the issue will be added to this project issues table https://github.com/orgs/DARPA-ASKEM/projects/5/
> feat: add integration github action

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/documentservice/DictionariesResource.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/documentservice/SetResource.java
I attempted to use githubs conflict resolution tools.  Lesson learned.
> fix(hmi-server): broken build

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/documentservice/DictionariesResource.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/documentservice/ExtractionResource.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/documentservice/SetResource.java
> broken build after conflicts

- packages/client/hmi-client/src/components/widgets/slider-panel.vue
- packages/client/hmi-client/src/page/data-explorer/DataExplorer.vue
- packages/client/hmi-client/src/page/data-explorer/components/selected-resources-header-pane.vue
- packages/client/hmi-client/src/page/data-explorer/components/selected-resources-options-pane.vue
https://user-images.githubusercontent.com/17088680/220458481-e122624c-7485-4f5f-92bf-acafcf0b5b80.mov
Separated the header and data from the explorer's pane. added a bunch of styling
Clean up for issue 687
> chore: clean up add to cart

- packages/client/hmi-client/tests/e2e/base.spec.ts
* Make end to end test run again by fixing front-end changes
> fix: update base.spec.ts

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/Dataset.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/Model.java
- packages/services/hmi-server/src/main/resources/application.properties
Could not parse models or datasets correctly.
One clear place to see this way home page's related to section was not being populated because of this
#755
> fix: deserialization breaks 

- packages/client/hmi-client/src/assets/css/facets-overrides.scss
- packages/client/hmi-client/src/components/facets/categorical-facet.vue
- packages/client/hmi-client/src/components/facets/numerical-facet.vue
- packages/client/hmi-client/src/types/XDD.ts
Minor facet visual cleanup
-font -> figtree
-section titles -> sentence case
-no more changing colours when hovering
> fix: 669 task five small facets panel style tweaks

- packages/client/hmi-client/src/assets/css/asset.scss
- packages/client/hmi-client/src/assets/css/theme/_variables.scss
- packages/client/hmi-client/src/assets/css/theme/designer/components/panel/_accordion.scss
- packages/client/hmi-client/src/components/dataset/Dataset.vue
- packages/client/hmi-client/src/components/documents/Document.vue
- packages/client/hmi-client/src/page/data-explorer/DataExplorer.vue
- packages/client/hmi-client/src/page/data-explorer/components/preview-panel.vue
- packages/client/hmi-client/src/page/data-explorer/components/search-results-list.vue
- packages/client/hmi-client/src/page/project/tera-project.vue
- accordion headers follow design
- filter chips follow design
> style: use primevue templates to implement custom styling

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/ModelContent.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/documentservice/KnownEntities.java
Clean up beans
No functional changes, app should work as-is.
> chore: clean up

- packages/client/hmi-client/src/components/documents/selected-document-pane.vue
- packages/client/hmi-client/src/page/Home.vue
Minor styling changes for front page modals.
> chore: minor styling changes

- packages/client/hmi-client/src/utils/project-card.ts
* Issue with local variables and scope.
> fix: update project-card placeholder

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/modelservice/ModelServiceProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/skema/SkemaRustProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/TransformResource.java
Create proxy routes to perform the following
- PetriNet acset to latex
- MathML to PetriNet acset
1. Convert mathML to Petri
```
curl -v -H "content-type: application/json" -XPOST "http://localhost:3000/api/transforms/mathml-to-acset" -H "${AUTHORIZATION_HEADER}" -d'
[
"<math display=\"block\" style=\"display:inline-block;\"><mrow><mfrac><mrow><mi>d</mi><mi>S</mi></mrow><mrow><mi>d</mi><mi>t</mi></mrow></mfrac><mo>=</mo><mo>−</mo><mi>β</mi><mi>S</mi><mi>I</mi></mrow></math>",
"<math display=\"block\" style=\"display:inline-block;\"><mrow><mfrac><mrow><mi>d</mi><mi>I</mi></mrow><mrow><mi>d</mi><mi>t</mi></mrow></mfrac><mo>=</mo><mi>β</mi><mi>S</mi><mi>I</mi><mo>−</mo><mi>γ</mi><mi>I</mi></mrow></math>",
"<math display=\"block\" style=\"display:inline-block;\"><mrow><mfrac><mrow><mi>d</mi><m …
```
> feat: add transform proxies

- packages/client/hmi-client/src/petrinet/petrinet-service.ts
- packages/client/hmi-client/src/temp/ModelEditor.vue
Add in plumbings to do petri => latex and mathml => petri transformation
Nominal test wired into http://localhost:8078/app/#/model-editor, look at the debugger console
> feat: petri-to-latex and mathml=to-petri plumbing

- packages/client/hmi-client/src/components/Navbar.vue
https://user-images.githubusercontent.com/636801/226019262-3c3d6584-fdec-4002-b24b-44471a0c1756.mov
> chore: change navbar for data explorer

- packages/client/hmi-client/src/components/models/Model.vue
- packages/client/hmi-client/src/petrinet/petrinet-service.ts
- packages/client/hmi-client/src/services/model.ts
- packages/client/hmi-client/src/services/provenance.ts
- packages/client/hmi-client/tests/unit/petrinet/petrinet.spec.ts
- packages/client/hmi-client/tests/unit/services/simulation.spec.ts
Allow users to save models that they have edited.
https://user-images.githubusercontent.com/17088680/226617639-9af1246b-68e4-4b16-8e6c-f5c22bb85efd.mov
#870
> feat: 870 task model editor tweaks save changes back into tds

- packages/client/hmi-client/src/components/models/Model.vue
Removed the v-bind since it's no longer needed.
> fix: model.vue linting error

- packages/client/hmi-client/src/petrinet/petrinet-service.ts
- packages/client/hmi-client/src/temp/TA2Playground.vue
Provided 2 petrinets (not typed) and no ontology, stratify them together by multiplying everything together.  
https://user-images.githubusercontent.com/17088680/226913176-ca9b0b29-f64c-4a8a-a3c3-cd8c0cadbdf2.mov
> feat: blind stratification in ta2-playground

- packages/client/hmi-client/src/components/models/Model.vue
* Display data in a nicer way.
> chore: massage model table

- packages/client/hmi-client/src/assets/css/theme/_variables.scss
- packages/client/hmi-client/src/page/project/components/tera-resource-sidebar.vue
- packages/client/hmi-client/src/page/project/tera-project.vue
Design tweaks on confirm delete modal
> chore: confirm remove tweaks

- packages/client/hmi-client/src/components/models/Model.vue
> fix: bad edge check

- packages/client/hmi-client/src/petrinet/petrinet-renderer.ts
Start drag at node's drag anchor instead of node centre
https://user-images.githubusercontent.com/1220927/229611166-2f7047df-1280-4d52-86e8-ae9c99a24ebc.mov
Go into edit mode, select a node and try to create an edge
> fix: drag- start anchor at the handle instead of of center

- packages/client/hmi-client/src/services/data.ts
- packages/client/hmi-client/src/services/github-import.ts
- packages/client/hmi-client/src/services/mit-askem.ts
- packages/client/hmi-client/src/services/provenance.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/code/CodeResource.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/ProvenanceResource.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/documentservice/ExtractionResource.java
* Standardizing our endpoints to use hyphens instead of underscores.
Resolves #862
> chore: update endpoints to use hyphens instead of underscores (#862)

- packages/client/hmi-client/src/components/mathml/tera-math-editor.vue
- packages/client/hmi-client/src/components/models/Model.vue
- packages/client/hmi-client/src/components/widgets/tera-resizable-panel.vue
Fixed some resizing issues including the one @Tom-Szendrey pointed out in the slack channel.  Sorry @jamiewaese-uncharted I realized that I actually hadn't pushed the subsequent commits to the PR before merging it.
https://github.com/DARPA-ASKEM/Terarium/issues/954
> chore: math viewer design ux tweaks

- packages/client/hmi-client/src/components/models/Model.vue
> chore: pretty up model toolbar

- packages/client/hmi-client/src/components/models/Model.vue
- packages/client/hmi-client/src/services/graph.ts
When a graph has no nodes do not try to recalculate the sizing
> fix: model renderer small tweaks

- packages/client/hmi-client/src/page/project/components/tera-project-overview.vue
- packages/client/hmi-client/src/services/project.ts
- packages/client/hmi-client/src/vite-env.d.ts
- packages/client/hmi-client/tsconfig.json
- packages/client/hmi-client/tsconfig.node.json
Fixed typing issues in `vite-svg-loader` integration
> fix: allow svg imports

- packages/client/hmi-client/src/components/mathml/tera-math-editor.vue
- packages/client/hmi-client/src/components/models/Model.vue
- packages/client/hmi-client/src/components/widgets/tera-resizable-panel.vue
- packages/client/hmi-client/src/page/Home.vue
- packages/client/hmi-client/src/page/project/components/tera-resource-sidebar.vue
- packages/client/hmi-client/src/page/project/tera-project.vue
- packages/client/hmi-client/src/services/model.ts
- packages/client/hmi-client/src/stores/resources.ts
This will allow a user to create a new model within the project.
Fields that the user can edit are as follows:
1) Title of model
2) Description
3) Formula
988-feat-add-ability-to-create-new-model
[newmodel.webm](https://user-images.githubusercontent.com/98172806/231870979-3c50ceaa-8456-4430-b85d-2e560bbab3ee.webm)
> feat: added ability to create a new model

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/loggingservice/LoggingResource.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/services/LogMessage.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/services/LoggingService.java
Updated the Logging endpoint in Quarkus
> fix: fixed logging resource

- packages/client/hmi-client/src/page/data-explorer/components/tera-facets-panel.vue
Last minute change for dataset facet broke counting for documents
> fix: a last minute change broke facet count numbers

- packages/services/extraction-server/src/app.py
> fix: updated broker default

- packages/client/hmi-client/src/components/workflow/tera-model-node.vue
- packages/client/hmi-client/src/components/workflow/tera-workflow-node.vue
- packages/client/hmi-client/src/stores/opened-workflow-node.ts
> chore: polish model config

- packages/client/hmi-client/src/components/models/tera-model.vue
- packages/client/hmi-client/src/petrinet/petrinet-renderer.ts
minor style change to the diagram background
> style: changed petrinet diagram background from grey to white

- .github/workflows/auto-labeler.yaml
* Fixes possible inject issue within a workflow
Resolves #1182
> fix: remedy possible injection issue in workflow

- packages/client/hmi-client/src/components/widgets/tera-modal.vue
- packages/client/hmi-client/src/components/workflow/tera-simulation-workflow.vue
- packages/client/hmi-client/src/page/Home.vue
- packages/client/hmi-client/src/page/project/tera-project.vue
> chore: revert z-indexes

- packages/client/hmi-client/src/components/models/tera-model.vue
Some Model Page Styling
-biblio information
-description added to parameters table
-counters added to accordion table headers
-data alignment done
> chore: polish model page a bit

- packages/client/hmi-client/src/components/widgets/tera-import-github-file.vue
> chore: removing prov

- packages/client/hmi-client/src/components/workflow/stratify-operation.ts
- packages/client/hmi-client/src/components/workflow/tera-simulation-workflow.vue
- packages/client/hmi-client/src/components/workflow/tera-stratify-node.vue
- packages/client/hmi-client/src/components/workflow/tera-stratify.vue
- packages/client/hmi-client/src/components/workflow/tera-workflow-node.vue
- packages/client/hmi-client/src/page/project/tera-project.vue
- packages/client/hmi-client/src/types/Project.ts
- packages/client/hmi-client/src/types/workflow.ts
-Stratify operation that accepts model configuration as input
-Stratify workflow node
-Startify drilldown view with input and output switcher and 3 step layout
Resolves #1195
> feat: basic stratify workflow node and drilldown

- packages/client/hmi-client/src/services/dataset.ts
Quick and dirty test to check something out.
> fix: upload to s3

- packages/client/hmi-client/src/page/data-explorer/DataExplorer.vue
Empty search + researching same query should result in a search
https://github.com/DARPA-ASKEM/Terarium/assets/17088680/d162d717-0778-47ab-88f1-e493f41bab14
> feat: allowing searching with empty query

- packages/client/hmi-client/src/types/Types.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/mit/MitProxy.java
* Add new endpoint
Resolves #1251
> feat: integrate mit data profiling into terarium

- packages/client/hmi-client/src/components/dataset/tera-dataset-datatable.vue
*  Fix TS issue where attribute type is not handled properly.
Resolves https://github.com/DARPA-ASKEM/Terarium/actions/runs/5349552837/jobs/9700931204#step:9:9
> fix(hmi-client): typecheck on datatable property

- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
Fixing an AOOBE which causes this page to never load.
Resolves #1271
> fix(hmi-client): fixing AOOBE

- packages/client/hmi-client/src/components/models/tera-model-configuration.vue
> fix: ignore time parsing in amr for the moment

- packages/client/hmi-client/src/App.vue
- packages/client/hmi-client/src/components/widgets/tera-import-github-file.vue
- packages/client/hmi-client/src/services/dataset.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/DatasetResource.java
Small improvements to github workflow. Moving it all to the back end to allow for larger files. hard reset of project view after upload is done.
Resolves #1285
> fix(hmi-client): improve github import of csv files

- packages/client/hmi-client/src/components/widgets/tera-context-menu.vue
> fix: close tera-context-menu after selection

- packages/client/hmi-client/src/components/home/tera-project-card.vue
Darkened the color of the icons & values.
ORIGINAL
NEW
> feat: make icons and stats on home page cards more readable

- packages/client/hmi-client/src/components/models/tera-model-configuration.vue
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/ModelProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/ModelResource.java
Model configuration API call is adjusted to work with TDS update
> fix: adjust api call for getting model configurations

- packages/client/hmi-client/src/components/asset/tera-asset.vue
- packages/client/hmi-client/src/components/models/tera-model.vue
- packages/client/hmi-client/src/components/workflow/tera-simulation-workflow.vue
- packages/client/hmi-client/src/page/project/components/tera-project-overview.vue
- packages/client/hmi-client/src/page/project/components/tera-project-page.vue
Workflow and model renaming works... sometimes due to elastic search update being slow. There is a higher chance of the workflow name updating than the model due the size they take up. If you want to see the updates for sure refresh the page. 
I'll open issue for tackling the elastic search issues.
https://github.com/DARPA-ASKEM/Terarium/assets/28237258/dc68bcac-2dec-448b-ab29-596d0dd275aa
> feat: edit model and workflow names

- packages/client/hmi-client/src/components/models/tera-model.vue
One liner: Default to description view on model page.
> fix: default to description view on model page

- packages/client/hmi-client/src/components/widgets/tera-related-publications.vue
> feat: remove gap from related publications

- packages/client/hmi-client/src/components/models/tera-model.vue
> feat: sentence case for all metadata labels on model page

- packages/client/hmi-client/src/components/widgets/tera-context-menu.vue
- packages/client/hmi-client/src/components/workflow/tera-simulation-workflow.vue
> feat: added 2 more options to the workflow menu

- packages/client/hmi-client/vite.config.ts
> fix: vite build

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/EventResource.java
> fix: ensure the username is added Event before structured logging

- packages/client/hmi-client/src/components/mathml/tera-math-editor.vue
- packages/client/hmi-client/src/components/models/tera-model-diagram.vue
- packages/client/hmi-client/src/utils/math.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/extractionservice/ExtractionServiceProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/extractionservice/ExtractionResource.java
Separates multi line latex equations into their own mathLIVE input.
> feat: 1350 task update the model equations layout

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/modelservice/StratifyRequest.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/modelservice/ModelServiceProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/modelservice/ModelingRequestResource.java
> fix post-body

- packages/client/hmi-client/src/assets/css/theme/_variables.scss
- packages/client/hmi-client/src/components/widgets/tera-tab-group.vue
Adjusted background color of inactive tabs so they can be distinguished from the background. Also slightly changed the color.
PREVIOUS
NEW
> feat: Jamie tabs background color tweak

- packages/client/hmi-client/vite.config.ts
> fix: vite path for docker compose, etc

- packages/client/hmi-client/src/components/models/tera-model-configuration.vue
> fix: default config reactivity issue

- packages/services/hmi-server/src/main/resources/application.properties
> fix: ciemss-service configuration

- packages/client/hmi-client/src/components/extracting/tera-drag-n-drop-importer.vue
- packages/client/hmi-client/src/page/project/components/tera-project-overview.vue
- packages/client/hmi-client/src/types/common.ts
> fix: added extension check to file-type check

- packages/client/hmi-client/src/components/mathml/tera-math-editor.vue
- packages/client/hmi-client/src/components/models/tera-model-diagram.vue
made several UI / plumbing improvements.
> fix: fixed several bugs

- packages/client/hmi-client/src/components/models/tera-model.vue
* When a user tries to duplicate a model by clicking "Make a copy" we now show a modal with an input field with a suggested model name.
* VIdeo demo: https://capture.dropbox.com/D6q8ALWjGxBZ2xFB
> Create copy model modal

- packages/client/hmi-client/src/components/dataset/tera-dataset-jupyter-panel.vue
- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
- packages/client/hmi-client/src/components/llm/tera-chatty-input.vue
- packages/client/hmi-client/src/components/llm/tera-chatty-response-code-cell.vue
- packages/client/hmi-client/src/components/llm/tera-jupyter-chat.vue
- packages/client/hmi-client/src/components/llm/tera-jupyter-response.vue
- packages/client/hmi-client/src/services/jupyter.ts
> feature: notebook previews and stand-alone code cells

- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
- packages/client/hmi-client/src/components/models/tera-model.vue
- packages/client/hmi-client/src/components/widgets/tera-related-publications.vue
* Some basic front end work, populating this list with documents that can be used for enrichment.
* Fixed a bug with selecting files for enrichment
* Changed related publications dialog to show better what is being enriched (models v dataset)
> task(hmi): front end work prepping for ta1 extraction/enrichment

- packages/client/hmi-client/src/components/models/tera-strata-model-diagram.vue
- packages/client/hmi-client/src/components/models/tera-typed-model-diagram.vue
Fix graph's pan/zoom resetting after each graph colouring command. Minor clean up of unused styles.
> stable zoom/pan, clean up

- packages/client/hmi-client/src/model-representation/petrinet/petrinet-service.ts
- packages/client/hmi-client/src/page/project/components/tera-project-overview.vue
- packages/client/hmi-client/src/page/project/components/tera-project-page.vue
* Show a modal prompting user to enter model name when creating a new model
* Video demo: https://capture.dropbox.com/pXRZ9wBQvud3g6V5
> feat: add modal prompt when creating new model

- packages/client/hmi-client/src/services/models/simulation-service.ts
> feat: allow ciemss simulate graph to display observed data

- packages/client/hmi-client/src/components/widgets/tera-related-publications.vue
* Restoring artifacts to modal list
* merging artifacts list with documents
* removing debug code.
> feat(hmi-client): related resources must show artifacts and documents

- packages/client/hmi-client/src/components/llm/tera-jupyter-chat.vue
> fix: allows grouping again

- packages/client/hmi-client/src/components/llm/tera-chatty-input.vue
- packages/client/hmi-client/src/page/project/components/code-editor.vue
- packages/client/hmi-client/src/services/github-import.ts
- packages/client/hmi-client/src/services/model.ts
- packages/client/hmi-client/src/services/models/simulation-service.ts
- packages/client/hmi-client/src/services/project.ts
- packages/client/hmi-client/src/types/Types.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/EventType.java
This adds instrumentation events for:
- adding resources to a project
- extracting models from code
- editing/saving models
- running chatty transforms
- running chatty code cells
- running simulations
- running calibrations
- importing from github
> feat: add instrumentation events

- packages/client/hmi-client/src/services/models/simulation-service.ts
> chore: fix lint

- packages/client/hmi-client/src/utils/pivot.ts
- packages/client/hmi-client/tests/unit/utils/pivot.spec.ts
> chore: clean up pivot util, add unit test

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/mira/MIRAProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/miraservice/MIRAResource.java
MIRA endpoints for reconstructing semantics.ode
> feat: add mira end-points

- packages/client/hmi-client/src/components/models/tera-model-configuration.vue
- packages/client/hmi-client/src/components/widgets/tera-modal.vue
* Ability to switch between variable types
* Added time series variables
* Time series cells are uneditable from the table view
* Time series variable stored in `configuration.metadata.timeseries` (for now), as there is no other way to store this in the current AMR structure
Each key in the timeseries object references a parameter id for the corresponding model configuration
* Unsure, if we will need to hook this up down the line in regards for simulating
https://github.com/DARPA-ASKEM/Terarium/assets/33158416/6fcaf021-b94d-4933-887b-1994e5f6074b
> Cole adding timeseries variables to model configuration

- packages/client/hmi-client/src/components/models/tera-model.vue
Save model on observable changes
> fix: persist observable changes back to DB

- packages/client/hmi-client/src/model-representation/petrinet/petrinet-service.ts
Allow reflexives to have multi-edge links to states
> fix: allow reflexive loops to be multi-edge

- packages/client/hmi-client/src/components/models/tera-model.vue
- packages/client/hmi-client/src/components/models/tera-stratified-model-configuration.vue
- packages/client/hmi-client/src/components/models/tera-stratify-value-matrix.vue
https://github.com/DARPA-ASKEM/Terarium/assets/28237258/7d600bf3-770d-4ca1-9aa6-ee6861c143e3
> feat: config matrices in strata model config properly

- packages/client/hmi-client/src/model-representation/petrinet/petrinet-service.ts
- Fix transition trying to update non-existing properties field
- Re-apply implicit rate => parameter relationship via naming
> fix: fix transition possibly updating non-existing properties

- packages/client/hmi-client/src/components/llm/tera-jupyter-chat.vue
- packages/client/hmi-client/src/components/models/tera-model-jupyter-panel.vue
Adds a dropdown on the model transform/notebook view that allows switching to a configuration instead of the default model.
> Add handling for model configurations in llm

- packages/client/hmi-client/src/components/workflow/simulate-ciemss-operation.ts
- packages/client/hmi-client/src/components/workflow/tera-simulate-ciemss-node.vue
Add numSamples and method params to simulate ciemss
> feat: add params to simulate ciemss

- packages/client/hmi-client/src/components/mathml/tera-math-editor.vue
quick fix for disabled button.
> fix: fix enable save

- packages/client/hmi-client/src/model-representation/petrinet/nested-petrinet-renderer.ts
> feat: add nesting for transitions

- packages/client/hmi-client/src/components/llm/tera-jupyter-chat.vue
- packages/client/hmi-client/src/components/llm/tera-jupyter-response.vue
- packages/client/hmi-client/src/components/models/tera-model-jupyter-panel.vue
Allows collapsing of the previews on the LLM panels and provides a check bock to set default behavior.
> feature: llm collapsed previews

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/SimulationResource.java
* Did not write the value of Datasets correctly, `ResourceType.Type.DATASETS` should print out as `datasets` and not `DATASETS`
> fix: to be able to save the issue

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/SimulationResource.java
* Forget about enum, not worth it.
> fix: hard code the value for a dataset

- packages/client/hmi-client/src/components/models/tera-model.vue
- packages/client/hmi-client/src/components/models/tera-stratified-model-configuration.vue
- packages/client/hmi-client/src/components/models/tera-stratified-value-matrix.vue
- packages/client/hmi-client/src/model-representation/petrinet/petrinet-service.ts
- packages/client/hmi-client/src/temp/models/stratify_2.ts
- Stratified variables are mapped to the base variables for appropriate matrix construction
- Proper values are in stratification matrices 
- More configs can be added.
https://github.com/DARPA-ASKEM/Terarium/assets/28237258/9b3b5ad6-d65e-4bd2-80f8-bf2fec4bcc99
> feat: proper values are in stratification matrices and more configs can be added

- packages/client/hmi-client/src/components/dataset/tera-dataset-jupyter-panel.vue
- packages/client/hmi-client/src/components/llm/tera-chatty-response-code-cell.vue
- packages/client/hmi-client/src/components/llm/tera-jupyter-chat.vue
- packages/client/hmi-client/src/components/llm/tera-jupyter-response.vue
- packages/client/hmi-client/src/components/models/tera-model-jupyter-panel.vue
Adds a reset button that allows you to reset the kernel in the llm session, keeping your code and other artifacts so you can edit and rerun.
> feature: Add ability to reset the notebook environments

- packages/client/hmi-client/src/page/project/components/tera-project-overview.vue
* Filter project overview datatable
https://github.com/DARPA-ASKEM/Terarium/assets/33158416/f6273b7a-8614-46d6-89cb-6871f5033038
> task: filter overview table

- packages/client/hmi-client/src/components/workflow/tera-calibration-node-julia.vue
- packages/client/hmi-client/src/services/models/simulation-service.ts
Julia Calibration has new output. This is the first step to handle this new format
> task: handle calibration new output - production fix

- packages/client/hmi-client/src/components/workflow/tera-calibrate-ensemble-ciemss.vue
- packages/client/hmi-client/src/components/workflow/tera-simulate-ciemss.vue
- packages/client/hmi-client/src/components/workflow/tera-simulate-ensemble-ciemss.vue
- packages/client/hmi-client/src/components/workflow/tera-simulate-julia.vue
- packages/client/hmi-client/src/services/dataset.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/SimulationProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/SimulationResource.java
* fixed a toast issue that was showing up as an error when there was no error. This is because the response code was 201 not 200.
* Users now must name their dataset when saving.
> Fix simulation dataset creation

- packages/client/hmi-client/src/components/workflow/tera-calibration-julia.vue
- packages/client/hmi-client/src/components/workflow/tera-calibration-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/tera-calibration-node-julia.vue
- packages/client/hmi-client/src/services/models/simulation-service.ts
Julia's calibration output has a new format with a new file name.
This is the first step in handling that new format
> Handle Julias new output for calibration

- packages/client/hmi-client/tests/unit/services/workflow.spec.ts
> chore: clean up workflow unit test

- packages/client/hmi-client/src/page/Home.vue
- packages/client/hmi-client/src/services/project.ts
- packages/client/hmi-client/src/types/Types.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/Project.java
* TDS changed their requirement to create a new project.
* This allow to add the new field that have become necessary.
* Added the Project types to the front-end.
> feat: change the minimum requirement to create a project with TDS

- packages/client/hmi-client/src/components/widgets/tera-import-github-file.vue
- packages/client/hmi-client/src/page/project/components/tera-project-overview.vue
- packages/client/hmi-client/src/services/artifact.ts
- packages/client/hmi-client/src/services/models/extractions.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/extractionservice/ExtractionServiceProxy.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/extractionservice/ExtractionResource.java
Extracting pdf files as they're uploaded by the user either on disk or github. Fire and forget, the artifacts are silently updated in the background.
Resolves #1679
> Feat(hmi): PDF extractions

- packages/client/hmi-client/src/components/models/tera-model-diagram.vue
- packages/client/hmi-client/src/components/workflow/tera-simulation-workflow.vue
- packages/client/hmi-client/src/page/project/components/tera-project-page.vue
* add condition to check for existing state/transition when creating nodes in model editor
* fix workflow tab being stuck in loading state
> fix: misc stuff

- packages/client/hmi-client/src/services/models/extractions.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/extractionservice/ExtractionServiceProxy.java
- packages/services/hmi-server/src/main/resources/application.properties
> extraction to ta1

- packages/client/hmi-client/src/components/models/tera-typed-model-diagram.vue
> fix: fix conflict with tera-typed-model-diagram.vue

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/ProjectProxy.java
* We need to see the EVAL project on production
> feat: increase number of projects downloaded

- packages/services/hmi-server/src/main/resources/application.properties
> Cherry pick gone wrong :D

- packages/client/hmi-client/src/api/event-source-manager.ts
- packages/client/hmi-client/src/components/workflow/tera-calibration-node-ciemss.vue
- packages/client/hmi-client/src/services/models/simulation-service.ts
* A follow up PR to address some comments and clean up the code on this [issue]((https://github.com/DARPA-ASKEM/Terarium/pull/1683))
> chore: event source changes

- packages/client/hmi-client/src/components/workflow/tera-calibration-julia.vue
- packages/client/hmi-client/src/components/workflow/tera-calibration-node-ciemss.vue
- packages/client/hmi-client/src/components/workflow/tera-calibration-node-julia.vue
- packages/client/hmi-client/src/components/workflow/tera-simulate-chart.vue
- packages/client/hmi-client/src/components/workflow/util.ts
How it looks:
Part [1/2]: #1752
> feat: update code to plot input dataset for Julia calibrate

- packages/client/hmi-client/vite.config.ts
Attempt to fix build
Run `yarn workspace hmi-client build`
> fix: fix webworker build

- packages/services/hmi-server/src/main/resources/application.properties
* Remove the dev/prod version of ta1-service
* Rename the env variable to knowledge-middleware
* [Needs Orchestration PR merge first](https://github.com/DARPA-ASKEM/orchestration/pull/278)
> task: update env setting for knowledge-middleware

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/ProjectResource.java
> bug: add error handling for get all project

- packages/client/hmi-client/src/components/models/tera-stratified-model-configuration.vue
- packages/client/hmi-client/src/components/models/tera-stratified-value-matrix.vue
- packages/client/hmi-client/src/python/PyodideController.ts
- packages/client/hmi-client/src/python/PyodideWorker.ts
- packages/client/hmi-client/src/temp/PyodideTest.vue
> Eval transitions

- packages/client/hmi-client/src/components/models/tera-model-diagram.vue
- packages/client/hmi-client/src/model-representation/petrinet/nested-petrinet-renderer.ts
- packages/client/hmi-client/src/model-representation/petrinet/petri-util.ts
- packages/client/hmi-client/src/utils/petrinet-color-palette.ts
> Update nested graph

- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/proxies/knowledgemiddleware/KnowledgeMiddlewareProxy.java
* I forgot to change the param names in the docstring
> nit: fix docstring

- packages/client/hmi-client/src/model-representation/petrinet/mira-petri.ts
- packages/client/hmi-client/src/model-representation/petrinet/nested-petrinet-renderer.ts
- packages/client/hmi-client/src/utils/petrinet-color-palette.ts
> Fix nested graph

- packages/client/hmi-client/src/model-representation/petrinet/nested-petrinet-renderer.ts
> feat: add margin to petrinet nesting

- packages/client/hmi-client/src/components/models/tera-model-jupyter-panel.vue
- packages/client/hmi-client/src/components/models/tera-model.vue
- packages/client/hmi-client/src/components/models/tera-typed-model-diagram.vue
- packages/client/hmi-client/src/model-representation/petrinet/petrinet-service.ts
- packages/client/hmi-client/src/types/Types.ts
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/Model.java
Remove dangling bits of AMR header change
> chore: remove deprecated fields

- packages/client/hmi-client/src/components/workflow/tera-calibration-node-ciemss.vue
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/models/SimulationIntermediateResultsCiemss.java
- packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/SimulationResource.java
Renaming a bunch of the ciemss MQ related stuff to make sure there are clear names now that Julia is being added as well
> task: adding ciemss name to ciemss mq related

- packages/client/hmi-client/src/components/model/petrinet/tera-model-configurations.vue
- packages/client/hmi-client/src/components/widgets/tera-modal.vue
Added a scrollbar for modal content that exceeds `65vh`.
> fix: modal overflow

- packages/client/hmi-client/src/page/WorkflowNode.vue
> fix: missed file from workflow reorganization

- packages/client/hmi-client/src/page/data-explorer/DataExplorer.vue
* A fix to change clear the facet filters when changing the resource type
> fix: clear facet filters on resource type change

- packages/client/hmi-client/package.json
- packages/client/hmi-client/src/services/jupyter.ts
- packages/client/hmi-client/src/services/workflow.ts
- packages/client/hmi-client/src/workflow/ops/dataset-transformer/tera-dataset-transformer.vue
- packages/client/hmi-client/src/workflow/tera-workflow.vue
- yarn.lock
Reverting crypto.randomuuid change for overall stableness. Was causing problems for testing, and the testing-fix in turn cause problems after the build.
> fix: revert randomuuid change

- packages/client/hmi-client/src/workflow/ops/dataset-transformer/tera-dataset-transformer.vue
- packages/client/hmi-client/src/workflow/ops/model-transformer/tera-model-transformer.vue
> fix: linter

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ProjectResource.java
hmiserver was not able to use currentUserService in this file as it was not set up (was just null)
> fix: minor fix

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/utils/rebac/AskemDatumType.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/utils/rebac/ReBACService.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/utils/rebac/Schema.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/utils/rebac/askem/RebacProject.java
> remove useTransportSecurity call for spiceDB channel

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ProjectController.java
> get location and server from tds response

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/AnnotationController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/AnnotationService.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/EventService.java
this fixes missing argument error for `Sort.by`
> update Sort.by function inputs

- packages/client/hmi-client/src/services/knowledge.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/TransformController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/proxies/modelservice/ModelServiceProxy.java
- packages/server/src/main/resources/application.properties
> fix: bug equations to amr

- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
- packages/client/hmi-client/src/components/model/petrinet/tera-model-description.vue
* documents array is still broken since we can't get the empty object yet, adding a null checker here!
> fix documents

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ExternalPublicationController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/ExternalPublicationProxy.java
- packages/server/src/test/java/software/uncharted/terarium/hmiserver/controller/tds/ExternalPublicationTests.java
- packages/server/src/test/java/software/uncharted/terarium/hmiserver/controller/xdd/XDDTests.java
* Fixing typing on the back end for external publications
* Adding tests
* Cleaning up xdd test
Resolves #1980
> fix(hmi-server): Correct external publication endpoints #1980

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/code/CodeController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/proxies/jsdelivr/JsDelivrProxy.java
All I changed was line 8 on JsDelivrProxy.java. My formatter shifted stuff
Code is fetched properly now:
> fix: jsdelivr.url var read properly from app.props

- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
- packages/client/hmi-client/src/components/dataset/utils.ts
- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/proxies/knowledge/KnowledgeMiddlewareProxy.java
* Display the `data_card` in a simple manner for now.
Resolves #1888
> fix: display data card

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/proxies/simulationservice/SimulationServiceProxy.java
- packages/server/src/main/resources/application.properties
We need to point to simulation service to make this work.
Resolves #2002
> fix(hmi-server): use correct url

- packages/client/hmi-client/src/services/notebook-session.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/NotebookSessionController.java
> fix: fix llm notebook errors

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/proxies/knowledge/KnowledgeMiddlewareProxy.java
* to be merged in tandem with https://github.com/DARPA-ASKEM/knowledge-middleware/pull/105
> tasK: update KnowledgeMiddlewareProxy to match new endpoints

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/SimulationController.java
> Update how datasets are updated

- packages/client/hmi-client/src/components/documents/tera-document-asset.vue
- packages/client/hmi-client/src/main.ts
- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DocumentController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/DocumentExtraction.java
* We are using the wrong urls to display extractions assets
* Instead we are using S3 pre-signed URLs
Resolves #2009
> task: display cosmos extractions from s3 instead of xdd

- packages/client/hmi-client/src/components/widgets/tera-related-documents.vue
* enrichment button loading state
https://github.com/DARPA-ASKEM/terarium/assets/33158416/71b3170b-a59f-4ea0-83fb-5d151012f7fd
> task: enrichment feedback

- .github/workflows/publish.yaml
Reverts DARPA-ASKEM/terarium#2051
> Revert "task: only run one publish workfkow at the time"

- packages/client/hmi-client/src/components/model/petrinet/tera-equation-container.vue
- packages/client/hmi-client/src/components/model/petrinet/tera-model-equation.vue
- packages/client/hmi-client/src/components/model/petrinet/tera-model-observable.vue
https://github.com/DARPA-ASKEM/terarium/assets/17088680/9b9de2ba-431d-40c1-8ff2-848ca2cb8625
> Chore: adding some user communication 

- packages/client/hmi-client/src/components/documents/tera-document-asset.vue
Fixing a tab bug thing
probably a cleaner way to write this but it works
> Thanks SHAWN!

- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
- packages/client/hmi-client/src/components/documents/tera-document-asset.vue
- packages/client/hmi-client/src/components/documents/tera-external-publication.vue
- packages/client/hmi-client/src/components/model/petrinet/tera-model-description.vue
* simply removing the green info messages that were present on some assets
> chore: remove green info messages

- packages/client/hmi-client/src/types/SimulateConfig.ts
- packages/client/hmi-client/src/workflow/ops/simulate-ciemss/simulate-ciemss-operation.ts
- packages/client/hmi-client/src/workflow/ops/simulate-ciemss/tera-simulate-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-julia/simulate-julia-operation.ts
- packages/client/hmi-client/src/workflow/ops/simulate-julia/tera-simulate-julia.vue
- packages/client/hmi-client/src/workflow/ops/simulate-julia/tera-simulate-node-julia.vue
- packages/client/hmi-client/src/workflow/tera-simulate-chart.vue
- packages/client/hmi-client/src/workflow/tera-workflow.vue
Demo video: https://capture.dropbox.com/mGz7OQen0wshrOty
Resolves #2034
> Persist chart configs when switching between different runs

- packages/client/hmi-client/src/components/widgets/tera-slider.vue
- packages/client/hmi-client/src/workflow/tera-workflow.vue
Fixed notes border from being hidden behind workflow and code assets.
> style: border adjust on project page

- packages/client/hmi-client/src/components/code/tera-code.vue
- packages/client/hmi-client/src/services/knowledge.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/proxies/knowledge/KnowledgeMiddlewareProxy.java
- Update params for `code-to-amr`
- Add loading spinner to Create model from code button
https://github.com/DARPA-ASKEM/terarium/assets/28237258/143dd50a-7a73-411e-9aa1-ba0b3a3bd62c
> feat: update code-to-amr endpoint params

- packages/client/hmi-client/src/types/SimulateConfig.ts
- packages/client/hmi-client/src/workflow/ops/simulate-ciemss/tera-simulate-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ciemss/tera-simulate-node-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-julia/tera-simulate-julia.vue
- packages/client/hmi-client/src/workflow/ops/simulate-julia/tera-simulate-node-julia.vue
> Show input configs in simulate drilldown

- packages/client/hmi-client/src/model-representation/petrinet/mira-petri.ts
- packages/client/hmi-client/src/router/index.ts
- packages/client/hmi-client/src/services/graph.ts
- packages/client/hmi-client/src/services/model.ts
- packages/client/hmi-client/src/services/workflow.ts
A handful of miscellaneous things 
- confusing and out of date comments
- unused code and experiment
> chore: house cleaning Oct 2023

- packages/client/hmi-client/src/components/dataset/tera-dataset-jupyter-panel.vue
- packages/client/hmi-client/src/components/model/tera-model-jupyter-panel.vue
> fix: fix reset spelling

- packages/client/hmi-client/src/page/Home.vue
Removed related papers section including its functions and css
> chore: remove related papers section on home page

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/miraservice/MIRAController.java
* fixed an issue where calling the mira endpoints would cause the app to hang
https://github.com/DARPA-ASKEM/terarium/assets/33158416/63f6e075-66fd-4ba9-9c2f-36af32d60c82
> fix: mira endpoints

- packages/client/hmi-client/src/App.vue
- packages/client/hmi-client/src/page/Home.vue
* Fixed an issue where navigating to a project directly does not load the project menu dropdown.
* Fixed an issue where navigating to a project in the menu would not load the overview page initially
Before:
https://github.com/DARPA-ASKEM/terarium/assets/33158416/ddae646d-bc18-4c8f-97dc-8b34dae7aa18
After:
https://github.com/DARPA-ASKEM/terarium/assets/33158416/4c4725ef-e8bf-4b50-a210-0a27dac9da94
> fix: project loading navigation issues

- packages/client/hmi-client/src/components/model/petrinet/tera-model-description.vue
* display model parameters name
* change the header from `ID` to `Symbol`
> task: display model parameters name

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/TransformController.java
> fix for not being able to display equations

- packages/client/hmi-client/src/App.vue
- packages/client/hmi-client/src/assets/css/theme/_variables.scss
- packages/client/hmi-client/src/page/data-explorer/DataExplorer.vue
- packages/client/hmi-client/src/page/data-explorer/components/tera-filter-bar.vue
- packages/client/hmi-client/src/stores/resources.ts
* A way to select topics in the explorer
* additions the filter-bar will be made in an additional PR (eg. document type, number of documents...)
https://github.com/DARPA-ASKEM/terarium/assets/33158416/e7dd4a6b-f09d-4e0d-b694-77efa58c191b
> feat: explorer topic selector

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DatasetController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/CsvAsset.java
> if a CSV row has null values, we set them as "" instead

- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/funman/FunmanPostQueriesRequest.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/funman/parts/FunmanWorkRequest.java
Updating post request type
May more strongly type this in next PR but this will be good for now.
Based off of: https://github.com/siftech/funman/blob/c503c8e8b9e4e36a23a343b1fe632e9aed817d88/src/funman/api/api.py#L211
> Task: Updating based off of siftech/funman

- packages/client/hmi-client/src/workflow/ops/stratify-mira/tera-stratify-mira.vue
* Fix share project modal being broken by style from another component
> fix: broken style

- packages/client/hmi-client/index.html
- packages/client/hmi-client/src/page/Home.vue
Potential fix for those who were having trouble with production on Chrome. Also threw in a color tweak that Neil wanted.
Inspiration: https://stackoverflow.com/questions/179355/clearing-all-cookies-with-javascript
> fix: clear cookies before keycloak is initialized

- packages/client/hmi-client/src/services/model.ts
Increase limit since we have > 100 models that exceeds the "search" limit.
> increate model return limit

- .gitignore
- hmiServerDev.sh
- packages/client/hmi-client/vite.config.local.ts
- packages/server/docker/Dockerfile.local
@dgauldie told me to create this.
> Build local docker-compose.yml file based on `full` config

- packages/server/src/main/resources/application.properties
> Only display errors from inside of the amqp framework

- packages/client/hmi-client/src/services/ClientEventService.ts
Unsure how this snuck in but its not in pantera. Fixing a recursive bug on init.
> Recursion issue on startup of SSE subsystem

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/LogController.java
> Remove PII from log

- packages/client/hmi-client/src/components/documents/tera-document-asset.vue
- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DocumentController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/document/DocumentExtraction.java
* issue where extractions are not showing from extraction job 
* XDD extractions like 'Figure', KM extraction like 'figure'.
> fix: xdd extractions not displaying

- Makefile
- containers/scripts/docker-compose-base.yml
- containers/scripts/docker-compose-data-services.yml
- containers/scripts/docker-compose-data.yml
> fix build issue

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/UserController.java
> remove secured from api call

- packages/client/hmi-client/src/workflow/tera-workflow-node.vue
- packages/client/hmi-client/src/workflow/tera-workflow.vue
Remove VIRIDIS_14 and associated functions from tera-workflow.vue
Remove VIRIDIS_14 and associated functions from tera-workflow-node.vue
> chore: remove viridis

- packages/client/hmi-client/src/components/code/tera-code-dynamic.vue
- packages/client/hmi-client/src/components/code/tera-code.vue
* Ability to edit code blocks. Lines only until a new way to save name/description for a code block is made.
https://github.com/DARPA-ASKEM/terarium/assets/33158416/95b12533-2821-4137-ae6d-0509f59eafb1
> feat: edit code blocks

- packages/client/hmi-client/src/services/jupyter.ts
- packages/client/hmi-client/src/workflow/ops/stratify-mira/tera-stratify-mira.vue
> Kernel dispatch mira stratify

- containers/docker-compose-local.yml
- containers/permissions/Dockerfile
- containers/permissions/schema
- containers/permissions/script.sh
- containers/permissions/test.sh
- containers/scripts/docker-compose-permissions.yml
- hmiServerDev.sh
> 2243 feat generate initial permissions

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/UserService.java
> Adding debug log

- packages/client/hmi-client/src/components/code/tera-code-dynamic.vue
- packages/client/hmi-client/src/components/code/tera-code.vue
- packages/client/hmi-client/src/page/WorkflowNode.vue
- packages/client/hmi-client/src/page/project/components/tera-resource-sidebar.vue
- packages/client/hmi-client/src/types/workflow.ts
- packages/client/hmi-client/src/workflow/ops/code-asset/code-asset-operation.ts
- packages/client/hmi-client/src/workflow/ops/code-asset/mod.ts
- packages/client/hmi-client/src/workflow/ops/code-asset/tera-code-asset-node.vue
- packages/client/hmi-client/src/workflow/ops/code-asset/tera-code-asset-wrapper.vue
- packages/client/hmi-client/src/workflow/tera-workflow.vue
* Creating a code-asset node in workflow with drilldown.
* Will need to figure a way to store "include in process" code blocks (data format) in another PR
https://github.com/DARPA-ASKEM/terarium/assets/33158416/0283878e-f856-4ef7-8b9d-d72ff3c4368a
> task: code asset workflow node

- packages/client/hmi-client/src/services/jupyter.ts
- packages/client/hmi-client/src/workflow/ops/model-from-code/tera-model-from-code.vue
> Kernel dispatch model from code

- packages/client/hmi-client/src/assets/css/theme/_variables.scss
> style: 1rem = 16px

- packages/client/hmi-client/src/components/funman/tera-constraint-group-form.vue
- packages/client/hmi-client/src/components/model/tera-model-jupyter-panel.vue
- packages/client/hmi-client/src/components/stratification/tera-mira-notebook.vue
- packages/client/hmi-client/src/components/stratification/tera-stratification-group-form.vue
- packages/client/hmi-client/src/components/widgets/tera-multi-select-modal.vue
- packages/client/hmi-client/src/page/Unauthorized.vue
- packages/client/hmi-client/src/page/project/components/tera-model-modal.vue
- packages/client/hmi-client/src/workflow/ops/dataset-transformer/tera-dataset-transformer.vue
- packages/client/hmi-client/src/workflow/ops/funman/tera-funman.vue
- packages/client/hmi-client/src/workflow/ops/model-transformer/tera-model-transformer.vue
> style: scope some components

- containers/scripts/docker-compose-permissions.yml
- hmiServerDev.sh
Waiting for images to pull to test - so if you can test faster than my Internet connection :)
> use image from ghcr

- packages/client/hmi-client/src/workflow/tera-operator.vue
> fix: open drilldown

- packages/client/hmi-client/src/assets/css/theme/_variables.scss
- packages/client/hmi-client/src/components/drilldown/tera-drilldown-header.vue
- packages/client/hmi-client/src/components/drilldown/tera-drilldown.vue
- packages/client/hmi-client/src/workflow/tera-workflow.vue
* Drilldown header component
Multiple tabs, full header design
https://github.com/DARPA-ASKEM/terarium/assets/33158416/7f4a7f93-cea7-40b2-b27f-6634d28019cf
Big close clickable area
https://github.com/DARPA-ASKEM/terarium/assets/33158416/ab985afc-faa1-4bd4-ba94-01e240c0c66b
Only one view (no tabs)
> task: tera drilldown header

- packages/client/hmi-client/src/workflow/ops/dataset/tera-dataset-node.vue
- packages/client/hmi-client/src/workflow/tera-operator.vue
Hid the multiselect input box and I trigger its menu by linking its `ref` to the icon button it and calling `show()` on it.
> style: dataset node design update

- packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-julia/tera-calibrate-julia.vue
- packages/client/hmi-client/src/workflow/ops/dataset-transformer/tera-dataset-transformer.vue
- packages/client/hmi-client/src/workflow/ops/model-transformer/tera-model-transformer.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ciemss/tera-simulate-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-julia/tera-simulate-julia.vue
* Wrapping some more nodes in drilldown:
- calibrate-ciemss
- calibrate-ensemble-ciemss
- calibrate-julia
- dataset-transformer
- model-transformer 
- simulate-ciemss
- simulate-ensemble-ciemss 
- simulate-julia
> task: update nodes to drilldown

- packages/client/hmi-client/src/workflow/ops/funman/tera-funman.vue
- packages/client/hmi-client/src/workflow/ops/model-from-code/tera-model-from-code.vue
- packages/client/hmi-client/src/workflow/ops/stratify-mira/tera-stratify-mira.vue
* Updating the final 3 nodes:
- funman
- model-from-code
- stratify-mira
> Update nodes 3

- packages/client/hmi-client/src/components/drilldown/tera-drilldown.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-julia/tera-calibrate-julia.vue
- packages/client/hmi-client/src/workflow/ops/code-asset/tera-code-asset-wrapper.vue
- packages/client/hmi-client/src/workflow/ops/dataset-transformer/tera-dataset-transformer.vue
- packages/client/hmi-client/src/workflow/ops/dataset/tera-dataset-workflow-wrapper.vue
- packages/client/hmi-client/src/workflow/ops/funman/tera-funman.vue
- packages/client/hmi-client/src/workflow/ops/model-from-code/tera-model-from-code.vue
- packages/client/hmi-client/src/workflow/ops/model-transformer/tera-model-transformer.vue
- packages/client/hmi-client/src/workflow/ops/model/tera-model-workflow-wrapper.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ciemss/tera-simulate-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-julia/tera-simulate-julia.vue
- packages/client/hmi-client/src/workflow/ops/stratify-mira/tera-stratify-mira.vue
- packages/client/hmi-client/src/workflow/tera-workflow.vue
* small change to the drilldown node so that we do not need to define a tab name if there is only 1 top level component
Updated all nodes to use the drilldown component:
https://github.com/DARPA-ASKEM/terarium/issues/2324
> task: update drilldown nodes

- .github/CONTRIBUTING.md
- README.md
- hmiServerDev.sh
Update the README.md with some extra information. Remove outdated information. 
Add some output to `hmiServerDev.sh` to know what environment / server params were parsed.
> docs: update and cleanup the readme.

- packages/client/hmi-client/src/components/drilldown/tera-drilldown.vue
- packages/client/hmi-client/src/workflow/ops/funman/tera-funman.vue
- packages/client/hmi-client/src/workflow/ops/stratify-mira/tera-stratify-mira.vue
* update startify-mira drilldown to now be sectioned with the tera-drilldown component
* create concept of a shared section in drilldown where section can be shared between tabs to avoid duplication
> update: stratify mira drilldown

- packages/client/hmi-client/src/components/optimize/tera-intervention-policy-group-form.vue
- packages/client/hmi-client/src/workflow/ops/model-optimize/tera-model-optimize.vue
> Optimize operator UI code cleanup

- packages/client/hmi-client/src/components/dataset/tera-dataset-jupyter-panel.vue
- packages/client/hmi-client/src/components/model/tera-model-jupyter-panel.vue
- packages/client/hmi-client/src/components/stratification/tera-mira-notebook.vue
- packages/client/hmi-client/src/services/jupyter.ts
- packages/client/hmi-client/src/temp/JupyterTest.vue
- packages/client/hmi-client/src/workflow/ops/model-from-code/tera-model-from-code.vue
- packages/client/hmi-client/src/workflow/ops/stratify-mira/tera-stratify-mira.vue
> Rename beaker kernel to match upstream changes

- packages/client/hmi-client/src/workflow/ops/model-from-code/tera-model-from-code.vue
This PR addresses breaking parts that arose from both beaker-kernel changes and the additions of petrinet's version of code-to-amr which broke the julia/decapodes conversions.
Note: I reorganized the imports into logical groups
With Julia/Decpode options selected, you can try to run the following decapode declarations:
```
h::Form0
Γ::Form1
n::Constant
ḣ == ∂ₜ(h)
ḣ == ∘(⋆, d, ⋆)(Γ * d(h) * avg₀₁(mag(♯(d(h)))^(n-1)) * avg₀₁(h^(n+2)))
```
> fix: beaker-kernel changes

- packages/client/hmi-client/src/workflow/ops/stratify-mira/tera-stratify-mira.vue
I'm calling `reset_request` followed by `stratify_request`/`execute_request`. These are asynchronous. Meaning that it's possible `stratify_request`/`execute_request` finishes before `reset_request` which could lead to issues. This PR makes sure `stratify_request`/`execute_request` are only called once `reset_request` finishes.
> Fix stratify mira reset

- containers/scripts/docker-compose-data.yml
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/EventController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DocumentController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/authority/Authority.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/authority/AuthorityInstance.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/authority/AuthorityType.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/authority/KeycloakRole.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/authority/Role.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/document/AddDocumentAssetFromXDDRequest.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/user/Annotation.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/user/Event.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/proxies/dataservice/ProjectProxy.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/repository/EventRepository.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/EventService.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/utils/hibernate/JpaConverterJson.java
- packages/server/src/test/java/software/uncharted/terarium/hmiserver/controller/events/EventTest.java
> changed project id to UUID

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/TDSCodeController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/code/Code.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/CodeService.java
Cleanup of the code object. UUID, swagger docs and correct error handng
> Code asset cleanup

- packages/client/hmi-client/src/assets/css/style.scss
- packages/client/hmi-client/src/assets/css/theme/_variables.scss
- packages/client/hmi-client/src/assets/css/theme/designer/components/button/_splitbutton.scss
- packages/client/hmi-client/src/assets/css/theme/designer/components/misc/_avatar.scss
- packages/client/hmi-client/src/components/navbar/tera-footer.vue
- packages/client/hmi-client/src/components/navbar/tera-navbar.vue
* Based on @jamiewaese-uncharted design
> New header menu

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ArtifactController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ConceptController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DatasetController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DocumentController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ProjectController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/SimulationController.java
* Correct http return codes
* improved swagger docs
* Correct return types
> Continued cleanup

- packages/client/hmi-client/src/services/document-assets.ts
incorrect endpoint for adding document from xdd
> Updating endpoint

- packages/client/hmi-client/src/components/model/petrinet/tera-model-semantic-tables.vue
- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config-editor.vue
- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config-node.vue
- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config.vue
- disable editing in preview
- don't inject existing configs in new config node
> Model config drilldown minor cleanup

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ArtifactController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DocumentController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/TDSCodeController.java
* create new endpoint to upload code to.
* fixing param types on simlar end points
> Code upload URL

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ProjectAssetService.java
> Unable to delete project asset

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/utils/rebac/ReBACService.java
Slight refactor for when running locally but hitting staging keycloak
> Rebac init issue

- packages/client/hmi-client/src/components/code/tera-code-dynamic.vue
- packages/client/hmi-client/src/components/code/tera-code.vue
- packages/client/hmi-client/src/components/drilldown/tera-drilldown.vue
- packages/client/hmi-client/src/components/widgets/tera-asset-block.vue
- packages/client/hmi-client/src/utils/code-asset.ts
- packages/client/hmi-client/src/workflow/ops/model-from-code/model-from-code-operation.ts
- packages/client/hmi-client/src/workflow/ops/model-from-code/tera-model-from-code.vue
* rewriting the code asset with asset blocks
* this pr is mostly a rewrite of the tera-code-dynamic component to use the AssetBlock component
> rewrite code asset with asset blocks

- .github/workflows/test-server.yaml
- containers/docker-compose-lean.yml
- packages/client/hmi-client/vite.config.ts
- packages/server/src/test/resources/application-test.properties
* Fixing broken server tests (dependencies and OOM)
* Adding new failed test view
NOTE: some individual tests may still be failing. this will be done seperately
> 2242 fix server test

- packages/client/hmi-client/src/page/project/components/tera-notes-sidebar.vue
- packages/client/hmi-client/src/services/models/annotations.ts
- packages/client/hmi-client/src/types/Types.ts
- packages/client/hmi-client/src/types/common.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/user/Annotation.java
Fixing some 400 errors being thrown
> fix(hmi): annotations errors

- packages/client/hmi-client/src/components/widgets/tera-common-modal-dialogs.vue
- packages/client/hmi-client/src/components/widgets/tera-modal.vue
* This dispatch an event when a modal is opened.
* Add an id to the project modal
Used for the guided tour to be able to select element within the modal
> [Task] add event for guided tour

- packages/client/hmi-client/src/types/common.ts
- packages/client/hmi-client/src/workflow/ops/model-config/model-config-operation.ts
- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config-table.vue
- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config.vue
Initial implementation of time varying params in model config:
https://github.com/DARPA-ASKEM/terarium/assets/33158416/0b4acd27-19b8-4889-b836-05f55c50fd6f
> time-varying params

- packages/client/hmi-client/src/components/model/petrinet/tera-model-description.vue
- packages/client/hmi-client/src/page/data-explorer/DataExplorer.vue
- packages/client/hmi-client/src/page/data-explorer/components/tera-preview-panel.vue
- removed selected resources footer
- added imports to `tera-model-description` that should've been there
> fix: remove selected resources footer

- hmiServerDev.sh
- packages/server/src/main/resources/application-local.properties
- packages/server/src/main/resources/application.properties
> beta removed

- package.json
* Run the `yarn` dev and local !
> [BUG] Update package.json

- packages/server/src/main/resources/application-local.properties
> fix(hmi-server): Local sim urls

- containers/scripts/docker-compose-data-services.yml
Updating the beaker docker configs to match beaker's env variable names
https://github.com/DARPA-ASKEM/beaker-kernel/blob/main/docker-compose.yaml#L19-L20
> updating beaker env var names

- .github/CODEOWNERS
This updates the code owners to a better list ;)
> fix: update code owners

- packages/client/hmi-client/src/utils/data-util.ts
- packages/client/hmi-client/src/workflow/ops/model-from-code/tera-model-from-code.vue
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
* adding file extensions to temp code files
> add file ext

- packages/client/hmi-client/src/workflow/ops/model-coupling/tera-model-coupling.vue
- packages/client/hmi-client/src/workflow/ops/model-from-code/tera-model-from-code.vue
Update to match beaker's julia update
> chore: bump julia to 1.10

- containers/scripts/docker-compose-data-services.yml
- containers/scripts/docker-compose-model-services.yml
- containers/scripts/docker-compose-sim-services.yml
> update sciml-service and beaker

- packages/client/hmi-client/src/components/model/petrinet/tera-model-description.vue
- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/AssetType.java
Reverts DARPA-ASKEM/terarium#2726
> Revert "Small fixes"

- packages/client/hmi-client/src/services/jupyter.ts
A bit better error/problem handling to prevent an indefinite connection attempt
> feat: timeout connection attempts

- packages/client/hmi-client/src/page/project/components/tera-upload-resources-modal.vue
- packages/client/hmi-client/src/services/model.ts
- packages/client/hmi-client/src/types/common.ts
- packages/client/hmi-client/src/utils/file.ts
**Note:** this branch is created off from `2698-new-resources-upload` and depend on the following PR: https://github.com/DARPA-ASKEM/terarium/pull/2732. Reviewing and merging PR https://github.com/DARPA-ASKEM/terarium/pull/2732 prior to review is required. 
https://github.com/DARPA-ASKEM/terarium/assets/3279838/2b3ef8a4-6dce-4123-bd0a-60f4b12b67b6
> Validate AMR json file and create a model from it

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ModelService.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/TerariumAssetService.java
- packages/server/src/main/resources/application-remote.properties
This is a naive first take on the idea based on the assumption that there exists such a field in ElasticSearch
> search for assets use isPublic only

- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss.vue
- Fix initial mapping/ensembleConfig not configured properly
- Rewrite and simplify mapping table, this had messed up rendering and invalid html
Note ciemss currently will fail if sample > 1
> fix: ensemble ciemss

- packages/client/hmi-client/src/services/search.ts
- packages/es-ingest/src/main/java/software/uncharted/terarium/esingest/ingests/model/ModelAddEmbeddingsPass.java
- packages/es-ingest/src/main/java/software/uncharted/terarium/esingest/models/output/model/Model.java
- packages/es-ingest/src/main/java/software/uncharted/terarium/esingest/service/ElasticIngestParams.java
- packages/es-ingest/src/main/java/software/uncharted/terarium/esingest/service/ElasticInsertService.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/search/SearchByAssetTypeController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/task/TaskRequest.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/task/TaskResponse.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/elasticsearch/ElasticsearchService.java
- packages/server/src/test/java/software/uncharted/terarium/hmiserver/controller/search/SearchByAssetTypeControllerTests.java
Revert the search to a GET
Allow for general search if no text is provided
Add pagination params. 
Update the model `gollmCard` property
Comments on taskrunner `additionalProperties`
> Updates, fixes, and comments

- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/simulation/SimulationType.java
> add optimize simulation type

- packages/client/hmi-client/src/services/model-templates/natural-conversion.json
Fix natural conversion expression
> fix: natural conversion template

- packages/client/hmi-client/src/workflow/ops/stratify-mira/tera-stratify-mira.vue
Allow model parameters to be stratified as well. e.g. using S, I and beta
> mira parameter stratify

- packages/client/hmi-client/src/workflow/ops/model-from-document/tera-model-from-document-drilldown.vue
> linter fix

- packages/client/hmi-client/src/workflow/ops/model-edit/tera-model-edit.vue
model-edit operator is not utilizing output state, so when selecting from the output preview dropdown nothing happens. 
This PR fixes this issue.
TODO: We still need to work out whether we want to create new output on every run? or when the model is saved?
Start from a simple model, e.g. SIR
- Add a new template A => B
- Save model to create output
- Remove I => R template
- Save model to create output
Should be able to exit, come back in,  and when switching between outputs see the changes restored, this might take a few seconds ad we need to rerun the code that was saved.
> fix: model-edit operator save/restore state

- packages/client/hmi-client/src/components/model/petrinet/model-diagrams/tera-model-diagram.vue
- packages/client/hmi-client/src/workflow/ops/model-from-document/tera-model-from-document-node.vue
> fix issue with equations to model operator

- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config.vue
> changed size of run button in the notebook

- packages/client/hmi-client/src/workflow/ops/model-comparison/tera-model-comparison.vue
> Jamie fix compare models column widths

- packages/client/hmi-client/src/page/data-explorer/components/tera-asset-card.vue
- packages/client/hmi-client/src/page/data-explorer/components/tera-preview-panel.vue
- packages/client/hmi-client/src/page/data-explorer/components/tera-search-results-list.vue
> fix: consistent name so xdd results appear

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/gollm/GoLLMController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/mira/MiraController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/search/SearchByAssetTypeController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/CompareModelResponseHandler.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/ConfigureFromDatasetResponseHandler.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/ConfigureModelResponseHandler.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/ModelCardResponseHandler.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/TaskResponseHandler.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/TaskService.java
- packages/server/src/test/java/software/uncharted/terarium/hmiserver/service/tasks/TaskServiceTest.java
Fixes how the handlers are executed.
> Fix task response handler lookup

- packages/client/hmi-client/src/components/navbar/tera-searchbar.vue
> Prettier search bar on Explorer page

- packages/client/hmi-client/src/components/dataset/tera-dataset-description.vue
- packages/client/hmi-client/src/components/dataset/tera-dataset-overview-table.vue
- packages/client/hmi-client/src/services/concept.ts
> fix issue with concepts not showing up properly

- packages/client/hmi-client/src/components/widgets/tera-pdf-embed.vue
- packages/client/hmi-client/src/workflow/ops/document/tera-document-operation-drilldown.vue
> Jamie pdf viewer in document page improvements

- packages/client/hmi-client/src/components/dataset/tera-save-dataset-from-simulation.vue
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/SimulationController.java
-Adding logger success
-Updating asset when we finish with it
> minor fix to sim -> dataset functionality

- packages/client/hmi-client/src/services/artifact.ts
- packages/client/hmi-client/src/services/code.ts
- packages/client/hmi-client/src/services/dataset.ts
- packages/client/hmi-client/src/services/document-assets.ts
Simplistic change hardcoded values.
> update all 30s timeouts to 1 hour

- packages/client/hmi-client/src/components/dataset/tera-dataset-overview-table.vue
- packages/client/hmi-client/src/components/widgets/tera-boxplot.vue
> Styled dataset stats column with a boxplot for numbers and a list for categoricals

- packages/client/hmi-client/src/model-representation/petrinet/petrinet-renderer.ts
Small cleanup as precursor to support rendering MMTs.
> chore: remove unused code from renderer

- packages/client/hmi-client/src/components/model/petrinet/tera-model-equation.vue
- packages/client/hmi-client/src/services/knowledge.ts
- packages/client/hmi-client/src/workflow/ops/model-from-document/tera-model-from-document-drilldown.vue
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
- packages/server/src/test/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnoweldgeControllerTests.java
- packages/server/src/test/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeControllerTests.java
* Add the creation of a model when calling the equations to model controller.
* Update the front-end to not communicate with the knowledge middleware.
* Try to add some test, but makes no sense.
> Update equations to model front end

- packages/client/hmi-client/src/services/model.ts
* Small clean up
* Remind to update the call to POST when the backend is ready, see PR https://github.com/DARPA-ASKEM/sciml-service/pull/167
> Update model to equations call

- packages/client/hmi-client/src/components/home/tera-project-card.vue
BEFORE
AFTER
I fixed the documents stat. Also added a proper tooltip.
> Fix broken document stats, add workflow stat, add tooltips

- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config-node.vue
> Configure model operator: don't show placeholder if a model is attached

- packages/client/hmi-client/src/components/operator/tera-operator-annotation.vue
- packages/client/hmi-client/src/main.ts
> Jamie refinement of add a note feature - text box opens in focus mode

- packages/client/hmi-client/src/components/llm/tera-notebook-jupyter-input.vue
- packages/client/hmi-client/src/model-representation/petrinet/petrinet-service.ts
- packages/client/hmi-client/src/services/model.ts
- packages/client/hmi-client/src/types/workflow.ts
- packages/client/hmi-client/src/workflow/ops/decapodes/decapodes-operation.ts
- packages/client/hmi-client/src/workflow/ops/decapodes/mod.ts
- packages/client/hmi-client/src/workflow/ops/decapodes/tera-decapodes-drilldown.vue
- packages/client/hmi-client/src/workflow/ops/decapodes/tera-decapodes-node.vue
- packages/client/hmi-client/src/workflow/ops/model-comparison/tera-model-comparison.vue
- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config.vue
- packages/client/hmi-client/src/workflow/ops/model-edit/tera-model-edit.vue
- packages/client/hmi-client/src/workflow/tera-workflow.vue
* decapodes operator, there really isnt much support for llms and decapodes right now, but this is a good base for the operator...It will generate julia code but it isnt runnable
https://github.com/DARPA-ASKEM/terarium/assets/33158416/2f042f58-47cc-4fc4-9f45-9b5282bce969
> decapodes operator

- packages/client/hmi-client/src/components/operator/tera-operator-annotation.vue
> a few small style tweaks to the add-a-note feature

- .github/CONTRIBUTING.md
- packages/client/hmi-client/src/services/toast.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/TransformController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/mira/MiraController.java
* Improve the message from some services that just throw a lot of 500
* Revert error toast to disapears, but after 9 seconds.
> Improve some error message

- packages/client/hmi-client/src/utils/code-asset.ts
- packages/client/hmi-client/src/workflow/ops/model-from-code/tera-model-from-code.vue
BEFORE
(note from Pascale)
AFTER
> made code blocks bigger, moved dropdowns to top

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ModelService.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/MdlToStockflowResponseHandler.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/SbmlToPetrinetResponseHandler.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/StellaToStockflowResponseHandler.java
> adding default names and values to model parameters

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ProjectController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ModelService.java
> set default parameter values to 1

- packages/client/hmi-client/src/components/navbar/tera-navbar.vue
Issue #3051
* Adding single/multi user to banner
Resolves #3051
> feat [hmi-client]: Add number of users logging in banner

- packages/client/hmi-client/src/page/data-explorer/components/tera-search-results-list.vue
> fix: missing search item component

- packages/client/hmi-client/src/assets/css/style.scss
> limit the height of a dropdown menu to 400px. Scroll on overflow

- packages/client/hmi-client/src/components/model/petrinet/tera-parameter-table.vue
* bugfix for issue where stratified model didnt have full editing capability
https://github.com/DARPA-ASKEM/terarium/assets/33158416/085038fd-f167-4a9c-9e75-1d5044739f53
> bugfix-stratify-edit

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
> Making profile have an optional documentId

- packages/client/hmi-client/src/workflow/tera-optimize-chart.vue
Use chart.js directly to workaround the issue with `primevue/chart` and `chartjs-plugin-annotation` conflicting. 
> Workaround annotation plugin

- packages/client/hmi-client/src/components/home/tera-project-overview-editor.vue
- packages/client/hmi-client/src/services/project.ts
- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ProjectController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/project/Project.java
> switched project overview to be a byte array

- packages/client/hmi-client/src/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss.vue
Removing bar chart nonsense + radio buttons to calculate weights
> ensemble cleanups 4

- packages/client/hmi-client/src/components/model/petrinet/tera-other-concepts-table.vue
- packages/client/hmi-client/src/components/model/petrinet/tera-petrinet-tables.vue
- packages/client/hmi-client/src/services/model.ts
- packages/client/hmi-client/src/utils/data-util.ts
* assign other concepts to initials and parameters
https://github.com/DARPA-ASKEM/terarium/assets/33158416/f06cf68a-92f0-4f48-a06c-9ea4be6718e1
> assign other concepts

- packages/client/hmi-client/src/workflow/ops/optimize-ciemss/tera-optimize-ciemss.vue
Updating optimize to use the new proxy chart, thanks Dan!
> Optimize -> Proxy Chart

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
Some random errors I ran into while using the KnowledgeController
> fix[hmi-server]: Fixing Knowledge errors

- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
- packages/client/hmi-client/src/services/calibrate-workflow.ts
- packages/client/hmi-client/src/workflow/ops/dataset/tera-dataset-node.vue
Now with fewer 500s on the server
> gatekeep request by checking presence of esgfId

- packages/client/hmi-client/src/workflow/ops/subset-data/tera-subset-data.vue
BEFORE
AFTER
Note, my rectangle drawing preview only shows if no preview image exists. If a real preview comes in, we show that instead.
> Jamie prettify subset dataset

- packages/client/hmi-client/src/components/model/petrinet/tera-parameter-table.vue
- packages/client/hmi-client/src/model-representation/service.ts
Prevent parameter updates from overwriting relevant configurations, in this case distribution-field gets overwritten which can cause cryptic errors downstream like TA3 operations.
> fix parameter update overwrites

- packages/client/hmi-client/package.json
- packages/client/hmi-client/src/components/dataset/tera-save-dataset-from-simulation.vue
- packages/client/hmi-client/src/components/optimize/tera-intervention-policy-group-form.vue
- packages/client/hmi-client/src/workflow/ops/optimize-ciemss/tera-optimize-ciemss.vue
- packages/client/hmi-client/src/workflow/tera-optimize-chart.vue
- yarn.lock
Jamie's branch had a bunch of merge conflicts as well as some changes that needed fixing up and some changes that needed reverting.
Rather than dealing with this i just grabbed relevant code into this new branch.
Please ensure that youre happy with this!
> Jamie's Prettify Optimize redone

- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
> metadata may not always contain format

- packages/client/hmi-client/src/services/calibrate-workflow.ts
Missed this one too. This will cause breaks in calibration and ensemble calibration setup step
> fetch dataset fix - 2

- packages/client/hmi-client/src/workflow/ops/optimize-ciemss/tera-optimize-ciemss.vue
> using dan's code better

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/climatedata/ClimateDataService.java
Additionally, if S3 url is not found, re-request instead of throwing an error
> add previews to image folder

- packages/client/hmi-client/src/components/widgets/tera-related-documents.vue
- packages/client/hmi-client/src/services/knowledge.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/proxies/skema/SkemaUnifiedProxy.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/ExtractionService.java
NOTE: SKEMA variable extraction fails when using COSMOS extracted text  on my test pdf...
> Changes to model extraction

- packages/client/hmi-client/src/workflow/ops/optimize-ciemss/optimize-ciemss-operation.ts
- packages/client/hmi-client/src/workflow/ops/optimize-ciemss/tera-optimize-ciemss.vue
Just rebuilding before I can test
> Optimize adding adding maxiter, Maxfeval

- containers/scripts/docker-compose-common.yml
> Update minio source

- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss.vue
> stretch out simulation ensemble chart

- packages/client/hmi-client/src/workflow/ops/calibrate-ensemble-ciemss/calibrate-ensemble-ciemss-operation.ts
- packages/client/hmi-client/src/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-node-ciemss.vue
-Update charts
-Move to new paradigm
-Clean onMount stuff up + watch on knobs
-Actually have proper pyciemss-service calls
> 3067 calibrate ensemble 3

- packages/client/hmi-client/src/components/funman/tera-constraint-group-form.vue
- packages/client/hmi-client/src/workflow/ops/funman/funman-operation.ts
- packages/client/hmi-client/src/workflow/ops/funman/tera-funman.vue
Per Dan Bryce, monotonicity should allow a linear combination of weights to be configured, rather than hardwired to `+- 1.0`
> funman monoton weights

- packages/client/hmi-client/src/components/navbar/tera-navbar.vue
Set multiple users by default.
> fix[hmi-client]: Set multiple users by defaults

- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config.vue
model-config debugging info for Nelson and using the notebook directly thread.
> debug for nelson

- packages/client/hmi-client/src/components/asset/tera-asset.vue
- packages/client/hmi-client/src/components/model/tera-model.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-ensemble-ciemss/tera-calibrate-ensemble-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-julia/tera-calibrate-julia.vue
- packages/client/hmi-client/src/workflow/ops/dataset/tera-dataset-drilldown.vue
- packages/client/hmi-client/src/workflow/ops/document/tera-document-operation-drilldown.vue
- packages/client/hmi-client/src/workflow/ops/funman/tera-funman.vue
- packages/client/hmi-client/src/workflow/ops/model-comparison/tera-model-comparison.vue
- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config.vue
- packages/client/hmi-client/src/workflow/ops/model-coupling/tera-model-coupling.vue
- packages/client/hmi-client/src/workflow/ops/model-edit/tera-model-edit.vue
- packages/client/hmi-client/src/workflow/ops/model-from-code/tera-model-from-code.vue
- packages/client/hmi-client/src/workflow/ops/model-from-equations/tera-model-from-equations-drilldown.vue
- packages/client/hmi-client/src/workflow/ops/optimize-ciemss/tera-optimize-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/regridding/tera-regridding.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ciemss/tera-simulate-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/simulate-julia/tera-simulate-julia.vue
- packages/client/hmi-client/src/workflow/ops/stratify-mira/tera-stratify-mira.vue
- packages/client/hmi-client/src/workflow/ops/subset-data/tera-subset-data.vue
I corrected the padding issues for all the operator drilldowns. Here is an overview of before/after images, zoomed way out so you can see the number of operators touched. 
Here are a couple random examples zoomed in:
> Jamie correct padding for all operators

- packages/client/hmi-client/src/workflow/ops/model-edit/tera-model-edit.vue
Parameter units now are in defaulted sample questions
> updating model edit sample Questions with units

- packages/client/hmi-client/src/components/dataset/tera-dataset-description.vue
- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
- packages/client/hmi-client/src/components/widgets/tera-carousel.vue
- packages/client/hmi-client/src/workflow/ops/subset-data/tera-subset-data.vue
subset previews are now displayed
adding the subset to the project without duplicating it but using the actual subset
> fix: add subset to project and show subset preview 

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/User.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/UserService.java
Found the tricky buggers
- 1) use CachePut on save actions
- 2) actually merge the roles not overwrite one for the other
> 3147 new user can get 403 even though admin has added them to public group

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/extractionservice/PdfExtractionRequest.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/proxies/documentservice/ExtractionProxy.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/ExtractionService.java
sending extraction request as a part to a body.
> fix[hmi-server]: Cosmos extraction fix

- packages/client/hmi-client/src/components/funman/tera-constraint-group-form.vue
- packages/client/hmi-client/src/workflow/ops/funman/tera-funman.vue
- more decimal places in input-number
- parameter constraint, note this is just the UI-parts, we are getting blank results, need to check if the payload spec is accurate
> funman tweaks

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelController.java
> Protect getModel NPE error

- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
- packages/client/hmi-client/src/components/navbar/tera-navbar.vue
* Fetch the dataset CSV only when the user wants to visualize them in the Data tab.
> Remove download of dataset if not on the data tab

- packages/client/hmi-client/src/components/dataset/tera-dataset.vue
- packages/client/hmi-client/src/services/dataset.ts
- packages/client/hmi-client/src/types/Types.ts
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/PresignedURL.java
> Download file for Dataset

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
> remove code part of the model card request

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/knowledge/KnowledgeController.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/dataservice/code/CodeFile.java
> fix[hmi-server]: Better error handling

- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config.vue
Warnings when creating model-configurations
model-configuration operator, use lower/upper bound of distribution of a parameter to be the same, try to run and should get a warning prompt dialog
> sanity check warnings

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ModelController.java
> model metadata null error

- packages/client/hmi-client/src/workflow/ops/model-config/tera-model-config.vue
> more lenient threshold

- packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/calibrate-operation.ts
- packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss.vue
- packages/client/hmi-client/src/workflow/ops/calibrate-ciemss/tera-calibrate-node-ciemss.vue
> adding more user options to calibrate

- packages/client/hmi-client/src/workflow/ops/simulate-ensemble-ciemss/tera-simulate-ensemble-ciemss.vue
> adding add chart

- packages/client/hmi-client/src/workflow/tera-workflow.vue
Extend notebook cloning to regrid-operator
> Extend notebook clone to regrid-operator

- packages/server/src/main/java/software/uncharted/terarium/hmiserver/models/climateData/ClimateDataResultSubset.java
- packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/climatedata/ClimateDataService.java
inspect status and deal with errors
> Expand climate-data error handling

- packages/client/hmi-client/src/components/optimize/tera-intervention-policy-group-form.vue
- packages/client/hmi-client/src/workflow/ops/optimize-ciemss/optimize-ciemss-operation.ts
- packages/client/hmi-client/src/workflow/ops/optimize-ciemss/tera-optimize-ciemss.vue
> Optimize - adding start_time as an option for intervention type
